### ISSUE TITLE
Ansible Collections not working

### ISSUE THREAD

**Issue by SpikePy** [actions/runner-images#10002]
### Description

When using modules from the azure.azcollection collection of ansible (that comes pre-installed in the image) it does not work.

```yaml
- name: Get kubernetes configuration of stage {{ inventory_hostname | upper }}
  azure.azcollection.azure_rm_aks_info:
    resource_group: '{{ azure_get_kubeconfig__aks_resourcegroup }}'
    name: '{{ azure_get_kubeconfig__aks_name }}'
    show_kubeconfig: admin
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240526.1.0

### Is it regression?

dont know

### Expected behavior

Playbook should run

### Actual behavior

fatal: [dev]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on fv-az363-549's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

### Repro steps

try to use a module of the mentioned collections.
