### ISSUE TITLE
macOS-14 not available in free version?  

### ISSUE THREAD

**Issue by jayroland88** [actions/runner-images#10017]
### Description

```
name: app store build & upload
 
on:
 workflow_dispatch:
 
jobs:
  deploy:
    runs-on: macOS-latest
......
```

I am getting error: github actions Error: Error: Unsupported platform macos-14

only macOS-12 works on free version? macOS-13 I got the same error 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Macos 13 14

### Is it regression?

no

### Expected behavior

should work on 13 &14

### Actual behavior

got error 

### Repro steps

runs-on: macOS-latest or macos-13 you'll get error:

 github actions Error: Error: Unsupported platform macos-14/13
