### ISSUE TITLE
System.BadImageFormatException for VSTest@2 task in agent version 3.240.1

### ISSUE THREAD

**Issue by genedodge** [actions/runner-images#10068]
### Description

On release of agent version `3.240.1`, builds started failing for a pipeline that uses the `VSTest@2` task.

[This release](https://github.com/microsoft/vstest/releases/tag/v17.10.0) may or may not be the cause?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20240610.1.1
https://github.com/actions/runner-images/releases/tag/win22%2F20240610.1

### Is it regression?

Agent version 3.239.1 did not exhibit this issue

### Expected behavior

Tests are run and coverage is collected

### Actual behavior

Fails with error:
`#[error]Data collector 'Code Coverage' message: Data collector caught an exception of type 'System.BadImageFormatException': 'Image is too small.'. More details: ..`

### Repro steps

Add VSTest@2 task to yaml build pipeline and run on agent `3.240.1` to see the error

Exact task in affected pipeline is:
```
  - task: VSTest@2
    displayName: 'Run Unit Tests'
    inputs:
      testAssemblyVer2: |
       **\*Test.Unit.dll
       **\*Tests*
       !**\obj\**
      vsTestVersion: latest
      runInParallel: false
      codeCoverageEnabled: true
      platform: '$(BuildPlatform)'
      configuration: '${{parameters.buildConfiguration}}'
      runSettingsFile: './coverage.runsettings'
```
