### ISSUE TITLE
Docker Compose task failing with Exit code 125\15

### ISSUE THREAD

**Issue by bhanusridhar** [actions/runner-images#10101]
### Description

From today afternoon IST, Docker compose task is failing in Azure devops pipeline with Exit code.
Microsoft hosted agent:
![image](https://github.com/actions/runner-images/assets/78581420/4d2ee005-53dd-44db-8905-e1f565057201)
Self hosted agent:
![image](https://github.com/actions/runner-images/assets/78581420/311ee0e8-8018-4701-9415-0624df8edfac)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

No. We have private repository

### Is it regression?

Not sure

### Expected behavior

Should be able to run docker compose task

### Actual behavior

Should be able to run docker compose task

### Repro steps

1. Able to pull the DB image and spin up the container using docker compose task.

**Comment by RaviAkshintala** [comment]
@bhanusridhar Thank you for bringing this issue to us, we are investigating on this issue and we will update you on this issue after our findings.

**Comment by RaviAkshintala** [comment]
@bhanusridhar Can you please share the Docker-compose file and Azure pipeline yaml file to investigate further, it would be great if you could provide us.

**Comment by bhanusridhar** [comment]
Docker compose file:
```
version: "3.9"
services:
  sql-server-db:
    container_name: testcontainer
    image: acr.azurecr.io/testimage:v1
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "PWD"
      ACCEPT_EULA: "Y"
      HOSTNAME: ${COMPUTERNAME}
    volumes:
      - C:\Volume1:C:\MountToHost
```

Yaml pipeline: I am mentioning the tasks here:
```
          - task: Docker@2
            displayName: 'Login to registry'
            inputs:
              containerRegistry: 'ServiceConnection'
              command: 'login'
          
          - task: DockerCompose@0
            displayName: Pull DB image
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'ServiceConnection'
              dockerComposeFile: '$(DockerComposeFile)'
              action: Run a Docker Compose command
              dockerComposeCommand: pull
          
          - task: DockerCompose@0
            displayName: Spin up DB container
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'ServiceConnection'
              dockerComposeFile: '$(DockerComposeFile)'
              action: Run a Docker Compose command
              dockerComposeCommand: up
              arguments: '-d'
```

@RaviAkshintala Please let me know if any information required.
