### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)

### ISSUE THREAD

**Issue by m-yavuz** [actions/runner-images#10113]
### Description

I face an issue with install packages on [Ubuntu 22.04 20240616](https://github.com/actions/runner-images/blob/releases/ubuntu22/20240616/images/ubuntu/Ubuntu2204-Readme.md)

When node version 18.x or 20.x and install any NPM package i got this error **`GLIBC_2.28' not found**

**P.S. I tried a different package with same issue as well.
P.S.: it is first time, i tried node version 18 and 20, it was 16 for long time** 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://github.com/actions/runner-images/assets/475717/326c480b-370b-4cf4-9141-2299799a54f1)

### Is it regression?

first time try Node 18.x 16.x, it was 16.x

### Expected behavior

install npm packages without issues  

### Actual behavior

Errors with install any package 

### Repro steps

Sample: 
**Pipeline:**
![image](https://github.com/actions/runner-images/assets/475717/bc6deaa7-dc08-48e4-bec6-81053dac2bc1)
**issue:**
![image](https://github.com/actions/runner-images/assets/475717/3a5deb29-5a58-42ff-8adb-667e3e5da4a1)

**Comment by vidyasagarnimmagaddi** [comment]
Hi @m-yavuz  , We will analyse the issue and provide resolution, thanks.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @m-yavuz  , Try the below snippet , we made changes to your provided yaml file 
Find below points:
1)We removed `checkLatest` which  does not supports GLIBC_2.28.it will support LTS versions only.
2)You are executing `npm install` command outside the directory. We executed the command by moving to location where packer.json is available.
```
pool:
  vmImage: ubuntu-22.04
steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- script: |
    cd $(Build.SourcesDirectory)/Application/
    npm install -g nodemon
  displayName: 'npm install and build'
  ```
Kindly try the same and provide the logs if errors.

**Comment by m-yavuz** [comment]
My change as the following :

```
        pool:
          vmImage: ubuntu-latest
```
.
.
.
```
                - task: NodeTool@0
                  displayName: Node install
                  inputs:
                    versionSpec: "20.x"
                    # checkLatest: true

                - script: |
                    cd $(Build.SourcesDirectory)/deployment/pulumi/amap/npr/env/
                    npm install -g nodemon
                  displayName: 'Install nodemon'
```

and still have the same issue 
![image](https://github.com/actions/runner-images/assets/475717/b341fb4a-5ea8-4126-9c06-52df5b2fb3b8)

also, when tried with another way, still same issue

```
                - script: |
                    npm install
                  workingDirectory: ${{ parameters.path}}
                  displayName: NPM install
```

**the only way to works to change node version to 16.x** 

```
                - task: NodeTool@0
                  displayName: Node install
                  inputs:
                    versionSpec: "16.x"
                    # checkLatest: true

                - script: |
                    npm install
                  workingDirectory: ${{ parameters.path }}
                  displayName: NPM install
```
**Which's outdated for some packages.**

![image](https://github.com/actions/runner-images/assets/475717/c952c9ee-8ad9-4fc6-bb8f-ee09aa40dd82)
