### ISSUE TITLE
ubuntu-latest is setting ubuntu20.04 instead of ubuntu22.04

### ISSUE THREAD

**Issue by feliasson** [actions/runner-images#10133]
### Description

```
    pool:
      vmImage: ubuntu-latest
```

When using MS-hosted images and the vmImage `ubuntu-latest` for `pool` in Azure DevOps pipeline the following is seen during a pipeline run:

![image](https://github.com/actions/runner-images/assets/45947114/5e4d3f96-a31e-44e6-bf96-3ccc4ce46681)

![image](https://github.com/actions/runner-images/assets/45947114/053d5bb8-1511-4f12-a1ee-36e43e48c30e)

According to [documentation](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) the `ubuntu-latest` YAML-label should be Ubuntu 22.04, therefor I consider this a bug. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Operating System
Ubuntu
20.04.6
LTS
```

```
Runner Image
Image: ubuntu-20.04
Version: 20240624.2.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20240624.2/images/ubuntu/Ubuntu2004-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240624.2
```

```
Runner Image Provisioner
2.0.370.1
```

### Is it regression?

No

### Expected behavior

The `ubuntu-latest` YAML-label to reflect Ubuntu 22.04 image and not Ubuntu 20.04 image.

### Actual behavior

The `ubuntu-latest` YAML-label is using Ubuntu 20.04 image and not the expected Ubuntu 22.04 image.

### Repro steps

1. In Azure DevOps and in an Azure Pipeline, define a pool from stage level in a template that has been called by `extends` from another repository and use `vmImage: ubuntu-latest`

**Comment by RaviAkshintala** [comment]
Hi @feliasson,
 
We have tested it from our side, and it is showing `ubuntu-22.04.`

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dependabot/npm_and_yarn/result/express-4.19.2

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script' 

Result:

 2024-06-27T09:16:34.8662048Z ##[section]Starting: Job
2024-06-27T09:16:35.0428058Z ##[section]Starting: Initialize job
2024-06-27T09:16:35.0430602Z Agent name: 'Hosted Agent'
2024-06-27T09:16:35.0430863Z Agent machine name: 'fv-az637-984'
2024-06-27T09:16:35.0430994Z Current agent version: '3.241.0'
2024-06-27T09:16:35.0465468Z ##[group]Operating System
2024-06-27T09:16:35.0465614Z Ubuntu
2024-06-27T09:16:35.0465686Z 22.04.4
2024-06-27T09:16:35.0465752Z LTS
2024-06-27T09:16:35.0465847Z ##[endgroup]
2024-06-27T09:16:35.0465934Z ##[group]Runner Image
2024-06-27T09:16:35.0466038Z Image: ubuntu-22.04
2024-06-27T09:16:35.0466135Z Version: 20240616.1.0

**Comment by feliasson** [comment]
Hi @RaviAkshintala, then maybe the behavior occurs when `pool` is set from `stage` level when using the `extends` definition . 

To give you an example how it looks like:
``` yaml
# pipeline yaml

resources:
  repositories:
  - repository: template
    type: git
    name: tooling
    ref: refs/heads/main

extends:
  template: pipeline-template/<template-name>-pipeline-template.yml@template
  parameters:
   <parameters>
```

``` yaml 
# <template-name>-pipeline-template.yml@template

parameters:
  <parameters>

stages:

- stage: stage1
    pool:
      vmImage: ubuntu-latest

  jobs:
   <jobs>
```
I hope this can help to reproduce the behavior.

**Comment by RaviAkshintala** [comment]
@feliasson As per your repro steps we have ran the pipeline and it is taking only ubuntu-22.04.Please find the below logs.
```
2024-06-28T07:05:19.5094686Z ##[section]Starting: Build
2024-06-28T07:05:19.6526690Z ##[section]Starting: Initialize job
2024-06-28T07:05:19.6529088Z Agent name: 'Hosted Agent'
2024-06-28T07:05:19.6529407Z Agent machine name: 'fv-az369-114'
2024-06-28T07:05:19.6529555Z Current agent version: '3.241.0'
2024-06-28T07:05:19.6560917Z ##[group]Operating System
2024-06-28T07:05:19.6561092Z Ubuntu
2024-06-28T07:05:19.6561187Z 22.04.4
2024-06-28T07:05:19.6561269Z LTS
2024-06-28T07:05:19.6561364Z ##[endgroup]
2024-06-28T07:05:19.6561483Z ##[group]Runner Image
2024-06-28T07:05:19.6561609Z Image: ubuntu-22.04
2024-06-28T07:05:19.6561722Z Version: 20240624.1.0
2024-06-28T07:05:19.6561953Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240624.1/images/ubuntu/Ubuntu2204-Readme.md
2024-06-28T07:05:19.6562242Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240624.1 ```


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry 
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection) `

**Comment by feliasson** [comment]
@RaviAkshintala but your example here is not using `extend` and calling another template where the `pool` value is set?

**Comment by kishorekumar-anchala** [comment]
Hi @feliasson ,

  No, I have used only hosted agents on Azure pipelines and also not set any other template to use pool .

**Comment by feliasson** [comment]
> Hi @feliasson ,
> 
> No, I have used only hosted agents on Azure pipelines and also not set any other template to use pool .

What kind of answer is that? How are we supposed to report bugs if you are not willing to take similar steps to try to reproduce the behavior? I don't understand.

**Comment by kishorekumar-anchala** [comment]
Hey @feliasson ,

   Kindly look into my investigation below ,
   
   1) I have tried with basic sample yaml pipeline as per your workaround.(Azure-pipelines.yaml)
   
```

stages:
- stage: BuildAndTest
  jobs:
  - template: templates/build-test.yml  
    parameters:
      vmImage: 'ubuntu-latest' 

```

2) this is build-test.yaml file 

```
   parameters:
- name: vmImage
  type: string
  default: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Job'
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: |
      echo "Starting build and test on ${{ parameters.vmImage }}"
```
     
  You can find below logs , it is taking 22.04 as ubuntu-latest . I hope the above workaround will  clarify your issue .
  
https://github.com/actions/runner-images/blob/ubuntu22/20240624.1/images/ubuntu/Ubuntu2204-Readme.md
2024-07-02T07:17:29.9344371Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240624.1

Thankyou !

**Comment by feliasson** [comment]
You are still not using the `extends` definition to call the template:
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/extends?view=azure-pipelines

**Comment by kishorekumar-anchala** [comment]
Hi @feliasson , I don't think so,  there is no difference. I tried the same but i am unable to reproduce the issue .



```
extends:
  template: templates/build-test.yml
    vmImage: 'ubuntu-latest'

```

2024-07-02T08:35:40.3792834Z Image: ubuntu-22.04
2024-07-02T08:35:40.3792953Z Version: 20240624.1.0
2024-07-02T08:35:40.3793228Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240624.1/images/ubuntu/Ubuntu2204-Readme.md
2024-07-02T08:35:40.3793559Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240624.1

**Comment by kishorekumar-anchala** [comment]
Hi @feliasson ,

  I hope the above workaround clarify your doubt, it is taking only ubuntu-22.04 when using ubuntu-latest.  Could you please provide your status ?

**Comment by feliasson** [comment]
> Hi @feliasson ,
> 
> I hope the above workaround clarify your doubt, it is taking only ubuntu-22.04 when using ubuntu-latest. Could you please provide your status ?

No there is nothing in your workaround that clarifies my doubt, because nothing in what you provided shows that you have properly used `extends` on a template from another repository, the pathing in your code example is from the same repository (`self`) for example.

Also you are not even inputting `parameters` in your example because it would look something like this if it was properly done:
```
# pipeline yaml file

extends:
  template: templates/build-test.yml@<loaded-repository>
  parameters: 
    vmImage: 'ubuntu-latest'
```

```
# templates/build-test.yml@<loaded-repository>

parameters:
  vmImage: ''

stages:

- stage: stage1
  pool:
    vmImage: ${{ parameters.vmImage }}

  jobs:
    <jobs>
```

If you are not looking to properly try to reproduce the bug then please close this issue so that we can stop wasting time.
