### ISSUE TITLE
Significant build time and bundle size for .NET MAUI on iOS

### ISSUE THREAD

**Issue by jenyangk** [actions/runner-images#10200]
### Description

As of today, my builds for my .NET MAUI application on iOS is taking significantly longer to build, from 10 minutes to 90 minutes. The bundle size has also doubled from 123 MB to 233 MB.

My team and I aren't sure what changed between today's and yesterdays' macOS-13 image that would affect this. But, something definitely changed between today and yesterday. We ran a few builds yesterday and didn't encounter anything wrong.

We've tried setting the Xcode version to 15.2 and .NET SDK version from 8.0.x (which had defaulted to 8.0.303 on the 9th of July) to 8.0.302 (which was the 8.0.x version used on the 8th of July).

The build time and bundle size for Android is the same. No change there. Only affecting iOS builds.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240707.2. Sorry, no public builds link.

### Is it regression?

20240630.1

### Expected behavior

Build should finish within 15 minutes with a 120+ MB bundle size.

### Actual behavior

The build is taking 90 minutes to finish and builds a bundle that is double in size.

### Repro steps

Run build script on Azure Pipelines with macOS-13 as the image.

```      
- task: Bash@3
   displayName: Build iOS App
   inputs:
      targetType: 'inline'
      script: |
            cd $(ProjectLocation)
            dotnet publish -f net8.0-ios -c:$(BuildConfiguration) /p:CodesignKey='$(CodesignKey)' /p:CodesignProvision='$(CodesignProvision)'
````

**Comment by jenyangk** [comment]
I went back an re-ran a few old builds of mine from last week which were running normally (finishing within 10 - 20 minutes). They are also now taking longer to finish (~ 1 hour 30 minutes). Definitely not a change to our configuration or code.

**Comment by pierre-galaup** [comment]
Hello,

I have the same problem with my runner for MAUI iOS too. 
I tried to update to a Macos-14 and xcode 15.4 but it doesn't change anything.

**Comment by sureshe456** [comment]
Hi @jenyangk,  We are looking into it. Will keep you posted.

**Comment by IeuanWalker** [comment]
Not sure if this helps the investigation or not.

But we have just built a pipeline for .net maui iOS and was shocked at the build times, but we are using Azure pipelines, so not sure if it's using the same infrastructure behind the scenes. 

![image](https://github.com/actions/runner-images/assets/6544051/b4e37091-3b8c-4363-8557-6e1a303429d7)

**Comment by ESO-ST** [comment]
I'm experiencing the same issue, this started happening with image version '20240708.1'

```
Agent name: 'Hosted Agent'
Agent machine name: 'Mac-1720751551587'
Current agent version: '3.241.0'
Operating System
macOS
14.5
23F79
Runner Image
Image: macos-14
Version: 20240708.1
Included Software: https://github.com/actions/runner-images/blob/macos-14/20240708.1/images/macos/macos-14-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-14%2F20240708.1
Runner Image Provisioner
2.0.370.1+55cddbb57f254a369b6e7b3b508cebdbee5d24be
Current image version: '20240708.1'
```

**Comment by giorgitedi** [comment]
We have been facing the same issue since July 9th. Previously, the building time was about 20 minutes, but now it takes 1 hour and 30 minutes. Additionally, the app size has increased from 90MB to 120MB. Most importantly, the app has started crashing.

We haven't made any changes or added new files, except for some functional/logical updates in the code base.

**Comment by ronan-burke-civ** [comment]
> Most importantly, the app has started crashing.

I'm seeing the exact same thing. Running the pipeline on an old commit from a few weeks ago now produces a build that crashes on startup. I'm pinning .NET MAUI version and .NET version in my pipeline. The only thing I can think of that has changed is the hosted DevOps runner?

**Comment by giorgitedi** [comment]
> > Most importantly, the app has started crashing.
> 
> I'm seeing the exact same thing. Running the pipeline on an old commit from a few weeks ago now produces a build that crashes on startup. I'm pinning .NET MAUI version and .NET version in my pipeline. The only thing I can think of that has changed is the hosted DevOps runner?

I found [this comment](https://github.com/actions/runner-images/issues/10120#issuecomment-2216472980) from last week and I think it is related.

Can you share a build task part from .yml file?

**Comment by ronan-burke-civ** [comment]
I'm pinning Xcode to 15.2 in the pipeline already so I'm not sure if it is that. This is how I'm building the app:
``` yml
  - task: DotNetCoreCLI@2
    displayName: 'Build iOS App'
    inputs:
      command: 'build'
      projects: '$(singleProjectCsproj)'
      arguments: '-c Release -f net8.0-ios -o "$(outputDirectory)" /p:BuildIpa=true /p:ArchiveOnBuild=true /p:RuntimeIdentifier="ios-arm64" /p:CodesignKey="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" /p:CodesignProvision=$(APPLE_PROV_PROFILE_UUID)'
```
