### ISSUE TITLE
No longer able to make VisionOS builds for Unity on macos-latest

### ISSUE THREAD

**Issue by StephenHodgson** [actions/runner-images#10219]
### Description

Previously I had been able to make automated builds on `macos-latest` with arm64 arch, but recent changes seem to have broken this. 

I get an error about FMOD trying to initialize but then failing the build after some timeout.
I am able to make automated builds on my self hosted runner with the same tooling as the vanilla GitHub hosted runner.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link
```
Current runner version: '2.317.0'
Operating System
  macOS
  14.5
  23F79
Runner Image
  Image: macos-14-arm64
  Version: 20240611.1
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240611.1/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240611.1
Runner Image Provisioner
  2.0.370.1+55cddbb57f254a369b6e7b3b508cebdbee5d24be
```
### Is it regression?

yes

### Expected behavior

I can perform automated building with Unity Game Engine and Github Actions Runners for Vision OS platform

### Actual behavior

```
FMOD failed to initialize the output device.: "A call to a standard soundcard driver failed, which could possibly mean a bug in the driver or resources were missing or exhausted. " (57)
Forced to initialize FMOD to to the device driver's system output rate 44100, this may impact performance and/or give inconsistent experiences compared to selected sample rate 48000
FMOD failed to initialize the output device.: "A call to a standard soundcard driver failed, which could possibly mean a bug in the driver or resources were missing or exhausted. " (57)
FMOD initialized on nosound output
```

### Repro steps
See PR https://github.com/RageAgainstThePixel/unity-build/pull/8

1. Create a new workflow using my Github Action as outlined in my repo readme.
2. Create a Unity account if needed and set secrets:
  - `UNITY_USERNAME`
  - `UNITY_PASSWORD`
4. Run the following workflow:
```yaml
name: unity-build-validation

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # max-parallel: 2 # Use this if you're activating pro license with matrix
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build-target: StandaloneLinux64
          - os: windows-latest
            build-target: StandaloneWindows64
          - os: macos-latest
            build-target: StandaloneOSX

    steps:
      - name: checkout self
        uses: actions/checkout@v4

      - name: checkout test project
        uses: actions/checkout@v4
        with:
          repository: RageAgainstThePixel/com.utilities.buildpipeine
          path: test-project

        # Installs the Unity Editor based on your project version text file
        # sets -> env.UNITY_EDITOR_PATH
        # sets -> env.UNITY_PROJECT_PATH
        # https://github.com/XRTK/unity-setup
      - uses: xrtk/unity-setup@v7
        with:
          build-targets: ${{ matrix.build-target }}
          version-file-path: 'test-project/**/ProjectSettings/ProjectVersion.txt'

        # Activates the installation with the provided credentials
        # https://github.com/XRTK/activate-unity-license
      - uses: xrtk/activate-unity-license@v5
        with:
          # Required
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
          # Optional
          license-type: 'Personal' # Chooses license type to use [ Personal, Professional ]
          # serial: ${{ secrets.UNITY_SERIAL }} # Required for pro/plus activations

      - name: Unity Build (${{ matrix.build-target }})
        uses: ./ #RageAgainstThePixel/unity-build
        with:
          build-target: ${{ matrix.build-target }}

      - name: Unity Build No Tests (${{ matrix.build-target }})
        uses: ./ #RageAgainstThePixel/unity-build
        with:
          build-target: ${{ matrix.build-target }}
          test: false

      - name: Unity Build No Artifacts (${{ matrix.build-target }})
        uses: ./ #RageAgainstThePixel/unity-build
        with:
          build-target: ${{ matrix.build-target }}
          publish-artifacts: false
```
