### ISSUE TITLE
Github workflow fails as it exhaust all available CPU even if I upgraded on  Github Enterprise 

### ISSUE THREAD

**Issue by ggkiokas** [actions/runner-images#10244]
### Description

Github workflow fails as it exhausts all available CPU even I upgraded on  Github Enterprise.
Please I need assistance for understanding how I can have larger runners

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/Seafair/poseidon/actions/runs/9975020032/job/27563828236

### Is it regression?

yes

### Expected behavior

Workflow should run without problems

### Actual behavior

Workflow fails with an error

### Repro steps

Please see the logs of this workflow:
https://github.com/Seafair/poseidon/actions/runs/9975020032/job/27563828236

**Comment by Prabhatkumar59** [comment]
Hi @ggkiokas - Thank you for bringing this issue to us. We are looking into this issue and will update you shortly on this issue after investigating.

**Comment by ggkiokas** [comment]
Thank you @Prabhatkumar59 ! Please lmk how I can switch to larger runners. I thought by default Github Enterprise plan includes them

**Comment by Prabhatkumar59** [comment]
@ggkiokas - Thanks for your response:)
To switch to larger runners on GitHub Actions, especially when you're facing CPU and disk space limitations, you need to make some configurations. GitHub Enterprise does offer options for larger runners, but you need to explicitly configure your workflows to use them. Below are the detailed steps and options for using larger runners. You can trying using below steps:-

**Check Available Runner Sizes**: 
You can verify the available runner sizes in your GitHub Enterprise setup. This information is typically available in your GitHub Enterprise documentation (https://docs.github.com/en/enterprise-server@3.13) 

**Specify Larger Runners in Workflow**: 
You can also update your GitHub Actions workflow configuration to specify a larger runner.

To make it easier for you, i am providing an example how to specify a larger runner in your workflow configuration:-

```
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, large]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        echo "Building the project..."
    - name: Test
      run: |
        echo "Running tests..."


```

**Using Self-Hosted Runners**
If GitHub-hosted runners are not sufficient, you can use self-hosted runners, which can be configured with more powerful hardware.

A. Set Up Self-Hosted Runners:

Follow the GitHub documentation to set up self-hosted runners: [Self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).


B. Specify Self-Hosted Runner in Workflow:

Use the **runs-on** keyword to specify the self-hosted runner.

```
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name:

```
So by suing above steps, you can utilize larger runners to ensure your workflows run smoothly without exhausting available CPU or disk space.
