### ISSUE TITLE
(Ubuntu 22.04) pip version discrepancy

### ISSUE THREAD

**Issue by melange396** [actions/runner-images#10346]
### Description

Recent `ubuntu-latest` (`22.04`) runner image changed to include `pip` version `24.x` instead of `22.0.2` [as claimed](https://github.com/actions/runner-images/blob/ubuntu22/20240721.1/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L39).

This seems unintended.  If not, consider updating the image's release notes and readme.

See explanation and workaround here: https://github.com/cmu-delphi/delphi-epidata/pull/1503

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`20240721.1.0` failed: https://github.com/cmu-delphi/delphi-epidata/actions/runs/10095233705/job/27915622079#step:1:10

### Is it regression?

yes; most recent run with `20240526.1.0` succeeded: https://github.com/cmu-delphi/delphi-epidata/actions/runs/9290024871/job/25565314861#step:1:9

### Expected behavior

i expect `pip` version `22.0.2` as noted here:
https://github.com/actions/runner-images/blob/ubuntu22/20240721.1/images/ubuntu/Ubuntu2204-Readme.md?plain=1#L39

### Actual behavior

we get `pip` version `24.1.2` as seen here:
https://github.com/cmu-delphi/delphi-epidata/actions/runs/10096915539/job/27920539469#step:5:10

### Repro steps

1. run a GH action with `runs-on: ubuntu-latest`
2. execute a step with `run: pip -V`
3. observe version mismatch

**Comment by RaviAkshintala** [comment]
@melange396 Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by xchen218** [comment]
Same issue in Ubuntu20.04.
Pip is declared to be 20.0.2 but some cmds that are legal with pip < 22 are reporting errors.

**Comment by RaviAkshintala** [comment]
Hi @melange396 We have followed your repro steps for ubuntu-latest. Kindly confirm.
```
name: Check pip Version

on: [push, pull_request]

jobs:
  check-pip-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check pip version
      run: pip -V
  ```
![image](https://github.com/user-attachments/assets/88201536-93ff-4fcd-ba30-2c853971ef65)

**Comment by melange396** [comment]
looks like you may also need:
```yaml
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
```
just [as we use](https://github.com/cmu-delphi/delphi-epidata/blob/8746ff2ef7a936bb93628bc1358471d7c6c4f5f8/.github/workflows/update_gdocs_data.yml#L13-L16), to get this output:
![image](https://github.com/user-attachments/assets/a82f7b00-f5fc-44b0-b6d4-47c3bc7b2b7b)

**Comment by RaviAkshintala** [comment]
Hi @melange396 We have followed your repro steps for ubuntu-latest. Kindly confirm.
```

name: Check pip Version
on: [push, pull_request]

jobs:
  check-pip-version:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install pip version 22
      run: |
        python -m pip install --upgrade pip==22.0.0
        
    
    - name: Check pip version
      run: pip -V
   ```
   
<img width="1461" alt="image" src="https://github.com/user-attachments/assets/16e0775c-abf4-422b-8804-5a803c78aef9">
