### ISSUE TITLE
pip and python3 mismatch on macos-14 runners

### ISSUE THREAD

**Issue by tstellar** [actions/runner-images#10385]
### Description

It appears that the default pip binary and default python3 binary on the macos-14 runners use different python installs.  So any python modules you install via pip are cannot be found by python3.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Version: 20240728.1

https://github.com/tstellar/llvm-project/actions/runs/10223278047/job/28289331074

### Is it regression?

Yes, it was working with 20240722.3

### Expected behavior

Python3 should be able to import modules installed via pip.

### Actual behavior

```
pip install pygithub
python3 -c 'import github'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'github'
```

### Repro steps

You can reproduce the problem with this workflow:

```
name: Test Python

on:
  push:

permissions:
  contents: read # Default everything to read-only

jobs:
  test-python:
    runs-on: macos-14
    steps:
      - shell: bash
        run: |
          pip install pygithub
          python3 -c 'import github'
```
