### ISSUE TITLE
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 72 MB. How to fix this ?

### ISSUE THREAD

**Issue by sagarkalankar1** [actions/runner-images#10386]
### Description

- I am using 'ubuntu-latest' as github runner for my pipeline.
- My GitHub Actions pipeline defines a workflow for building and publishing an Android project to Firebase App Distribution.
- My pipeline sometimes given warning - "You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 72 MB" and pipeline fails.

- Seeing other github issues similar to this one, I found and tried a workaround as below:-

sudo rm -rf /usr/share/dotnet
sudo rm -rf /opt/ghc
sudo rm -rf "/usr/local/share/boost"
sudo rm -rf "$AGENT_TOOLSDIRECTORY"

But above folders does not exist when I tried viewing folders on my github runner 'ubuntu-latest'.

I can see below files and folders:-
36G	    /usr
23G	    /usr/local
13G	    /usr/local/lib
12G	    /usr/local/lib/android/sdk
12G	    /usr/local/lib/android
12G	    /opt
8.5G    /opt/hostedtoolcache
7.8G	    /usr/local/lib/android/sdk/ndk
6.7G	/usr/lib
5.6G	/usr/share
5.5G	/usr/local/.ghcup/ghc
5.5G	/usr/local/.ghcup
5.0G	/opt/hostedtoolcache/CodeQL/2.18.1/x64/codeql
5.0G	/opt/hostedtoolcache/CodeQL/2.18.1/x64
5.0G	/opt/hostedtoolcache/CodeQL/2.18.1
5.0G	/opt/hostedtoolcache/CodeQL
3.1G	    /swapfile
3.0G	/opt/hostedtoolcache/CodeQL/2.18.1/x64/codeql/swift
2.8G	/usr/local/.ghcup/ghc/9.10.1

What can I do for this issue ?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner version: '2.317.0'

### Is it regression?

It is occuring randomly.

### Expected behavior

It should not give this warning and build should be completed successfully and build should not fail due to disk space issue.

### Actual behavior

My pipeline sometimes gives warning - "You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 72 MB" and pipeline fails.

### Repro steps

This issue comes due to disk space issue of github runner.

**Comment by Prabhatkumar59** [comment]
Hi @sagarkalankar1 -Thank you for bringing this issue to our attention. We will update you on this issue after investigating.

**Comment by danibonilha** [comment]
I'm facing a similar issue with an android build that was working fine last week. Now it fails with `java.io.IOException: No space left on device`

**Comment by Prabhatkumar59** [comment]
Hi @sagarkalankar1 - You can try the following strategies to free up space and optimize your pipeline:

A. **Clean Up Unnecessary Directories and Files**
You can add steps in your workflow to remove unnecessary directories and files to free up space.

```
name: Build and Publish Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Remove unnecessary directories to free up space
      run: |
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y your-required-packages

    - name: Build the Android project
      run: ./gradlew build

    - name: Publish to Firebase App Distribution
      run: |
        # Your commands to publish the build to Firebase

```
B. **Cache Dependencies**
Use caching to avoid re-downloading dependencies, which can save space and speed up builds.

    ```
- name: Cache Gradle files
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
```

C. **Optimize Gradle Configuration**

Optimize your Gradle configuration to reduce the amount of data generated during builds.

Add the following to your **gradle.properties**:

```
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
```
D. If disk space continues to be an issue, consider using self-hosted runners with larger disk space.

E. **Monitor Disk Usage**
Add steps to monitor disk usage throughout the build process.

    ```
- name: Check disk usage
      run: df -h

    - name: Check directory sizes
      run: du -sh /usr/local/* /opt/* /usr/* | sort -hr
```
F. **For your understanding I am providing an example of the workflow with added cleanup steps**:-

```
```
name: Build and Publish Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Remove unnecessary directories to free up space
      run: |
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y your-required-packages

    - name: Build the Android project
      run: ./gradlew build

    - name: Publish to Firebase App Distribution
      run: |
        # Your commands to publish the build to Firebase

    - name: Check disk usage
      run: df -h
```

    - name: Check directory sizes
      run: du -sh /usr/local/* /opt/* /usr/* | sort -hr
```

By using above steps, you can try to manage disk space and reduce the likelihood of your builds failing due to insufficient disk space.

**Comment by danibonilha** [comment]
> I'm facing a similar issue with an android build that was working fine last week. Now it fails with `java.io.IOException: No space left on device`

The issue seems to be with the ubuntu-latest image since the pipeline works if I run on an mac-os image and it was working before the latest update.

Was working: 
Image: ubuntu-22.04
Version: 20240721.1.0

Is failing: 
Image: ubuntu-22.04
Version: 20240730.2.0

**Comment by mantljosh** [comment]
We are running into a similar issue - we run elasticsearch in docker that we use in our test suite, and we get an error `high disk watermark [90%] exceeded` which prevents it from working. We started observing this when the image changed to `20240730.2.0` - last successful run was on `20240721.1.0`

**Comment by alainib** [comment]
same probleme for me

```
Run df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   [6](https://github.com/xxx/actions/runs/10262882021/job/28393484095#step:16:7)4G  8.7G  89% /
tmpfs           3.9G  172K  3.9G   1% /dev/shm
tmpfs           1.6G  1.1M  1.6G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
tmpfs           [7](https://github.com/xxx/actions/runs/10262882021/job/28393484095#step:16:8)93M   12K  793M   1% /run/user/1001
```


i just run clean action before with this script 



```
name: Free Disk Space (Android)

on:
  workflow_dispatch: # To trigger manually

jobs:
  free-disk-space:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
```


any solution please ?

**Comment by Prabhatkumar59** [comment]
@alainib @danibonilha @mantljosh - By this week, new image version will be rolled out. So, kindly try once after new image version rolled out.
However, for you, I am providing an updated workflow that integrates more aggressive cleanup steps:-

```
name: Build and Publish Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify a fixed version of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Free Disk Space Before Build
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y your-required-packages

    - name: Cache Gradle files
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build the Android project
      run: ./gradlew build

    - name: Publish to Firebase App Distribution
      run: |
        # Your commands to publish the build to Firebase

    - name: Free Disk Space After Build
      run: |
        echo "Disk space before post-build cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        echo "Disk space after post-build cleanup:"
        df -h
```
**Explanation**:- 
**Pre-Build Cleanup**:

The script cleans up various large directories (/**usr/local/.ghcup**, /**opt/hostedtoolcache/CodeQL**, /**usr/local/lib/android/sdk/ndk**, /**usr/share/dotnet**, /**opt/ghc**, /**usr/local/share/boost**) to free up space.
**df -h** is used to show the disk space before and after cleanup for monitoring purposes.
**Post-Build Cleanup**:

Similar cleanup steps are performed after the build to ensure any temporary files created during the build process are removed.
**df -h** is again used to show the disk space before and after cleanup.

By this approach, you should be able to manage disk space more effectively and prevent build failures due to insufficient disk space.

**Comment by alainib** [comment]
@Prabhatkumar59  wow thank you for fast answer and response :) 
 
 i will try it . what is the best approach please ?
 1) add this to the yml script who fail and run it each time 
 2) create another yaml file and run it only when needed 
 
 i'm not sure if multiples yml file share folders like in macos/linux etc or each one have it's one space like in docker and running  cleanup yml file whould not affect my reel yml file . thanks

**Comment by mantljosh** [comment]
FWIW we changed `ubuntu-latest` to `ubuntu-24.04` and it seems to be working okay with the new version

**Comment by Prabhatkumar59** [comment]
Hi @alainib - Here are the best approaches which I am providing you to handle the disk space issue effectively:

**Approach 1**: **Add Cleanup Steps to the Failing YAML File**
Adding cleanup steps directly to the failing YAML file ensures that cleanup is performed every time the workflow runs. This approach guarantees that disk space issues are addressed before the build process starts.

Updated YAML File Example:

```
name: Build and Publish Android Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Free Disk Space Before Build
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y your-required-packages

    - name: Cache Gradle files
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build the Android project
      run: ./gradlew build

    - name: Publish to Firebase App Distribution
      run: |
        # Your commands to publish the build to Firebase

    - name: Free Disk Space After Build
      run: |
        echo "Disk space before post-build cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        echo "Disk space after post-build cleanup:"
        df -h

```
This approach 1 ensures that cleanup is performed before every build, preventing disk space issues from affecting the build process.


**Approach 2**: **Create a Separate Cleanup YAML File**

You can try to create a separate YAML file dedicated to disk space cleanup. This approach allows you to trigger the cleanup workflow manually or on a schedule, without cluttering the main build YAML file.

Cleanup YAML File Example:


```
name: Free Disk Space

on:
  workflow_dispatch:  # Trigger manually
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h
```
**Main Build YAML File (Simplified) which is as follows:-**

```
name: Build and Publish Android Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y your-required-packages

    - name: Cache Gradle files
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build the Android project
      run: ./gradlew build

    - name: Publish to Firebase App Distribution
      run: |
       # Your commands to publish the build to Firebase
```
       
 This approach 2 provides flexibility, allowing you to trigger cleanup manually or on a schedule. This keeps the main build YAML file clean and focused.

So, by the above approaches, you will able to fix those issues.
