### ISSUE TITLE
The hosted runner encountered an error while running your job. (Error Type: Disconnect).

### ISSUE THREAD

**Issue by sagarkalankar1** [actions/runner-images#10401]
### Description

- I am using 'ubuntu-latest' as github runner for my pipeline.
- My GitHub Actions pipeline defines a workflow for building and publishing an Android project to Firebase App Distribution.
- My pipeline sometimes failing with error - "**The hosted runner encountered an error while running your job. (Error Type: Disconnect)**." 
  
- I am getting one more error as below and pipeline fails:-  
   "**Received request to deprovision: The request was cancelled by the remote provider.**" 

- I am getting one more error as below and pipeline fails:-
  "**The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled**"

- I am getting one more error as below and pipeline fails:-  
  "The hosted runner: GitHub Actions 339 lost communication with the server. Anything in your workflow that terminates the 
  runner process, starves it for CPU/Memory, or blocks its network access can cause this error."  

I have already added the clean up steps as below and now I am not getting the error of limited disk space but I am getting above errors and pipeline is failing.
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

What can I do for this issue ?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner version: '2.317.0'

### Is it regression?

It is occuring randomly.

### Expected behavior

It should not give this warning and build should be completed successfully and build should not fail due to disk space issue.

### Actual behavior

- My pipeline sometimes failing with error - "**The hosted runner encountered an error while running your job. (Error Type: Disconnect)**." 
  
- I am sometimes getting one more error as below and pipeline fails:-  
   "**Received request to deprovision: The request was cancelled by the remote provider.**" 

- I am sometimes getting one more error as below and pipeline fails:-
  "**The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled**"

- I am sometimes getting  one more error as below and pipeline fails:-  
  "The hosted runner: GitHub Actions 339 lost communication with the server. Anything in your workflow that terminates the 
  runner process, starves it for CPU/Memory, or blocks its network access can cause this error."  

### Repro steps

Using github runner 'ubuntu-latest' for building android applications and pushing build to firebase app distribution.

**Comment by Prabhatkumar59** [comment]
Hi @sagarkalankar1 - As I can see, the errors you're encountering, such as "Disconnect," "Deprovision," and "Shutdown signal," indicate that the GitHub-hosted runners are facing issues that go beyond disk space. These errors are often related to resource constraints, runner decommissioning, or network issues. 
Here's how you can address these problems:

A. **Review Resource Usage**

**High Resource Consumption**: Ensure that your build process isn't consuming excessive CPU, memory, or disk resources, which could lead to the runner being unresponsive or terminated.
**Optimize Build Process**: Consider optimizing your build process by breaking it down into smaller steps or jobs, reducing the complexity of each job, and minimizing resource-intensive operations.

B. **Increase Timeout and Retry Logic**

**Increase Timeout**: Add a timeout setting to your workflow steps to prevent premature job termination.
Retry Logic: Implement retry logic to re-run specific steps if they fail due to transient errors.
**For you, I am providing an example as well which is as follows:-**

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Android project
      run: ./gradlew build
      timeout-minutes: 60  # Adjust the timeout as needed
      continue-on-error: true

    - name: Retry if build fails
      run: ./gradlew build
      if: failure() && steps.checkout.outcome == 'success'  # Retry only if the build fails

```

C. **Split the Workflow into Multiple Jobs**
Split Complex Workflows: Break your workflow into multiple smaller jobs that can run independently. This approach can help reduce the load on the runner and prevent it from being overwhelmed.

**Example as follows:-**

```
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Build Android project
      run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Publish to Firebase App Distribution
      run: ./gradlew publish

```

D. **Monitor and Troubleshoot Network Issues**
**Network Stability**: Ensure that there are no network issues affecting the hosted runners. Since the errors mention losing communication with the server, monitoring network stability could be crucial.
**Run Diagnostics**: Add diagnostic steps to check network availability and connectivity during the workflow.

**Example as follows:-**

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check network connectivity
      run: ping -c 4 google.com

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Android project
      run: ./gradlew build
```

By using above steps, it should help in mitigating the random failures and improve the stability of your pipeline.
I hope, this will resolve your issues.

**Comment by MichaelPesce** [comment]
@Prabhatkumar59 
looking at C:

if you checkout in the prepare job, do you have access to the checked out repository in the following jobs?

**Comment by Prabhatkumar59** [comment]
Hi @MichaelPesce - When you split the workflow into multiple jobs, the files and artifacts created in one job are not automatically available in the subsequent jobs. To solve this, you can use GitHub Actions' artifact storage to pass the checked-out code or any other files from one job to another.

Here's an updated version of the workflow which I am providing below:-
```
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive the repository
        run: tar -czf repo.tar.gz .
      
      - name: Upload repository as artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo
          path: repo.tar.gz

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Download repository artifact
        uses: actions/download-artifact@v3
        with:
          name: repo

      - name: Extract repository
        run: tar -xzf repo.tar.gz

      - name: Build Android project
        run: ./gradlew build

      - name: Archive build artifacts
        run: tar -czf build.tar.gz app/build/outputs
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Extract build artifacts
        run: tar -xzf build.tar.gz

      - name: Publish to Firebase App Distribution
        run: ./gradlew publish

```
**Explanation**:
**Prepare Job**:

Checks out the repository.
Archives the repository into a **repo.tar.gz** file.
Uploads this archive as an artifact.
**Build Job**:

Downloads the **repo.tar.gz** artifact from the **prepare** job.
Extracts the repository.
Builds the Android project.
Archives the build artifacts (like APKs) and uploads them as an artifact.
**Deploy Job:**

Downloads the build artifacts from the **build** job.
Extracts the build artifacts.
Publishes the project to Firebase App Distribution.
By this way, each job has access to the files it needs from the previous jobs.
