### ISSUE TITLE
nvm v0.40.0 introduced error if `.nvmrc` exists

### ISSUE THREAD

**Issue by Skenvy** [actions/runner-images#10432]
### Description

See https://github.com/nvm-sh/nvm/issues/3405.

Prior to the current nvm version, you could source `$NVM_DIR/nvm.sh` without issue, but the current nvm version, `v0.40.0` appears to cause an error when trying to source, if you already have an `.nvmrc` present.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-22.04
20240804.1.0
[link](https://github.com/Skenvy/Collatz/actions/runs/10281408675/job/28654085524)

### Is it regression?

20240730.2.0 [link](https://github.com/Skenvy/Collatz/actions/runs/10246321949/job/28343171592)

### Expected behavior

Should be able to source nvm.sh with an nvmrc present.

### Actual behavior

"Error code 3"

### Repro steps

```yaml
name: Test nvm versions with nvmrc
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
env:
  UNAUTO_NODE_VERSION: v18.18.2 # "NODE_VERSION" is read by the nvm install script.
jobs:
  nvmrc-present-install-nvm:
    strategy:
      fail-fast: false
      matrix:
        # including all from the previous version on the runner, 'v0.39.5', to the current version, 'v0.40.0'
        nvm-version: ['v0.39.5', 'v0.39.6', 'v0.39.7', 'v0.40.0']
    runs-on: ubuntu-latest
    steps:
    - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/${{ matrix.nvm-version }}/install.sh | bash
    - run: echo "$UNAUTO_NODE_VERSION" > .nvmrc
    - run: source $NVM_DIR/nvm.sh && nvm install $(cat .nvmrc)
  nvmrc-present-default-nvm: # v0.40.0 atm
    runs-on: ubuntu-latest
    steps:
    - run: echo "$UNAUTO_NODE_VERSION" > .nvmrc
    - run: source $NVM_DIR/nvm.sh && nvm install $(cat .nvmrc)
  nvmrc-absent-default-nvm: # v0.40.0 atm
    runs-on: ubuntu-latest
    steps:
    - run: source $NVM_DIR/nvm.sh && nvm install $UNAUTO_NODE_VERSION
```
