### ISSUE TITLE
CRAC JDK is not usable as criu needs SUID permissions to work

### ISSUE THREAD

**Issue by snicoll** [actions/runner-images#10466]
**Description:**
I am trying to use CRAC in GitHub Actions. With the following definition:

```
 - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: 'jdk+crac'
          distribution: 'zulu'
```

I can't use `criu` as it's missing `SUID` permissions. Courtesy of @wkia, it would work if the archive was extracted using `sudo tar xz`.

There's not much, but here it is failing: https://github.com/spring-projects/spring-lifecycle-smoke-tests/actions/runs/10032558509/job/27724454193

With a manual setup (see https://github.com/spring-projects/spring-lifecycle-smoke-tests/commit/efd6ee22b9eafdf1276739574ff57d67e1156bba), it is working: https://github.com/spring-projects/spring-lifecycle-smoke-tests/actions/runs/10039511315

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

**Expected behavior:**
`criu` works out-of-the-box

**Actual behavior:**
`criu` fails as it's missing SUID permissions

**Comment by Prabhatkumar59** [comment]
Hi @snicoll - Thank you for bringing this issue to our attention. We will look into this issue and will update you on this issue after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @snicoll - From the above comments, as I can see that you want an automatic setup using the **actions/setup-java@v3** action and considering that **jdk+crac** is a supported distribution, here's a more automated approach which I am providing to you:-

**Proposal for Automated Setup**
 You can try using a combination of **setup-java** and a custom script to automate the SUID fix after the JDK is installed:
 
 ```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install necessary dependencies
      run: sudo apt-get update && sudo apt-get install -y criu

    - name: Set up Java with CRAC support
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: 'jdk+crac'
        distribution: 'zulu'

    - name: Fix CRIU SUID Permissions
      run: |
        sudo find $JAVA_HOME -name criu | sudo xargs chmod u+s

    - name: Verify CRAC JDK with CRIU
      run: java -version

```
**Providing explanation for you as well:**-
**Install Dependencies**: The necessary CRIU package is installed.
**Set up Java**: The **actions/setup-java@v3** action installs the **jdk+crac**.
**Fix Permissions**: After the JDK is installed, the script finds the CRIU executable and sets the SUID bit using **chmod u+s**.
**Verify Installation**: Finally, it verifies the setup by running **java -version**.

**And after that Next Steps would be**:-
**Automation Request**: If you believe this setup should be automated by the GitHub action itself, it would be best to raise an issue or contribute to the **actions/setup-java** repository to handle CRIU and SUID settings automatically when the **jdk+crac** distribution is selected. 

Also, to automate CRIU usage with the **jdk+crac** distribution in GitHub Actions, you can suggest modifying the **actions/setup-java** action to include a post-installation step that runs **sudo tar xz** to set the necessary SUID permissions. This would allow the **jdk+crac** distribution to work out-of-the-box without manual intervention.

These above solution ensures that the process is as automated as possible within the constraints of the current GitHub Actions environment and you should now get resolution for your query.
