### ISSUE TITLE
Darcs package missing for Ubuntu 24.04 runners

### ISSUE THREAD

**Issue by tmcgilchrist** [actions/runner-images#10476]
### Description

The `darcs` package is missing for Ubuntu 24.04 runners. It is available on 22.04 runners.
It is also available on regular Ubuntu 24.04 and 22.04 running on desktop docker.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.319.1'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
Download action repository 'ocaml/setup-ocaml@v3' (SHA:190141893c2e2eb492dfe4973030d58ad763a5dc)
Complete job name: build (ubuntu-24.04, 5.2)

### Is it regression?

Yes

### Expected behavior

Darcs package should be available and installable as per regular Ubuntu 24.04 LTS

### Actual behavior

Darcs package is missing from the package index available to Ubuntu 24.04 runner

### Repro steps

Using this configuration should demonstrate the failure:
```
name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Update Ubuntu
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-cache search darcs
          sudo apt-get install darcs
```

Ubuntu 24.04 will fail because it can't install `darcs` while 22.04 will pass.
