### ISSUE TITLE
On `windows-latest` `pkg-config` reports zlib in the default include path which is not available

### ISSUE THREAD

**Issue by mmomtchev** [actions/runner-images#10487]
### Description

On `windows-latest` `pkg-config` reports zlib in the default include path which is not available

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/mmomtchev/magickwand.js/actions/runs/10549844848/job/29225358447

### Is it regression?

No

### Expected behavior

`pkg-config` does not report `zlib` or reports it with the correct directory

### Actual behavior

On `windows-latest` `pkg-config` reports zlib in the default include path which is not available

### Repro steps

```yaml
name: Node.js CI

on:
  push:
    branches: ["*"]

jobs:
  native:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: 
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-12
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          pkg-config --cflags zlib
          pkg-config --libs zlib
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - run: cc -o test-zlib test-zlib.c
        if: runner.os != 'Windows'
      - run: cl -o test-zlib test-zlib.c
        if: runner.os == 'Windows'
```

```c
#include <zlib.h>

int main() {
	return 0;
}
```
