### ISSUE TITLE
Julia and R are missing on macos arm64

### ISSUE THREAD

**Issue by IanButterworth** [actions/runner-images#10517]
### Description

New issue in case the discussion at https://github.com/actions/runner-images/issues/9394 is missed

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.319.1'

### Is it regression?

No

### Expected behavior

These runtimes are included.

### Actual behavior

These runtimes are not included.

### Repro steps

NA

**Comment by giordano** [comment]
If the concern was about upstream support on the new platform, Julia has [tier 1 support on Apple Silicon](https://julialang.org/downloads/#supported_platforms) (aarch64-apple-darwin), and [it has been so for over one year](https://julialang.org/blog/2023/04/julia-1.9-highlights/#apple_silicon_achieves_tier_1_status) now

**Comment by erik-bershel** [comment]
Hey @IanButterworth!

It was decided to remove the specified packages from the image due to the fact that they can be installed in less than a minute and also due to the need to take into account maintenance needs. I checked - the situation has not changed. Both packages can be quickly and easily installed at runtime using both official sources and the pre-installed Homebrew package manager. For example:

```yml
jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14, macos-13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Julia
        run: |
          curl -fsSL https://install.julialang.org | sh -s -- -y
          # Depending on which shell you are using, run one of the following
          # commands to reload the PATH environment variable:
          . /Users/runner/.bashrc
          . /Users/runner/.bash_profile
          . /Users/runner/.zshrc
          julia --version
          juliaup --version
      - name: R
        run: |
          brew install r
          r --version
```

Unfortunately, the reasons for which the decision was made have not changed. We have to work to remove as many pre-installed packages as possible that are less frequently used and at the same time can be installed quickly and easily by users from new images, both to simplify the image build and maintenance process and to free up more available disk space.
