### ISSUE TITLE
mac-latest runners no longer provision enough disk space

### ISSUE THREAD

**Issue by StephenHodgson** [actions/runner-images#10520]
### Description

Previously the mac-latest runners would have enough disk space to install a single version of the Unity Editor to build my games with, but now that is no longer the case.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link
```
Current runner version: '2.319.1'
Operating System
  macOS
  14.6.1
  3G93
Runner Image
  Image: macos-14-arm64
  Version: 20240827.4
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240827.4/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240827.4
Runner Image Provisioner
  2.0.84.1+6d6c56aa16f1b9c7dd7935df5d63980397e4def
```
### Is it regression?

yes

### Expected behavior

Enough disk space to install the required software for the Unity Engine and download and build my game.

Previous version of the runner had enough space.
Prev good run: https://github.com/buildalon/unity-setup/actions/runs/10542831903

### Actual behavior

Running out of disk space, when previously there was enough.

> [!WARNING]
> You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 53 MB

### Repro steps

```yaml
name: validate
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest]
        unity-versions:
          - 2019.x
          - 2020.x
          - 2021.x
          - 2022.x
          - 6000.x
        include:
          - os: ubuntu-latest
            build-targets: StandaloneLinux64
          - os: windows-latest
            build-targets: StandaloneWindows64
          - os: macos-latest
            build-targets: StandaloneOSX
    steps:
      - uses: buildalon/unity-setup@v1
        with:
          unity-version: ${{ matrix.unity-versions }}
          build-targets: ${{ matrix.build-targets }}
```
