### ISSUE TITLE
Error: The process dotnet.exe failed with exit code 1

### ISSUE THREAD

**Issue by verback2308** [actions/runner-images#10621]
### Description

Copied from [Azure Pipelines Tasks](https://github.com/microsoft/azure-pipelines-tasks/issues/20424)

All our pipelines started crashing with an error on dotnet publish since last Saturday (September 14):
![image](https://github.com/user-attachments/assets/e3e6783a-2ebc-4880-a976-c8872135e7d2)

There are no details in the logs except that the command returned error 1:
![image](https://github.com/user-attachments/assets/3c08d696-0537-49a6-afa8-91f4ba90847f)

Version of the last successful pipeline the same as other - 2.245.1

Old pipelines for previous branches were checked - they also started crashing with an error, however - code is the same:

![image](https://github.com/user-attachments/assets/69e3c9e5-156e-4deb-9d52-dc14ce9a62c0)

Diff between latest successful (left) and current (right) build:
<img width="1985" alt="image" src="https://github.com/user-attachments/assets/2685f772-0a8b-45de-bc07-593cc2311b4e">

Temporarily switched to a self-hosted agent, everything works there.
Solution compiles on a dev machine (osx, win) with a success.

upd1:  just found a workaround - added step with SDK installation:
```yml
- task: UseDotNet@2 
displayName: 'Install .NET Core SDK' 
inputs: version: 7.x 
performMultiLevelLookup: true 
includePreviewVersions: true # Required for preview versions
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20240912.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20240912.1/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240912.1

### Is it regression?

-

### Expected behavior

Build should finish with a success

### Actual behavior

The process dotnet.exe failed with exit code 1

### Repro steps

```yml
pool:
  vmImage: 'windows-latest'

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  pvs-solution: 'PVS/PVS.sln'
  client: 'PVS.Clients.WebClient.Core'

steps:

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - task: Cache@2
    displayName: 'NuGet Cache'
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
      restoreKeys: |
        nuget | "$(Agent.OS)"
        nuget
      path: '$(NUGET_PACKAGES)'
      cacheHitVar: 'CACHE_RESTORED'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet packages for PVS'
    condition: ne(variables.CACHE_RESTORED, true)
    inputs:
      command: 'restore'
      restoreSolution: '$(pvs-solution)'
      feedsToUse: 'config'
      nugetConfigPath: 'PVS/NuGet.Config'

  - task: DotNetCoreCLI@2
    displayName: 'Publish $(Client)'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'PVS/$(Client)/$(Client).csproj'
      arguments: '-c Release --no-self-contained -f net7.0 /p:ExcludeApp_Data=False -o "$(Build.BinariesDirectory)/$(Client)"'
      zipAfterPublish: false
      modifyOutputPath: false
```
