### ISSUE TITLE
sudo update permission failed and sudo not found in ubuntu-latest

### ISSUE THREAD

**Issue by gblikas** [actions/runner-images#10693]
### Description

This minimal example fails for me on github actions: 

```yml
name: main

on:
  push:
    branches: [ staging, main ]
  pull_request:
      branches: [ staging, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cache-path: ${{ github.workspace }}/vcpkg_cache
          - os: macos-latest
            cache-path: ${{ github.workspace }}/vcpkg_cache
    env:  
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ matrix.cache-path }}

    steps:
    - name: install sudo
      if: matrix.os == 'ubuntu-latest'
      run: apt update && apt install sudo
```

Produces the error, 

```
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches ([13]
```

And, when using `sudo apt update` i get a "sudo not found" error. 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest-16-cores
> Ubuntu Latest (22.04) · 16-cores · 64 GB RAM · 600 GB SSD

### Is it regression?

no

### Expected behavior

I should be able to either (1) not use `sudo` and have the update work or (2) the latest image should `sudo`. If this is a configuration error, a more helpful error is expected.

### Actual behavior

See above*

### Repro steps

Run the provided minimal example

**Comment by hemanthmanga** [comment]
Hi @gblikas, Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by gblikas** [comment]
@hemanthmanga let me know if you need any more information.

**Comment by hemanthmanga** [comment]
Hi @gblikas, Sudo is available in Ubuntu-latest, In GitHub Actions you usually do not have to install sudo, since the runner already has elevated privileges, could you please try with the below work around for ubuntu-latest,
```
name: main

on:
  push:
    branches: [ staging, main ]
  pull_request:
    branches: [ staging, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache

    steps:
    - name: install sudo
      run: |
        sudo apt update
        sudo apt install -y sudo   #### sudo available in ubuntu
```

**Comment by gblikas** [comment]
> Hi @gblikas, Sudo is available in Ubuntu-latest, In GitHub Actions you usually do not have to install sudo, since the runner already has elevated privileges,Thanks.

@hemanthmanga as mentioned in my main post, I tried it both ways... same error.

**Comment by directentis1** [comment]
> Hi @gblikas, Sudo is available in Ubuntu-latest, In GitHub Actions you usually do not have to install sudo, since the runner already has elevated privileges,Thanks.

It also happened to me in the past few days (it didn't happen like that before, maybe because of some recent changes)

If I run with sudo, `sudo: command not found error`, 
but if not run with sudo, `Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)`
![image](https://github.com/user-attachments/assets/55b56845-9d30-4ac9-9834-d9d293aee8a5)

**Comment by gblikas** [comment]
@hemanthmanga I tried deleting the old runners we allocated, and still the same issue. Have you successfully run the yml I sent you (above)?

**Comment by hemanthmanga** [comment]
Hi @gblikas, Could you please try the below work around and please find the sudo version in the attached snippets.
```

name: main

on:
  push:
    branches: [ staging, main ]
  pull_request:
    branches: [ staging, main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      
    steps:
      - name: sudo
        run: |
              sudo apt update
              sudo apt install -y sudo   ##### sudo available in ubuntu
              sudo -v
```
![image](https://github.com/user-attachments/assets/32988114-858a-4a02-8341-3d5fb6064fcb)

**Comment by gblikas** [comment]
> Hi @gblikas, Could you please try the below work around and please find the sudo version in the attached snippets.
> 
> ```
> 
> name: main
> 
> on:
>   push:
>     branches: [ staging, main ]
>   pull_request:
>     branches: [ staging, main ]
>   workflow_dispatch:
> 
> 
> jobs:
>   build:
>     runs-on: ${{ matrix.os }}
>     strategy:
>       matrix:
>         os: [ubuntu-22.04, ubuntu-24.04]
>     env:
>       VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
>       VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
>       
>     steps:
>       - name: sudo
>         run: |
>               sudo apt update
>               sudo apt install -y sudo   ##### sudo available in ubuntu
>               
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/166606741/373370584-32988114-858a-4a02-8341-3d5fb6064fcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTk4MjgsIm5iZiI6MTcyODQxOTUyOCwicGF0aCI6Ii8xNjY2MDY3NDEvMzczMzcwNTg0LTMyOTg4MTE0LTg1OGEtNGEwMi04MzQxLTNkNWZiNjA2NGZjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQyMDMyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDAxYjZlODZjZDVhNmVhZTZiYWMyNzkxZmVhYmE0YTI0OTc1ODZiYjI5ZTEyMzRiNDJhZTUzNTAwNzllNmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7mZVKJizPTdYEKePzpBFxpF6LFRPJaXm8y2SgybOCEE)

@hemanthmanga that worked fine.

**Comment by hemanthmanga** [comment]
Hi @gblikas, As mentioned earlier, the runner already has elevated privileges and there is no issues with sudo. please try the workaround given below, hopefully it will resolve your issue.
```
name: main

on:
  push:
    branches: [ staging, main ]
  pull_request:
    branches: [ staging, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cache-path: ${{ github.workspace }}/vcpkg_cache
          - os: macos-latest
            cache-path: ${{ github.workspace }}/vcpkg_cache
    env:  
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ matrix.cache-path }}

    steps:
    - name: install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y << Add your package here>>
```
