### ISSUE TITLE
cat: /etc/docker/daemon.json: No such file or directory

### ISSUE THREAD

**Issue by hansehe** [actions/runner-images#10697]
### Description

Hi, 

I'm using the docker github actions package to install docker for building container images:
- https://github.com/docker-practice/actions-setup-docker

But just yesterday, I continuously get this error in the github actions pipeline:
```
Run docker-practice/actions-setup-docker@master
check docker systemd status
check docker version
add apt source
update apt cache
show available docker version
remove default moby
install docker
check docker version
check docker systemd status
show default daemon json content
  /usr/bin/sudo cat /etc/docker/daemon.json
  cat: /etc/docker/daemon.json: No such file or directory
  Error: Error: The process '/usr/bin/sudo' failed with exit code 1
```

The job runs on ubuntu-latest (, with this setup:

```yaml
name: CD

on: 
  workflow_dispatch: {}
  push:
    tags: [ 'v*' ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_channel:
          - stable

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: ${{ matrix.docker_channel }}
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install requirements
        run: |
          pip install DockerBuildManagement
      
      - name: Publish
        run: |
          dbm -build -publish prod
```

I think it's a problem with some runners hosted by github since I tried the same job in another organization on github where it works.

After some digging, I then downgraded to ubuntu-22.04, and then it all works. So is there something wrong with ubuntu-24.04 and docker compatibility?

Best regards.
Hans Erik Heggem

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Is it regression?

ubuntu-22.04

### Expected behavior

To successfully install docker with docker-practice/actions-setup-docker@master

### Actual behavior

The docker installation fails with:
```
  /usr/bin/sudo cat /etc/docker/daemon.json
  cat: /etc/docker/daemon.json: No such file or directory
  Error: Error: The process '/usr/bin/sudo' failed with exit code 1
```

### Repro steps

Setup a github actions script with above configurations (maybe pinning to using ubuntu-24.04) and then the job fails with installing docker.

**Comment by RaviAkshintala** [comment]
Hi @hansehe Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating

**Comment by emarcey** [comment]
Is there any update on this? I am experiencing the same issue, which is preventing my PR checks from running

**Comment by emarcey** [comment]
@hansehe fwiw, I was able to work around just now by switching runners to ubuntu-22.04 instead of ubuntu-latest

**Comment by RaviAkshintala** [comment]
Hi @hansehe Please replace ubuntu-24.04 to ubuntu-22.04 for now, and test your changes. It should work.

**Comment by RaviAkshintala** [comment]
Hi @hansehe We are awaiting for your reply, Thanks.

**Comment by hansehe** [comment]
Hi, and yes, it works by using an earlier version of Ubuntu. And please tell us when the newest version works again, and thanks for your help.

**Comment by RaviAkshintala** [comment]
Hi @hansehe Could you please try with the below workaround. Hope your issue will be resolved, Thanks.

https://github.com/RaviAkshintala/runner-images-Ravi/actions/runs/11286832733/workflow#L18

**Comment by francesco-ballarin** [comment]
Hi @RaviAkshintala,
is there a solution that does not involve adding an extra action?

I do all the `docker pull`, `docker build`, `docker push` myself (rather than calling an action), and encounter the same issue as in the opening post.
The snippet of the action that triggers the error
```
      - name: Enable experimental docker features
        run: |
          sudo sed -i 's/}/,"experimental": true}/' /etc/docker/daemon.json
          sudo systemctl restart docker
```
and I can't work around this by not enabling the experimental docker features, because I need them later on in the action.

**Comment by hansehe** [comment]
Hey @RaviAkshintala , and thanks, for me this update (https://github.com/actions/runner-images/issues/10697#issuecomment-2406586001) works super

**Comment by anton-blashchuk-zoolatech** [comment]
@RaviAkshintala the issue is not resolved, please reopen the ticket

**Comment by henzeb** [comment]
I know this thread is closed, but for people looking for answers (as for me the specific image workaround didn't work):

the /etc/docker/daemon.json is not required by the docker daemon, so it runs with all the standards if it is not there. For this particular use case, a workaround would be creating the file containing an empty json object, before running this action. The file would look like this:

```json
{
}
```

For other situations, you can create the file yourself by adding it to the repo and copy when needed:

```yaml
- name: Configure docker daemon
  run: |
    sudo cp ./path/to/daemon.json /etc/docker/daemon.json
    sudo systemctl restart docker
```
