### ISSUE TITLE
libstdc++-14 bits/unicode.h in Ubuntu 24.04 is broken

### ISSUE THREAD

**Issue by tommie** [actions/runner-images#10725]
### Description

Based on investigation in https://github.com/tommie/v8go/issues/67.

My ubuntu-latest builds of libv8 started failing because of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115119.

The GCC 14 currently in Ubuntu 24.04 is broken for `v8/third_party/abseil-cpp/absl/base/internal/cycleclock.cc` with

    /usr/lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/unicode.h:807:4: error: expression is not assignable

The workaround is to

```yaml
  steps:
    - name: Remove GCC 14
      run: |
        # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115119
        sudo apt-get purge -yq gcc-14 g++-14 libstdc++-14-dev
        sudo apt-get autopurge -yq
```

The https://github.com/actions/runner-images/blob/ubuntu24/20240922.1/images/ubuntu/Ubuntu2404-Readme.md documentation only lists GCC 13 as installed version, which required some `dpkg -l` debugging. I see the #10636 tracking bug says all three latest versions are installed.

I suggest either updating docs, or removing GCC 14 until 14.2 is backported to Ubuntu 24.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

* Image: ubuntu-24.04
* Version: 20240922.1.0

https://github.com/tommie/v8go/actions/runs/11136183688/job/30947620891 (the Linux builds were failing because libgtk is also not installed in 24.04)

### Is it regression?

yes, 20240915.1.0 was fine: https://github.com/tommie/v8go/actions/runs/11024590821/job/30618097058

### Expected behavior

That libv8 compiles.

### Actual behavior

libv8 does not compile.

### Repro steps

See https://github.com/tommie/v8go/blob/master/.github/workflows/v8build.yml. (This is part of the v8upgrade workflow, but can also be run separately.)
