### ISSUE TITLE
macos-15 on macos-13-xlarge runners label 

### ISSUE THREAD

**Issue by marciorgb** [actions/runner-images#10813]
### Description

Upon running multiple parallel jobs on runners with the label `macos-13-xlarge`, we sometimes receive the macOS 15 operating system instead of the expected macOS 13.7

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

- Image: macos-13-arm64
- Version: 20241014.21

And

- Image: macos-15-arm64
- Version: 20241014.193

### Is it regression?

No

### Expected behavior

The label act as expected and the macos-13-xlarge only calls the Macos 13.7 OS

### Actual behavior

With multiple jobs at the same time the `macos-13-xlarge` label also runs in the Macos 15.9 OS

### Repro steps

Create a workflow with matrix that start multiple jobs  (10+) at the same time and sometimes the operational system is the macos 15

```
name: Workflow disptach test

on:
  workflow_dispatch: ~

jobs:
  run:
    strategy:
      matrix:
        tests: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: macos-13-xlarge
    steps:
      - name: Echo
        run: |
          echo "TRUE"
```
