### ISSUE TITLE
[macOS] OpenSSL 1.1 will be removed  and  OpenSSL 3 will be the default for all macOS images once [date not determined]

### ISSUE THREAD

**Issue by sarathrajsrinivasan** [actions/runner-images#10817]
### Breaking changes

OpenSSL 1.1 will be removed from all macOS images and the default version will be switched to OpenSSL 3.

### Target date

⚠️ **_We will notify you of planned changes when exact dates are set._** ⚠️

### The motivation for the changes

OpenSSL 1.1 has reached its end-of-life (EOL) and is no longer supported. Due to its deprecation, Homebrew has removed it from its available packages.

### Possible impact

If your library/project is not compatible with OpenSSL 3 and you build them based on default OpenSSL version - your workflow will be broken.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Use the below step in your workflow to download and install OpenSSL 1.1 manually
```
    - name : Install  OpenSSL 1.1 manually
      run : |
        wget https://www.openssl.org/source/openssl-1.1.1w.tar.gz
        tar -xvf openssl-1.1.1w.tar.gz
        cd openssl-1.1.1w
        ./config --prefix=/usr/local/openssl
        make
        sudo make install
        export PATH=/usr/local/openssl/bin:$PATH
```

**Comment by eregon** [comment]
This means currently some runs on macos-14 have openssl@1.1 and some don't:
https://github.com/eregon/setup-ruby/actions/runs/11724213556/job/32657603152

This is quite problematic because if something is built on macos-14 on a run with openssl@1.1 (and the software links to that) it can fail when that's later used in another run as openssl@1.1 `/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib` is gone.

**Comment by jorupp** [comment]
Is there a way to configure our build so we _only_ run on the `OpenSSL@3`-equipped images?  We can't add the `-legacy` flag we need for `OpenSSL@3` because it breaks when the build runs on an `openssl@1.1.1`-equipped image.

**Comment by jorupp** [comment]
We worked around it with `InstallAppleCertificate@2` by putting two copies of the task in our pipeline - one with `opensslPkcsArgs: -legacy` and one without, and with `continueWithError: true` on both so the one that fails won't fail our build.

**Comment by mikeharder** [comment]
Could this change be breaking `actions/setup-python` on Mac?

https://github.com/actions/runner-images/issues/10812#issuecomment-2463898503

**Comment by fengga** [comment]
> Is there a way to configure our build so we _only_ run on the `OpenSSL@3`-equipped images? We can't add the `-legacy` flag we need for `OpenSSL@3` (called within `InstallAppleCertificate@2`'s pre-job) because it breaks when the build runs on an `openssl@1.1.1`-equipped image, and we can't manually install `openssl@1.1.1` via a script because the call to `openssl` is in `InstallAppleCertificate@2`'s pre-job.

I'm facing the same problem and if rollout to openssl@3.0 all the `InstallAppleCertificate@2` task will be broken.
Even if I use a cert signed by openssl@3.0 there is still a problem:

`InstallAppleCertificate@2` will generate one command:

security import ***/MSALCPPAppleBuildCertificate_fgh.p12 -P *** -A -t cert -f pkcs12 -k ***/ios_signing_temp.keychain

which requires the MSALCPPAppleBuildCertificate_fgh.p12 signed by openssl@1.1

https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1385795&view=logs&j=9c650f88-aede-5522-025a-32fa3c2465b6&t=a74cb428-1f82-4e39-8054-c06bdb9b0377&l=20

**Comment by sarathrajsrinivasan** [comment]
Hi All,

We are currently reverting the change and keeping OpenSSL 1.1 in our images. It will be the default version for now.
Will keep you posted with the updates.

**Comment by dalemyers** [comment]
@sarathrajsrinivasan Why was this reverted? After having spent time adjusting our flows to make it work with v3, we now need to undo that work, causing more disruption. This is likely the case for many others.

**Comment by eregon** [comment]
@dalemyers There is no need to undo that work, openssl@3 is available before & after that change.

**Comment by dalemyers** [comment]
> @dalemyers There is no need to undo that work, openssl@3 is available before & after that change.

It us, but it's not the default, and various tasks expect one version or the other, so they need to be adjusted. Anything we control calling `openssl` directly is fine.

**Comment by gabsamples6** [comment]
We are still facing this issues and we are really stuck, is the fix/revert going to be applied soon? thanks

**Comment by surendrapatel-rak** [comment]
> > We are still facing this issues and we are really stuck, is the fix/revert going to be applied soon? thanks
> 
> Are you seeing v1.1.1 or v3 right now? We've been running ours with both versions of the task that's having an issue and using `continueWithError: true` to ignore the failing one. Every run this week has had the v1.1.1-style call succeed and the v3-style call fail.

Is it not possible to skip the task (not needed) based on the agent macOS version check?

**Comment by gabsamples6** [comment]
I have just tried on using both and both failed. This is just mad now - what are we going to do? Can someone post a full workaround if any? We cannot deploy an app to prod because of this

```
    - task: InstallAppleCertificate@2
      displayName: 'Install an Apple certificate ${{ parameters.appleCertificateP12 }} '
      inputs:
        certSecureFile: ${{ parameters.appleCertificateP12 }}
        certPwd: '${{ parameters.p12password }}'
        keychain: 'temp'
        opensslPkcsArgs: '-legacy'       USING LEGACY HERE
     continueOnError: true
      
    - task: InstallAppleCertificate@2
      displayName: 'Install an Apple certificate ${{ parameters.appleCertificateP12 }} '
      inputs:
        certSecureFile: ${{ parameters.appleCertificateP12 }}
        certPwd: '${{ parameters.p12password }}'
        keychain: 'temp'
      continueOnError: true
	  
```
