### ISSUE TITLE
Regression: on current macos-latest, ERROR: Could not find a version that satisfies the requirement skia-python (from versions: none) with  "python -m pip install --pre skia-python"

### ISSUE THREAD

**Issue by HinTak** [actions/runner-images#10863]
### Description

Regression: on current macos-latest, 
ERROR: Could not find a version that satisfies the requirement skia-python (from versions: none) 
with  

"python -m pip install --pre skia-python"

Broken:
Current runner version: '2.320.0'
Operating System
  macOS
  14.7
  [2](https://github.com/HinTak/skia-python-examples/actions/runs/11526215740/job/32089960387#step:1:2)3H124
Runner Image
  Image: macos-14-arm64
  Version: 20241022.[3](https://github.com/HinTak/skia-python-examples/actions/runs/11526215740/job/32089960387#step:1:3)61
  Included Software: https://github.com/actions/runner-images/blob/macos-1[4](https://github.com/HinTak/skia-python-examples/actions/runs/11526215740/job/32089960387#step:1:4)-arm64/20241022.3[6](https://github.com/HinTak/skia-python-examples/actions/runs/11526215740/job/32089960387#step:1:7)1/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F2024[10](https://github.com/HinTak/skia-python-examples/actions/runs/11526215740/job/32089960387#step:1:11)22.361

Last working version:

Current runner version: '2.319.1'
Operating System
  macOS
  14.6.1
  [2](https://github.com/HinTak/skia-python-examples/actions/runs/11004737297/job/30556227438#step:1:2)3G93
Runner Image
  Image: macos-1[4](https://github.com/HinTak/skia-python-examples/actions/runs/11004737297/job/30556227438#step:1:4)-arm64
  Version: 20240918.8
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm[6](https://github.com/HinTak/skia-python-examples/actions/runs/11004737297/job/30556227438#step:1:7)4/20240918.8/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F2024091[8](https://github.com/HinTak/skia-python-examples/actions/runs/11004737297/job/30556227438#step:1:9).8

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/HinTak/skia-python-examples/actions/runs/11526215740

### Is it regression?

Yes

### Expected behavior

In the older image, install was successful.
https://github.com/HinTak/skia-python-examples/actions/runs/11004737297

Run python -m pip install --pre skia-python
Collecting skia-python
  Downloading skia_python-130.0b10-cp312-cp312-macosx_11_0_arm[6](https://github.com/HinTak/skia-python-examples/actions/runs/11004737297/job/30556227438#step:4:7)4.whl.metadata (3.7 kB)
Collecting numpy (from skia-python)
  Downloading numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting pybind11>=2.6 (from skia-python)
  Downloading pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Downloading skia_python-130.0b10-cp312-cp312-macosx_11_0_arm64.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 5[7](https://github.com/HinTak/skia-python-examples/actions/runs/11004737297/job/30556227438#step:4:8).4 MB/s eta 0:00:00
Downloading pybind11-2.13.6-py3-none-any.whl (243 kB)
Downloading numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 63.0 MB/s eta 0:00:00
Installing collected packages: pybind11, numpy, skia-python
Successfully installed numpy-2.1.1 pybind11-2.13.6 skia-python-130.0b[10](https://github.com/HinTak/skia-python-examples/actions/runs/11004737297/job/30556227438#step:4:11)

### Actual behavior

Run python -m pip install --pre skia-python
ERROR: Could not find a version that satisfies the requirement skia-python (from versions: none)
ERROR: No matching distribution found for skia-python
Error: Process completed with exit code 1.

### Repro steps

Run python -m pip install --pre skia-python

**Comment by HinTak** [comment]
Thanks.

**Comment by sureshe456** [comment]
Hi @HinTak, We ran the workflow and tested the command("python -m pip install --pre skia-python") on macos-14 and macos-14-arm64 images, and it worked as expected. Please verify it on your end.
```
name: issue-10863

on:
  workflow_dispatch:

jobs:
  tests:
    name: tests on ${{ matrix.os }} (${{ matrix.arch }}) for ${{ matrix.cp }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-14', 'macos-14-large']
        arch: [auto64]
        cp: ["cp312"]
    env:
      PYGLFW_LIBRARY: glfw-3.4.bin.MACOS/lib-universal/libglfw.3.dylib
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - name: Install pre-release version of skia-python
        run: python -m pip install --pre skia-python
```
<img width="1082" alt="Screenshot 2024-11-15 at 4 11 51 PM" src="https://github.com/user-attachments/assets/5a079e56-e68d-49f2-bbfa-28e96609a7ef">
