### ISSUE TITLE
corepack not available on macOS 15

### ISSUE THREAD

**Issue by daveisfera** [actions/runner-images#10905]
### Description

With macOS 14 and previous, you can run `corepack enable` to use `yarn` as the package manager, but this doesn't work with [macOS 15](#10686)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-15-arm64
Version: 20241022.250

### Is it regression?

Yes (worked with macOS 14)

### Expected behavior

Ability to use `yarn` as the package manager is maintained

### Actual behavior

```
Run corepack enable
/Users/runner/work/_temp/aeab8a80-fdd5-[4](https://github.com/awresports/awresports-app/actions/runs/11678040481/job/32516898250#step:4:5)d0f-b29d-003c16bb6745.sh: line 1: corepack: command not found
Error: Process completed with exit code 127.
```

### Repro steps

1. Run `corepack enable`
2. Observe failure
3. Try to use `yarn` without and also fails

**Comment by susmitamane** [comment]
Hi @daveisfera We will look into the issue and keep you posted with updates.

**Comment by daveisfera** [comment]
Thanks for the update! I changed it to be a Regression in the initial report, because it's either a regression or a breaking change and either way it should be fixed

**Comment by aartis17** [comment]
Hi @daveisfera,
To enable corepack, you need to install it using Homebrew. In your workflow file, use the command `brew install corepack` to install corepack, and then run  `corepack enable` to activate it.

Please see workflow file which I used:
```
name: Enable Corepack and Use Yarn

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-15']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: install Corepack
      run: brew install corepack  
      
    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies using Yarn
      run: yarn install
```

Please see below snip for the same.

<img width="1503" alt="Screenshot 2024-11-18 at 3 51 49 PM" src="https://github.com/user-attachments/assets/9d99be3c-8d65-43aa-af38-173c2f3c4e5b">

**Comment by daveisfera** [comment]
Why isn't `corepack` installed by default like it was with previous versions of macOS?

I know that different use case are struggling whether to include yarn/corepack by default (`[setup-node](https://github.com/actions/setup-node/issues/531)`, [`docker` concerned about size](https://github.com/nodejs/docker-node/issues/404#issuecomment-663182317), [`docker` concerned about ease of use](https://github.com/nodejs/docker-node/issues/351), but I think that the macOS base runner doesn't really have a size concern (or at least `corepack` isn't really moving that needle very much), and `corepack` is supposed to be [included by default in an `npm` install](https://github.com/nodejs/corepack?tab=readme-ov-file#default-installs) and the [`yarn` install instructions rely on that fact](https://yarnpkg.com/getting-started/install).

So I think that this should be fixed to match the behavior of previous macOS versions and project recommendations/defaults, but if it's really not going to be included, then I'd recommend installing it with `npm` rather than `homebrew`, because that's what the [`corepack` project recommends](https://github.com/nodejs/corepack?tab=readme-ov-file#manual-installs).

**Comment by aartis17** [comment]
Hi @daveisfera,

I run enabling corepack without installing it, its working, I cannot see any error.
Please see below github workflow :

```
name: Enable Corepack 

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-15' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Enable Corepack
      run: corepack enable
```
Output:
<img width="1119" alt="Screenshot 2024-11-22 at 2 21 29 PM" src="https://github.com/user-attachments/assets/4d9dd262-4822-4aa7-b233-f43bfb35a17d">
