### ISSUE TITLE
VCPKG_INSTALLATION_ROOT env variable not available

### ISSUE THREAD

**Issue by giallu** [actions/runner-images#10904]
This documentation:
https://github.com/actions/runner-images/blob/win22/20231023.1/images/win/Windows2022-Readme.md#environment-variables

promises an environment variable `VCPKG_INSTALLATION_ROOT`. However, when I try to use this in a build step like so:

    - name: Configure CMake
      if: runner.os == 'Windows'
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --toolchain="${{env.VCPKG_INSTALLATION_ROOT}}/scripts/buildsystems/vcpkg.cmake"

The variable seems to be not there. I tried a few variations:

 - `${{env.VCPKG_INSTALLATION_ROOT}}`
 - `$VCPKG_INSTALLATION_ROOT`

_Originally posted by @mcourteaux in https://github.com/actions/runner-images/issues/6376#issuecomment-1781269302_

**Comment by giallu** [comment]
I noticed the issue with an Ubuntu 22.04 runner but I can confirm I got the same issue also in a Windows run as reported in the original comment

**Comment by vidyasagarnimmagaddi** [comment]
Hi @giallu , Thanks for bringing to us , we will look into this and update. Thank you !

**Comment by ELeeScape** [comment]
I can confirm that the problem still exists on Ubuntu images - $VCPKG_INSTALLATION_ROOT does not exist in the Ubuntu 24.04 runner but does exist in the Windows 2022 runner.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @giallu 
We have tried at our end
```
name: Testing vcpkg env var in gha 

on: push
jobs:
  testing-vcpkg:
    runs-on: windows-2022
    steps:
      - name: Check vcpkg env var in gha
        run: |
          echo $env:VCPKG_INSTALLATION_ROOT
 ```
it worked.
For Windows the syntax for retrieving environment variable is `$env:VCPKG_INSTALLATION_ROOT`
The declaring  should be `$env:<env_var_name>` .kindly try from your end.

**Comment by ELeeScape** [comment]
@vidyasagarnimmagaddi  You got it backwards.  You tested it on windows-2022, which both @giallu and I confirmed DOES work.  You need to test it on the ubuntu-24.04 image.

**Comment by vidyasagarnimmagaddi** [comment]
> @vidyasagarnimmagaddi You got it backwards. You tested it on windows-2022, which both @giallu and I confirmed DOES work. You need to test it on the ubuntu-24.04 image.

Sure, will analyze and revert you back

**Comment by vidyasagarnimmagaddi** [comment]
Hi @giallu 
We tried to check in Ubuntu 24.04 
```
name: Testing vcpkg env var in gha

on: push

jobs:
  testing-vcpkg:
    runs-on: ubuntu-24.04  # Change to Ubuntu 24.04
    steps:
      - name: Check vcpkg env var in gha
        run: |
          echo $VCPKG_INSTALLATION_ROOT
```

It worked.

**Comment by ELeeScape** [comment]
Hmm.  I can't speak for anyone else, but in my case, I was using ADO and was referencing the $VCPKG_INSTALLATION_ROOT variable in my pipeline YAML, not in a script executing on the agent.  This is because the vcpkg tool expects $VCPKG_ROOT to be set in the environment, not $VCPKG_INSTALLATION_ROOT, so I was trying to set it like this:

```
jobs:
- job: TestLinux

  pool:
    vmImage: 'ubuntu-24.04'

  steps:
  - bash: echo $VCPKG_ROOT
    env:
      VCPKG_ROOT: $(VCPKG_INSTALLATION_ROOT)

- job: TestWindows

  pool:
    vmImage: 'windows-2022'

  steps:
  - pwsh: Write-Host $env:VCPKG_ROOT
    env:
      VCPKG_ROOT: $(VCPKG_INSTALLATION_ROOT)
```

Last week, this did NOT work for me on Ubuntu (it would echo an empty string on Ubuntu) but did work on Windows.  Today, re-running the same pipeline script, it does work on both Ubuntu and Windows.  I don't know what changed but my problem seems to be resolved now.
