### ISSUE TITLE
[azure devops] AVPIdentity: AppleVirtualPlatformHostKey.mm:234: Assert: platformExpert,  value: 0

### ISSUE THREAD

**Issue by jeromelaban** [actions/runner-images#10925]
### Description

When starting the iOS simulators on macos-15, the following assertion happens:

```
AVPIdentity: AppleVirtualPlatformHostKey.mm:234: Assert: platformExpert,  value: 0
AVPIdentity: AppleVirtualPlatformHostKey.mm:234: Failed to get AppleVirtualPlatformARMPE service.
```

The message shows up as stdout, "polluting" machine readable outputs like `simctl`.

This is azure devops specific, this does not happen on github actions.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20241106.316

### Is it regression?

Not for this image, but compared to other images, yes.

### Expected behavior

No assertions in the log

### Actual behavior

Many messages like this one:

```
AVPIdentity: AppleVirtualPlatformHostKey.mm:234: Assert: platformExpert,  value: 0
AVPIdentity: AppleVirtualPlatformHostKey.mm:234: Failed to get AppleVirtualPlatformARMPE service.
```

### Repro steps

Run the following pipeline:

```yaml
pool:
  vmImage: 'windows-2022'

trigger:
  - main

stages:
- stage: Setup
  jobs:
  - job: Pipeline_Validations

    pool:
      vmImage: 'macos-15'

    steps:
    - checkout: self
      clean: 'true'
      fetchDepth: 0

    - bash: |
        /bin/bash -c "sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer"
  
        echo "Listing iOS simulators"
        xcrun simctl list devices --json
  
        export SIMULATOR_VERSION="com.apple.CoreSimulator.SimRuntime.iOS-18-1"
        export SIMULATOR_NAME="iPad Pro 13-inch (M4)"
  
        export UITEST_IOSDEVICE_ID=`xcrun simctl list -j | jq -r --arg sim "$SIMULATOR_VERSION" --arg name "$SIMULATOR_NAME" '.devices[$sim] | .[] | select(.name==$name) | .udid'`
        xcrun simctl boot $UITEST_IOSDEVICE_ID
  
        sleep 300
      name: Run
```
