### ISSUE TITLE
`macos-14-xlarge` Randomly returns `device not found` when booting iOS simulators inside a matrix

### ISSUE THREAD

**Issue by AleBorini** [actions/runner-images#10960]
### Description

Hello everyone,  

Since this morning, my E2E pipelines running on `macos-14-xlarge` have been intermittently returning the error: `No devices found` for the matching requirements whenever I attempt to boot a simulator for `iPhone 15` with `iOS 18.1`. 

I have also tested with iPhone 14 on iOS 17.2 and encountered the same issue.  I am running my pipeline with `xcode-version: "15.2.0"`, and the workflow is set up to spin up a matrix of the same job to run on a different machines.  

The same job running on different runners reports varying outcomes. Given that it is a matrix, everything should be identical. In some cases, I have observed:

<img width="599" alt="Screenshot 2024-11-13 at 11 25 52" src="https://github.com/user-attachments/assets/c3f522e7-8956-4335-9404-82a86238154c">

And on other runners I see:

<img width="458" alt="Screenshot 2024-11-13 at 11 25 18" src="https://github.com/user-attachments/assets/1a50b593-8754-4e42-b657-5f8e80e57e97">

Changing iPhone model and OS version do not prevent the issue from happening. 

Pipeline runs as follows (removed sensible datas like token and directories names). The step that is failing is `name: Launch iOS Simulator`. `[Run ](name: Detox - Test suite)` is on the same page when it tries to boot the simulator is fails with `No devices found`

```
  run-detox:
    name: Run Detox
    needs: [build]
    runs-on: macos-14-xlarge
    strategy:
      fail-fast: false
      matrix:
        groups: ["Smoke-1", "Smoke-2", "Smoke-3", "Smoke-4", "Smoke-5", "Smoke-6"]

    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - name: Build dependencies
        uses: ./.github/actions/build-dependencies

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2.0"

      - name: Launch iOS Simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 15"
          os_version: "18.1"

      - name: Install Detox Tools
        run: |
          brew tap wix/brew
          brew install wix/brew/applesimutils

      - uses: actions/download-artifact@v4
        name: Download artifact Detox build
        with:
          name: detox-build-${{ github.event.pull_request.head.sha || github.sha }}
          path: |
            apps/directory-path-removed-here

      - name: Detox - Rebuild framework
        run: yarn detox rebuild-framework-cache

      - name: Detox - Test suite
        run: yarn detox:test -t=${{ matrix.groups }} --loglevel fatal  --take-screenshots failing --headless
        working-directory: apps/directory-path-removed-here
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
  Image: macos-14-arm64
  Version: 20241022.361

### Is it regression?

https://github.com/LEGO/fabuland/actions/runs/11814376690

### Expected behavior

Same simultators should be available across all the runner sharing the same image. 

### Actual behavior

Since this morning, my E2E pipelines running on `macos-14-xlarge` have been intermittently returning the error: `No devices found` for the matching requirements whenever I attempt to boot a simulator for `iPhone 15` with `iOS 18.1`. 

### Repro steps

- Create a matrix running on `runs-on: macos-14-xlarge`, In my case it's a matrix of 6. 
- Run the job with `xcode-version: "15.2.0"` to the job
- Try to boot a simulator with using command line or Action  
    In my case it was: 
    ```
          - name: Launch iOS Simulator
            uses: futureware-tech/simulator-action@v3
            with:
              model: "iPhone 15"
              os_version: "18.1"
    ```
- Some runners should return `No devices found` when try to reach the simulator
