### ISSUE TITLE
Disable man-db dpkg trigger

### ISSUE THREAD

**Issue by lengau** [actions/runner-images#10977]
### Description

This isn't necessarily a bug - more a performance enhancement request, but there's no category for that.

When running `apt install` commands on Ubuntu hosted runners, the runners spend about 45 seconds just processing man-db triggers:

![image](https://github.com/user-attachments/assets/f86e985c-5e00-4fa9-a29e-ceaae356ceb3)

However, in very few cases are these runners ever going to actually use these man-db changes, so this is close to a minute of wasted time for each run.

Adding the following commands to the setup of each runner image would disable this trigger:

```
echo "set man-db/auto-update false" | debconf-communicate
dpkg-reconfigure man-db
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Fri, 15 Nov 2024 17:03:46 GMT
Runner Image
Fri, 15 Nov 2024 17:03:46 GMT   Image: ubuntu-24.04
Fri, 15 Nov 2024 17:03:46 GMT   Version: 20241112.1.0
Fri, 15 Nov 2024 17:03:46 GMT   Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20241112.1/images/ubuntu/Ubuntu2404-Readme.md
Fri, 15 Nov 2024 17:03:46 GMT   Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20241112.1
```

Relevant step: https://github.com/canonical/starflow/actions/runs/11860374887/job/33055486302?pr=23#step:2:88

### Is it regression?

no

### Expected behavior

man-db triggers don't get run on `apt-get install`

### Actual behavior

man-db triggers do get run

### Repro steps

Run the following workflow, note that it takes tends to timeout during the trigger processing.

```yaml
name: Self-tests for scanners

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  man-db:
    steps:
      - run: |
          sudo apt-get update
          timeout 30s sudo apt-get --yes install python3-build
```
