### ISSUE TITLE
Ubuntu 24.04: netcat is a virtual package

### ISSUE THREAD

**Issue by GregoireW** [actions/runner-images#11028]
### Description

When I try to build a ubuntu 24.04 runner image from script in this repo, I got an issue  with netcat:

```
Package netcat is a virtual package provided by:
  netcat-traditional 1.10-48
  netcat-openbsd 1.226-1ubuntu2
You should explicitly select one to install.
```

not sure how to resolve this cleanly.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

24.04

### Is it regression?

was succesful on 22.04

### Expected behavior

toolset should install without error

### Actual behavior

fail with 
```
Package netcat is a virtual package provided by:
  netcat-traditional 1.10-48
  netcat-openbsd 1.226-1ubuntu2
You should explicitly select one to install.
```

### Repro steps

error is showing when `install-apt-common.sh`  is executed

**Comment by kleverson1988** [comment]
O erro que você está vendo acontece porque o Ubuntu 24.04 não sabe qual versão do pacote netcat instalar, já que ele é um "pacote virtual", ou seja, depende de outras versões, como netcat-traditional ou netcat-openbsd. O gerenciador de pacotes precisa que você escolha uma delas.

Como resolver:

1. Escolher uma versão do netcat para instalar:

Se você preferir o netcat-traditional, execute:
sudo apt-get install netcat-traditional

Ou, se preferir o netcat-openbsd, execute:
sudo apt-get install netcat-openbsd

2. Alterar o script: Se o erro ocorre no script install-apt-common.sh, você pode adicionar uma linha para instalar um desses pacotes logo no começo do script. Por exemplo:

Para instalar o netcat-traditional:
sudo apt-get install -y netcat-traditional

Ou, para o netcat-openbsd:
sudo apt-get install -y netcat-openbsd

Resumo:
Você só precisa dizer explicitamente qual versão do netcat deseja instalar, e o erro será resolvido. Adicionar a linha correta no seu script vai ajudar a garantir que o pacote seja instalado sem problemas.

**Comment by RaviAkshintala** [comment]
Hi @GregoireW Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating

**Comment by habandy** [comment]
@RaviAkshintala 
Not sure if this is relevant for this topic, but i found it while looking for the same reason/problem. 
https://launchpad.net/ubuntu/noble/+package/ncat

**Comment by hemanthmanga** [comment]
Hi @GregoireW, We successfully reproduced the netcat package in Ubuntu 24. Our builds are successful.
```
name: Install Netcat

on:
  push

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update apt-get
      run: sudo apt-get update

    - name: Install Netcat
      run: sudo apt-get install -y netcat-openbsd

    - name: Verify Netcat Installation
      run: nc -h
```
Kindly try building with the latest image version 20241124.1. If the issues persist, please provide us with the error logs or the build details.
