### ISSUE TITLE
[macOS 15 Arm64] - "bundle install" is failing

### ISSUE THREAD

**Issue by SamirNEddine** [actions/runner-images#11096]
### Description

Running `bundle install` is failing on the `macos-15` runner

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-15-arm64
Version: 20241125.405

### Is it regression?

yes

### Expected behavior

`bundle install` should work

### Actual behavior

`bundle install` don't work. The error I'm getting:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/runner/work/ios-app/ios-app/vendor/bundle/ruby/3.2.0/gems/nkf-0.2.0/ext/nkf
/Users/runner/hostedtoolcache/Ruby/3.2.2/arm64/bin/ruby extconf.rb
creating Makefile

current directory:
/Users/runner/work/ios-app/ios-app/vendor/bundle/ruby/3.2.0/gems/nkf-0.2.0/ext/nkf
make DESTDIR\= sitearchdir\=./.gem.[202](https://github.com/kartoon-ai/ios-app/actions/runs/12163537928/job/33922978016#step:6:208)41204-7443-4mjq8s
sitelibdir\=./.gem.20241204-7443-4mjq8s clean

current directory:
/Users/runner/work/ios-app/ios-app/vendor/bundle/ruby/3.2.0/gems/nkf-0.2.0/ext/nkf
make DESTDIR\= sitearchdir\=./.gem.20241[204](https://github.com/kartoon-ai/ios-app/actions/runs/12163537928/job/33922978016#step:6:210)-7443-4mjq8s
sitelibdir\=./.gem.20241204-7443-4mjq8s
compiling nkf.c
In file included from nkf.c:14:
In file included from
/Users/runner/hostedtoolcache/Ruby/3.2.2/arm64/include/ruby-3.2.0/ruby/ruby.h:25:
/Users/runner/hostedtoolcache/Ruby/3.2.2/arm64/include/ruby-3.2.0/ruby/defines.h:16:10:
fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make: *** [nkf.o] Error 1

make failed, exit code 2
``` 

### Repro steps

The workflow steps we're using:

```
jobs:
  build:
    name: Build and Upload app on TestFlight
    runs-on: macos-15

    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.app/Contents/Developer'

      - name: Select Swift version
        uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: "5.8"

      - name: Install bundler
        run: gem install bundler -v 2.5.16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
```

**Comment by susmitamane** [comment]
Hi @SamirNEddine 

We will look into the issue and keep you posted with updates.

Thank You.

**Comment by susmitamane** [comment]
Hi @SamirNEddine Tested same workflow which you have provided but i am not seeing any issues related to the `bundle install` failure. For me the workflow is working fine and bundle install is working fine with all required steps. 

Could you please check and confirm once if you are still facing the same issue.

Please find below screenshots of successful workflows:
<img width="1654" alt="Screenshot 2024-12-05 at 2 32 10 PM" src="https://github.com/user-attachments/assets/60d6c8dd-c672-4c7a-a5d0-920f8db13f61">
<img width="1654" alt="Screenshot 2024-12-05 at 2 31 23 PM" src="https://github.com/user-attachments/assets/84a874b7-e4e6-4a0c-8438-c0b3319b9cb7">

Thank you.

**Comment by SamirNEddine** [comment]
@susmitamane I'd like to point out is that what's puzzeling is that we have another workflow that looks kind of similar but it's working (you can find it below). I'm unable to find any difference between the two. I even tried by elimination to remove everything else like the slack module with no luck.

```
name: CI

on:
  pull_request:
    branches:
      - develop

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test app scheme
    runs-on: macos-15-xlarge

    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_16.app/Contents/Developer'

      - name: Select Swift version
        uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: "5.8"

      - name: Install bundler
        run: gem install bundler -v 2.5.16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Global dependencies versions
        run: |
          ruby --version
          gem --version
          bundler --version
          swift --version

      - name: Run tests
        working-directory: ./App
        run: bundle exec fastlane tests

```
