### ISSUE TITLE
AWS ECR login fails in windows-2022 20241211.1.0

### ISSUE THREAD

**Issue by PatTheSilent** [actions/runner-images#11172]
### Description

We've started experiencing failures to login to AWS ECR starting from windows-2022 20241211.1.0
We're using "big" runners, which have received the update to 20241211.1.0 on which we're experiencing this failure. 
We're not experiencing this on windows-2022 runners, which still have 20241201.2.0

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Works as expected in 20241201.2.0
fails in 20241211.1.0

### Is it regression?

20241201.2.0

### Expected behavior

I'm able to authenticate with AWS ECR using aws-actions/amazon-ecr-login@v1

### Actual behavior

```
Error: Could not login to registry redacted.dkr.ecr.eu-west-1.amazonaws.com: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `A specified logon session does not exist. It may already have been terminated.`
```

### Repro steps

1. Have the following steps in your workflow:

```yaml
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    aws-region: eu-west-1
    role-to-assume: arn:aws:iam::redacted:role/redacted
    role-skip-session-tagging: true
    role-duration-seconds: 3600

- name: Login to Amazon ECR
  id: login-ecr
  uses: aws-actions/amazon-ecr-login@v1
  with:
    mask-password: true
```
2. Observe failure
