### ISSUE TITLE
Snap Install not working - hangs/no-output

### ISSUE THREAD

**Issue by nayan-shrivastava-dazn** [actions/runner-images#11170]
### Description

Hi, We are using snap to install node - sudo snap install node --classic --channel=${{ inputs.node_version }}
during the github workflow run, The command just stops and operation is cancelled after 15 mins of timeout. After rerun it sometime works.

Operating System
  Ubuntu - 22.04.5 LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20241201.1.0

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

 20241201.1.0
 
 
![image](https://github.com/user-attachments/assets/113cf6d8-1307-416e-bb27-1d379205a86d)

### Is it regression?

no idea

### Expected behavior

It should quickly install node and move on to next step

### Actual behavior

stuck on this command, node install

### Repro steps

sudo snap install node --classic --channel=${{ inputs.node_version }}
this command is being used in a GHA build step.

**Comment by kishorekumar-anchala** [comment]
Hi @nayan-shrivastava-dazn , Thankyou for raising the issue with us , we will look into the issue and update you on this Asap.

**Comment by hemanthmanga** [comment]
Hi @nayan-shrivastava-dazn, We appreciate your patience. Please attempt the workaround provided below, Hope it will resolve the issue. Thank you.

```
name: Install Node.js using Snap

on: [push, pull_request]

jobs:
  install-node:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        run: sudo snap install node --classic --channel=${{ inputs.node_version }}
        
      - name: Verify Node.js version
        run: node -v
```
