### ISSUE TITLE
Error when using macOS-15 in `runs-on` matrix configuration

### ISSUE THREAD

**Issue by Drewniok** [actions/runner-images#11317]
### Description

I am encountering an issue (while creating this [PR](https://github.com/cda-tum/fiction/pull/624)), specifically when configuring a GitHub Actions workflow matrix that includes macOS-15. Adding macOS-15 to the matrix causes the workflow to fail in evaluating the `runs-on` property, resulting in the following error:

```
Error when evaluating 'runs-on' for job 'build_and_test'. .github/workflows/macos.yml (Line: 40, Col: 14): Unexpected value ''
```

This issue does not occur when macOS-15 is excluded from the matrix.

#### Workflow Configuration

Here is the relevant snippet (whole workflow can be found [here](https://github.com/cda-tum/fiction/pull/624/commits/cd81198c398cae9e903ee3492c0073daea413b7d)) of the GitHub Actions workflow:

```yaml
jobs:
  build_and_test:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
        compiler: [g++-12, g++-13, g++-14, clang++]
        include:
          - os: macos-13
            architecture: x64
          - os: macos-14
            architecture: arm64
          - os: macos-15
            architecture: arm64
          - compiler: clang++
            ccompiler: clang
          - compiler: g++-12
            ccompiler: gcc-12
          - compiler: g++-13
            ccompiler: gcc-13
          - compiler: g++-14
            ccompiler: gcc-14

        exclude:
          - os: macos-13
            compiler: g++-13
          - os: macos-14
            compiler: g++-12
          - os: macos-14
            compiler: g++-13
          - os: macos-15
            compiler: g++-12
          - os: macos-15
            compiler: g++-13

    name: 🍎 ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

https://github.com/cda-tum/fiction/actions/runs/12647205220/workflow

### Is it regression?

https://github.com/cda-tum/fiction/actions/runs/12261209867

### Expected behavior

The workflow should execute with macOS-15 in the matrix, just like it does with macOS-13 and macOS-14.

### Actual behavior

When macOS-15 is included in the matrix, the workflow fails with the error message mentioned above. Removing macOS-15 resolves the issue.

### Repro steps

1. Add macOS-15 to the `os` matrix in the workflow configuration.
2. Run the workflow.
3. Observe the error during evaluation of the `runs-on` property.

**Comment by susmitamane** [comment]
Hi @Drewniok 

We will look into the issue and keep you posted with updates.

Thank You.

**Comment by susmitamane** [comment]
Hi @Drewniok,
- I tested both workflows you provided and found that the issue seems to be with the tags you're using for macOS 15 images. The matrix.os value is missing or mismatched in the include or exclude lists. The correct tags should be macos-15-large (intel) and macos-15-xlarge (arm64).

- I've verified the workflows using macos-15-large (intel) and macos-15-xlarge (arm64), and they are working fine on my end. I've attached screenshots of Yaml and runs for reference. Please check from your side and let me know if you need further assistance. 

<img width="1654" alt="Screenshot 2025-01-08 at 12 41 22 PM" src="https://github.com/user-attachments/assets/2a19b78a-23ef-4321-98b8-8b9f2c7d09bb" />
<img width="1654" alt="Screenshot 2025-01-08 at 12 42 02 PM" src="https://github.com/user-attachments/assets/b028b23c-0f86-45db-91bf-0c609fa5a02e" />
<img width="1654" alt="Screenshot 2025-01-09 at 12 32 39 PM" src="https://github.com/user-attachments/assets/9e6249b8-3ff7-4f8f-9d3a-6a0a27fcd210" />

- As it is public repo I noticed that you've used the tags mentioned above in some of your workflows, and now the error has changed. It appears to be related to the compilation of fiction.cpp, which seems to be tied to the application's configuration. Kindly let us know if you are still encountering the same issue for which this ticket was logged.
Thank you.

**Comment by Drewniok** [comment]
Hi @susmitamane, 

Thank you for investigating my problem. Using your approach, it now works. Thank you very much!
From my side we can close this issue.

**Comment by Drewniok** [comment]
Hi @susmitamane,

Thanks for your help! The following workflow now works as expected:

```
jobs:
  build_and_test_other_macos:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
        architecture: [x64, arm64]
        compiler: [g++-13, g++-14, clang++]
        include:
          - os: macos-13
            architecture: x64
          - os: macos-14
            architecture: arm64
          - os: macos-15
            architecture: arm64
          - compiler: clang++
            ccompiler: clang
          - compiler: g++-13
            ccompiler: gcc-13
          - compiler: g++-14
            ccompiler: gcc-14
        exclude:
          - os: macos-14
            architecture: x64
          - os: macos-15
            architecture: x64
          - os: macos-13
            architecture: arm64
```

From my side we can close this issue. Thank you again!
