### ISSUE TITLE
windows 2022 image: chocolateyInstall.ps1 script is failing with ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (409) Conflict."

### ISSUE THREAD

**Issue by antika080** [actions/runner-images#11338]
### Description

windows 2022 image: chocolateyInstall.ps1 script is failing with ERROR: "The remote server returned an error: (409) Conflict."

 . Performing other installation steps.
 Attempt to get headers for https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip failed.
   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (409) Conflict."
 Downloading azcopy10 64 bit
   from 'https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (409) Conflict."
 This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of azcopy10 was NOT successful.
 Error while running 'C:\ProgramData\chocolatey\lib\azcopy10\tools\chocolateyInstall.ps1'.
  See log for details.
 Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
 Failures
 - azcopy10 (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\azcopy10\tools\chocolateyInstall.ps1'.
  See log for details.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

NA

### Is it regression?

No

### Expected behavior

chocolateyInstall.ps1 script should be running without error

### Actual behavior

chocolateyInstall.ps1 script fails with  ERROR: "The remote server returned an error: (409) 

### Repro steps

run chocolateyInstall.ps1 script

**Comment by vidyasagarnimmagaddi** [comment]
Hi @antika080 , Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @antika080 ,
kindly note that `azureedge.net` , will no longer be available for downloading the azcopy10.
The current url for downloading the azcopy is https://azcopyvnext.azureedge.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip

, It will be replaced by  `awgzd8g7aagqhzhe.b02.azurefd.net` , in future for downloading the azcopy url will be  https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip.

we have tried to new url :https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip. it is working  fine.

Reference: [PR](https://github.com/chocolatey-community/chocolatey-packages/pull/2612) .
Thanks

**Comment by denyos** [comment]
We are having the same issue. This is caused by the CDN migration in combination with the urls in choco.

I've raised an issue in the chocolatey repository for this:
https://github.com/chocolatey-community/chocolatey-packages/issues/2611

**Comment by vidyasagarnimmagaddi** [comment]
https://github.com/chocolatey-community/chocolatey-packages/pull/2612

**Comment by denyos** [comment]
The fix has been approved in the choco repo and we have just build a new image without errors.

```
    azure-arm.image: azcopy10 v10.27.1.20250109 [Approved]
    azure-arm.image: azcopy10 package files install completed. Performing other installation steps.
    azure-arm.image: Downloading azcopy10 64 bit
    azure-arm.image:   from 'https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_windows_amd64_10.27.1.zip'
    azure-arm.image:
    azure-arm.image: Download of azcopy_windows_amd64_10.27.1.zip (22.67 MB) completed.
    azure-arm.image: Hashes match.
    azure-arm.image: Extracting C:\Users\packer\AppData\Local\Temp\chocolatey\azcopy10\10.27.1.20250109\azcopy_windows_amd64_10.27.1.zip to C:\ProgramData\chocolatey\lib\azcopy10\tools...
    azure-arm.image: C:\ProgramData\chocolatey\lib\azcopy10\tools
```
