### ISSUE TITLE
Podman remoteSocket not existing

### ISSUE THREAD

**Issue by elgohr** [actions/runner-images#11366]
### Description

In contrast to `ubuntu-22.04`, `ubuntu-24.04` comes with a non-existing Podman remote socket.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

2.321.0

### Is it regression?

https://github.com/elgohr/runner-podman/actions/runs/12746956270

### Expected behavior

The socket should be enabled by default (like in `ubuntu-22.04`)

### Actual behavior

remoteSocket does not exist.

### Repro steps

```
name: Show
on: push
jobs:
  show:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
      - run: podman system info
```
Take a look at `remoteSocket.exists`

**Comment by Prabhatkumar59** [comment]
Hi @elgohr - Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by kishorekumar-anchala** [comment]
Hi @elgohr - Issue got resolved now, we can see RemoteSocket.exits= true . please find the attachment below.

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/bb806b64-0f11-4c39-801f-38a8efe257ce" />

**Comment by kishorekumar-anchala** [comment]
Hi @elgohr - it seems remotesocket.exists is disabled by default with ubuntu distribution , i request you to modify the workflow to start the service. thank you !. 

```
name: Show enable
on: push
jobs:
  show:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
      - run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            systemctl --user enable --now podman.socket
          fi
          podman system info
```

For more info:  https://github.com/containers/podman/issues/25016
