### ISSUE TITLE
Error - cat: /etc/docker/daemon.json: No such file or directory - ubuntu-24.04

### ISSUE THREAD

**Issue by YasharF** [actions/runner-images#11408]
### Description

This issue is to reopen/replace https://github.com/actions/runner-images/issues/10697 as the issue was not resolved, and users were asked to downgrade to Ubuntu 22.04 as a workaround.  Now that ubuntu-24.04 is being rolled out as ubuntu-latest, can you revisit the problem? 

As it was stated in the other issue, when using docker github actions package to install docker for building container images https://github.com/docker-practice/actions-setup-docker , the workflow fails with the following response:

```
Run docker-practice/actions-setup-docker@master
check docker systemd status
check docker version
add apt source
update apt cache
show available docker version
remove default moby
install docker
check docker version
check docker systemd status
show default daemon json content
  /usr/bin/sudo cat /etc/docker/daemon.json
  cat: /etc/docker/daemon.json: No such file or directory
  Error: Error: The process '/usr/bin/sudo' failed with exit code 1
```

I have tried both ubuntu-22.04 and ubuntu-latest (ubuntu-24.04) today and the docker compatibility issue with Ubuntu 24.04 is still there.  The following is the main.yml in my case:

```
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

```

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

**Failed** build using ubuntu-latest aka ___ubuntu-24.04___  https://github.com/YasharF/mailchecker/actions/runs/12816611467

**Passed** build after downgrading aka ___ubuntu-22.04___  https://github.com/YasharF/mailchecker/actions/runs/12816853681

### Is it regression?

ubuntu-24.04 aka ubuntu-latest

### Expected behavior

To successfully install docker with docker-practice/actions-setup-docker@master

### Actual behavior

The docker installation fails with:

```
  /usr/bin/sudo cat /etc/docker/daemon.json
  cat: /etc/docker/daemon.json: No such file or directory
  Error: Error: The process '/usr/bin/sudo' failed with exit code 1
```

### Repro steps

Setup a github actions script with above configurations (maybe pinning to using ubuntu-24.04) and then the job fails with installing docker.
