### ISSUE TITLE
ubuntu-latest (24.04) runner hangs at end of Nix build job

### ISSUE THREAD

**Issue by FelixBoulet-Eaton** [actions/runner-images#11401]
### Description

Since `ubuntu-latest` has been updated to 24.04, some of our Nix-based builds have been hanging at the end of a step; they stay hung up until the timeout kicks in, cancelling the build.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Image: ubuntu-24.04
Version: 20250105.1.0
Example not public.

### Is it regression?

Yes, works with Image: ubuntu-22.04 Version: 20250105.1.0. Link not public.

### Expected behavior

The runner should finish the build job without hanging. Logs from Nix:
```
docs> ++ local hookName=exitHook
docs> ++ declare -F exitHook
docs> ++ type -p exitHook
docs> ++ '[' -n '' ']'
docs> ++ return 0
docs> + return 0
docs> + return 0
```

### Actual behavior

The runner hangs after the build script exits (same logs as the expected behavior, but the build step never finishes and hangs).

### Repro steps

Run a workflow that uses a Nix builder step:
```yaml
name: Documentation
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    # We want to deploy docs when we have changes to anything in the docs folder
    # or to the root-level nix-related files.
    paths:
      - "docs/**"
      - "*.nix"
      - "flake.lock"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "*.nix"
      - "flake.lock"
permissions:
  contents: read
  pull-requests: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIX_GITHUB_PRIVATE_USERNAME: ${{ secrets.CI_GITHUB_USERNAME }}
      NIX_GITHUB_PRIVATE_PASSWORD: ${{ secrets.CI_GITHUB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v29
        with:
          github_access_token: ${{ secrets.CI_GITHUB_PASSWORD }}
      - name: Cache Nix Packages
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build docs
        run: nix build -L .#docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

Here, "Build docs" is the step that hangs on the new runner.
The Nix file that is being built is as follows:
```nix
{
    fetchurl,
    buildNpmPackage,
    git,
    # Kroki deps
    openjdk_headless,
    plantuml,
    graphviz,
    d2
}:
let
  # Kroki server for diagrams
  krokiVersion = "0.24.1";
  krokiSrc = fetchurl {
    name = "kroki-${krokiVersion}-src";
    url = "https://github.com/yuzutech/kroki/releases/download/v${krokiVersion}/kroki-standalone-server-v${krokiVersion}.jar";
    hash = "sha256-hkrDdp1ssUUFShLNeR36v34rRIfCpBot4HFeiMV473k=";
  };

  krokiRunScript = ''
    echo "Starting Kroki server"
    export KROKI_DOT_BIN_PATH=${graphviz}/bin/dot
    export KROKI_PLANTUML_BIN_PATH=${plantuml}/bin/plantuml
    export KROKI_D2_BIN_PATH=${d2}/bin/d2
    ${openjdk_headless}/bin/java -jar ${krokiSrc} > /dev/null &
  '';
in
buildNpmPackage {
  name = "docs";

  src = ./.;
  npmDepsHash = "sha256-Q8+lU5Y/osq33F4mtjU6vg/bMD/eVJTrMxm90e53DZw=";

  nativeBuildInputs = [ git ];

  preBuild = ''
    # Hack for antora to think we are in a git repo
    # See https://gitlab.com/antora/antora/-/issues/284
    git init -b main ..
    touch .gitignore
    git add .gitignore
    git -c user.name='nix' -c user.email=nix@nixos.org commit -m 'temp'

    # Output directory
    export ANTORA_OUT_DIR=$out

    # Start Kroki
    ${krokiRunScript}
  '';

  shellHook = krokiRunScript;

  dontNpmInstall = true;

  dontFixup = true;
}
```

`src` contains a basic static AsciiDoc web app.
