### ISSUE TITLE
Ububu 22 runner use Ubuntu 24 version

### ISSUE THREAD

**Issue by SimonC-Audigent** [actions/runner-images#11484]
### Description

I have a Job running on Ubuntu 22.04:
```
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
```

since ~11:50 UTC
It is deploying with Ubuntu 24.04 (extract from the GHA logs):
```
Operating System
  Ubuntu
  24.04.1
  LTS
```

It was working fine a few minute before that.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Current runner version: '2.321.0'
Operating System
  Ubuntu
  [2](https://github.com/AuDigent/spark-segments-jobs/actions/runs/12988296190/job/36218963033#step:1:2)4.04.1
  LTS
Runner Image
  Image: ubuntu-2[4](https://github.com/AuDigent/spark-segments-jobs/actions/runs/12988296190/job/36218963033#step:1:4).04
  Version: 202[5](https://github.com/AuDigent/spark-segments-jobs/actions/runs/12988296190/job/36218963033#step:1:5)0120.5.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250120.5/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250120.5
Runner Image Provisioner
  2.0.41[7](https://github.com/AuDigent/spark-segments-jobs/actions/runs/12988296190/job/36218963033#step:1:8).1

### Is it regression?

yes

### Expected behavior

 ubuntu-22.04 should run on Ubuntu 22

### Actual behavior

 ubuntu-22.04 runs on Ubuntu 24

### Repro steps

Deploy a job with ubuntu-22.04

**Comment by SimonC-Audigent** [comment]
After different tries it seems there is some caching issues. it is a job deployed with workflow_dispatch:
```
name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      project:
        type: string
      tag:
        type: string
        default: test
      java_version:
        type: number
        default: 17

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment }}
    steps:
```

we changed from  ubuntu-24.04 to ubuntu-22.04 a week ago. If I am using parameter I have previously used in the past it will use 24.04 like if we never changed the action, but if I am using different parameters if will use ubuntu-22.04 instead. (Note that the patch updating the version has been deployed on the main branch as well as the current branch)
