### ISSUE TITLE
Ubuntu 24.04 Android emulator does not find devices created via avdmanager

### ISSUE THREAD

**Issue by mxschmitt** [actions/runner-images#11482]
### Description

TL:DR: Devices created via `avdmanager` cannot be used with `emulator`.

Investigation:

`avdmanager`'s device was put into `/home/runner/.config/.android` but the `emulator` looked it up in `/home/runner/.android`
   
Workaround for now is: `ln -s /home/runner/.config/.android /home/runner/.android`.

It looks like its **not** caused by a different Android SDK version. My guess is either its caused by environment variables or some underlying OS difference between 22.04 and 24.04.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Runner Image
  Image: ubuntu-24.04
  Version: 20250120.5.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250120.5/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250120.5

Build link: https://github.com/mxschmitt/test/actions/runs/12987872128/job/36217638223

### Is it regression?

Yes. It was working fine in 22.04. Might be either caused by runner-images or Ubuntu 24.04. 

### Expected behavior

`emulator` and `avdmanager` are using the same device storage. So if I create a device using `avdmanager` the `emulator` is able to find it.

### Actual behavior

It does not find it. If you run the reproduction, you observe, that `${ANDROID_HOME}/emulator/emulator -list-avds` does not return anything in Ubuntu 24.04. In 22.04 it returns the created device `android35`.

### Repro steps

Create a repository with this workflow:

```yaml
name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
      fail-fast: false
    steps:
    - run: |
        export ANDROID_ARCH="x86_64"
        ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-35;google_apis;$ANDROID_ARCH" platform-tools emulator
        ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager create avd --force --name android35 --device "Nexus 5X" --package "system-images;android-35;google_apis;$ANDROID_ARCH"
        ${ANDROID_HOME}/emulator/emulator -list-avds
```
