### ISSUE TITLE
Python libs permission denied on Ubuntu

### ISSUE THREAD

**Issue by jack-rep** [actions/runner-images#11499]
### Description

When running on new latest image, we get python libs permission error:
```
ERROR    ERROR! Unexpected Exception, this is probably a bug: [Errno 13] Permission denied: b'/usr/local/lib/python3.10/dist-packages/ansible_collections'
```

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [x] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [x] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Image: ubuntu-24.04
Version: 20250120.5.0
and
Image: ubuntu-22.04
Version: 20250120.2.0

### Is it regression?

yes. was working just fine few days ago on Ubuntu 22.04 at least

### Expected behavior

Expected ansible-lint to run normally

### Actual behavior

got error Permission Denied to python libraries

### Repro steps

```
jobs:
  ansible-lint:
    name: "ansible-lint"
    runs-on: "ubuntu-24.04"
    steps:
      - uses: "actions/checkout@v4"
      - run: "pip install ansible-lint"
      - name: Ansible-Lint
        run: "ansible-lint
```

installing python with the following, solves the issue:
```
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
```
