### ISSUE TITLE
Ubuntu-latest Failed to retrieve from https://security.ubuntu.com/

### ISSUE THREAD

**Issue by MadDeCoDeR** [actions/runner-images#11522]
### Description

The ubuntu-latest uses dead links from security.ubuntu.com

```shell
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libgl1-mesa-dev_24.0.9-0ubuntu0.3_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libegl1-mesa-dev_24.0.9-0ubuntu0.3_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mesa/mesa-common-dev_24.0.9-0ubuntu0.3_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
``` 
[Action Run with the issue](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/actions/runs/13082391869/job/36520268077)

Code Snippet:
```
jobs:
    linux-build:
        runs-on: ubuntu-latest
    
        steps:
         {Steps to retrieve the Repository's Code with actions/checkout}
        - name: Download Depedencies
          id: step4
          run: sudo apt-get install -y build-essential autoconf libtool cmake libglu1-mesa-dev freeglut3-dev mesa-common-dev libxmu-dev libxi-dev libgl-dev libx11-dev libxft-dev libxext-dev nasm libwayland-dev libxkbcommon-dev libegl1-mesa-dev libdecor-0-dev libxrandr-dev libxxf86vm-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev python3-jinja2 libltdl-dev
``` 

After checking the [https://security.ubuntu.com](https://security.ubuntu.com) the only thing that is missing from their directory is the .deb packages that is trying to download, the directories are still the same

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Current runner version: '2.322.0'

Failed Build Link: https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/actions/runs/13082391869

### Is it regression?

IDK

### Expected behavior

Expected to download and install depedencies

### Actual behavior

Failed to find and retrieve depedencies

### Repro steps

1. Start a workflow with ubuntu-latest
2. Try to install with apt libgl1-mesa-dev or libegl1-mesa-dev or mesa-common-dev
3. Observe Action Logs

**Comment by cminyard** [comment]
I'm having the same error fetching the libudev-dev:
```
  Err:37 http://security.ubuntu.com/ubuntu noble-updates/main amd64 libudev-dev amd64 255.4-1ubuntu8.4
    404  Not Found [IP: 52.252.163.49 80]
  Fetched 8103 kB in 2s (3595 kB/s)
  E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_255.4-1ubuntu8.4_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This has happened before, is there any way to avoid this happening in the future?

**Comment by hemanthmanga** [comment]
Hi @MadDeCoDeR,  Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by hemanthmanga** [comment]
Hi @MadDeCoDeR, Regarding the issue, I have tried installing the dependencies mentioned in the reproduction steps. The ubuntu-latest environment installs the dependencies without issues, using the below workaround.

```
name: Install Dependencies

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libegl1-mesa-dev mesa-common-dev
    - name: Verify installed dependencies
      run: |
        apt list --installed | grep -E 'libgl1-mesa-dev|libegl1-mesa-dev|mesa-common-dev'
```

Please find the below screenshots

![Image](https://github.com/user-attachments/assets/5c7406ee-cc8e-4f42-a885-14bed90dcbe9)
