### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by PaulieScanlon** [actions/runner-images#11531]
### Tool name

postgresql.service

### Tool license

MIT

### Add or update?

- [ ] Add
- [x] Update

### Desired version

postgresql 17

### Brief description of tool

I've been using postgresql.service to perform scheduled dump/restore of my postgres database and it works great with the built-in version. However. Since the built-in service is set to "latest" there might be cases where i'll hit mismatch errors. 

It would be so good if, when using the built-in service i could set which version of Postgres to use. E. g

```yml
jobs:
  dump-and-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL Service
        run: |
          sudo systemctl start postgresql.service -v 17 // i've added the -v 17 to show one way this could work
```

Watta you think?

### Provide a basic test case to validate the tool's functionality.

```bash

```

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Can this tool be installed during the build?

```bash

```

**Comment by lakshminarayana02** [comment]
Hi
We are validating your request and according to the description, we assume that it  is required for latest Ubuntu version.

**Comment by lakshminarayana02** [comment]
Hi
acknowledged, we'll keep you updated.

**Comment by PaulieScanlon** [comment]
Great, thanks @lakshminarayana02!

**Comment by lakshminarayana02** [comment]
Hi
We expected to implement changes during the March 1st or 2nd week deployments. Please bear with us.

**Comment by Prabhatkumar59** [comment]
Hi @PaulieScanlon - The requirement will be taken care under this announcement(https://github.com/actions/runner-images/issues/11723).
Thanks!

**Comment by PaulieScanlon** [comment]
Thanks, @Prabhatkumar59. I've reviewed the update, and perhaps I'm not understanding correctly. My original request was to allow users to choose which version of Postgres to install, not to update the current version to 17.

E.g, this example uses the `-v` flag to install version 17.
```yml
jobs:
  dump-and-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL Service
        run: |
          sudo systemctl start postgresql.service -v 17
```
 Or, in this example it uses the `-v` flag to install version 14. 

```yml
jobs:
  dump-and-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL Service
        run: |
          sudo systemctl start postgresql.service -v 14
```

The idea is that users will be able to decide which version of Postgres the built-in service installs in the runner. Is that going to be possible with the next update?

**Comment by Prabhatkumar59** [comment]
Hi @PaulieScanlon - Thanks for your inputs. We are checking closely into this and will provide you further updates on this. Thanks!

**Comment by Prabhatkumar59** [comment]
Hi @PaulieScanlon - Since this request is not planned for implementation, we are closing this issue for now. If there are any updates or further discussions in the future, feel free to reach out. Thanks

**Comment by PaulieScanlon** [comment]
Hi @Prabhatkumar59, thanks for the update. 

That's a real shame. It's somewhat restricting to have a fixed version of Postgres installed because it's potluck if it's the same version of Postgres your actual database is using. 

I think this feature would be super helpful and provide ultimate flexibility for folks who use Postres in Actions. I've currently been working around this issue by installing Postgres in the environment, but it seems unnecessary given it's already part of the running image... but I need control over the version. For example.

```yml
name: Some Postgres Job

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }} 
  PG_VERSION: '17'

jobs:
  dump-and-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Set PostgreSQL binary path
        run: echo "POSTGRES=/usr/lib/postgresql/${{ env.PG_VERSION }}/bin" >> $GITHUB_ENV

      - name: PostgreSQL version
        run: |
          "$POSTGRES/psql" "$DATABASE_URL" -c "SELECT version();"
```
