### ISSUE TITLE
Docker build fails due to segmentation fault after GitHub runner update (Ubuntu 24.04, QEMU issue?)

### ISSUE THREAD

**Issue by giovaborgogno** [actions/runner-images#11589]
### Description

The action fails when is building the docker image, yesterday I ran the action and worked properly but today it fails, I checked the versions, yesterday the runner version was: Image: ubuntu-24.04 Version: 20250202.1.0, but today: Image: ubuntu-24.04 Version: 20250209.1.0

Error:
```
#7 67.41 Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
#7 67.49 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#7 68.02 Segmentation fault (core dumped)
#7 68.09 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#7 68.53 Segmentation fault (core dumped)
#7 68.53 dpkg: error processing package libc-bin (--configure):
#7 68.53  installed libc-bin package post-installation script subprocess returned error exit status 139
#7 68.58 Errors were encountered while processing:
#7 68.58  libc-bin
#7 68.75 E: Sub-process /usr/bin/dpkg returned an error code (1)
#7 ERROR: process "/bin/sh -c apt-get update &&     apt-get install -y     g++     make     cmake     unzip     libcurl4-openssl-dev" did not complete successfully: exit code: 100
------
 > [build-image 2/6] RUN apt-get update &&     apt-get install -y     g++     make     cmake     unzip     libcurl4-openssl-dev:
67.41 Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
67.49 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
68.02 Segmentation fault (core dumped)
68.09 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
68.53 Segmentation fault (core dumped)
68.53 dpkg: error processing package libc-bin (--configure):
68.53  installed libc-bin package post-installation script subprocess returned error exit status 139
68.58 Errors were encountered while processing:
68.58  libc-bin
: Sub-process /usr/bin/dpkg returned an error code (1)
------
Dockerfile:7
--------------------
   6 |     # Install aws-lambda-cpp build dependencies
   7 | >>> RUN apt-get update && \
   8 | >>>     apt-get install -y \
   9 | >>>     g++ \
  10 | >>>     make \
  11 | >>>     cmake \
  12 | >>>     unzip \
  13 | >>>     libcurl4-openssl-dev 
  14 |     # Include global arg in this stage of the build
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y     g++     make     cmake     unzip     libcurl4-openssl-dev" did not complete successfully: exit code: 100
```

I have this action:

```
name: Deploy Cluster API

on:
  # Trigger on push to specific branches
  push:
    branches:
      - main
  # Trigger on manual workflow dispatch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run deploy script
        run: |
          chmod +x scripts/deploy-cluster-api.sh
          ./scripts/deploy-cluster-api.sh

```

the deploy script uses:

```
docker build --platform linux/arm64 --provenance=false -t $ECR_REPOSITORY_NAME .
```

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Yesterday the action used this and everything were okay.
Runner Image
  Image: ubuntu-24.04
  Version: 20250202.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250202.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250202.1

Today the action used this and fails.
Runner Image
  Image: ubuntu-24.04
  Version: 20250209.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250209.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250209.1

### Is it regression?

20250202.1.0

### Expected behavior

Should build the image

### Actual behavior

The build fails

### Repro steps

.

**Comment by giovaborgogno** [comment]
I don't know if the bug is related with the runner or just a coincidence, but I found a work around https://github.com/tonistiigi/binfmt/issues/240

**Comment by shink** [comment]
Same issue for arm64

**Comment by henkhofs** [comment]
@giovaborgogno  why did you close it? Issue is clearly not resolved in ubuntu-24.04 (which is not ubuntu-latest) breaking a lot of workflows

**Comment by henkhofs** [comment]
i'm actually running into the same issue with multi-platform builds, but it also happens with ubuntu-22.04

**Comment by henkhofs** [comment]
For me the issue was fixed by adding a specific qemu version to the setup-qemu action in my docker build and push composite action:

```
   - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:qemu-v7.0.0-28
```
