### ISSUE TITLE
Python environment broken using uv/pip after `setup-python`

### ISSUE THREAD

**Issue by flying-sheep** [actions/runner-images#11639]
### Description

When installing Python modules into `setup-python`’s system environment for Python 3.12 on `ubuntu-24.04`, they can’t be imported for some reason.

See also:

- https://github.com/theislab/anndata2ri/issues/211
- https://github.com/scverse/pertpy/pull/704

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

20250126.1.0 and 20250209.1.0

- https://github.com/theislab/anndata2ri/actions/runs/13410556199/job/37459572518
- https://github.com/scverse/pertpy/actions/runs/13060568006/job/36442285406?pr=704

### Is it regression?

Yes, it worked with ubuntu 22.04 and runners 20241215.1.0 and 20250105.1.0:
- https://github.com/theislab/anndata2ri/actions/runs/12647235334/job/35239243341
- https://github.com/scverse/pertpy/actions/runs/12718464229/job/35456949286

### Expected behavior

installed Python packages are importable

### Actual behavior

ModuleNotFoundError: No module named '…'

### Repro steps

```yaml
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install build
      - run: python -m build
```
