### ISSUE TITLE
windows-arm-latest-large: bash: command not found

### ISSUE THREAD

**Issue by nichoj10** [actions/runner-images#11635]
### Description

We have a step in our build pipeline that invokes bash to execute a git command. Running this step on the `windows-arm-latest-large` image returns an error with:
```
bash: command not found
```
This documentation suggests to me that bash should be available on the windows arm images: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md. We've found the command runs fine on the windows-latest-large image.

Step:
```
steps:
  - name: Set up git for Windows
    if: ${{ inputs.target_os == 'windows' }}
    shell: bash
    run: git config --system core.longpaths true
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

n/a

### Is it regression?

not sure?

### Expected behavior

step succeeds

### Actual behavior

step fails with command not found

### Repro steps

step provided
