### ISSUE TITLE
Xcode - Single XCTest suite gets run multiple times

### ISSUE THREAD

**Issue by evliu** [actions/runner-images#11712]
### Description

Our github action runs `xcodebuild test -project Project.xcodeproj -scheme Project\ DEV -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' -parallel-testing-enabled NO | xcpretty && exit ${PIPESTATUS[0]}`

It starts the test correctly, but then midway through the current tests, it starts the same test again for no known reason and fails our tests intermittently but passes just fine after business hours.
Logs tend to look like this
```
All tests
Test Suite Project.xctest started
AppInitFlowControllerTests
    ✓ testCheckServerMaintenanceThrowsCorrectError (0.015 seconds)
...
Selected tests
Test Suite Project.xctest started
...
VersionHistoryModelTests
    ✓ testVersionHistoryModel (0.002 seconds)
    ✓ testVersionHistoryModelInvalidDate (0.083 seconds)
Executed 225 tests, with 0 failures (0 unexpected) in 4.165 (9.503) seconds

Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
2025-03-03 18:13:48.387 xcodebuild[[359](https://github.com/cg-tech/project-mobile/actions/runs/13599568322/job/38119598047#step:6:360)1:22114] [MT] IDETestOperationsObserverDebug: 216.435 elapsed -- Testing started completed.
2025-03-03 18:13:48.388 xcodebuild[3591:22114] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2025-03-03 18:13:48.388 xcodebuild[3591:22114] [MT] IDETestOperationsObserverDebug: 216.435 sec, +216.435 sec -- end
Failing tests:
	PushNotificationServiceTests.successfullySendsDeviceToken()
** TEST FAILED **
```

Our Project.yml for the testing looks like this
```
  Test:
    runs-on: macOS-15
    needs: Build
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app && /usr/bin/xcodebuild -version

      - name: Testing App iPhone 16 iOS 18.2
        run: xcodebuild test -project Project.xcodeproj -scheme Project\ DEV -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' -parallel-testing-enabled NO | xcpretty && exit ${PIPESTATUS[0]}
```

Our test plan only has one set of XCTest, and locally, it always just runs that test suite and passes with no issues.

Any insights would be amazing, I've spent hours looking into this for many months now. Right now, we just re-run the action until it passes. It's also always a random test that seemingly fails even though it passes on the first run of the XCTest suite.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [x] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

all versions of the macos images for years now

### Is it regression?

No

### Expected behavior

The XCTest suite runs once and passes.

### Actual behavior

The XCTtest suite runs more than once (up to three times) and one besides the first fails sometimes even though it says `0 tests executed`

### Repro steps

We run our test action, with the main part being `xcodebuild test -project Project.xcodeproj -scheme Project\ DEV -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' -parallel-testing-enabled NO | xcpretty && exit ${PIPESTATUS[0]}`
