### ISSUE TITLE
`perf stat` does not work on Linux runners (even ARM ones)

### ISSUE THREAD

**Issue by Luni-4** [actions/runner-images#11789]
### Description

When I run the `perf stat` command, I do not obtain the same output that I get locally. GitHub Actions fails, and I do not know if that is caused by something that I'm not aware of or there is a bug. I've tried to look for a solution online also but without any results. Thanks a lot for your help!  

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

```console
Current runner version: '2.322.0'
Operating System
  Ubuntu
  24.04.2
  LTS
Runner Image
  Image: ubuntu-24.04
  Version: 20250309.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250309.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250309.1
Runner Image Provisioner
  2.0.422.1
GITHUB_TOKEN Permissions
  Actions: write
  Attestations: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Complete job name: perf
```

Build link: https://github.com/SoftengPoliTo/lich/actions/runs/13838452249/job/38719427144

### Is it regression?

This is the first time I've experienced this kind of behavior, so it is not a regression in my case.

### Expected behavior

The CI script inserted below completes without failures.

### Actual behavior

Getting the following error

```console
Run sudo perf stat --timeout 10000 -ae power/energy-cores/,power/energy-pkg/,power/energy-psys/
  sudo perf stat --timeout 10000 -ae power/energy-cores/,power/energy-pkg/,power/energy-psys/
  shell: /usr/bin/bash -e {0}
event syntax error: 'power/energy-cores/,power/energy-pkg/,power/energy-psys/'
                     \___ Bad event or PMU

Unable to find PMU or event on a PMU of 'power'

Initial error:
event syntax error: 'power/energy-cores/,power/energy-pkg/,power/energy-psys/'
                     \___ Cannot find PMU `power'. Missing kernel support?
Run 'perf list' for a list of valid events

 Usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events
Error: Process completed with exit code 129.
```

### Repro steps

This is the GitHub Actions script:

```yml
name: perf

on:
  push:
    branches:
      - master

jobs:
  perf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install perf
      run: |
        sudo apt-get update && sudo apt-get install linux-tools-common \

    - name: Enable perf event paranoid flag
      run: sudo sysctl kernel.perf_event_paranoid=1

    - name: Set Kernel KPTR  Restriction
      run: sudo sysctl kernel.kptr_restrict=0

    - name: See cpu Info
      run: cat /proc/cpuinfo

    - name: Show perf info events
      run: cat /boot/config-$(uname -r) | grep PERF_EVENTS

    - name: Show perf list
      run: sudo perf list

    - name: Run perf
      run: sudo perf stat --timeout 10000 -ae power/energy-cores/,power/energy-pkg/,power/energy-psys/
```

At the `Run perf` step, I get the following error:

```console
Run sudo perf stat --timeout 10000 -ae power/energy-cores/,power/energy-pkg/,power/energy-psys/
  sudo perf stat --timeout 10000 -ae power/energy-cores/,power/energy-pkg/,power/energy-psys/
  shell: /usr/bin/bash -e {0}
event syntax error: 'power/energy-cores/,power/energy-pkg/,power/energy-psys/'
                     \___ Bad event or PMU

Unable to find PMU or event on a PMU of 'power'

Initial error:
event syntax error: 'power/energy-cores/,power/energy-pkg/,power/energy-psys/'
                     \___ Cannot find PMU `power'. Missing kernel support?
Run 'perf list' for a list of valid events

 Usage: perf stat [<options>] [<command>]

    -e, --event <event>   event selector. use 'perf list' to list available events
Error: Process completed with exit code 129.
```

Looking at the `perf list` output (attached in the `perf-list.log`), `power/` is not present, though.

[perf-list.log](https://github.com/user-attachments/files/19232449/perf-list.log)

Would it be possible to enable `/power` in some way? Searching for online, it seems it is necessary to build the kernel again with different parameters. 

Thanks a lot for your help! Let me know if you need additional information.
