### ISSUE TITLE
macos-14 build 20250304.890 exhibits xcode archive fails compared with 20250127.727 (mac intel)

### ISSUE THREAD

**Issue by M1ke** [actions/runner-images#11837]
### Description

This bug is hard to adequately describe, because xcode's ability to debug failed CI builds is non-existant thanks to its poor quality logging capabilities.

What we are observing on hosted macod-14 runners is that a project which built in xcode on image version 20250127.727 now fails to build on 20250304.890, even if run for the same specific commits.

The xcode project ends with the log:

```
▸ Building library libreact-native-calendar-events.a
    Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'react-native-config' from project 'Pods')
▸ Running script 'Run Script'
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target '<redacted>' from project '<redacted>')
    Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target '<redacted>' from project '<redacted>')
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/runner/Library/Developer/Xcode/DerivedData/<redacted>-brfvshermxhrdpfhiotpxsdtbuxg/Build/Intermediates.noindex/ArchiveIntermediates/<redacted>/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-config.build/Script-46EB2E0000E170.sh (in target 'react-native-config' from project 'Pods')
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```

If we compare the working build from 20250127 that section of log reads

```
▸ Building library libreact-native-calendar-events.a
    Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'react-native-config' from project 'Pods')
▸ Running script 'Run Script'
▸ Compiling react-native-config-dummy.m
▸ Compiling ReactNativeConfig.m
```

It's unclear which version or config change in the image precipitates this error; is it possible to run a build on a prior version so we can test?

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [x] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

20250304.890

### Is it regression?

Yes 20250127.727

### Expected behavior

Build succeeds

### Actual behavior

Build fails

### Repro steps

Hard to reproduce, we're building a React Native project, but it's relatively standard - cocoapods, react native build, xcode build

**Comment by archita105** [comment]
Hi @M1ke , We will investigate the issue and keep you posted on further updates.
Thank you.

**Comment by M1ke** [comment]
Thanks; the builds are private but I can arrange to preview items with somebody on a screenshare if it's helpful, as we're relying on this in a production context.

**Comment by M1ke** [comment]
If there was a way to use an old hosted image that would be super useful, even if it was just a couple of versions back.

**Comment by archita105** [comment]
Hi @M1ke , 
Unfortunately, using an old hosted image is not possible. Since your workflow is private, could you share your YAML pipeline code to help us reproduce the issue?

**Comment by M1ke** [comment]
@archita105 thanks, here's a slightly redacted version (just company name etc removed)

```
  - task: InstallAppleCertificate@2
    condition: succeeded()
    inputs:
      certSecureFile: ${{ parameters.certificateSecureFile }}
      certPwd: ${{ parameters.certificatePassword }}

  - task: InstallAppleProvisioningProfile@1
    condition: succeeded()
    inputs:
      provProfileSecureFile: ${{ parameters.provisioningProfile }}

  - script: brew install watchman
    displayName: Installing watchman

  - task: NodeTool@0
    displayName: Installing node
    condition: succeeded()
    inputs:
      versionSpec: '12.x'

  - script: npm ci
    condition: succeeded()
    displayName: Installing node packages

  - script: "npm install react-native-webview@^8"
    condition: succeeded()
    displayName: Installing ios-specific react native webview

  - task: Bash@3
    condition: succeeded()
    displayName: Building Fonts
    inputs:
      filePath: "$(System.DefaultWorkingDirectory)/bin/font-build"

  - task: Bash@3
    condition: succeeded()
    displayName: Running setup script
    inputs:
      filePath: bin/setup
      workingDirectory: $(System.DefaultWorkingDirectory)

  - bash: |
      config_path="$(System.DefaultWorkingDirectory)/App/Config"
      urls_path="$config_path/Urls${{ parameters.urls }}.js"
      echo "Writing from $urls_path"

      if ! cp "$urls_path" "$config_path/Urls.js" ; then
        echo "The URls at $urls_path could not be found"
        exit 1
      fi
    condition: succeeded()
    # This actually has no effect for ios as it doesn't import Urls.js from AppConfig.ios.js
    displayName: Setting Urls

  - task: Bash@3
    condition: succeeded()
    displayName: Setting brand
    inputs:
      filePath: "$(System.DefaultWorkingDirectory)/bin/set-brand.sh"
      arguments: ${{ parameters.brand }}

  # This can be removed when react-native is updated as it is now a prebuild step in xcode and gradle
  - script: >
      npx react-native bundle
      --platform ${{ parameters.platform }}
      --dev false
      --entry-file index.js
      --bundle-output ${{ parameters.bundleOutput }}
      --assets-dest ${{ parameters.assetsDest }}
    condition: succeeded()
    displayName: Bundling React Native

  - script: |
      echo "##vso[task.setvariable variable=packageVersion]$(jq -r ".version" $(System.DefaultWorkingDirectory)/package.json)"
    displayName: Read package version

  - script: >
      find '${{ parameters.projectPath }}' -name 'Info.plist' ! -path '${{ parameters.projectPath }}/Pods/*' |
      xargs -n1 -I {} /usr/libexec/PlistBuddy {}
      -c "Set :CFBundleVersion ${{ parameters.buildNumber }}"
      -c "Set :CFBundleShortVersionString $(packageVersion)"
    displayName: 'Setting version'

  - task: Cache@2
    condition: succeeded()
    displayName: 'Cocoapods cache'
    inputs:
      key: 'pods | "$(Agent.OS)" | ${{ parameters.projectPath }}/Podfile.lock'
      restoreKeys: pods | "$(Agent.OS)"
      path: '${{ parameters.projectPath }}/Pods'
      cacheHitVar: podsCached

  - task: CocoaPods@0
    condition: succeeded()
    inputs:
      workingDirectory: "${{ parameters.projectPath }}"

  # This is a workaround due to react-native being out of date, this can be removed when its updated
  - script: |
      sed -i.bo 's/ node->getLayout()\.hadOverflow |/ node->getLayout()\.hadOverflow ||/' ./node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp
    displayName: Compile error workaround

  - task: Xcode@5
    condition: succeeded()
    inputs:
      actions: 'clean'
      scheme: ABC
      sdk: 'iphoneos'
      configuration: Release${{ parameters.brand }}
      xcWorkspacePath: ${{ parameters.projectPath }}/ABC.xcworkspace
      xcodeVersion: 15
      packageApp: true
      signingOption: 'manual'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
      exportTeamId: ${{ parameters.teamId }}
```

Worth noting that whilst this is using an older React Native build, older Node version, everything built fine until a couple of weeks ago when the latest runner version was released. The failure is in the Xcode step and there's a lot of logs but no clear log line that tells us what's wrong.
