### ISSUE TITLE
macOS runner fails to launch unit tests

### ISSUE THREAD

**Issue by ospfranco** [actions/runner-images#11874]
### Description

This is related to https://github.com/actions/runner-images/issues/9511

I have a workflow where I'm trying to run Xcode unit/ui tests. Same as on the mentioned previous ticket, everything works smoothly on local environment. I have even decoupled the booting of the simulator from the running of the test command. 

The tests pass correctly, but sometimes they fail and I get the following output:

```
18m 55s
Run set -o pipefail && \
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:B3DE5744-A428-48F9-BB83-4ECBB3588607, OS:[1](https://github.com/OpacityLabs/opacity-core/actions/runs/14055419837/job/39353724805?pr=174#step:10:1)8.2, name:iPhone 16 }
{ platform:iOS Simulator, id:B3DE5744-A428-48F9-BB83-4ECBB3588607, OS:18.2, name:iPhone [16](https://github.com/OpacityLabs/opacity-core/actions/runs/14055419837/job/39353724805?pr=174#step:10:17) }
▸ Running script '[CP] Copy XCFrameworks'
▸ Compiling OpacityObjCWrapper.mm
▸ Compiling OpacityIOSHelper.mm
▸ Compiling ModalWebViewController.mm
▸ Compiling Reachability.m
▸ Compiling OpacityCore-dummy.m
▸ Building library libOpacityCore.a
▸ Running script 'Copy generated compatibility header'
▸ Compiling Pods-OpacityPod_Example-dummy.m
▸ Building library libPods-OpacityPod_Example.a
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Linking __preview.dylib
▸ Copying /Users/runner/Library/Developer/Xcode/DerivedData/OpacityPod-gnxpsoqitkyxkfdmqauoirrnhwkb/Build/Products/Debug-iphonesimulator/OpacityPod_Example.app/.env
▸ Copying InfoPlist.strings
▸ Compiling Main.storyboard
▸ Compiling LaunchScreen.storyboard
▸ Processing OpacityPod-Info.plist
▸ Precompiling /Users/runner/work/opacity-core/opacity-core/opacity-ios/pod_example/Opacity/OpacityPod-Prefix.pch
▸ Compiling main.m
▸ Compiling OpacityAppDelegate.m
▸ Linking OpacityPod_Example.debug.dylib
▸ Generating 'OpacityPod_Example.app.dSYM'
▸ Linking OpacityPod_Example
▸ Generating 'OpacityPod_Example.app.dSYM'
▸ Touching OpacityPod_Example.app (in target 'OpacityPod_Example' from project 'OpacityPod')
▸ Processing empty-OpacityPod_UITests.plist
▸ Linking OpacityPod_UITests
▸ Copying Info.plist
▸ Touching OpacityPod_UITests.xctest (in target 'OpacityPod_UITests' from project 'OpacityPod')
2025-03-25 09:14:41.336 xcodebuild[15755:78707]  iOSSimulator: C9F44F56-39AF-4789-879E-E342D540CFCD: Failed to launch app with identifier: com.opacitycore.OpacityPod-UITests.xctrunner and options: {
    "activate_suspended" = 1;
    arguments =     (
    );
    environment =     {
        "APP_DISTRIBUTOR_ID_OVERRIDE" = "com.apple.AppStore";
        "CA_ASSERT_MAIN_THREAD_TRANSACTIONS" = 0;
        "CA_DEBUG_TRANSACTIONS" = 0;
        "DYLD_FRAMEWORK_PATH" = "/Users/runner/Library/Developer/Xcode/DerivedData/OpacityPod-gnxpsoqitkyxkfdmqauoirrnhwkb/Build/Products/Debug-iphonesimulator:/Applications/Xcode_16.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks";
        "DYLD_INSERT_LIBRARIES" = "/Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS [18](https://github.com/OpacityLabs/opacity-core/actions/runs/14055419837/job/39353724805?pr=174#step:10:19).2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib";
        "DYLD_LIBRARY_PATH" = "/Users/runner/Library/Developer/Xcode/DerivedData/OpacityPod-gnxpsoqitkyxkfdmqauoirrnhwkb/Build/Products/Debug-iphonesimulator:/Applications/Xcode_16.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib";
        "LLVM_PROFILE_FILE" = "/var/folders/bz/h4njq8yd7td8qk42rt_9f0p00000gn/T/com.opacitycore.OpacityPod-UITests.xctrunner/EF45[19](https://github.com/OpacityLabs/opacity-core/actions/runs/14055419837/job/39353724805?pr=174#step:10:20)CB-B305-46A6-8129-8D27B3886C34-15755-0000000A80B7692A/755A779C-5F62-42DE-A695-EB8732758501-%p%c.profraw";
        "MTC_CRASH_ON_REPORT" = 1;
        NSApplicationQuitWithoutSuddenTermination = YES;
        NSUnbufferedIO = YES;
        "OS_ACTIVITY_DT_MODE" = YES;
        "RUN_DESTINATION_DEVICE_NAME" = "Clone 2 of iPhone 16";
        "RUN_DESTINATION_DEVICE_PLATFORM_IDENTIFIER" = "com.apple.platform.iphonesimulator";
        "RUN_DESTINATION_DEVICE_UDID" = "C9F44F56-39AF-4789-879E-E342D540CFCD";
        "SQLITE_ENABLE_THREAD_ASSERTIONS" = 1;
        TERM = dumb;
        XCTestBundlePath = "PlugIns/OpacityPod_UITests.xctest";
        XCTestConfigurationFilePath = "";
        XCTestSessionIdentifier = "E05E6E99-2521-4BFE-9F70-B5BA1886F1E8";
        "__XCODE_BUILT_PRODUCTS_DIR_PATHS" = "/Users/runner/Library/Developer/Xcode/DerivedData/OpacityPod-gnxpsoqitkyxkfdmqauoirrnhwkb/Build/Products/Debug-iphonesimulator";
        "__XPC_DYLD_FRAMEWORK_PATH" = "/Users/runner/Library/Developer/Xcode/DerivedData/OpacityPod-gnxpsoqitkyxkfdmqauoirrnhwkb/Build/Products/Debug-iphonesimulator";
        "__XPC_DYLD_LIBRARY_PATH" = "/Users/runner/Library/Developer/Xcode/DerivedData/OpacityPod-gnxpsoqitkyxkfdmqauoirrnhwkb/Build/Products/Debug-iphonesimulator";
        "__XPC_LLVM_PROFILE_FILE" = "/var/folders/bz/h4njq8yd7td8qk42rt_9f0p00000gn/T/com.opacitycore.OpacityPod-UITests.xctrunner/EF4519CB-B305-46A6-8129-8D27B3886C34-15755-0000000A80B7692A/755A779C-5F62-42DE-A695-EB8732758501-%p%c.profraw";
    };
    stderr = "/dev/ttys002";
    stdout = "/dev/ttys002";
    "terminate_running_process" = 1;
    "wait_for_debugger" = 1;
} (error = Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "Simulator device failed to launch com.opacitycore.OpacityPod-UITests.xctrunner." UserInfo={NSLocalizedDescription=Simulator device failed to launch com.opacitycore.OpacityPod-UITests.xctrunner., NSUnderlyingError=0x600002bfa1f0 {Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.opacitycore.OpacityPod-UITests.xctrunner" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.opacitycore.OpacityPod-UITests.xctrunner" failed., NSUnderlyingError=0x600002bfb090 {Error Domain=FBProcessExit Code=64 "The process failed to launch." UserInfo={NSUnderlyingError=0x600002bf88d0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo=0x600001b68180 (not displayed)}, BSErrorCodeDescription=launch-failed, NSLocalizedFailureReason=The process failed to launch.}}, FBSOpenApplicationRequestID=0x1249, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace).}}, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace)., FBSOpenApplicationRequestID=0x1249, SimCallingSelector=launchApplicationWithID:options:pid:error:, BSErrorCodeDescription=RequestDenied})
[20](https://github.com/OpacityLabs/opacity-core/actions/runs/14055419837/job/39353724805?pr=174#step:10:21)25-03-25 09:19:52.462 xcodebuild[15755:48954] [MT] IDETestOperationsObserverDebug: 896.078 elapsed -- Testing started completed.
2025-03-25 09:19:52.473 xcodebuild[15755:48954] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
20[25](https://github.com/OpacityLabs/opacity-core/actions/runs/14055419837/job/39353724805?pr=174#step:10:26)-03-25 09:19:52.473 xcodebuild[15755:48954] [MT] IDETestOperationsObserverDebug: 896.078 sec, +896.078 sec -- end
Failing tests:
	OpacityPod_UITests.testInAppBrowserOpens()

** TEST FAILED **
```

As mentioned on the previous ticket, I believe this is an issue on the runner itself, some UI dialog popping up or something else that blocks the execution of the `.xctrunner`. However, the solution on the previous ticket (changing the selected xcode version) is not working for me. Both Xcode 16.1 and 16.2 fail with the same error

When trying a `macos-15` runner I get an accessibility access error:

```
Testing failed:
	OpacityPod_UITests-Runner (24149) encountered an error (The test runner failed to initialize for UI testing. (Underlying Error: Failed call to AXDisableAccessibilityOnTermination: kAXErrorCannotComplete))
```

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [x] macOS 14 Arm64
- [ ] macOS 15
- [x] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Here is a link to a build with 16.1

https://github.com/OpacityLabs/opacity-core/actions/runs/14055419837/job/39353724805?pr=174

Here is one with 16.2

https://github.com/OpacityLabs/opacity-core/actions/runs/14056131221/job/39355907281?pr=174

These are on a private repo, not sure if you need a public reproduction... then it will be hard to provide one.

### Is it regression?

No

### Expected behavior

Tests not to timeout

### Actual behavior

Timeout error

### Repro steps

This is the workflow that I'm using

```yaml
ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "true"
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Add stdlib source
        run: rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Create .env file
        run: |
          echo "OPACITY_API_KEY=${{ secrets.OPACITY_API_KEY }}" > opacity-ios/pod_example/Opacity/.env
        env:
          OPACITY_API_KEY: ${{ secrets.OPACITY_API_KEY }}
      - name: Install Rust Target
        run: rustup target add aarch64-apple-ios-sim
      - run: mise build ios debug aarch64-apple-ios-sim
        shell: bash
      - name: Boot simulator
        run: |
          xcrun simctl boot "iPhone 16" || exit 1
          xcrun simctl bootstatus "iPhone 16"
      - name: Run e2e Tests
        run: |
          set -o pipefail && \
          xcodebuild test \
            -workspace OpacityPod.xcworkspace \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -scheme OpacityPod_Example \
            -only-testing:OpacityPod_UITests \
            -destination-timeout 200 \
            -default-test-execution-time-allowance 900 | xcpretty && exit ${PIPESTATUS[0]}
        working-directory: opacity-ios/pod_example
      - name: Output xcresult on failure
        if: failure()
        run: |
          XCRESULT_PATH=$(find /Users/runner/Library/Developer/Xcode/DerivedData/OpacityPod-* -name "Test-OpacityPod_Example-*.xcresult" -type d -print -quit)
          if [ ! -z "$XCRESULT_PATH" ]; then
            echo "Found xcresult at: $XCRESULT_PATH"
            xcrun xcresulttool get object --legacy --path "$XCRESULT_PATH" --format json | jq .
          else
            echo "No xcresult file found"
          fi
```

However, as I mentioned some times they pass and sometimes they fail.
