### ISSUE TITLE
ubuntu-latest failing to build scala projects running on sbt

### ISSUE THREAD

**Issue by shamwilA** [actions/runner-images#11975]
### Description

Description
After pointing ubuntu-latest to ubuntu-24.0 image, all our pipeline for scala projects using sbt package manager fails

sbt: command not found

Could you please add the sbt package

Thanks a lot!

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Ubuntu 24.04

### Is it regression?

Ubuntu 22.04

### Expected behavior

sbt binary should exist in Ubuntu 24.04 

### Actual behavior

sbt: command not found

### Repro steps

Add a task to azure-pipelines.yaml as below

```
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                sbt test
```
