### ISSUE TITLE
Installing project dependencies stuck in ubuntu-22.04 using Yarn

### ISSUE THREAD

**Issue by kendepelchin** [actions/runner-images#12043]
### Description

Hi,
We're having issues with a GitHub action that installs yarn.
We have 3 jobs that all need to install the project dependencies. First two are good, the last one is stuck and won't go through. They are run in parallel.
The only difference is that the first two jobs use ubuntu-latest to run, the one that is failing uses ubuntu-22.04.

When we bump to ubuntu-latest, it goes through. But we can't use this instance as we rely on some mongo dependencies that can't be run on the latest ubuntu.
Re-running with debug logs enabled also didn't help us to pinpoint the exact issue.
The action just keeps running until we manually cancel it.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

Runner Image
  Image: ubuntu-22.04
  Version: 20250406.1.0
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20250406.1

### Is it regression?

Yes, succesful runs on 20250323.1.0 (https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20250323.1)

### Expected behavior

Project dependencies are installed and jest is ran.

### Actual behavior

Project dependencies are stuck and we can't get through to the next step in the pipeline.

### Repro steps

```
on:
 pull_request:
   branches:
     - '*'

env:
 NODE_VERSION: 20.8.1

jobs:
 eslint:
   if: github.event.pull_request.draft == false
   name: Run ESLint checks
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: "${{env.NODE_VERSION}}"
         cache: 'yarn'

     - name: Install project dependencies
       run: yarn

     - name: ESLint
       run: |
         export NODE_OPTIONS=--max_old_space_size=4096
         yarn lint

 type-check-shared-and-server:
   if: github.event.pull_request.draft == false
   name: Run TS checks
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: "${{env.NODE_VERSION}}"
         cache: 'yarn'

     - name: Install project dependencies
       run: yarn

     - name: TS checks shared
       run: npx tsc --noEmit --project ./shared/tsconfig.json

     - name: TS checks server
       run: npx tsc --project ./server/tsconfig.ci.json

     - name: TS checks editor
       run: npx tsc --noEmit --project ./editor/tsconfig.json

     - name: TS checks client
       run: npx tsc --noEmit --project ./client/tsconfig.json

 jest:
   if: github.event.pull_request.draft == false
   name: Run unit and integration tests
   runs-on: ubuntu-22.04
   steps:
     - uses: actions/checkout@v4
     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: "${{env.NODE_VERSION}}"
         cache: 'yarn'

     - name: Install project dependencies
       run: yarn

     - name: Test using Jest
       run: yarn test
```

**Comment by kendepelchin** [comment]
Not sure if the following issue is related as it states the jobs gets cancelled: https://github.com/actions/runner-images/issues/11988
Ours get stuck and kept idling for hours

**Comment by RaviAkshintala** [comment]
Hi @kendepelchin Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by RaviAkshintala** [comment]
Hi @kendepelchin Kindly share the logs; it will help in resolving the issue.

**Comment by enescakir** [comment]
> Not sure if the following issue is related as it states the jobs gets cancelled: [#11988](https://github.com/actions/runner-images/issues/11988) Ours get stuck and kept idling for hours

It's probably related. It was canceled at #11988 due to `timeout-minutes: 30`, so it got stuck and was canceled after 30 minutes. Since the default timeout is 6 hours, your job idled for hours.

**Comment by kendepelchin** [comment]
@RaviAkshintala 
I've combined them here: https://gist.github.com/kendepelchin/df8bbdfba6568e260e1dd59c45694f68
Let me know if you need more information

**Comment by sir-captainmorgan21** [comment]
We are also running into this issue. Seems to have started within the last week to few weeks? Haven't changed any versions of yarn or ubuntu or anything

**Comment by sir-captainmorgan21** [comment]
@kendepelchin if you check out the last comment here (https://github.com/shelfio/jest-mongodb/issues/479). It worked for us until this gets sorted out

**Comment by rst-roomle** [comment]
We are also running into this issue. The timeout happens on 
npm ci

The workflow fails using:
Runner Image
  Image: ubuntu-22.04
  Version: 20250406.1.0

The workflow runs successfully using:
Runner Image
  Image: ubuntu-22.04
  Version: 20250323.1.0
  
Runner Image
  Image: ubuntu-24.04
  Version: 20250413.1.0

Running the workflow as container job also works.

Not sure if it is related to the node and npm version:
/opt/hostedtoolcache/node/18.18.0/x64/bin/node
v18.18.0
/opt/hostedtoolcache/node/18.18.0/x64/bin/npm
9.8.1

**Comment by kendepelchin** [comment]
@sir-captainmorgan21 We fixed it temporary like this:

```
runs-on: ubuntu-22.04
    container:
      # TODO: This was added because of https://github.com/actions/runner-images/issues/12043
      # TODO: remove this when above issue is resolved.
      image: node:20.8.1-bullseye
```


Running a container with node inside of Ubuntu 22.04
