### ISSUE TITLE
Ubuntu 24.04 - Unsatisfied i386 dependencies with unusual workaround

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [actions/runner-images#12091]
### Description

When trying to install i386 dependencies on projects that include `libsdl2-dev` and `libsdl2-dev:i386`, apt-get will report:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-dev:i386 : Depends: libglib2.0-dev-bin:i386 (= 2.80.0-6ubuntu3.2)
                       Depends: libglib2.0-dev-bin-linux:i386 (= 2.80.0-6ubuntu3.2)
E: Unable to correct problems, you have held broken packages.
```

# Current workaround:

By adding `libvulkan-dev` and `libvulkan-dev:i386`, all dependency issues are fixed for me... but many critical OS programs are uninstalled in the process:

```
The following packages will be REMOVED:
  apport byobu cifs-utils clang-format-16 clang-format-17 clang-format-18
  clang-tidy-16 clang-tidy-17 clang-tidy-18 clang-tools-16 clang-tools-17
  clang-tools-18 cloud-init command-not-found grub-gfxpayload-lists grub-pc
  grub-pc-bin landscape-common llvm-16-dev llvm-16-tools llvm-17-dev
  llvm-17-tools llvm-18-dev llvm-18-tools mercurial netplan.io
  networkd-dispatcher os-prober pastebinit python-is-python3 python3-apport
  python3-bcrypt python3-cffi-backend python3-commandnotfound
  python3-cryptography python3-dbus python3-dev python3-distupgrade
  python3-gdbm python3-gi python3-jinja2 python3-jsonschema
  python3-launchpadlib python3-lazr.restfulclient python3-markupsafe
  python3-netifaces python3-netplan python3-newt python3-oauthlib
  python3-openssl python3-parted python3-pyrsistent python3-service-identity
  python3-software-properties python3-systemd python3-twisted
  python3-update-manager python3-venv python3-yaml python3-zope.interface
  python3-zstandard python3.12-dev python3.12-venv software-properties-common
  sosreport ssh-import-id ubuntu-minimal ubuntu-pro-client
  ubuntu-pro-client-l10n ubuntu-release-upgrader-core ubuntu-server
  update-manager-core update-notifier-common walinuxagent
```

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

`20250323.1.0`: https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64/actions/runs/14290573310
`20250420.1.0`: https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64/actions/runs/14636181842 (ignore the Windows errors)

### Is it regression?

Image: ubuntu-22.04, Version: 20250316.1.0: https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64/actions/runs/14024425568

### Expected behavior

- No resort to install `libvulkan-dev` and `libvulkan-dev:i386`
- No need to purge critical programs linked to the operating system

### Actual behavior

See the description...

### Repro steps

1. Clone https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64
2. Trigger `workflow_dispatch` for `.github/workflows/build.yml` on `up2025` branch
3. Wait a few minutes to see the result...

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Jj0YzL5nvJ ,Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Jj0YzL5nvJ , We have followed your repro steps and appears, the builds is [successful](https://github.com/vidyasagarnimmagaddi/mupen64plus-video-glide64/actions/runs/14657275845/job/41134452715) . kindly let us know .

**Comment by kishorekumar-anchala** [comment]
Hi @Jj0YzL5nvJ - This issue does not appear to be related to the runner image repository. I kindly request you to review the code and make the necessary changes accordingly. I will be closing this issue, but please feel free to reach out if you have any concerns. Thank you!

**Comment by Jj0YzL5nvJ** [comment]
Clearly `dpkg` or `apt` are not resolving dependencies for i386. The true issue is how adding "_random_" dependencies solves the dependency problem for i386 but renders the operating system unusable.

### The whole point is to point out that this behavior would be unacceptable in a non-volatile installation/image.

This [code](https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64/actions/runs/14732882706) summarizes the issue:
```
name: SDL2 i386 Dependency Tests

on: [push, pull_request, workflow_dispatch]

jobs:

  Ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - deps: crossbuild-essential-i386 g++-i686-linux-gnu gcc-i686-linux-gnu
            tsk: Crossbuild
          - deps: g++-multilib gcc-multilib
            tsk: Multilib
          - deps: crossbuild-essential-i386 g++-i686-linux-gnu gcc-i686-linux-gnu libvulkan-dev libvulkan-dev:i386
            tsk: Crossbuild + Workaround
          - deps: g++-multilib gcc-multilib libvulkan-dev libvulkan-dev:i386
            tsk: Multilib + Workaround
    name: Ubuntu 24.04 / ${{ matrix.tsk }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Testing dependency installation resolution for SDL2 i386
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get --fix-broken --reinstall -y install build-essential clang g++ gcc git nasm pkg-config libsdl2-dev libsdl2-dev:i386 ${{ matrix.deps }}
```
