### ISSUE TITLE
azure-streamanalytics-cicd is broken on ubuntu-24.04 image

### ISSUE THREAD

**Issue by kipusoep** [actions/runner-images#12201]
### Description

When I use the ubuntu-latest (which now resolves to ubuntu-24.04), the azure-streamanalytics-cicd tool is not working:

```
Generating script.
Script contents:
azure-streamanalytics-cicd build --v2 -project "asa-<REDACTED>/asaproj.json" -outputPath "Output"
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/d5251474-4037-4419-9449-3c9520b22e83.sh
Error: The file /opt/hostedtoolcache/node/22.15.0/x64/lib/node_modules/azure-streamanalytics-cicd/bin/LocalRunService.dll does not exist. There seems an error during the installation.
Please try 'npm install -g -f azure-streamanalytics-cicd' to reinstall the package.
```

The pipeline looks like this:

```yaml
stages:
- stage: build
  displayName: 'Build Stream Analytics'
  jobs:
  - job:
    steps:
    - task: NodeTool@0
      displayName: 'Use Node.js 22.x'
      inputs:
        versionSpec: 22.x
    
    - task: Npm@1
      displayName: 'Install Stream Analytics package'
      inputs:
        command: custom
        verbose: false
        customCommand: 'install -g azure-streamanalytics-cicd'
        
    - script: 'azure-streamanalytics-cicd build --v2 -project "asa-<REDACTED>/asaproj.json" -outputPath "Output"'
      displayName: 'Build StreamAnalytics'
```

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

20250511.1.0

### Is it regression?

Yes, ubuntu-22.04 works fine

### Expected behavior

The tool should be able to run

### Actual behavior

The tool cannot run due to an error

### Repro steps

Use the pipeline above and the ubuntu-24.04 image should suffice.
