### ISSUE TITLE
Latest Windows 2022/2025 and Ubuntu 24.04 runner $env:GITHUB_WORKSPACE in PWSH broken

### ISSUE THREAD

**Issue by c-baumgartner** [actions/runner-images#12282]
### Description

Trying to write something to $env:GITHUB_WORKSPACE resolve to a D:\a\ folder that was working fine until the latest version of the runner image.

This is happening since today on all our actions accross several repos with the same issue. Updating to windows-2025 works fine if you are lucky and get a previous verion/tag

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [x] Windows Server 2022
- [x] Windows Server 2025

### Image version and build link

Image windows-2022 version 20250527.1.0 

### Is it regression?

Image: windows-2022  Version: 20250511.1.0

### Expected behavior

$env:GITHUB_WORKSPACE resolve to a writable filepath

### Actual behavior

An error message telling me that the system cannot write to the path:

```pwsh
Compress-Archive: D:\a\_temp\81e166c2-942a-4fa4-99a4-35773c600511.ps1:30
Line |
  30 |  Compress-Archive -Path $Path -DestinationPath "$ZipTargetPath/users.z …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The path 'D:\a\repo-name\repo-name\export\users' either does not exist or is not a
     | valid file system path.
```

### Repro steps

```yaml
- name: Export
  uses: Azure/powershell@v1
  with:
    azPSVersion: "latest"
    inlineScript: |
      $OutputPath = Join-Path $env:GITHUB_WORKSPACE -ChildPath 'export'
      "Test" | Out-File $OutputPath\test.txt
```
