### ISSUE TITLE
DevEnv takes a long time to initialize

### ISSUE THREAD

**Issue by MH-ZShearer** [actions/runner-images#5301]
### Description

In order to build a Visual Studio Installer Project (`.vdproj`), Visual Studio must be ran via `DevEnv.exe`. When building the installer, it takes anywhere from 2-10. This appears to be regression from #128. I'm not sure when the regression initially occurred as this is the first time I needed DevEnv.

In the reproduction steps below, I use `seanmiddleditch/gha-setup-vsdevenv@v4`. This appears to be required to ensure the installer is built due to the behavior of DevEnv.exe. It seems likely that you may be able to start and wait for the DevEnv process to finish, but I doubt that will result in a faster build. This action does add a lot of clutter to the environment variables as well.

Unfortunately, all our repositories are private and can't be shared publicly. For troubleshooting, I attempted to test our Action against windows-2019 based on #128. I experienced the same issue, as mentioned in Actual Behavior.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-2019 -> 20220316.1
windows-2022 -> 20220316.1

### Is it regression?

Maybe, see description

### Expected behavior

I expected about 20-30 seconds, but I'd be happy with less than 120 seconds.

### Actual behavior

It takes at least 2 minutes to **start** DevEnv, but typically takes 5-10 minutes. The last two runs clocked in at 8:40 and 8:28 on windows-2022 and windows-2019, respectively.

### Repro steps

``` yaml
name: DevEnv Test
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4

    - name: Restore NuGet Packages
      run: msbuild /t:Restore

    - name: Build the application
      run: msbuild /t:Build /p:Configuration=Release

    # Required to Build VS Installer Projects
    - name: Disable Out of Process Building
      run: .\DisableOutOfProcBuild.exe
      working-directory: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild

    # Can take 10+ minutes to complete
    - name: Build the Installer
      run: DevEnv Installer/Installer.vdproj /build Release
```
