### ISSUE TITLE
Support Linux ARM64 build images

### ISSUE THREAD

**Issue by robd003** [actions/runner-images#5631]
### Tool name

ARM64 Linux

### Tool license

new processor architecture

### Add or update?

- [X] Add
- [ ] Update

### Desired version

arm64

### Brief description of tool

Now that Azure supports ARM64 could we **please** get GitHub actions to support building Linux ARM64 binaries using ARM64 machines?

Using cross-compiling on x86_64 systems is about 5x slower.

### URL for tool's homepage

https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by al-cheb** [comment]
Duplicate https://github.com/actions/virtual-environments/issues/2552

**Comment by pukkandan** [comment]
@al-cheb Please do not close this as duplicate. @AlenaSviridenko closed #2552 because Azure did not support ARM at the time, asking to "[create a new one [issue] in case of any other questions](https://github.com/actions/virtual-environments/issues/2552#issuecomment-771478000)". Now, over an year later, Azure does support ARM64. So either this issue or #2552 should be re-opened

**Comment by JimBobSquarePants** [comment]
Please reconsider closing this.

**Comment by Perksey** [comment]
Please reopen!

**Comment by adamdecaf** [comment]
@al-cheb can we re-open this and add support for ARM64?

**Comment by al-cheb** [comment]
We plan to add this feature in the future but its not yet been prioritized.

**Comment by gdams** [comment]
Presumably the announcement of Arm64 VMs in Azure will make enabling this much easier?

**Comment by calvinjhuang** [comment]
@al-cheb do we have a timeline for this in the near future?

**Comment by rafskov** [comment]
@al-cheb do we have an ETA on this?

**Comment by ShayBox** [comment]
Any priority or eta on this?  
Currently trying to add `arm64` architecture and updating repositories leads to Azure repo Not Found errors.  
This would be great, currently there's a large influx of people using ARM64 servers due to Always-Free Oracle Cloud servers, I'd like to cross compile binaries to support said servers with action runners.

**Comment by pukkandan** [comment]
They did say it has not been prioritized, which likely means that there is no ETA. Everyone asking for an ETA doesn't help and is likely just going to get this issue locked...

**Comment by trusktr** [comment]
Haven't tried it yet, but this allows to run on different architectures include ARM64:

https://github.com/uraimo/run-on-arch-action

**Comment by martin-g** [comment]
> Haven't tried it yet, but this allows to run on different architectures include ARM64:
> 
> https://github.com/uraimo/run-on-arch-action

Works like a charm!
But it is based on QEMU and it is much slower than native execution!

**Comment by acidjazz** [comment]
> > Haven't tried it yet, but this allows to run on different architectures include ARM64:
> > https://github.com/uraimo/run-on-arch-action
> 
> Works like a charm! But it is based on QEMU and it is much slower than native execution!

Can I see how you yall set yours up? @trusktr and @martin-g

**Comment by martin-g** [comment]
Sure!
https://github.com/lh3/bwa/blob/master/.github/workflows/ci.yaml#L33-L46

**Comment by nodesocket** [comment]
Is this supported? I tried with:

```yaml
env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  foobar:
      runs-on: [arm64-ubuntu-latest]
```

But the GitHub actions just hang with:

```
Waiting for a runner to pick up this job...
```

Using QEMU is very slow.

**Comment by ddelange** [comment]
If you have access to an arm64 machine, you can [set up](https://github.com/actions/actions-runner-controller/blob/v0.27.0/docs/about-arc.md) self-hosted runners. There are no GitHub runners available that run on arm64, you can just self-host ([blog](https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/)).

The runner images are available for `linux/arm64,linux/amd64`, for instance [`ghcr.io/actions/actions-runner-controller/actions-runner-dind:ubuntu-20.04`](https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller%2Factions-runner-dind).

Hope that helps!

**Comment by richard-viney** [comment]
If it helps anyone, I've been using arm64 runners GitHub Actions runners provided via buildjet.com and they've been working well. I'm not associated with BuildJet in any way.

**Comment by AndrewBarba** [comment]
@richard-viney All I can say is _thank you_ for mentioning buildjet. Seriously that was way too easy. Im not even going to follow this thread anymore, why wait for GH when they are a click of a button and cheaper.

**Comment by LiterallyWar** [comment]
> We plan to add this feature in the future but its not yet been prioritized.

Can it be the future yet?

**Comment by ddelange** [comment]
> We need arm runners to build docker images for our ARM servers, and this like it should do the trick.

fwiw, we use our arm64 cluster to build the arm64 images for the cluster:

```yaml
jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir ~/.kube && printf "$KUBECONFIG" >> ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1 # https://github.com/docker/buildx/issues/1536#issuecomment-1402004792
          driver: kubernetes
          driver-opts: |
            namespace=docker-registry
            replicas=1
            requests.cpu=1m
            limits.cpu=4
            limits.memory=2G
            rootless=true
            nodeselector=kubernetes.io/arch=arm64
            "tolerations=key=arch,value=arm64,operator=Equal,effect=NoSchedule"

     - ...
```
