### ISSUE TITLE
Add tvOS and watchOS to Xcode 14b5

### ISSUE THREAD

**Issue by Brett-Best** [actions/runner-images#6051]
### Tool name

Xcode 14b5 tvOS & watchOS Components

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

The version associated with Xcode 14b5

### Approximate size

Unknown

### Brief description of tool

Xcode 13 and below included all OS platforms by default.
This changed in Xcode 14, where you now get to choose what platforms to install.

https://github.com/SwiftUIX/SwiftUIX/pull/378

This is a package that supports all Apple OS platforms.
Currently we are unable to build and test for tvOS, tvOS Simulator, watchOS, watchOS Simulator with Xcode 14b5.

### URL for tool's homepage

https://developer.apple.com/download/all/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes, unsure how to do it from the command line.
However, when you first open Xcode 14 it prompts you to install the components.
```

**Comment by btfranklin** [comment]
If it helps at all, I just installed Xcode Beta 5, and the versions offered are:
iOS 16.0 (built-in)
macOS 13.0 (built-in)
watchOS 9.0
tvOS 16.0

**Comment by Brett-Best** [comment]
Since I last looked, they seem to have added a command that will hopefully help!

https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
> To download and install all the platforms that the Xcode version you selected supports, use the -downloadAllPlatforms option on xcodebuild.
    `xcodebuild -downloadAllPlatforms`

**Comment by igorboskovic3** [comment]
Hi @Brett-Best we will consider this and get back to you.

**Comment by Brett-Best** [comment]
Any updates? `xcodebuild -downloadAllPlatforms` takes about 8 minutes to run in an action

**Comment by victomized** [comment]
Anyone care to chat with me in private? I have some questions I really need answers to

**Comment by davdroman** [comment]
Here's an ad-hoc step whilst #6140 is pending:

```yml
- name: Install additional SDKs
  if: ${{ matrix.swift == 5.7 && (matrix.platform == 'tvOS' || matrix.platform == 'watchOS') }}
  run: xcodebuild -downloadAllPlatforms
  env:
    DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
```
