### ISSUE TITLE
Inconsistent virtual-environment

### ISSUE THREAD

**Issue by esudaley** [actions/runner-images#6056]
### Description

The github runner is providing inconsistent virtual environments. This occurred not only across runs, but even within a matrix running the same job across multiple containers. This was specifically noticed in the runner's Chrome version.
Env #1 featured Chrome 103.0.5060.134, whereas env #2 featured Chrome 104.0.5112.79

1) Environment: ubuntu-22.04
Version: 20220731.1
  
2) Environment: ubuntu-22.04
Version: 20220807.1

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220731.1
20220807.1

### Is it regression?

Unknown

### Expected behavior

Consistent virtual environment 

### Actual behavior

Inconsistent virtual environment 

### Repro steps

jobs:
  sample-job:  
    runs-on: ubuntu-22.04
    steps:
      - run: google-chrome --product-version

**Comment by mikhailkoliada** [comment]
Hello! We release a new version of the image weekly and gradually. So it may happen.

**Comment by gk-bbai** [comment]
We're still seeing this issue.  Runners in matrixed jobs don't always have the same environment.

With the below configuration some of the jobs randomly have Chrome 113 and others randomly have Chrome 114 (it changes each time I re-run the job).

```
jobs:
    e2e-chrome-tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                # run copies of the current job in parallel
                container: [1, 2, 3]

        steps:
            ...
```
