### ISSUE TITLE
Unable to use command line `winxp` component

### ISSUE THREAD

**Issue by inaryart** [actions/runner-images#6067]
### Description

Unable to use command line `winxp` component, everything worked fine 3 days ago.
If possible, please allow the xp component to exist by default.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/inaryart/test-actions/runs/7805719506?check_suite_focus=true

### Is it regression?

na

### Expected behavior

Can successfully install xp components

### Actual behavior

Failed to install xp components

### Repro steps

- local machine
If you have enterprise version vs2022 on your machine you can successfully install xp components using following command:
```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --add "Microsoft.VisualStudio.Component.WinXP" --installpath="C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet
```
Then use the following command `dir C:\ProgramData\Microsoft\VisualStudio\Packages` to find
```
Microsoft.Windows.XPSupport.Msi.versionxxxxxxxxxxxxxxxxx
```
- github actions

If executing the same command in github actions does not install correctly
```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:  windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        shell: cmd
        run: |
          attrib "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe"
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --add "Microsoft.VisualStudio.Component.WinXP" --installpath="C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet
           dir C:\ProgramData\Microsoft\VisualStudio\Packages
```
