### ISSUE TITLE
Ubuntu : Update the libyaml version to 0.2.5 (latest)

### ISSUE THREAD

**Issue by WaKeMaTTa** [actions/runner-images#6094]
### Description

Hello,

I'm using the ruby gem `pysch` to properly format YAML files.

`pysch` uses `libyaml` package.

The Ubuntu does not have the last version v0.2.5, then is causing problems.

**Solution**

Please upgrade the libyaml version to v0.2.5 ( https://github.com/yaml/libyaml )

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220807.1

### Is it regression?

No

### Expected behavior

Ubuntu image should have libyaml v0.2.5

### Actual behavior

Your libyaml library is outdated: please upgrade to >= 0.2.5

## The GitHub Action

```yml
name: "Format YAML files"

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  # This action can be started by a manual click:
  workflow_dispatch:

jobs:
  build:
    name: "Format YAML fiels"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # required by peter-evans/create-pull-request@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Format YAMLs
        run: bin/format_phrase

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: ":globe_with_meridians: Locales : Pull from phrase.com to master branch"
          body: ""
          commit-message: ":globe_with_meridians: Locales : Pull from phrase.com to master branch"
          add-paths: config/locales
          branch: phrase-pull
          branch-suffix: timestamp
          base: master
```

## The `bin/format_phrase`

```ruby
#!/usr/bin/env ruby
require 'yaml'

if Gem::Version.new(Psych::LIBYAML_VERSION) < Gem::Version.new('0.2.5')
  warn "Your libyaml library is outdated: please upgrade to >= 0.2.5.\n" \
       "The generated YAML will include output trailing spaces for empty scalar nodes, whereas " \
       "Phrase doesn't include them."
end

# Method to "deep sort" keys in a Hash (i.e. recursively), the way that Phrase would do.
#
# The "translation ordering on export" setting has been set to "Default" in Phrase. This is
# translated as MySQL `utf8mb4_general_ci` collation being used. (Whereas the "Natural" option
# is translated as `utf8mb4_unicode_ci` collation).
#
# This collation does not compare Strings exactly the same way as Ruby does. Especially, in this
# collation, the `_` character is considered to be **before** letters, whereas in Ruby it's
# considered as **after** (cf ASCII RFC https://www.rfc-editor.org/rfc/rfc20.html#page-2).
#
# in Ruby (and more generally in ASCII):
#
#     '_' > 'a' => false
#
# in SQL:
#
#     SELECT '_' > 'a' COLLATE utf8mb4_general_ci => 1
#
# To mitigate this difference, we replace the `_` character by `|`, which is considered as before
# letters, in both Ruby and `utf8mb4_general_ci` MySQL collation (`'|' > 'a'` is true).
def sort_hash_alphabetically(hash)
  hash.sort_by do |(key, _value)|
    key.tr('_', '|')
  end.to_h.transform_values! do |v|
    v.is_a?(Hash) ? sort_hash_alphabetically(v) : v
  end
end

APP_ROOT = File.expand_path('..', __dir__)

def locale_files
  Dir.glob("#{APP_ROOT}/config/locales/**/*.yml")
end

def format_phrase(data)
  YAML.dump(sort_hash_alphabetically(data))
end

def check_the_format(fix: false)
  error = false
  locale_files.each do |filepath|
    source = File.read(filepath)
    formatted_source = format_phrase(YAML.load(source))
    if formatted_source != source
      error = true
      msg = fix ? 'is corrected' : 'not properly formatted'
      puts "#{filepath.gsub(/^#{APP_ROOT}/, '.')} #{msg}"
    end
    File.write(filepath, formatted_source) if fix
  end
  if error
    exit(1)
  else
    puts "Locale files are properly formatted"
    exit
  end
end

require 'optparse'

OptionParser.new do |opts|
  opts.banner = "Usage: bin/format_phrase [options]"

  opts.on("-f", "--fix", "Updates the locale files to Phrase format (default)") do
    check_the_format(fix: true)
  end

  opts.on("-c", "--check", "Checks that locale files are properly formatted") do
    check_the_format
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

check_the_format(fix: true)
```
