### ISSUE TITLE
Cannot find an installed Xcode satisfying '13.4' on macos-12-Readme.md

### ISSUE THREAD

**Issue by StNebel** [actions/runner-images#6108]
### Description

Cant fint Xcode 13.4 via xcversion on macos-12.

GitHub workflow 

```
on:
   ...
  
jobs:
  test:
    name: XCTests

    runs-on: macos-12
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.5,name=iPhone 13 Pro Max']
        xcode: ['/Applications/Xcode_13.4.app/Contents/Developer']

    steps:
    - name: Checkout
      timeout-minutes: 5
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Cache
      timeout-minutes: 5
      uses: actions/cache@v2
      id: myId
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    - name: Bundle Install
      timeout-minutes: 5
      run: bundle install
    - name: Swiftgen Install
      timeout-minutes: 5
      run: brew install swiftgen
    - name: Git-LFS Install
      timeout-minutes: 5
      run: brew install git-lfs
    - name: Build and Test
      timeout-minutes: 30
      run: bundle exec fastlane ios allTests
```

<img width="854" alt="grafik" src="https://user-images.githubusercontent.com/54270778/185378138-9e239ff2-15e9-485e-ac81-8f5692d1bd77.png">

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.295.0'
Operating System
  macOS
  12.5
  21G72
Virtual Environment
  Environment: macos-12
  Version: 20220815.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20220815.1/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20220815.1
Runner Image Provisioner
  1.0.0.0-main-20220812-3
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2' (SHA:7884fcad6b5d53d10323aee724dc68d8b9096a2e)
Download action repository 'actions/cache@v2' (SHA:937d24475381cd9c75ae6db12cb4e79714b926ed)

### Is it regression?

idk

### Expected behavior

can find xcode 13.4 on macos-12

### Actual behavior

can not find xcode 13.4 on macos-12

### Repro steps

see description - default workflow
