### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by mwisner** [actions/runner-images#6131]
### Description

Hi,

Within the past few days one specific repo of ours has started receiving:

```
GitHub Actions has encountered an internal error when running your job.
```

Before this, our workflows ran flawlessly for at least the past year, and we have many other repos that have had no issues

I've created a very basic workflow:

```yaml
name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo "test test test"
```

Within the repo in question, this workflow, along with all the other workflows fail. Things I've tried:

- Changing out the `runs-on` to `macos-latest`, `ubuntu-22.04` etc... (The same result)
- Copy this exact same workflow into a new repo (success)

Is there anything repo-specific that would cause this error? 

Note: We are using GH enterprise cloud.

I'm at a bit of a loss here.... Any help or recommendations would be much appreciated. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`ubuntu-latest`

### Is it regression?

yes

### Expected behavior

runs

### Actual behavior

Error: GitHub Actions has encountered an internal error when running your job.

### Repro steps

n/a.
