### ISSUE TITLE
x86_64 Android 31 emulator launch fails on Ubuntu latest runner

### ISSUE THREAD

**Issue by mpconte** [actions/runner-images#6253]
### Description

After installing a x86_64, Android 31 system image:

```
sdkmanager --install "system-images;android-31;google_apis;x86_64"
  echo "no" | avdmanager --verbose create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'
```

Android emulator fails to launch created avd due to an unfound shared library:
```
$ANDROID_SDK_ROOT/emulator/emulator -avd testAVD

/usr/local/lib/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220905.1

### Is it regression?

no

### Expected behavior

Successfully launch an Android emulator for running instrumentation tests

### Actual behavior

```
INFO    | Android emulator version 31.3.10.0 (build_id 8807927) (CL:N/A)
emulator: INFO: Found systemPath /usr/local/lib/android/sdk/system-images/android-31/google_apis/x86_64/
/usr/local/lib/android/sdk/emulator/qemu/linux-x86_64/qemu-system-x86_64: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
Error: Process completed with exit code 127
```

### Repro steps

Sample workflow:

```
name: Android CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create directory for jni libs
      run: mkdir app/libs && mkdir app/libs/arm64-v8a      

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2    
        
    - name: Create Android emulator
      run: |
        sdkmanager --install "system-images;android-31;google_apis;x86_64"
        echo "no" | avdmanager --verbose create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'
    - name: Copy jar files to app folder
      run: gradle extractLibs

    - name: Launch Emulator
      run: | 
        $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD
    - name: Run instrumentation tests
      run: |                
        gradle connectedAndroidTest --stacktrace
    - name: Build apk file
      run: gradle assembleRelease

    - name: Upload (unsigned) APK
      uses: actions/upload-artifact@v2.2.4
      with:
          name: kotlin_demo_apk
          path: ${{github.workspace}}/app/build/outputs/apk/release/app-release-unsigned.apk
```
