### ISSUE TITLE
Windows 2022 Agents suddenly using old version of Nuget tool

### ISSUE THREAD

**Issue by shillam** [actions/runner-images#6328]
### Description

Windows 2022 build agents have started defaulting to using nuget version 4.1.0

Previous builds (last good build was Monday 26th September) were using 5.8.0.

As a workaround I have added the following step to force a newer version of nuget to be used:

```yaml
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet >=6.3.0-0'
  inputs:
    versionSpec: '>=6.3.0-0'
    checkLatest: true
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20220925.1

### Is it regression?

Version: 20220919.1

### Expected behavior

Expect build agent to use consistent version of nuget, the documentation for the agent suggests that the following nuget version is installed:

NuGet 6.3.0.131

### Actual behavior

Nuget restore commands are failing to restore projects with .NET Core 3.1

### Repro steps

Create a solution with a .NET Core 3.1 project, restore this solution in the pipeline.
