### ISSUE TITLE
[macos-latest] Gradle 7.5.1 requires JDK 11 or higher, but default for system (and therefore Gradle@2 task is still JDK 8)

### ISSUE THREAD

**Issue by spoelstraethan** [actions/runner-images#6336]
### Description

We upgraded the gradle-wrapper in our project to use the latest version supplied by the build system instead of overriding with an old version, now we are getting failures due to the `default` JDK set for `macos-latest` aka `macos-11`.

Gradle 7.5.1 requires JDK 11 or higher, but default for system (and therefore Gradle@2 task is still JDK 8)

This may affect other agent OSes, but we are only using `macos-latest` and hitting this.

```
* Where:
Build file '/Users/runner/work/1/s/android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
      Your current JDK is located in /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.345-1/x64/Contents/Home/jre
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

Current task definition:

```
   - task: Gradle@2
     inputs:
        gradleWrapperFile: './android/gradlew'
        workingDirectory: 'android'
        tasks: $(GradleTask)
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
```

We can work around this by adding `jdkVersionOption: '1.11'` to the block which overrides the `JDKVersion` value, but it seems weird to need an override when the `macos-latest` image ONLY includes the newer Gradle which requires a version of the JDK that isn't currently `default`.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '2.210.1'
Operating System
macOS
11.7
20G817
Runner Image
Image: macos-11
Version: 20220925.1
Included Software: https://github.com/actions/runner-images/blob/macOS-11/20220925.1/images/macos/macos-11-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20220925.1
Runner Image Provisioner
1.0.0.0-main-20220916-1
Current image version: '20220925.1'
Agent running as: 'runner'

### Is it regression?

yes

### Expected behavior

Using the system supplied version of Gradle shouldn't require overriding `default` specified in the `Gradle@2` task, which should hopefully use the `system` default and not specify `jdk8`.

### Actual behavior

We need to override things to make it work.

### Repro steps

Create a React Native project with android and ios targets.
Create a pipeline and add a Gradle@2 step to build it after npm install happens.

**Comment by dmitry-shibanov** [comment]
Hello @spoelstraethan. Thank you for your report. For now we're not planing to switch default Java version from 8 to 11 because some customers and other software can depend on Java 8. One of possible solution for you is to use [JavaToolInstaller](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops).

You can try to use this snippet to set up Java 11:
```yaml
steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 11'
  inputs:
    versionSpec: 11
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
```

For now I'm going to close the issue.
