### ISSUE TITLE
Unable to perform GET, POST, PUT requests on GitHub default runners.

### ISSUE THREAD

**Issue by MausamGaurav** [actions/runner-images#6353]
### Description

I am trying to perform simple get and post requests through the 'requests' library in Python. They don't seem to work and my tests fail.

Example test:
```
def test_page():
    url = f"{COGNITO_DOMAIN}/login?client_id={CLIENT_ID}&response_type=code&scope=email+openid&redirect_uri={APP_URI}"
    
    #...........

    ## Get request example 
    page_response = requests.get(url)
```

The error I am getting is the below:
```
error = NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1c9ad32c80>: Failed to establish a new connection: [Errno -2] Name or service not known')
_pool = <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f1c9ad33fa0>
```

I have tried enabling http and https in the workflow yaml file:
```
      - name: allow http and https in firewall # to allow GET and POST requests through the internet
        run: |
          sudo ufw enable; sudo ufw allow http; sudo ufw allow https; sudo ufw allow out http; sudo ufw allow out https
```

However, this doesn't resolve the issue.

FYI, The below is the yaml file I used.
```
name: Test Workflow
on:
  push: # enabling push event on master branch to fire the workflow
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      - name: install packages # install packages from the requirements.txt file
        run: |
          python -m pip install -r requirements.txt
      - name: allow http and https in firewall # to allow GET and POST requests through the internet
        run: |
          sudo ufw enable; sudo ufw allow http; sudo ufw allow https; sudo ufw allow out http; sudo ufw allow out https
      - name: perform pytests # perform tests
        run: |
          python -m pytest tests/test_authenticate.py
        env:
          APP_URI: ${{ secrets.APP_URI }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_USER_GROUPS: ${{ secrets.TEST_USER_GROUPS }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

```

**How do I allow GitHub runners to connect to the internet to perform python tests like above?**

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.297.0

### Is it regression?

No

### Expected behavior

============================================================== 4 passed in 7.21s ==============================================================

### Actual behavior

![image](https://user-images.githubusercontent.com/51297767/193780721-1b55131d-197b-4e27-9ad7-b3906a67c6d0.png)

### Repro steps

1) Install a suitable python version on the GitHub runner.
2) Perform a 'GET' or 'PUT' request in Python using the 'requests' library.
