### ISSUE TITLE
macos-12 Python can't find Tcl/Tk 8.6 shared libraries

### ISSUE THREAD

**Issue by austinmatherne-wk** [actions/runner-images#6442]
### Description

macos-12 has a similar issue as reported for macos-11 in #4931 where `libtcl8.6.dylib` can't be found by Python.

I think the symlink [created here](https://github.com/actions/runner-images/blob/145f9dff8f8a60a99a59ad3137383bd1fb7bea67/images/macos/provision/core/commonutils.sh#L85-L91) for Big Sur also needs to be created for Monterey.

I created a repo ([macos-12-github-runner-tkinter](https://github.com/austinmatherne-wk/macos-12-github-runner-tkinter)) with [a simple workflow](https://github.com/austinmatherne-wk/macos-12-github-runner-tkinter/blob/main/.github/workflows/tkinter.yml) to [reproduce the issue](https://github.com/austinmatherne-wk/macos-12-github-runner-tkinter/actions/runs/3294696107). Along with [a branch](https://github.com/austinmatherne-wk/macos-12-github-runner-tkinter/blob/tcltk-symlink/.github/workflows/tkinter.yml) that manually creates the symlinks in the workflow and [resolves the issue](https://github.com/austinmatherne-wk/macos-12-github-runner-tkinter/actions/runs/3294712612).

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failing:
Version: 20221018.2
https://github.com/austinmatherne-wk/macos-12-github-runner-tkinter/actions/runs/3294696107

Passing (with manually created symlinks in workflow):
Version: 20221018.2
https://github.com/austinmatherne-wk/macos-12-github-runner-tkinter/actions/runs/3294712612

### Is it regression?

No

### Expected behavior

Python can import tkinter.

### Actual behavior

Python can't import tkinter.

### Repro steps

# Fails
```
name: tkinter import test

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-12
    steps:
      - name: Install Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - name: import tkinter
        run: python3 -c 'import tkinter'
```

# Passes
```
name: tkinter import test

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-12
    steps:
      - name: Install Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.10'
      - name: symlink tcltk
        run: |
          version=$(brew info tcl-tk --json | jq -r '.[].installed[].version')
          ln -s /usr/local/Cellar/tcl-tk/$version/lib/libtcl8.6.dylib /usr/local/lib/libtcl8.6.dylib
          ln -s /usr/local/Cellar/tcl-tk/$version/lib/libtk8.6.dylib /usr/local/lib/libtk8.6.dylib
      - name: import tkinter
        run: python3 -c 'import tkinter'
```
