### ISSUE TITLE
Ubuntu Runner Az Cli-Unable to parse parameter

### ISSUE THREAD

**Issue by milkyware** [actions/runner-images#6584]
### Description

I currently use a JSON string to pass parameters into deploying ARM templates to Azure using Az Cli using the command `az deployment group what-if`.  The task being used is below:

``` yaml
- task: AzureCLI@2
    displayName: What If Template
    inputs:
      azureSubscription: ${{parameters.azureSubscription}}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        az deployment group create `
          --resource-group ${{parameters.resourceGroupName}} `
          --template-file ${{parameters.templatePath}} `
          --parameters '$(templateParameters)' `
          --what-if
```

The variable **templateParameters** is a JSON string e.g. `{\"environment\":{\"value\":\"dev\"}}`. When using the ubuntu image  **20221114.1** I get the error **ERROR: Unable to parse parameter: **. This error does not happen when using **20221027.1** or when using the **windows-latest** image. The broken image is using Az Cli 2.42 and the working Ubuntu image is using Az Cli 2.41.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
Version: 20221114.1

### Is it regression?

Yes, Image: ubuntu-20.04 Version: 20221027.1

### Expected behavior

I would expect the json string parameters to be parsed and applied to the ARM template

### Actual behavior

Error produced by Az Cli of **Unable to parse parameter**

### Repro steps

1. Create pipeline using the ubuntu-latest vmImage
2. Check that the os runner is 20221114.1
3. Build JSON string parameters with the quotes escaped e.g. {\"environment\":{\"value\":\"dev\"}
4. Pass the parameters into the az deployment group command e.g. az deployment group what-if --resource-group rg-test  --template-file .\armtemplate.json --parameters '{\"environment\":{\"value\":\"dev\"}}'
