### ISSUE TITLE
.NET Code Coverage no longer being generated - 20221114.1

### ISSUE THREAD

**Issue by slewis96** [actions/runner-images#6588]
### Description

We've noticed since yesterday that our builds have been running on either image version '20221114.1' or '20221027.1' any build that runs using '20221114.1' have been failing to produce any code coverage during their test run tasks, the task looks as follows:
```
- task: DotNetCoreCLI@2
  displayName: Run unit and service tests
  inputs:
     command: test
     projects: |
       app/**/*ServiceTests/*.csproj
       app/**/*UnitTests/*.csproj
     arguments: '--configuration ${{ parameters.buildConfiguration }} /p:CollectCoverage=true /p:ThresholdStat=total /p:Exclude=[xunit.*]* /p:CoverletOutputFormat=json%2ccobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/ /p:MergeWith=$(Build.SourcesDirectory)/TestResults/Coverage/coverage.json /maxcpucount:1 "--logger:\"console;verbosity=detailed\""'
     nobuild: true
     publishTestResults: true
     testRunTitle: Run unit and service tests
```

Builds on image version 20221027.1 work without any issue.

The only additional change from the output of this task is that:
- We have seen several NETSDK1138 warnings.
- The 'Calculating coverage result...' section after the test run is missing

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221114.1

### Is it regression?

No

### Expected behavior

Code coverage calculated and report generated after test runs

### Actual behavior

Test run without any issue however the code coverage doesn't get generated causing failures on further steps of our pipelines

### Repro steps

Run dotnet test via the DotNetCLI@2 task using image version 20221114.1
