### ISSUE TITLE
ubuntu-latest yields 22.04

### ISSUE THREAD

**Issue by jonatanBroberg** [actions/runner-images#6608]
### Description

We have several workflows running on ubuntu-latest and today they all started to fail. Error is related to access rights of creating a folder on the host `OneTimeSetUp: System.UnauthorizedAccessException : Access to the path '/home/runneradmin' is denied.`

When running `lsb_release -a` as a step in the workflow we get 22.04 - even though README specifies that ubuntu-latest should give us 20.04.

Is the latest tag incorrect or is README out of date? 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Is it regression?

ubuntu-latest (last week)

### Expected behavior

ubuntu-latest yields 20.04

### Actual behavior

ubuntu-latest yields 22.04

### Repro steps

```
name: Test workflow
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Print ubuntu version
        run: lsb_release -a
```
