### ISSUE TITLE
The child process does not spawn successfully Error: spawn mongodump ENOENT

### ISSUE THREAD

**Issue by didaquis** [actions/runner-images#6639]
### Description

Hi. 

I have a GitHub Action set up to backup a database. This GitHub Action has been running for months without incident, but now it has stopped working. 
After a bit of research I have found the problem. `runs-on: ubuntu-latest` was using Ubuntu 20.04 until last week but now use Ubuntu 22. This change causes the GitHub Action to fail (I tested this by modifying my code to use the previous Ubuntu version). 

Working Action: 
<img width="986" alt="Funcionando" src="https://user-images.githubusercontent.com/6883041/204081921-7dda4588-9b52-45a2-8661-62507dd60ce6.png">

Non Working Action:
<img width="963" alt="Sin Funcionar" src="https://user-images.githubusercontent.com/6883041/204081932-b82ec699-cc0c-415e-97ca-412204dc9e30.png">

Error with Ubuntu 22:
<img width="1038" alt="ERROR" src="https://user-images.githubusercontent.com/6883041/204081936-4fbbf84f-efe5-4b16-8c2f-918ef8020bca.png">

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221119.2

### Is it regression?

20221027.1

### Expected behavior

I expect that the GitHub Action should not fail or at least find a "migration guide" to adapt my code to the latest image of Ubuntu.

### Actual behavior

The GitHub Action fail. 

### Repro steps

Execute the GitHub Action. 

This is my code (just relevant parts)

```yml
name: Create a backup of the database

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4 2-27/6 * *'
    - cron: '17 6 1 * *'

jobs:
  getBackup:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run get_backup
```

```js

	const timeout = 2 * 60 * 1000; // Two minutes
	const date = getDate();

	const backupChildProcess = spawn('mongodump', [
		`--uri=${databaseURI}`,
		`--archive=./backups/${date}.gz`,
		'--gzip'], { timeout: timeout });

	backupChildProcess.on('exit', (code, signal) => {
		if (code || signal) {
			logger.error(`child process exited with code ${code} and signal ${signal}`);
			core.setFailed(`child process exited with code ${code} and signal ${signal}`);
			return;
		}

		logger.info('The database has been successfully backed up');
		core.notice(`The database has been successfully backed up. Created file: ./backups/${date}.gz`);
	});

	backupChildProcess.on('error', (err) => {
		logger.error('The child process does not spawn successfully', err);
		core.setFailed('The child process does not spawn successfully');
	});

```
