### ISSUE TITLE
Xcode 14.1 keeps failing to build without any information about what failed

### ISSUE THREAD

**Issue by jacobbullock** [actions/runner-images#6642]
### Description

I tried to update our pipelines to use Xcode 14. The build logs show:

```
/usr/bin/xcodebuild -version
Xcode 14.1
Build version 14B47b
```

That is also the same version I have locally and it is building fine locally. 

The build fails, but there is no info about what failed:

```
** BUILD FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```

with `system.debug` turned on it's not much more helpful:

```
...
##[debug]success of first tool:false
##[debug]rc:0
##[debug]success:true
##[debug]task result: Failed
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
##[debug]Processed: ##vso[task.issue type=error;]Error: /usr/bin/xcodebuild failed with return code: 65
##[debug]Processed: ##vso[task.complete result=Failed;]Error: /usr/bin/xcodebuild failed with return code: 65
##[debug]Agent.Version=2.213.2
...
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20221121.1

### Is it regression?

No, Xcode 13 runs fine on that same version, but we haven't tried Xcode 14 on a previous version

### Expected behavior

I'd expect that Xcode 14.1 will build the project and the pipeline will complete successfully

### Actual behavior

The build is failing without any information

### Repro steps

We are pushing builds through bitbucket and using web hooks to trigger the pipeline. 

Specifying `xcodeVersion: '14'` fails
Specifying `xcodeVersion: '13'` succeeds

**Comment by mikhailkoliada** [comment]
Hi! Please provide repro steps

**Comment by jacobbullock** [comment]
What are you looking for? I mentioned in the ticket that it's a pipeline kicked off from Bitbucket. I can't share the whole pipeline file, but do you need more of it?

**Comment by flowridr** [comment]
Same problem here with xcode 14.1 (13 was working fine).

`/usr/bin/xcodebuild -sdk iphoneos -configuration Release -workspace /Users/runner/work/1/s/***.xcodeproj/project.xcworkspace -scheme *** archive -destination generic/platform=iOS -verbose CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=*** PROVISIONING_PROFILE=*** PROVISIONING_PROFILE_SPECIFIER=*** | /usr/local/lib/ruby/gems/3.0.0/bin/xcpretty -r junit --no-color`

Results in:
##[error]Error: /usr/bin/xcodebuild failed with return code: 65

**Comment by usmaanirfan** [comment]
Is someone looking into it?

**Comment by shatodj** [comment]
It looks like an issue with Fastlane. No solution so far.

https://github.com/fastlane/fastlane/issues/20825

**Comment by MichaelAmadheo** [comment]
This is also happening to me, something is wrong with xcode 14 on azure. Currently, i specify the xcode version to 13 by using xcodeVersion: '13' and it still building fine.

**Comment by florentm35** [comment]
We have the same problem on our project, but with one configuration it's work but with other it does :
- The working configuration has setup at 24/11/2022 with a MacOs 11 
- The other configuration has setup at 06/01/2023 with MacOs 12 and failed

**Comment by dsame** [comment]
@florentm35 can you please double check:

 1. both builds use either "Development" or "Distribution" certificate/provision pair
 1. none of build use "iOS App Development"/"iOS Distribution" certificate instead of "Apple Development"/"Apple Distribution"

**Comment by dsame** [comment]
Thanks to @dymv there's a promising [repro](https://github.com/akv-demo/SPMBundleSign/actions/runs/3998977376) that works with XCode 13 and fails with XCode 14

It demonstrates the `xcodebuild` depends on correct combination of 3 options:

  - CODE_SIGN_IDENTITY="Apple Distribution"
  - DEVELOPMENT_TEAM="_appleId_"
  - CODE_SIGN_STYLE="Manual"
  
If none provider **both builds sucessed**
if `CODE_SIGN_IDENTITY="Apple Distribution"` or `CODE_SIGN_IDENTITY="Apple Distribution" DEVELOPMENT_TEAM="_appleId_"` are provided **xcode 14 fails**
if all three `CODE_SIGN_IDENTITY="Apple Distribution"`, `DEVELOPMENT_TEAM="_appleId_"` and `CODE_SIGN_STYLE="Manual" are provided **both builds sucessed**

But this repro does not issue the "65 code" error. I suspect it is because the build does not use fastlane which may add some extra options to change the output somehow.

**Comment by tulio-mcsantos** [comment]
If anyone was having problems with this running this way worked for me:

```
- task: Xcode@5
    displayName: 'Build IPA'
    inputs:
      actions: 'clean'
      configuration: 'Release'
      exportOptionsPlist: '$(IOS_FOLDER)/nativeApp/Info.plist'
      sdk: 'iphoneos'
      xcWorkspacePath: '$(IOS_FOLDER)/nativeApp.xcworkspace'
      scheme: 'nativeApp'
      packageApp: true
      exportPath: 'output'
      signingOption: 'manual'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
      args: 'ENABLE_BITCODE=NO'
```

Important to note here is that if I specify `xcodeVersion: '14'` the build will run on 14.2, at this date, and fail. But if I do not pass the xcodeVersion, it runs on 14.2 and pass.

**Comment by jacobbullock** [comment]
@darecki our problem was spm related as well. It was trying to sign local packages and failing. The trick there is to change the Xcode part of the pipeline to archive first and then export and sign with entitlements.

**Comment by dsame** [comment]
The issue is closed because it is not related to the runner images repo. The root cause is the incompatibility between XCode 13/14 and there's no common solution for the different build scenarios. 

The comment https://github.com/actions/runner-images/issues/6642#issuecomment-1402377143 points out the way to start solving the problem in specific case.

**Comment by shatodj** [comment]
For those who are still lost, this is what helped me:

- first: disable useXPretty so you can see the actual error
- if there is a problem with signing the app (or signing your SPM packages/pods) disable manual or automatic signing and use the project default
- Sign app using `exportOptionsPlist`

Here is my Azure pipeline task which now works

```yaml
          - task: Xcode@5
            displayName: Build application
            inputs:
              actions: 'build'
              configuration: '$(buildConfiguration)'
              sdk: '$(sdk)'
              xcWorkspacePath: 'APP.xcworkspace'
              scheme: '$(scheme)'
              xcodeVersion: 'specifyPath'
              xcodeDeveloperDir: '/Applications/Xcode_14.2.app/Contents/Developer'
              packageApp: true
              destinationTypeOption: devices
              args: '-verbose"'
              signingOption: 'default'
              useXcpretty: true # or `false` if you want to see hidden errors
              exportOptions: 'plist'
              exportOptionsPlist: 'PATH/TO/YOUR/exportOptions.plist'
```

and this is a sample of my `exportOptions.plist`

```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.app.app</key>
		<string>The Name of my Distribution Certificate from Xcode project</string>
	</dict>
	<key>signingStyle</key>
	<string>manual</string>
	<key>teamId</key>
	<string>XXXXXX</string>
	<key>method</key>
	<string>enterprise</string>
</dict>
</plist>
