### ISSUE TITLE
MacOS 12 runners do not include iOS 16.1 simulator

### ISSUE THREAD

**Issue by macintosh-HD** [actions/runner-images#6660]
### Description

I was wondering why our builds where failing constantly.
On investigation I found out that `xcodebuild` was complaining that no `iphonesimulator16.1` sdk was present:
```
xcodebuild: error: SDK "iphonesimulator16.1" cannot be located.
Error: Xcodebuild action failed (64)!
```

In the description of the macOS 12 runner image the simulator is listed as included

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20221121.1

### Is it regression?

no

### Expected behavior

`xcodebuild` should not fail at this stage and the simulator should be present.

### Actual behavior

`xcodebuild` fails and running `xcodebuild -showsdks` does not list the iOS 16.1 simulator.

### Repro steps

Run this workflow:
```yaml
name: List SDKs
on:
  push:

jobs:
  list:
    runs-on: macos-12
    steps:
      - name: List SDKs
        run: |
          xcodebuild -showsdks
```
