### ISSUE TITLE
GitHub Actions on Windows doesn't stop on error

### ISSUE THREAD

**Issue by justanotheranonymoususer** [actions/runner-images#6668]
### Description

Here's a pipeline which demonstrates the bug, it should fail but it keeps on running, leading to unexpected consequences in the rest of the pipeline:

```
  build-windows-failure-bug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        run: |
          curl https://does-not-exist.this-will-fail/
          curl https://example.com/
```
Here's a more complete example:
https://github.com/justanotheranonymoususer/actions-test/blob/5c0935375762cfbcc8f6231aae60c50a6c2b284b/.github/workflows/blank.yml

Execution result:
https://github.com/justanotheranonymoususer/actions-test/actions/runs/3569092631

You can see that on ubuntu-latest, it fails properly, but in windows-latest, it doesn't fail even though it should.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-latest

### Is it regression?

Not/don't know

### Expected behavior

Windows pipeline fails on first error

### Actual behavior

Windows pipeline keeps running

### Repro steps

See pipeline in the description

**Comment by ddobranic** [comment]
hello @justanotheranonymoususer, thank you! we will investigate.

**Comment by ddobranic** [comment]
@justanotheranonymoususer you could slightly modify you workflow and get the same results for Ubuntu and Windows.
Here is an example:
```
build-windows-failure-bug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fail test
        run: |
          curl https://dfgjndrgierngiergnregerg
          curl https://example.com/
        shell: bash
```

**Comment by ddobranic** [comment]
@justanotheranonymoususer, i am going to close the issue. if you have any questions or concerns, please feel free to reopen.

**Comment by justanotheranonymoususer** [comment]
You showed a workaround, but the default behavior is still undesired, is
it?

**Comment by justanotheranonymoususer** [comment]
I did a couple of other checks. I tried these shells: bash, sh, powershell, pwsh, cmd.
* These continue even if there's an error: pwsh, cmd
* These abort as expected: bash, sh, powershell

Here's what [the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell) say:

## `cmd`

> There doesn't seem to be a way to fully opt into fail-fast behavior other than writing your script to check each error code and respond accordingly. Because we can't actually provide that behavior by default, you need to write this behavior into your script.

## `pwsh` (default on Windows)

> Fail-fast behavior when possible. For `pwsh` and `powershell` built-in shell, we will prepend `$ErrorActionPreference = 'stop'` to script contents.

For `cmd`, it's known and documented that it continues after a failure. But for `pwsh`, it should abort after the first error, which seems like a bug as it actually continues execution.

I'm not sure what "when possible" means in the PowerShell documentation. I think it should be fixed, and, if not possible, documented properly.

**Comment by Gustl22** [comment]
@ddobranic how I can achieve the same behavior (to abort) with `powershell` or `pwsh`  as I need some of their commands?

**Comment by coffeebe4code** [comment]
Same issue. Windows passes but linux fails.
```
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          cargo test
          ./target/release/e2e

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo build --release
          cargo test
          ./target/release/e2e
```
