### ISSUE TITLE
NET SDK msbuild conflict in 20221127.1

### ISSUE THREAD

**Issue by rfdrake** [actions/runner-images#6678]
### Description

I tried building a project with dotnet 7.x.x and got an error that said msbuild was too old.  

```
##[error]The nuget command failed with exit code(1) and error(/home/vsts/work/1/s/api/myproject/myproject.csproj : error : Version 7.0.100 of the .NET SDK requires at least version 17.3.0 of MSBuild. The current available version of MSBuild is 16.10.1.31701. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.
```

I then specified 6.0.403 in global.json and it also required a newer version of MSbuild than what was installed.

```
##[error]The nuget command failed with exit code(1) and error(/home/vsts/work/1/s/api/myproject/myproject.csproj : error : Version 6.0.403 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.10.1.31701. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.
```

I'm not that familiar with the dotnet toolchain so I don't know if this is something that can be fixed with more options in our pipeline or other config files, or if it's an actual bug in the runner image.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221127.1

### Is it regression?

20221002.2

### Expected behavior

It should build with the installed version of msbuild.

### Actual behavior

I get an error saying dotnet SDK requires msbuild 17.x.x.

### Repro steps

Here is a copy of part of our azure-pipeline.yml with some details removed.   We have not yet tried to run this on an older ubuntu image, but that is going to be our next step to work around the problem.

```
trigger:
  - development
  - stage
  - production

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: '<a uuid>'
      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'api/projectdirectory'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/api'      
```
