### ISSUE TITLE
Regression in user variable handling when using MSBuild

### ISSUE THREAD

**Issue by projectgoav** [actions/runner-images#6687]
### Description

Have been directed here via: https://developercommunity.visualstudio.com/t/MSB6006:-java-exited-with-code-1/10180082

Problem stems from how variables are being handled in pipeline runners. The MSBuild variable `$(buildConfiguration)` is being resolved before MSBuild has had a chance to set it and therefore is always empty. This results in malformed paths and so fails our pipeline builds.

* `macos-11` - doesn't have the problem
* `macos-12` - has the problem
* `macos-latest` - has the problem

The last successful build was on Tuesday 18th October. Problem was first noticed Friday 21st October and reported Monday 24th October. After some back & forth, we were directed here. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`macos-12` - '20221127.5'

### Is it regression?

`macos-11` and `macos-12` before 13th October

### Expected behavior

The `$(buildConfiguration)` MSBuild variable should be set by MSBuild. This then allows you to use it in an output path.

### Actual behavior

`$(buildConfiguration)` has not been set by the time it is resolved resulting in an empty variable. When used in a path, this results in a malformed path and so fails any build using it.

### Repro steps

- Create a Xamarin.Android application
- YAML with the following step will fail
```
- task: XamarinAndroid@1
  inputs:
    projectFile: './<path_to>.csproj'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
    configuration: 'Debug'
    createAppPackage: false
```

(YAML with the following step will pass)
```
- task: XamarinAndroid@1
  inputs:
    projectFile: './<path_to>.csproj'
    outputDirectory: '$(build.binariesDirectory)/<something_else>'
    configuration: 'Debug'
    createAppPackage: false
```
