### ISSUE TITLE
apt install riscv64-* fails on both Ubuntus (and properly all others)

### ISSUE THREAD

**Issue by fwsGonzo** [actions/runner-images#6726]
### Description

There is a missing binutils archive on the Azure repo.

```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-riscv64-linux-gnu_2.38-4ubuntu2_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
```

Anything that requires the 64-bit RISC-V binutils fails with a 404. I checked the directory and it is indeed missing that particular .deb file, but there are other binutils deb files for 64-bit RISC-V binutils. So, maybe a typo?

I only checkmarked the platforms I have tested on, but I assume all are affected.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install -y gcc-10-riscv64-linux-gnu g++-10-riscv64-linux-gnu
```

### Is it regression?

Yes

### Expected behavior

The .deb file should be present, or perhaps named differently.

### Actual behavior

The file is missing, it's a 404.

### Repro steps

```
$ curl  -D - http://azure.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-riscv64-linux-gnu_2.38-4ubuntu2_amd64.deb
HTTP/1.1 404 Not Found
Date: Thu, 08 Dec 2022 16:32:53 GMT
Server: Apache/2.4.29 (Ubuntu)
Content-Length: 283
Content-Type: text/html; charset=iso-8859-1
X-Cache: MISS from 192.168.0.5
X-Cache-Lookup: MISS from 192.168.0.5:8000
Via: 1.1 192.168.0.5 (squid/5.2)

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at gb.archive.ubuntu.com Port 80</address>
</body></html>
```
