### ISSUE TITLE
Ubuntu-latest stopped running Node.Js script in Actions

### ISSUE THREAD

**Issue by theDavidBarton** [actions/runner-images#6738]
### Description

My Actions stopped working a few days ago (e.g.: [see "Run main script"](https://github.com/theDavidBarton/koronavirus.gov.hu-scraper/actions/runs/3666162585/jobs/6197707490) job) and I realized Actions using Ubuntu 22.04 and not 20.04. It is related to https://github.com/actions/runner-images/issues/6399. The main script just simply not executed. There is no error msg.

Reverting back to Ubuntu-20.04 solved the issue: https://github.com/theDavidBarton/koronavirus.gov.hu-scraper/actions/runs/3666215143/jobs/6197790588

_Note:_ it won't fail the job, it will only silently skips script execution.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221204.2 https://github.com/theDavidBarton/koronavirus.gov.hu-scraper/actions/runs/3666162585/jobs/6197707490

### Is it regression?

20221204.2 https://github.com/theDavidBarton/koronavirus.gov.hu-scraper/actions/runs/3666215143/jobs/6197790588

### Expected behavior

It should run the Node.Js script with 22.04 as before with 20.04.

### Actual behavior

The Node.Js script is not executed.

### Repro steps

1. Run `scrape` job here https://github.com/theDavidBarton/koronavirus.gov.hu-scraper/actions/workflows/scrape.yml with an ubuntu-latest
2. It won't run the Node.Js script but goes to the next job immediately

**Comment by igorboskovic3** [comment]
This probably is related to https://github.com/actions/runner-images/issues/6698

**Comment by theDavidBarton** [comment]
@igorboskovic3 

## minimal repro steps

**prequisities:** 

`package.json`
```json
{
  "dependencies": {
    "puppeteer": "^5.3.0"
  },
  "engines": {
    "node": "16.x"
  }
}
```
`index.js`
```js
const puppeteer = require('puppeteer')

const runScrape = async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto('https://koronavirus.gov.hu')
  console.log('the Node.Js script is launched successfully)
  await browser.close()
}
runScrape()
```
`.github/workflows/scrape.yml`
```yml
name: scrape

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  scrape-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install project
        run: yarn
      - name: Run main script
        run: node index.js
```

available here as well. I removed everything irrelevant from the point of view of the Ubuntu issue: https://github.com/Crocodiles-in-the-Basement/koronavirus.gov.hu-scraper

**steps:**
1. trigger a workflow dispatch in Actions (https://github.com/Crocodiles-in-the-Basement/koronavirus.gov.hu-scraper/actions/workflows/scrape.yml)
2. it will not run the Node.Js script with Ubuntu-latest (https://github.com/Crocodiles-in-the-Basement/koronavirus.gov.hu-scraper/actions/runs/3679654093/jobs/6224349730#step:5:2)
