### ISSUE TITLE
In Windows-2022, A app compiled by MinGW `g++` fails.

### ISSUE THREAD

**Issue by kzrnm** [actions/runner-images#6755]
### Description

Related: #5459 #6627 

I ran the simple workflow below. the step that run `hello` fails in cmd.

```yml
on:
  workflow_dispatch:

jobs:
  fix:
    runs-on: windows-latest
    steps:
        shell: pwsh
        run: |
          '
          #include <cstdio>
          #include <vector>
          using namespace std;
          int main(int, char* argv[]) {
              vector<int> a(4);
              printf("%d\n", a.size());
              return 0;
          }
          ' > hello.cpp
      - name: Compile
        run: g++ -o hello hello.cpp
      - run: hello
        shell: cmd
        name: Run hello on cmd
        id: hello
```

---

It seems `C:/Program Files/Git/mingw64/bin/lib*.dll` hidden by `C:\Strawberry\c\bin\lib*.dll`.

Adding `C:/Program Files/Git/mingw64/bin/` to beginning of `$PATH`, it works fine.

```yml
      - name: Fix
        shell: bash
        run: |
          mkdir bin
          cp C:/Program\ Files/Git/mingw64/bin/lib*.dll bin/
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
```

---

I create a action which add mingw to beginning of $PATH.
https://github.com/kzrnm/fix-mingw

But I hope any solution that works by default because this behavior is not obvious.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20221204.3 or older

### Is it regression?

no

### Expected behavior

a executable file `hello` exit 0.

### Actual behavior

a executable file `hello` exit -1073741511.

### Repro steps

I wrote in the description section.
