### ISSUE TITLE
fatal: detected dubious ownership in repository at

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner-images#6775]
### Description

I started seeing this error today

![image](https://user-images.githubusercontent.com/55927613/207656546-77bf93b1-013d-4bfe-80b2-b0be3d5cd880.png)

It makes no sense, as the actions/checkout added the repo to the safe safe dir list

![image](https://user-images.githubusercontent.com/55927613/207656662-e22b83ee-b9e1-4946-8708-957f983d1701.png)

What could the issue be in this case?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![image](https://user-images.githubusercontent.com/55927613/207821691-ee9683cc-bf8e-4bc1-af44-40c0e54de57b.png)

### Is it regression?

yes. Version: 20221125.1 https://github.com/VodafoneIS/sf-metadata/actions/runs/3601296318/jobs/6066928420

### Expected behavior

Since `actions/checkout@v3` already run `/usr/bin/git config --global --add safe.directory /__w/sf-metadata/sf-metadata`  I was not expecting to have issues with safe directories.

### Actual behavior

![image](https://user-images.githubusercontent.com/55927613/207823271-aeeae1cf-bedc-4a66-b708-24d2c3fa46a8.png)

![image](https://user-images.githubusercontent.com/55927613/207823353-e0756061-8ace-4900-8d08-8a15e7405949.png)

### Repro steps

1. Create a docker container that runs on linux.
2. Add a shell script in it that uses a `git` command to do something, like creating a git commit or fetch all tags
3. Run this shell script in a Job. This job must use `ubuntu-lates`, run in the container you created in step 1, and execute the shell script from step 2.

````yml
...

jobs:

  upload-lwc-converage:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/salesforce-build-image:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  steps:
      - name: Checkout
        uses: actions/checkout@v3
        
       - name: run my sh script located in the docker container
         run:  /scripts/do_something_with_git.sh
````

**Comment by igorboskovic3** [comment]
Hi @AllanOricil we will take a look, thanks.

**Comment by AllanOricil** [comment]
@igorboskovic3 I've set all my workflows to run on `ubuntu-20.04` but the same issue happened, maybe because it is using Version: 20221212.2. The last job that ran without a problem was using `ubuntu-20.04 20221125.1`. So, how can I also set the build version?

**Comment by igorboskovic3** [comment]
Hi @AllanOricil, unfortunately you cannot set an old build version, just current one.

**Comment by AllanOricil** [comment]
@igorboskovic3 
I dont understand why we started seeing this issue. This safe dir feature was introduced to git in v2.35.2 https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
but the checkout action shows that we are using git v2.2.1
![image](https://user-images.githubusercontent.com/55927613/207856204-620931ad-6624-4304-9ae4-968589ac4efd.png)

**Comment by Alexey-Ayupov** [comment]
Hello @AllanOricil, we have noticed that the "checkoutv3" action uses a git version that is already installed no matter in the container or in the runner. Below you can find our simple workflow, which went successfully.
```
jobs:
  run_from_container:
    name: test1
    runs-on: ubuntu-latest
    container:
      image: alpine/git

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: git clone
        run: | 
          git clone --depth=1 https://github.com/actions/runner-images
          ls -la runner-images
          
  run_from_runner:
    name: test2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check the data
        run: ls $GITHUB_WORKSPACE
```
From this small experiment, you can see that container and runner have different versions. of git. Please pay close attention to your rights in the container and the git version installed in your container as well.
  
It seems like the issue does not directly relate to a runner, so we will close the issue for now. Feel free to reach us if you have any questions.

**Comment by AllanOricil** [comment]
@Alexey-Ayupov @igorboskovic3 I did not change anything in any of my workflows since yesterday and this issue started. There is something wrong somewhere and I cant figure out what is it...

**Comment by AllanOricil** [comment]
@Alexey-Ayupov @igorboskovic3 could this action be the reason? 
https://github.com/fregante/setup-git-user/blob/master/index.js

I run it after running git checkout. I need it, because inside my workflow I create commits and tags.
This action was in my workflow already, and It should not be causing the issue.

**Comment by AllanOricil** [comment]
I ran this workflow, and again I had the same problem

![image](https://user-images.githubusercontent.com/55927613/207903832-2055038a-6a29-4ab7-a785-0ff8413785c6.png)

````yml
...
jobs:
  validate-changes:
    name: Validate Metadata Changes
    strategy:
      matrix:
        environment: ${{ fromJSON(inputs.VALIDATION_ENVIRONMENTS) }}
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/vodafoneis/salesforce-build-image:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      SF_REPORT_APEX_CODE_COVERAGE: ${{ secrets.SF_REPORT_APEX_CODE_COVERAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Print Git Version
        run: |
          git --version
          touch a.txt
          git add .
          git commit -m "test"

````

**Comment by AllanOricil** [comment]
@igorboskovic3 @Alexey-Ayupov tell me it is not a bug somewhere... 
Look, I added a step ` Add safe.directory /__w/sf-metadata/sf-metadata` and later on the my other git commands fail? Something weird is happening. I insist you reopen this ticket and investigate more. This was not happening, my workflows were working without a problem few days ago without this extra step to set the safe.directory.

![image](https://user-images.githubusercontent.com/55927613/207915717-615a2c87-08ee-4579-8fbd-e167be6479e8.png)

**Comment by AllanOricil** [comment]
It is something on my image. I dont know what is it yet, but I just used an image from 7 days ago, and it is working again. will check all my dependencies and then I come back here to tell you what I found.

**Comment by Alexey-Ayupov** [comment]
Hi @AllanOricil . Thank you for not giving up on searching for root cause. It would be great if you provide your findings.

**Comment by AllanOricil** [comment]
These are the only diffs between my images. 

IMAGE 1 => is the one which I have no issues
IMAGE 2 => image where the problem started

![image](https://user-images.githubusercontent.com/55927613/208150486-5df49975-585d-4034-b3e3-d129743e4a12.png)

So, since there aren't any other changes, I have no clue what is causing the problem. Would you like to have access to both images? That may help you to find the real issue.

**Comment by AllanOricil** [comment]
@benzsuankularb @Alexey-Ayupov @igorboskovic3 
No idea. I just used an older docker image and my problem was gone. Im not sure exactly what is wrong here because there are people reporting the same error and they are not even using docker images. Im just luck, I guess? 

In the image below, every commit represents a new container image build. I used the image from `b937316` and my issue was gone.  My workflows were using `@main` before and the problem started.

![image](https://user-images.githubusercontent.com/55927613/208387732-6f29d6ec-752f-4c8b-ba07-1c9a7bbc2433.png)

Why did I choose that one? I just picked up the image from the week where all my workflows were not facing that issue.

I just don't know why changing the image fixed my problem, as the only changes between both images are these

![image](https://user-images.githubusercontent.com/55927613/208388906-399207f5-bb0e-403f-ab35-1c571469e6c9.png)

**Comment by AllanOricil** [comment]
https://github.com/actions/checkout/issues/1048#issuecomment-1356485556

**Comment by Waed93** [comment]
I am having the same issue and haven't done any changes. I can see that this issue has been closed with no solution

**Comment by Waed93** [comment]
this is fixed by using
sudo git config --global --add safe.directory /is/htdocs/wp1090589_IC9AIO06VX/your_project_name
it will ask you for the sudo password and there you go :)

**Comment by AllanOricil** [comment]
> this is fixed by using sudo git config --global --add safe.directory /is/htdocs/wp1090589_IC9AIO06VX/your_project_name it will ask you for the sudo password and there you go :)

this isn't a fix for all scenarios

**Comment by AllanOricil** [comment]
@igorboskovic3  @Alexey-Ayupov  could you please reopen this and investigate more.  Another random guy reported this in Reddit.
https://www.reddit.com/r/github/comments/znfag2/new_dubious_ownership_error_in_github_workflow/

**Comment by AllanOricil** [comment]
@igorboskovic3 @Alexey-Ayupov I believe the issue comes from this debian updgrade

![image](https://user-images.githubusercontent.com/55927613/208716606-623759da-149a-49ba-91a8-28510aa72dbe.png)

![image](https://user-images.githubusercontent.com/55927613/208716669-c3c9c6d7-00d6-4fc7-848e-5f2befbd0a8d.png)

Do you have any ideas how I can set this in the dockerfile?

**Comment by AllanOricil** [comment]
This post also thinks this debian upgrade is the cause of the problem
https://phabricator.wikimedia.org/T325128

**Comment by AllanOricil** [comment]
@Alexey-Ayupov @igorboskovic3 I HAVE FINALLY SORTED THIS ISSUE. I built my images without upgrading git to `deb10u6`. For those out there that are not using container images, you are probably facing the same issue because the runners has probably upgraded this git package. So, you can solve this by creating your own container image which does not have this security upgrade that was released to git. In your image, make sure to not upgrade the package. You can do it in my ways,


I did it like this
```dockerfile
RUN apt-mark hold git
RUN apt-mark hold git-man
```

**Comment by Nicoowr** [comment]
Thanks @AllanOricil !
Another temporary fix is to add the suggested command in the CI/CD pipeline:
`git config --global --add safe.directory /__w/{repo_name}/{repo_name}`

**Comment by AllanOricil** [comment]
> Thanks @AllanOricil !
> Another temporary fix is to add the suggested command in the CI/CD pipeline:
> `git config --global --add safe.directory /__w/{repo_name}/{repo_name}`

@Nicoowr this does not work when using containers. I tried it already

**Comment by michaelpeterswa** [comment]
As with @Nicoowr, we encountered this for the first time today on the self-hosted 2.299.1 version of the GitHub Actions Runner. In our case, we were using a `python:3.8-buster` Docker Container inside the action. We observed that the issue disappeared after switching to a `python:3.8-bullseye` container which presumably has an updated version of Git. As suggested by @AllanOricil above, try to find a newer container image, currently that seems to be resolving the issue!

**Comment by ssbarnea** [comment]
To be honest this should not have being closed because it is 100% related to runners. I see no reason why the permissions should be messed on a runner, it is just bad runner configuration or bad volument mounting for action images.

Yep, it is a side effect of getting a newer git, one that is more sensitive to bad permissions, one that uncovers an issue that was ignored for a very long time.

**Comment by FedericoCeratto** [comment]
@ssbarnea setting the permissions correctly should be a better solution. A workaround is to do so manually in the CI when running as root:
```
     steps:
      - name: Change Owner of Container Working Directory
        run: chown root:root .

```

**Comment by AllanOricil** [comment]
> @ssbarnea setting the permissions correctly should be a better solution. A workaround is to do so manually in the CI when running as root:
> ```
>      steps:
>       - name: Change Owner of Container Working Directory
>         run: chown root:root .
> 
> ``` 

Thanks. I did not thought about it. Does it really work? The downside of this approach is that we must add this step on every workflow in multiple repositories.

**Comment by yaqwsx** [comment]
I also think this issue shouldn't be closed as, clearly, the permissions are set wrongly. The failing git is only a symptom.

**Comment by refah7991** [comment]
i have similar error to yours , but i can't solve? may you helpp me.
![Screenshot (23)](https://user-images.githubusercontent.com/75289954/212872132-d6fea526-70d3-4f84-91ae-382d63d9362d.png)

**Comment by hungry1526** [comment]
I hit this issue too, not sure what is the right way to fix this. My workflow is failing at line 35 at https://github.com/hungry1526/arc-cicd-demo-src/blob/master/.github/workflows/az-vote-cicd.yml . Anyone has clue? 

![image](https://user-images.githubusercontent.com/1637753/213406367-857e9c9b-812e-4adb-9dee-2e2f14179d4d.png)

**Comment by AllanOricil** [comment]
Problem started again, even holding git packages upgrades.

**Comment by AllanOricil** [comment]
> - name: Change Owner of Container Working Directory
>         run: chown root:root .

This works if you are running jobs using containers.

**Comment by cedricve** [comment]
Started having this issue as well.. out-of-the-blue..

**Comment by joelnotified** [comment]
👍 Running into this issue now as well

**Comment by cedricve** [comment]
@joelnotified  if you are installing additional packages in your build one of them might be causing this. What I noticed is that previous "succesful" builds no longer work anymore as well.

**Comment by danharrin** [comment]
Me too.

Correct output of my action from yesterday - https://github.com/filamentphp/filament/actions/runs/4036577703/jobs/6939267792

The same action today - https://github.com/filamentphp/filament/actions/runs/4043321725/jobs/6952104956

**Comment by andrew-belac** [comment]
Same error for us

**Comment by danharrin** [comment]
@Alexey-Ayupov could you reopen this issue please?

**Comment by imhemish** [comment]
Same issue today after I force pushed my repository, the github pages build failed giving out this error.

**Comment by jmmclean** [comment]
added this line after my checkout step, which resolved it...but i too started getting this weird error

```
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
 ```
