### ISSUE TITLE
Ubuntu latest: Ansible failed to run task with json_query filter

### ISSUE THREAD

**Issue by Hellseher** [actions/runner-images#6797]
### Description

Ubuntu latest runner has missing ansible required modules.

Fixed by purging ansible installed by pipX and installing it globally by apt-get
``` yaml
- name: "purge pipx ansible"
  run: |
    sudo pipx uninstall-all --verbose
- name: "install ansible"
  run: |
    sudo apt-get update
    sudo apt-get install --yes ansible python3-boto3
    ansible-galaxy collection install amazon.aws:4.3.0
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

``` 
 Error was a <class 'ansible.errors.AnsibleError'>, original message: You need to install "jmespath" prior to running json_query filter
```

Run any provisioning which requires `jmespath`

### Is it regression?

ubutnu-latest

### Expected behavior

Provided ansible on the image should works with all expected required dependencies.

### Actual behavior

```Error was a <class 'ansible.errors.AnsibleError'>, original message: You need to install \"jmespath\" prior to running json_query filter"```

### Repro steps

```
{{ ansible_mounts|json_query('[].size_total')|max }}
```
