### ISSUE TITLE
Encoding change in latest windows-2022 image

### ISSUE THREAD

**Issue by Vampire** [actions/runner-images#6800]
### Description

By build started to fail suddenly yesterday.
The jobs using `windows-latest` use the image `20221204.3` and still are successful.
But the jobs using `windows-2022` use the image `20221215.2` and fail.

As you can see at https://github.com/Vampire/setup-wsl/actions/runs/3717585200/jobs/6305120322 it seems the output of the command `wslconfig.exe /list` is suddenly no longer `UTF-16LE` encoded.

Is that an intended and expected change, or is that a bug? I cannot find anything in the readme about it.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image Version: 20221215.2
Build link: https://github.com/Vampire/setup-wsl/actions/runs/3717585200/jobs/6305117574

### Is it regression?

Yes, 20221204.3, https://github.com/Vampire/setup-wsl/actions/runs/3717585200/jobs/6305117620

### Expected behavior

No undocumented change in behavior

### Actual behavior

Changed behavior

### Repro steps

Run `wslconfig.exe /list | iconv -f UTF-16LE -t UTF-8`

**Comment by igorboskovic3** [comment]
Hi @Vampire , we will check this and get back to you.

**Comment by igorboskovic3** [comment]
Hi @Vampire can you provide minimal repro steps, thanks

**Comment by Vampire** [comment]
As `windows-latest` is now on the new image version too, here a full reproducer using `windows-2019` and `windows-2022`:
https://github.com/Vampire/setup-wsl/actions/runs/3731724357
```yaml
name: Foo

on: push

jobs:
    foo:
        name: Windows 2022
        runs-on: windows-2022
        steps:
            - uses: Vampire/setup-wsl@v1
            - shell: wsl-bash {0}
              run: wslconfig.exe /list | iconv -f UTF-16LE -t UTF-8

    bar:
        name: Windows 2019
        runs-on: windows-2019
        steps:
            - uses: Vampire/setup-wsl@v1
            - shell: wsl-bash {0}
              run: wslconfig.exe /list | iconv -f UTF-16LE -t UTF-8
```

**Comment by igorboskovic3** [comment]
Hi @Vampire thank you for your steps and findings. As addition i would like to share that `wslconfig.exe` is [deprecated ](https://learn.microsoft.com/en-us/windows/wsl/basic-commands#deprecated-wsl-commands) and you should use `wsl.exe`. We tested it and for `windows-22` wsl.exe worked and for `windows-19` wslconfig.exe worked. I will close this now, if you have any additional questions feel free to reach us.
![image](https://user-images.githubusercontent.com/68074361/208453155-38e74ac4-56ef-4737-ac21-3efe72aafe5f.png)
![image](https://user-images.githubusercontent.com/68074361/208453231-193eaea9-9cb1-488b-b6c5-47756c1f5410.png)
```
jobs:
    foo:
        name: Windows 2022
        runs-on: windows-2022
        steps:
            - uses: Vampire/setup-wsl@v1
            - shell: wsl-bash {0}
              run: wsl.exe --list | iconv -f UTF-16LE -t UTF-8

    bar:
        name: Windows 2019
        runs-on: windows-2019
        steps:
            - uses: Vampire/setup-wsl@v1
            - shell: wsl-bash {0}
              run: wslconfig.exe /list | iconv -f UTF-16LE -t UTF-8

```
