### ISSUE TITLE
Post-InstallAppleCertificate return Error 162

### ISSUE THREAD

**Issue by florentm35** [actions/runner-images#6927]
### Description

We have some breavior with InstallAppleCertificate@2 :

```yaml
  - task: InstallAppleCertificate@2
    displayName: "Install Apple p12 cert"
    inputs:
      certSecureFile: "$(ios.p12.name)"
      certPwd: $(ios.p12.password)
      keychain: "temp"
      deleteCert: true
```

During the post execution we have an exit code 162

```
Starting: Install Apple p12 cert
==============================================================================
Task         : Install Apple certificate
Description  : Install an Apple certificate required to build on a macOS agent machine
Version      : 2.214.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-apple-certificate
==============================================================================
/usr/bin/security delete-certificate -Z B8E15147EFA0804390D038EF28D277CA3F84018D /Users/runner/work/_temp/ios_signing_temp.keychain
/usr/bin/security delete-keychain /Users/runner/work/_temp/ios_signing_temp.keychain
security: SecKeychainItemDelete: UNIX[No such file or directory]
##[error]Unhandled: The process '/usr/bin/security' failed with exit code 162
Finishing: Install Apple p12 cert
```

The probleme is non blocking because the pre install and install work fine, but it's ugly for the historique of this pipeline

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '2.214.1'
Operating System
 -  macOS
 -  12.6.2
 -  21G320
 
Runner Image
 -  Image: macos-12
 -  Version: 20221215.1

### Is it regression?

No

### Expected behavior

![image](https://user-images.githubusercontent.com/31475579/212909752-1900e74b-8c2e-4bed-bdfa-f5042a469e6d.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/31475579/212909874-cf779213-1e4e-4dcd-ad43-d7258b02fad9.png)

### Repro steps

Simple use :
```yaml
  - task: InstallAppleCertificate@2
    displayName: "Install Apple p12 cert"
    inputs:
      certSecureFile: "$(ios.p12.name)"
      certPwd: $(ios.p12.password)
      keychain: "temp"
      deleteCert: true
```
