### ISSUE TITLE
Configuration Differences between Standard and Larger Runners

### ISSUE THREAD

**Issue by swyphcosmo** [actions/runner-images#6930]
### Description

I've recently migrated some workflows from the standard runner to a larger runner. The same docker container is used on the larger runner, and the [webfactory/ssh-agent](https://github.com/webfactory/ssh-agent) action sets up Github deploy keys for our projects. The container is configured as a non-root user.

On the larger runner, we're seeing an `EACCES: permission denied` error when the ssh-agent action tries to copy keys. I've been able to get the workflow to pass on the larger runner by adding `options: --user root` to the container config, but we'd like to continue using a non-root user.

The only difference I can find in the two action reports is that the larger runners are using an older runner image (`20221204.2`) compared to the standard runner (`20230109.1`). Maybe there are other runner specific settings that we don't have visibility into.  

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Standard Runner at version: 20230109.1
Larger Runner at Version: 20221204.2

### Is it regression?

Version 20230109.1 works on standard runners, but 20221204.2 does not work on larger runners

### Expected behavior

Build will succeed on both standard and larger runners.

### Actual behavior

Standard runners work as expected. Larger runners fail with permissions issues trying to add files to the users home directory.

### Repro steps

The repo and workflows are in private repos, but I would expect that a job with the following steps can reproduce the issue:

```
jobs:
  permissions_test:
    runs-on: ubuntu-20.04
    container:
      image: <some docker image based on ubuntu:20.04>
    steps:
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SOME_REPO_DEPLOY_KEY }}
```
