### ISSUE TITLE
az acr login fails with GH Actions Ubuntu 20.04 & 22.04 version 20230122.1

### ISSUE THREAD

**Issue by adamcroissant-arrive** [actions/runner-images#6970]
### Description

Github actions workflows are failing to log in to ACR on the latest versions of `ubuntu-22.04` and `ubuntu-20.04` runners. `az acr login` fails with an unexpected error that cannot be reproduced on earlier versions of the same runners.

This prevents us from publishing docker images using our existing workflows & secrets.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu 20.04 version 20230122.1
Ubuntu 22.04 version 20230122.1

Build examples are private

### Is it regression?

yes - last worked on version 20230118.1

### Expected behavior

Successfully logs into ACR using `azure/CLI@v1` and retrieves token that works with `docker/login-action@v2.1.0`

Previously working output of `azure/CLI@v1`:
```
Run azure/CLI@v1
Starting script execution via docker image mcr.microsoft.com/azure-cli:2.44.1
WARNING: The login server endpoint suffix '.azurecr.io' is automatically omitted.
WARNING: You can perform manual login using the provided access token below, for example: 'docker login loginServer -u 00000000-0000-0000-0000-000000000000 -p accessToken'
az script ran successfully.
cleaning up container...
MICROSOFT_AZURE_CLI_[16](https://github.com/Arrive-Logistics/bulk-pricing-service/actions/runs/3990361393/jobs/6843900935#step:4:17)74506437307_CONTAINER
```

Previously working output of `docker/login-action@v2.1.0`:
```
Run docker/login-action@v2.1.0
Logging into ***...
Login Succeeded!
```

### Actual behavior

Fails to log in to ACR via action `azure/CLI@v1` with error message:
```
WARNING: Unable to get AAD authorization tokens with message: 2023-01-23 21:02:22.575569 An error occurred: CONNECTIVITY_REFRESH_TOKEN_ERROR
Access to registry '***' was denied. Response code: 429. Please try running 'az login' again to refresh permissions.
```

Also ends up exposing ACR password in the env output from `docker/login-action@v2.1.0`, when it is normally redacted as expected.

Results in failure when doing docker login via action `docker/login-action@v2.1.0`:
```
Logging into ***...
Error: Error response from daemon: Get "https://***/v2/": unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

### Repro steps

Running a workflow with the following yml snippet demonstrates the issue:
```
- uses: Azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}

- uses: azure/CLI@v1
  with:
    inlineScript: |
      echo "DOCKER_TOKEN=$(az acr login --name ${{ secrets.ACR_REGISTRY_NAME }} --expose-token --output tsv --query accessToken)" >> $GITHUB_ENV
      
- uses: docker/login-action@v2.1.0
  with:
    registry: ${{ secrets.ACR_REGISTRY_NAME }}
    username: 00000000-0000-0000-0000-000000000000
    password: ${{ env.DOCKER_TOKEN }}
```
