### ISSUE TITLE
Azurite Table emulator not working

### ISSUE THREAD

**Issue by jessejiang0214** [actions/runner-images#7022]
### Description

Check this issue https://github.com/Azure/Azurite/issues/1761
We found that some application takes the port of Azurite table services(port is 10002), 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

[20221215.2](https://dev.azure.com/ARENAICT/ETI/_build/results?buildId=33901&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=59fb43df-f574-462c-a031-0cc0632b5022&l=8)

### Is it regression?

No

### Expected behavior

The table services should run maybe with differnet port. 

### Actual behavior

The table services didn't run

### Repro steps

You can test with any [table sample code](https://learn.microsoft.com/en-us/azure/storage/common/storage-samples-dotnet#table-samples-v11)

**Comment by charlestonXdao** [comment]
also having this problem

**Comment by bogdan-damian-bgd** [comment]
Hello @jessejiang0214, we'll take a look at it.

**Comment by sergei-pyshnoi** [comment]
Hello @jessejiang0214 , can you provide more detailed repro steps? In the first look, we didn`t find that port 10002 is busy.

**Comment by jessejiang0214** [comment]
Hi @sergei-pyshnoi , 

I'm spent some time on this issue. I found that this issue only can reproduce on Azure DevOps.

Here's github repo with action, which I try to reproduce this issue with minimum code. But it works fine.
https://github.com/jessejiang0214/azurite-table-service-test/actions/runs/4070082791

When I used same code in Azure DevOps, it is not working.

Here's the YAML file in DevOps
```
trigger:
- main

pool:
  vmImage: windows-2022

steps:
- script: dotnet build
  displayName: 'build'

- script: start "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe"
  displayName: 'Start azruite'

- script: dotnet test
  displayName: 'test'
```

You can use my code to test on DevOps and hope you can see the result.

**Comment by sergei-pyshnoi** [comment]
Hello, @jessejiang0214 . The main problem in separate steps 'Start azruite' and 'test' . In AZ Devops, the processes that launched in one step doesn`t shared with another. In your case, when testing is started, the azurite.exe process unavailable. Here is example where tests finished successfully:
```
trigger:
- main

pool:
  vmImage: windows-2022

steps:
- script: dotnet build
  displayName: 'build'

- script: |
    start /B "" "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator\azurite.exe"
    dotnet test
  displayName: 'Start azruite'
```

![image](https://user-images.githubusercontent.com/121864472/216336452-60571495-1619-486a-912a-7057097909eb.png)
