### ISSUE TITLE
Azure Function Core tools cannot start in Latest Ubuntu Image (230129.2)

### ISSUE THREAD

**Issue by cites89** [actions/runner-images#7033]
### Description

Hi,

Since the introduction of Image Version 230129.2 for Ubuntu Azure Function Core tools is unable to start in our pipeline.
During the startup process the follow error is thrown:

Microsoft.WindowsAzure.ResourceStack: Unable to load shared library 'advapi32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libadvapi32.dll: cannot open shared object file: No such file or directory.
Value cannot be null. (Parameter 'provider')

In the revious Image version 20230122.1 this wasn't the case. 

What has changed between this two image versions? This is unclear for me. Some assistance into what might be missing or a fix for this issue would be of great help.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: ubuntu-22.04
Version: 20230129.2
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230129.2/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230129.2

### Is it regression?

20230122.1

### Expected behavior

We expected Azure Function core tools 4 to start up normally.

### Actual behavior

Since the introduction of Image Version 230129.2 for Ubuntu Azure Function Core tools is unable to start in our pipeline.
During the startup process the follow error is thrown:

Microsoft.WindowsAzure.ResourceStack: Unable to load shared library 'advapi32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libadvapi32.dll: cannot open shared object file: No such file or directory.
Value cannot be null. (Parameter 'provider')

In the revious Image version 20230122.1 this wasn't the case. 

What has changed between this two image versions? This is unclear for me. Some assistance into what might be missing or a fix for this issue would be of great help.

### Repro steps

1) Install Azurite using NPM
2) Run Azurite
3) Install Azure Function Core Tools version 4 using NPM
4) Go to a folder where a logic workflow exists
5) RUN:  func start --verbose

**Comment by bogdan-damian-bgd** [comment]
Hello @cites89, we'll take a look at it.

**Comment by sergei-pyshnoi** [comment]
Hello @cites89  ,can you provide more detailed repro steps with code and pipeline example?

**Comment by cites89** [comment]
Hi @sergei-pyshnoi

We use a .yaml template to run the pipeline. The template that takes care of testing the Logic App workflows looks like this:

```
parameters:
- name: preTasks
  type: object
  default: []
- name: postTasks
  type: object
  default: []
- name: testWorkingDirectory
  type: string
  default: ''

jobs:
- job: test_logic_app
  displayName: Test logic app workflow
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    
  - ${{ parameters.preTasks }}

  - task: DotNetCoreCLI@2
    inputs:      
      command: 'restore'
      projects: '**/*.csproj'     
    displayName: 'dotnet restore' 

  - task: NodeTool@0 
    inputs:
        versionSpec: 14.x
  - bash: |
          sudo npm install -g azurite@3.20.1
          sudo azurite -v
          sudo mkdir azurite
          sudo azurite --silent --location azurite --debug azurite\debug.log &
    displayName: 'Install and Run Azurite'

  - task: PowerShell@2
    displayName: 'Install Azure Function Core Tools'
    inputs:
      targetType: 'inline'
      script: |
              sudo npm i -g azure-functions-core-tools@4 --unsafe-perm true

  - task: PowerShell@2
    displayName: 'Run Azure Function Core Tools'
    inputs:
      targetType: 'inline'
      script: |
              cd <root-dir-of-workflow>
              func start --verbose

  - ${{ parameters.postTasks }}
```

This is the workflow we are trying run on the Agent.
[basic-workflow.zip](https://github.com/actions/runner-images/files/10569988/basic-workflow.zip)
