### ISSUE TITLE
ArchiveFiles@2 fails due to Node 16 missing

### ISSUE THREAD

**Issue by Christoba** [actions/runner-images#7037]
### Description

![image](https://user-images.githubusercontent.com/6994341/216446509-4630580d-de87-4706-b8de-b840961f56cd.png)

Perhaps related to the upcoming Node JS 18 [Announcment](https://github.com/actions/runner-images/issues/7002), ArchiveFiles@2 failed today with message 
```
##[error]This step requires a node version that does not exist in the agent filesystem. Path: C:\agents\2.214.1\externals\node16\bin\node.exe
```
This step was running on `windows-latest` built in agent.

Our workaround entailed bootstrapping Node 16 back onto the agent via:
```
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x' # Required for archive files
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20230129.1

### Is it regression?

No

### Expected behavior

ArchiveFiles@2 to work successfully

### Actual behavior

##[error]This step requires a node version that does not exist in the agent filesystem. Path: C:\agents\2.214.1\externals\node16\bin\node.exe

### Repro steps

Run ArchiveFiles@2

**Comment by bogdan-damian-bgd** [comment]
Hi @Christoba, we'll take a look on it.

**Comment by Alexey-Ayupov** [comment]
Hello @Christoba,
The simplest pipeline with ArchiveFiles@2 task could not reproduce the issue.
Could you please try to run ArchiveFiles@2 task one more time? Or provide exact repro steps.

My pipeline:
```
pool:
  vmImage: windows-latest

steps:

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Scripts'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
``` 
Agent specification and pipeline result
![image](https://user-images.githubusercontent.com/116575425/216630548-77cf448a-c81e-4ab7-a950-855828864bfd.png)
![image](https://user-images.githubusercontent.com/116575425/216630870-0152a593-6988-4caf-b42e-11c01a77ac80.png)
