### ISSUE TITLE
Deploy to aws broken after 2023-02-04

### ISSUE THREAD

**Issue by benbai123** [actions/runner-images#7049]
### Description

I use github action to deploy my project to aws elasticbeanstalk, it works well till 2023-02-04 and broken today.

There are 2 messages in failed action

```
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>
```

And

```
ERROR: CommandError - An error occurred while handling git command.
Error code: 128 Error: fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

I have checked the versions of ubuntu, actions/checkout@v2 git are

* Current runner version: '2.301.1'

* ubuntu 22.04.1
    * Image: ubuntu-22.04
    * Version: 20230129.2
* git version 2.39.1

And they are not changed from previous success action.

What I have tried:

* Create a new branch from previous success commit and run the Action, failed.
* Add `git config --global --add safe.directory /github/workspace` before or after actions/checkout, failed.

My yml as below

```
name: CD

on:
  push:
    branches:
      - develop
      - '**force_deploy**'

env:
  AWS_ENVIRONMENT_NAME: MY_ENVIRONMENT
  AWS_DEFAULT_REGION: MY_REGION

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install Dependencies
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm install --prefer-offline
      # TODO: Enable junit xml report later with `yarn lint -f junit -o reports/junit/eslint/results.xml`
      # Because GitHub Workflow doesn't support junit reports yet.
      - name: Run ESLint
        run: npm run lint

  deploy-dev:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          node -v
          yarn -v
          npm install

      - name: Deploy
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'deploy MY_ENVIRONMENT'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
```

What I did before it broken is just change several lines of a js file.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
  Image: ubuntu-22.04
  Version: 20230129.2
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/2023012[9](https://github.com/Looplus/looplus-api-nest/actions/runs/4103340879/jobs/7077414052#step:1:10).2/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230129.2

### Is it regression?

first failed build: https://github.com/Looplus/looplus-api-nest/actions/runs/4099975042, previous successful build: https://github.com/Looplus/looplus-api-nest/actions/runs/4090737669

### Expected behavior

build success and deployed to my aws elasticbeanstalk

### Actual behavior

Failed with message `not a git repository` and error 128

### Repro steps

1. create a branch with name ends with `_force_deploy` to trigger the action.
