### ISSUE TITLE
Xamarin iOS Builds on latest versions of macos-12 and macos-11 are failing with error `The "GetNuGetShortFolderName" task was not found`

### ISSUE THREAD

**Issue by ewh1995** [actions/runner-images#7070]
### Description

Starting today (2/8/2023), we have noticed that our Xamarin iOS builds running on Microsoft-hosted agents in Azure Devops with tags macos-11 and macos-12 have started failing during our Xamarin.iOS build task with the below error:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(238,3): error MSB4036: The "GetNuGetShortFolderName" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin" directory.`

This error is occurring across multiple branches of our application, including several that were succeeding yesterday and have not changed. We are only seeing this error on Xamarin.iOS builds, we are also concurrently building with Xamarin.Android and are not having this issue.

We have noticed that on all successful builds, the current image version for both macos-11 and macos-12 agents was `20230125.1`, while on all failing builds the current image version was `20230205.1`. We have also had a small percentage of our builds this morning succeed and found that those were also running on `20230125.1`, so that leads us to believe that this error is being caused by something in the new image version that is in the process of being pushed to all of the macos-11/12 agent machines.

Can you please investigate this issue and see if there is anything that can be fixed in the image (or anything that we should change in our pipeline/project)? Please let me know if you need any additional information to investigate this issue.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230205.1

### Is it regression?

20230125.1

### Expected behavior

Azure Devops pipeline successfully builds with Xamarin.iOS build task on images macos-11 and macos-12 consistently.

### Actual behavior

Azure Devops pipeline fails with `MSB4036: The "GetNuGetShortFolderName" task was not found.` on macos-11 and macos-12.

### Repro steps

1. Start a pipeline build using the Xamarin.iOS build task and macos-11 or macos-12 build agent versions.
2. Wait for the Xamarin.iOS build task to start.
   a. If the agent image version is 20230205.1, the build will fail with the "GetNuGetShortFolderName" error.

**Comment by ddobranic** [comment]
thank you for reporting @ewh1995 we will take a look.

**Comment by mikhailkoliada** [comment]
@ewh1995 Hello, could you provide a minimal code snippets to reproduce the issue?

**Comment by ewh1995** [comment]
@mikhailkoliada Sure, I have provided our pipeline code below (omitting sensitive info and the code for tasks after the error). The failure is happening in the XamariniOS task. Please let me know if you need anything else.
```
name: '1.0 ($(Build.BuildId))'
jobs:  
  - job: iOS
    pool:
      vmImage: 'macOS-11'

    variables:
      buildConfiguration: 'Release'
      devopsPath: '$(System.DefaultWorkingDirectory)/devops'
      infoPlistPath: '$(System.DefaultWorkingDirectory)/DemoApp/DemoApp.iOS/Info.plist'
  
    steps:
    # # To manually select a Xamarin SDK version on the Hosted macOS agent, enable this script with the SDK version you want to target
    # # https://go.microsoft.com/fwlink/?linkid=871629
    - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_11 
      displayName: 'Select Xamarin SDK version'

    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: '$(certFileName)'
        certPwd: '$(iosCertPassword)'
        keychain: 'temp'
    
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: '$(provProfileFileName)'
  
    - task: NuGetToolInstaller@1
      displayName: 'Install Nuget'
      
    - task: NuGetCommand@2
      displayName: 'Nuget Restore'
      inputs:
        command: restore
        restoreSolution: '**/*.sln'
        vstsFeed: '$(internalFeedId)'
  
    # Dynamically fix formatting issues in Xamarin csproj files
    - task: Bash@3
      displayName: 'Fix iOS Xamarin Csproj Files'
      inputs:
        filePath: '$(devopsPath)/ios-xamarin-fix-csproj.sh'
        arguments: '$(buildConfiguration) iPhone'

    # Update bundle version of app based on build id
    - task: ios-bundle-version@1
      displayName: 'Update Build Version'
      inputs:
        sourcePath: '$(System.DefaultWorkingDirectory)/DemoApp/DemoApp.iOS/Info.plist'
        versionCodeOption: 'buildid'
        versionCode: '$(Build.BuildId)'
        versionName: # Intentionally leave versionName blank to use version set in file
        printFile: true'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
          
    - task: PythonScript@0
      displayName: 'Set Nuget Package Versions'
      inputs:
        scriptSource: 'filePath'
        scriptPath: '$(devopsPath)/nuget-version-set.py'
        arguments: '-n $(Build.BuildId) -b $(Build.SourceBranchName)'

    ### FAILING HERE
    - task: XamariniOS@2
      displayName: 'Build Xamarin iOS app'
      inputs:
        solutionFile: '**/DemoApp.iOS.csproj'
        configuration: '$(buildConfiguration)'
        buildForSimulator: false
        packageApp: true
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
        signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'
```
