### ISSUE TITLE
.Net 5.0.0 missing from current build

### ISSUE THREAD

**Issue by quasarea** [actions/runner-images#7079]
### Description

According to https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#net-core-tools
.NET Core Tools should contain:
.NET Core SDK: 3.1.120, 3.1.202, 3.1.302, 3.1.426, 5.0.104, 5.0.214, 5.0.303, 5.0.408, 6.0.113, 6.0.203, 6.0.308, 6.0.405, 7.0.102

but when trying to run nukeeper I get missing sdk notification.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-latest, 20230206.1

### Is it regression?

yes, 20230129.1

### Expected behavior

To execute nukeeper as it used to. 

Current image details:
```
Failing:  Today at 15:35
Agent name: 'Azure Pipelines 34'
Agent machine name: 'WIN-T6IU89HFF7P'
Current agent version: '2.217.2'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20230206.1'
Agent running as: 'VssAdministrator'
```
Last succesful image details:
```
Passing: Yesterday at 11:14
Agent name: 'Azure Pipelines 18'
Agent machine name: 'fv-az297-14'
Current agent version: '2.217.2'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20230129.1'
Agent running as: 'VssAdministrator'
```

### Actual behavior

```
Pool: [Azure Pipelines](https://dev.azure.com/AVEVA-VSTS/3c9dc12c-13df-4cbe-9381-d08e9dab412f/_settings/agentqueues?poolId=&queueId=270)
Image: windows-latest
Agent: Azure Pipelines 34
Started: Today at 15:35
Duration: 58s
```

```
You must install or update .NET to run this application.

App: C:\Users\VssAdministrator\.dotnet\tools\nukeeper.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  3.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  3.1.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  3.1.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.13 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64

```

### Repro steps

```
      - job: NuKeeper
        steps:
          - checkout: self
            lfs: true
            fetchDepth: 1
            path: s\Source

          - task: NuGetToolInstaller@1
            inputs:
              versionSpec:
              checkLatest: true

          - pwsh: | # Install NuKeeper
              dotnet tool update --global nukeeper --add-source https://api.nuget.org/v3/index.json --ignore-failed-sources
            displayName: Install NuKeeper
            retryCountOnTaskFailure: 3

          - pwsh: | # NuKeeper
              nukeeper inspect --outputfile nukeeper.log
            displayName: NuKeeper
            ignoreLASTEXITCODE: true
            continueOnError: true
```
