### ISSUE TITLE
Docker Compose does not run with new image windows-2022 with Docker 23.00 - The current Compose file version is not compatible with your engine version.

### ISSUE THREAD

**Issue by meneasysoft** [actions/runner-images#7080]
### Description

I think docker compose v2 2.15.1 is not compatible with Docker 23.00 shipped with the new windows image ( https://github.com/actions/runner-images/blob/win22/20230206.1/images/win/Windows2022-Readme.md )

I think docker compose 2.16.0 should be integrated into the new windows-2022 image:
https://github.com/docker/compose/releases/tag/v2.16.0

I always get the following error since the new image is used:
##[error]The current Compose file version is not compatible with your engine version. Please upgrade your Compose file to a more recent version, or set a COMPOSE_API_VERSION in your environment.
##[error]The process 'C:\ProgramData\Chocolatey\bin\docker-compose.exe' failed with exit code 1

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Runner Image
Image: windows-2022
Version: 20230206.1

Included Software: https://github.com/actions/runner-images/blob/win22/20230206.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230206.1

### Is it regression?

Yes it still worked in
20230129.1

### Expected behavior

The error: [error]The current Compose file version is not compatible with your engine version. Please upgrade your Compose file to a more recent version, or set a COMPOSE_API_VERSION in your environment.

should not occur and the compose command should work

### Actual behavior

The error occurs: [error]The current Compose file version is not compatible with your engine version. Please upgrade your Compose file to a more recent version, or set a COMPOSE_API_VERSION in your environment.

### Repro steps

In Azure-DevOps I use in the pipeline:

```
  - task: DockerCompose@0
    displayName: Run services
    inputs:
     containerregistrytype: 'Container Registry'         
     dockerComposeFile: 'build/docker/docker-compose.yml'
     dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE=$(System.DefaultWorkingDirectory)'
     action: 'Run services'
     buildImages: false
```
My docker-compose (docker-compose.yml) file looks like this (details changed):

```
version: '3.0'

services:
  sqlserver:
    image: willh/mssql-server-windows-developer:latest
    container_name: sqlserver
    shm_size: 4gb
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=a(!)Passcode
```
I did some adjustments to my pipeline and my docker-compose.yml file but that did not help.
More details here: https://stackoverflow.com/questions/75399574/azure-devops-compose-error-the-current-compose-file-version-is-not-compatible

**Comment by ddobranic** [comment]
hello, @meneasysoft! thank you for reporting. we will take a look.

**Comment by mikhailkoliada** [comment]
v2.16.0 will be a part of the next release

**Comment by mathias-kogler-snkeos** [comment]
Is there a workaround available?
When is the next release planned?

**Comment by meneasysoft** [comment]
Thank you for the information about v2.16.0 being part of the next release.

My pipelines do not work any more until this is fixed.
I would also like to know whether there is a workaround or not and how long it will take for the next release. 

Please also make sure that v2.16.0 will fixes the described issue. I am not able to see if this helps for myself. It is just my hope that this will help, looking at the release notes of docker-compose v2.16.0.

**Comment by SillyCode** [comment]
Will the fix be available on windows-2019? 
I experience the same issue on it

**Comment by mikhailkoliada** [comment]
It should be available by the end of the week on all OSes

**Comment by meneasysoft** [comment]
Should this already work again?
With the following image the problem still is occuring:

Version: 20230214.1
Included Software: https://github.com/actions/runner-images/blob/win22/20230214.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230214.1

**Comment by mikhailkoliada** [comment]
Deployed

**Comment by SillyCode** [comment]
```
Operating System
Microsoft Windows Server 2019
10.0.17763
Runner Image
Image: windows-2019
Version: 20230214.1
```

Still getting this issue:
`The current Compose file version is not compatible with your engine version. Please upgrade your Compose file to a more recent version, or set a COMPOSE_API_VERSION in your environment.`

My docker-compose:

```
version: "3.9"
services:
  sql-server-db:
    container_name: my-mssql
    image: my-mssql-image:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "***************"
      ACCEPT_EULA: "Y"
```

Can anyone confirm that this release works?

**Comment by meneasysoft** [comment]
I still have the same issue windows-2022 image.
So i can **not** confirm that this works.
There is still an issue and I am disappointed that this issue was closed without verifying that the actual problem was solved.

**Comment by thomas000274** [comment]
Yeah it's a great issue when someone thinks that they control over some issues they can't get past & blaming them instead of themselves. I'm accountable for mine: just a reaction. On Feb 20, 2023 12:23 AM, meneasysoft ***@***.***> wrote:
I still have the same issue windows-2022 image.
So i can not confirm that this works.
There is still an issue and I am disappointed that this issue was closed without verifying that the actual problem was solved.

**Comment by meneasysoft** [comment]
> Yeah it's a great issue when someone thinks that they control over some issues they can't get past & blaming them instead of themselves. I'm accountable for mine: just a reaction. On Feb 20, 2023 12:23 AM, meneasysoft ***@***.***> wrote: I still have the same issue windows-2022 image. So i can not confirm that this works. There is still an issue and I am disappointed that this issue was closed without verifying that the actual problem was solved. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-> I corrected my comment and apologize if this was misunderstood.

**Comment by miaooss** [comment]
Hi, I seem to have the same issue on the windows-2019.

```
Exception in thread Thread-21:
Traceback (most recent call last):
  File "threading.py", line 950, in _bootstrap_inner
  File "threading.py", line 888, in run
  File "compose\cli\log_printer.py", line 202, in watch_events
  File "compose\project.py", line 626, in yield_loop
  File "compose\project.py", line 594, in build_container_event
  File "compose\container.py", line 44, in from_id
  File "docker\utils\decorators.py", line 19, in wrapped
The current Compose file version is not compatible with your engine version. Please upgrade your Compose file to a more recent version, or set a COMPOSE_API_VERSION in your environment.
  File "docker\api\container.py", line 774, in inspect_container
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
Aborting on container exit...
##[error]PowerShell exited with code '1'.
```

**Comment by eleasysoft** [comment]
I have tested several docker images and repo and assume that is an issue with docker-compose.
Depending on the docker-image, it sometimes works, sometimes not.
The given message "The current Compose file version is not compatible with your engine version." is wrong and do not point to the error.
I think that docker-compose do compare the builder-version of the image with the version of the executor, because I could solve the issue for me by re-building my image on the agent.
I couldn't find any reported issue in docker-compose, so I would be glad if someone could confirm it.
Regards, Éric.

**Comment by skotlar** [comment]
Nothing solved for hosted agents Windows 2019 and 2022
The only possible workaround is to run Powershell script downloading correct version of docker-compose.exe and then another script to run downloaded  docker-compose.exe with all needed commands and parameters

**Comment by mathias-kogler-snkeos** [comment]
I figured out a workaround:

Calling `docker-compose` invokes the version installed via Chocolatey.
```
which docker-compose
/c/ProgramData/Chocolatey/bin/docker-compose
```
and as you can see here - that's the old version:
```
C:\ProgramData\Chocolatey\bin\docker-compose.exe --version
docker-compose version 1.29.2, build 5becea[4]
```

Looking at the [install docker script](https://github.com/actions/runner-images/blob/main/images/win/scripts/Installers/Install-Docker.ps1#L40) for windows runners I figured out the path where `docker-compose` 2.16 is installed.

If I call `C:\ProgramData\docker\cli-plugins\docker-compose.exe up` instead of `docker-compose up` it works for me.

**Comment by SillyCode** [comment]
Can confirm that replacing the `DockerCompose@0` task with a PowerShell task that explicitly calls the latest Docker Compose from `C:\ProgramData\docker\cli-plugins` works.

```
- task: PowerShell@2
      displayName: Run Docker-Compose
      inputs:
        targetType: 'inline'
        script: C:\ProgramData\docker\cli-plugins\docker-compose.exe -f docker-compose.yml up -d
```
Thanks @mathias-kogler-snkeos for the suggestion.

**Comment by eleasysoft** [comment]
Thanks @mathias-kogler-snkeos for pointing to the error.
You may also use 'dockerComposePath' to avoid rewriting all tasks.
```
- task: DockerCompose@0
  displayName: Run services
  inputs:
    action: Run services
    projectName: docker-compose
    ....
    dockerComposePath: 'C:\ProgramData\docker\cli-plugins\docker-compose.exe'

```

Fun fact:
```
docker compose version
docker-compose version
```
an returning different versions:
```
Docker Compose version v2.16.0
docker-compose version 1.29.2

```
This means, instead of using the absolut path, you could call "docker compose".
