### ISSUE TITLE
Update/Add kubelogin

### ISSUE THREAD

**Issue by kauemendes** [actions/runner-images#7098]
### Tool name

kubelogin

### Tool license

https://github.com/Azure/kubelogin/blob/master/LICENSE

### Add or update?

- [X] Add
- [ ] Update

### Desired version

v0.0.26

### Approximate size

20mb

### Brief description of tool

Update from kubeconfig 

```
users:
  - name: clusterUser_{your-resource-group}_{your-aks-name}
    user:
      auth-provider:
        config:
          apiserver-id: ...
          client-id: ...
          config-mode: '1'
          environment: AzurePublicCloud
          tenant-id: ...
        name: azure
 ````
 
Starting from Kubernetes v1.26 (December/2022), `az aks get-credentials` generated provider will be removed from the kubectl binary, so we need an alternative method to be able to authenticate to AKS.

The new method to use recommended is kubelogin to generate the new provider as follow: 
```
users:
  - name: clusterUser_{your-resource-group}_{your-aks-name}
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - --login
          - azurecli
          - --server-id
          - 6dae42f8-4368-4678-94ff-3960e28e3630
        command: kubelogin
        env: null
        provideClusterInfo: false
```

The kubelogin binary is now responsible for generating the token, which uses the Azure CLI behind the scenes.

### URL for tool's homepage

https://github.com/Azure/kubelogin

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
From Homebrew

# install
brew install Azure/kubelogin/kubelogin

# upgrade
brew update
brew upgrade Azure/kubelogin/kubelogin
```

From powershell
```
az aks install-cli
$targetDir="$env:USERPROFILE\.azure-kubelogin"
$oldPath = [System.Environment]::GetEnvironmentVariable("Path","User")
$oldPathArray=($oldPath) -split ";"
if(-Not($oldPathArray -Contains "$targetDir")) {
    write-host "Permanently adding $targetDir to User Path"
    $newPath = "$oldPath;$targetDir" -replace ";+", ";"
    [System.Environment]::SetEnvironmentVariable("Path",$newPath,"User")
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","User"),[System.Environment]::GetEnvironmentVariable("Path","Machine") -join ";"
}
```
```


### Tool installation time in runtime

35 seconds

### Are you willing to submit a PR?

yes
