### ISSUE TITLE
Starting OpenSSH fails on Windows runners

### ISSUE THREAD

**Issue by joecotton-wk** [actions/runner-images#7169]
### Description

Hello,

I'm following [the directions provided by Microsoft](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement) to enable and run an SSH agent for my GHA workflow on Windows runners. This is necessary when pulling down private code for building Golang binaries. Instead, starting the SSH agent fails with the following message:

```
     | Service 'OpenSSH Authentication Agent (ssh-agent)' cannot be started due to the following error: Cannot start
     | service 'ssh-agent' on computer '.'.
```

Here's my workflow yaml file:

```yaml
jobs:
  run-build:
    runs-on: windows-2022
    steps:
      - name: Do we have OpenSSH
        run: Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'
        shell: pwsh
      - name: Check the SSH agent service exists
        run: Get-Service ssh-agent
        shell: pwsh
      - name: Start the SSH agent
        run: Start-Service ssh-agent
        shell: pwsh
      - name: Check the SSH agent is running
        run: Get-Service ssh-agent
        shell: pwsh
```

I've spun up a small example project you can examine if you wish.

- Example workflow yaml: https://github.com/joecotton-wk/openssh-agent-on-gha-windows-runners/blob/test-comment/.github/workflows/build.yml
- Example workflow run and error message: https://github.com/joecotton-wk/openssh-agent-on-gha-windows-runners/actions/runs/4235991470/jobs/7360285505

Any insights are appreciated.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230214.1

### Is it regression?

Unsure

### Expected behavior

Starting the SSH agent should succeed

### Actual behavior

Starting the SSH agent is failing with the following message:

```
Service 'OpenSSH Authentication Agent (ssh-agent)' cannot be started due to the following error: Cannot start service 'ssh-agent' on computer '.'.
```

### Repro steps

Please see the yaml and example repos in the description
