### ISSUE TITLE
Ubuntu latest - apt-get upgrade causes failure - grub

### ISSUE THREAD

**Issue by userdocs** [actions/runner-images#7204]
### Description

Updating the runner fails for some grub reason

```yml
name: ubuntu latest

on:
  workflow_dispatch:

jobs:
  ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Host - update
        run: sudo apt-get update

      - name: Host - upgrade
        run: sudo apt-get -y upgrade
```

```
Setting up grub-efi-amd64-bin (2.06-2ubuntu14.1) ...
Setting up grub-efi-amd64-signed (1.187.3~22.04.1+2.06-2ubuntu14.1) ...
mount: /var/lib/grub/esp: special device /dev/disk/by-id/scsi-14d534654202020200690df035523a242afc173af9e57f2a4-part15 does not exist.
dpkg: error processing package grub-efi-amd64-signed (--configure):
 installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 32
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Errors were encountered while processing:
 grub-efi-amd64-signed
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code 100.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.301.1'
Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230219.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230219.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230219.1
Runner Image Provisioner
  2.0.117.1

### Is it regression?

don't know

### Expected behavior

not fail on apt-get upgrade

### Actual behavior

It's failing due to some grub related issue.

### Repro steps

```yml
name: ubuntu latest

on:
  workflow_dispatch:

jobs:
  ubuntu_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Host - update
        run: sudo apt-get update

      - name: Host - upgrade
        run: sudo apt-get -y upgrade
```
