### ISSUE TITLE
az bicep install failing with vmImage: windows-latest

### ISSUE THREAD

**Issue by RobBowman** [actions/runner-images#7261]
### Description

I have a yaml devops pipeline containing the following:

````yaml
  - stage: Publish
    jobs:
      - job: PublishBicepModule
        pool: 
          vmImage: windows-latest
        steps:           
          - task: PowerShell@2
            name: InstallBicep
            displayName: Install Bicep
            inputs:
              pwsh: true
              targetType: inline
              script: |
                az bicep install
```` 

This worked ok up to 8th March but from 9th March it causes the following error:

> ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: No section: 'bicep'

If I change the vmImage to ubuntu-latest then it works ok

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230307.2

### Is it regression?

yes - it worked ok with 20230226.1

### Expected behavior

bicep should be installed

### Actual behavior

error message as described above 

### Repro steps

- create a pipeline as show in the description
- run the pipeline
