### ISSUE TITLE
Update OpenSSL (Light > Normal)

### ISSUE THREAD

**Issue by riverar** [actions/runner-images#7283]
### Tool name

OpenSSL

### Tool license

- Apache-2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Light > Normal

### Approximate size

140MB

### Brief description of tool

The windows images appear to have a _light_ version of OpenSSL installed. This means none of the development libraries are installed, necessitating the use of vcpkg or other manual steps, which take roughly 15-30 minutes to compile and complete.

Ref: https://github.com/actions/runner-images/blob/main/images/win/toolsets/toolset-2022.json#L360-L372

I'm also a bit confused as to what version of OpenSSL is installed on the images. The documentation/toolset reports 1.x but here's the output from `windows-2022`:

```
PS C:\> openssl version
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
```

### URL for tool's homepage

https://slproweb.com/products/Win32OpenSSL.html

### Provide a basic test case to validate the tool's functionality.

N/A

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by erik-bershel** [comment]
Hey @riverar! You have some strange output. Please check workflow you used. Example:
<img width="1073" alt="Screenshot 2023-03-15 at 11 00 35" src="https://user-images.githubusercontent.com/110455084/225275211-a73ea7d2-aa5b-4dd3-a1c7-ea52ac3fe77b.png">

If you want to use another version of OpenSSL lib you may install it in runtime. For example:
```
jobs:
  upd_ssl:
    runs-on: windows-latest
    steps:
    - name: Update SSL via Chocolatey (1.1.1.2000)
      run: choco install openssl
    - name: Update SSL via Chocolatey (toolkit 3.1.0)
      run: choco upgrade openssl.light
```
<img width="1072" alt="Screenshot 2023-03-15 at 12 20 21" src="https://user-images.githubusercontent.com/110455084/225294437-d33bfbf9-5f80-47f7-8d45-f5a52a933a04.png">


We won't change OpenSSL library for Windows due to maintenance concerns.
