### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by virzak** [actions/runner-images#7317]
### Tool name

shfmt

### Tool license

BSD 3-Clause "New" or "Revised" License

### Add or update?

- [X] Add
- [ ] Update

### Desired version

3.6.0

### Brief description of tool

Ensures all shell scripts are properly formatted.

### URL for tool's homepage

https://github.com/mvdan/sh

### Provide a basic test case to validate the tool's functionality.

```bash
Format files

shfmt -l -w script.sh
```

Check that all .sh files + pre-commit are properly formatted
```
find build scripts -name '*.sh' |
  (cat && find .husky/ -name pre-commit) |
  xargs shfmt.exe -d
```
```


### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Yes


    - task: ChocolateyCommand@0
      displayName: 'Download shfmt'
      inputs:
        command: 'install'
        installPackageId: 'shfmt'
        installPackageVersion: '3.6.0'
```

### Tool installation time in runtime

15 seconds

### Are you willing to submit a PR?

yes
