### ISSUE TITLE
nvm doesn't work

### ISSUE THREAD

**Issue by Santas** [actions/runner-images#7367]
### Description

nvm command not found. It should exist based on https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230317.1

### Is it regression?

don't know

### Expected behavior

nvm is available on PATH

### Actual behavior

nvm doesn't exist

### Repro steps

```
name: Main
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: nvm ls
```
