### ISSUE TITLE
Add yq in windows images

### ISSUE THREAD

**Issue by peruzzof** [actions/runner-images#7443]
### Tool name

yq

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

8MB

### Brief description of tool

The tool is already installed in ubuntu images, I just would like to include it in the windows images.

The discussion for linux is at #3645

### URL for tool's homepage

https://github.com/mikefarah/yq

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Download from GH and unzip into tools directory
```

### Tool installation time in runtime

~10s

### Are you willing to submit a PR?

yes

**Comment by sergei-pyshnoi** [comment]
Hello @peruzzof . We will take a look.

**Comment by sergei-pyshnoi** [comment]
@peruzzof Hello! We would not like to install the tool due to small installation time and maintenance concerns. Please, install it in runtime by adding additional step in your pipeline. I am closing this issue, but if you have additional questions feel free to ask.

**Comment by bartekpacia** [comment]
Hi! Could this decision be reconsidered? My reasoning is that `jq` is there, but `yq` isn't.

**Comment by skeet70** [comment]
It's a bit strange that it's present in both Mac and Linux runners but not Windows.

**Comment by QuintinWillison** [comment]
For anybody stumbling across this issue who needs help with "install it in runtime by adding additional step in your pipeline", adding this step worked for us:

```yml
    # We are using a cross-platform composite action that needs yq to be available.
    # GitHub decided to not make it available: https://github.com/actions/runner-images/issues/7443#issuecomment-1514597691
    - name: Make yq tool available on Windows runners
      if: "matrix.os == 'windows-latest'"
      run: choco install yq
```

I agree with others that this should be a standard tool available to all runners. Ironically enough, we're using it to pull out values from a GitHub workflow file (introspection). 😆
