### ISSUE TITLE
Maven broken as repo.maven.apache.org not resolvable

### ISSUE THREAD

**Issue by credmond** [actions/runner-images#7465]
### Description

The runner cannot resolve `repo.maven.apache.org`, crucial for Maven dependency downloads. This issue is new. 

And `repo.maven.apache.org` is up, accessible, and resolvable (i.e., from outside workflow runners).

The runner can resolve/access other domains, including `apache.org`, as per reproducible steps provided.

The error below is from a simple curl test, similar error reported via Maven:

`curl: (6) Could not resolve host: repo.maven.apache.org`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-20.04
  Version: 2023040[9](https://github.com/credmond/ct-parent-pom/actions/runs/4749324880/jobs/8436474201#step:1:10).1

Image: ubuntu-22.04
  Version: 20230409.1

### Is it regression?

Happening in 22.04 and 20.04

### Expected behavior

Runner should be able to resolve `repo.maven.apache.org`.

### Actual behavior

Runner is unable to resolve `repo.maven.apache.org`, which means Maven cannot download dependencies.

### Repro steps

Use this simple workflow, and observe the final curl does not work:

```
name: Bug

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Curl that works
        uses: wei/curl@master
        with:
          args: https://google.ie

      - name: Another curl that also works
        uses: wei/curl@master
        with:
          args: https://apache.org

      - name: Curl that does not work
        uses: wei/curl@master
        with:
          args: https://repo.maven.apache.org
```
