### ISSUE TITLE
Internal github Issue with multiple runner images being automatically picked up and hanging on xcodebuild command

### ISSUE THREAD

**Issue by nikiizvorski** [actions/runner-images#7473]
### Description

Our CI/CD on iOS is stuck at the xcodebuild command exactly before it starts to test on macOS 11. The problem is in the Github Action images that are automatically loaded. The latest images just hang and not working at all. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Just create a new branch from develop that have no code changes but was working and building recently. You can see that it was working as expected before without any changes. It should be working producing the issue now too. Make a commit to trigger the Action and depending if your action pickup the correct image it could work or it could produce the error. It will most certainly pickup the latest so it should be stuck for hours.

### Is it regression?

20230416.1

### Expected behavior

The build should work fine without any changes on our side. It should be able to show a warning, error and not hang into infinity without timeout and showing what the error could be. 

### Actual behavior

It starts to hang and it's stuck for hours on the same command xcodebuild command

### Repro steps

Example setup we are having the issues with:

```
# SDK workflow

name: CI/CD

# Workflow structure
on:
  # Triggers the workflow on push or pull request on all branches
  push:
    branches:
      - '*'
env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
      
    name: Compile SDK Libraries
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Install the Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
            
      # Install cocoapods and test
      - name: Cocoapod install
        run: pod install

      # Run test for SDK
      - name: Run tests for SDK
        run: >-
          xcodebuild clean test -workspace SDK.xcworkspace -scheme "SDK" -destination "name=iPhone 8,OS=14.5" -enableCodeCoverage YES -skip-testing:SDKTests/ScanTest
          
```

The setup is with a Host Application in the test suite which has allowed testing Host API too.

Sample of the application used is this:

```
import UIKit
import CoreLocation
import CoreBluetooth
import SQLite
import SwiftCBOR
import SwiftProtobuf
@testable import SDK

/**
    This application will be used for instrumented tests please make sure to keep this ViewController only with the permissions
     If you need to update it either make a new one or bear in mind when running tests.
 */
class ViewController: UIViewController, CLLocationManagerDelegate, CBCentralManagerDelegate {
    private let locationManager = CLLocationManager()
    var centralManager: CBCentralManager?
   
    // load the view first
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // request location and Bluetooth permissions
        self.requestPermissions()
    }
    
    // request location and bluetooth
    func requestPermissions() {
        // set manager for permissions
        locationManager.delegate = self
        
        // check status for location permission
        switch CLLocationManager.authorizationStatus() {
        case .authorizedWhenInUse, .authorizedAlways:
            // ask for bluetooth permissions
            centralManager = CBCentralManager(delegate: self, queue: nil)
        case .notDetermined:
            // ask for permissions
            locationManager.requestWhenInUseAuthorization()
        default:
            print("Location permission denied")
            break;
        }
    }
   
    // central manager check
    func centralManagerDidUpdateState(_ central: CBCentralManager) {
        switch central.state {
        case .poweredOn:
            print("Permissions granted proceed")
            break
        case .poweredOff:
            break
        default:
            break
        }
    }
    
    // location manager check
    func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
        // handle success
        if status == .authorizedWhenInUse || status == .authorizedAlways {
            print("Location permission have been granted")
            // ask for ble permissions
            centralManager = CBCentralManager(delegate: self, queue: nil)
        }
    }
}
```

And a sample that is running as a test is the following test case:

```

import XCTest
import CryptoKit
@testable import SDK

#if !targetEnvironment(simulator)
class IpnEid: XCTestCase {
    
    func test01_createIpnEid() {
        /* Given */
        let uri = createIpn(node: 0, service: 0)
        
        /* Then */
        XCTAssertNotNil(uri!)
    }
    
    func test02_checkValidIpnEid() {
        /* Given */
        let uri = createIpn(node: 0, service: 0)
        
        /* Then */
        XCTAssertNotNil(uri!.isIpnEid())
    }
    
    func test03_checkIpnSchemeAndPathFail() {
        /* Given */
        let uri = URL(string: "ipn://test")
        
        /* Then */
        XCTAssertThrowsError(try uri!.checkIpnSchemeAndPath())
    }
    
    func test04_checkValidIpnEidFail() {
        /* Given */
        let uri = URL(string: "ipn://test")
        
        /* Then */
        XCTAssertThrowsError(try uri!.checkValidIpnEid())
    }
    
    func test05_checkIpnAuthoryFail() {
        /* Given */
        let uri = URL(string: "ipn:0.0/test")
        
        /* Then */
        XCTAssertThrowsError(try uri!.checkValidIpnEid())
    }
}
#endif
```

The versions we used are cocoapods 1.11.3
MacOS11 XCode 12.5.1 and Iphone 8 iOS 14.5 simulator

**Issue has been detected**:
I have found the issue it's with the runner image that is automatically loaded once our jobs pickup. I am getting the problem between the 3 versions available that are loaded automatically swapped on the action between:

20230416.1
20230411.1
20230318.1 -> The only working one was 3 weeks ago when we made a push and today when auto picked up
Here is a link to the images: https://github.com/actions/runner-images/commits/releases/macOS-11/20230416/images/macos/macos-11-Readme.md

**Additional Information**:
Here is example images of the build running and being stuck with each one of the runners loaded. All tests have been performed yesterday and the day before that:

- Failed build today with latest image:
Image: macos-11
Version: 20230416.1
<img width="1417" alt="Screenshot 2023-04-20 at 18 25 04" src="https://user-images.githubusercontent.com/8210718/233556417-662e887d-6412-4956-95e7-0d5901afd5e1.png">

Link: https://github.com/NodleCode/NodleSdk-iOS/actions/runs/4754250557/jobs/8446843361

- Failed image today with previous image:
Image: macos-11
Version: 20230411.1
<img width="1427" alt="Screenshot 2023-04-20 at 18 26 09" src="https://user-images.githubusercontent.com/8210718/233556932-5093013a-b322-495c-9bf5-6bfde4c3d4e6.png">

Link: https://github.com/NodleCode/NodleSdk-iOS/actions/runs/4751460626/jobs/8440637819

- Working today with older image auto picked:
Image: macos-11
Version: 20230318.1
<img width="1420" alt="Screenshot 2023-04-20 at 18 28 18" src="https://user-images.githubusercontent.com/8210718/233556995-aab556ce-4daf-4455-a732-e00a4994b420.png">

Link: https://github.com/NodleCode/NodleSdk-iOS/actions/runs/4750955005/jobs/8439602898

- Working image 3 weeks ago:
Image: macos-11
Version: 20230318.1
<img width="1382" alt="Screenshot 2023-04-20 at 18 21 55" src="https://user-images.githubusercontent.com/8210718/233557052-61d44aab-1898-4909-91bc-7cf0e24060f8.png">

Link: https://github.com/NodleCode/NodleSdk-iOS/actions/runs/4539848116/jobs/8000116858

**Additional input on the subject**:
We are being stuck at this for 2 days now and we will need soon to be able to make this work in order to go forward with our product. Your input is really needed and appreciated. I can't provide full access to the repos since they aren't public but i took the time to write the sample and all information needed. 

Please let me know with what i can be of use to reproduce and any suggestion would be highly appreciated. I wanted to be able to use the old images but support told me that isn't possible and to contact you so i can see if there is any way to go back to the working images.
