### ISSUE TITLE
azure-streamanalytics-cicd is broken on newest runner image

### ISSUE THREAD

**Issue by yfredrix** [actions/runner-images#7474]
### Description

NPM installing the azure-streamanalytics-cicd tools is crashing on the newest runner image, it did work on the previous image versions.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230417.2

### Is it regression?

yes; 20230407.1

### Expected behavior

An npm install of azure-streamanalytics-cicd should work, and give the ability to run tests on stream analytics jobs.

### Actual behavior

After the install step using npm custom (install -g azure-streamanalytics-cicd) it crashes with the following statement
A JSON parsing exception occurred in [C:\npm\prefix\node_modules\azure-streamanalytics-cicd\bin\LocalRunService.deps.json], offset 0 (line 1, column 1): Invalid value.
Error initializing the dependency resolver: An error occurred while parsing: C:\npm\prefix\node_modules\azure-streamanalytics-cicd\bin\LocalRunService.deps.json
##[error]Cmd.exe exited with code '-2147450741'.

### Repro steps

Run a pipeline with the following steps
```
- job: asa_test
  pool: 
    vmImage: windows-latest
  displayName: Test the Azure Stream Analytics
  steps:
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install -g azure-streamanalytics-cicd --unsafe-perm=true --allow-root'
  
  - script: |
      azure-streamanalytics-cicd test -project $(System.DefaultWorkingDirectory)/asaproj.json ^
                                      -outputpath $(System.DefaultWorkingDirectory)/TestResults/ ^
                                      -testConfigPath $(System.DefaultWorkingDirectory)/Test/TestConfig.json
  ```
This should reproduce the issue, it does require a default working directory with a vscode ASA project.
