### ISSUE TITLE
windows-2019 image no longer has "powershell.exe"

### ISSUE THREAD

**Issue by stefantalpalaru** [actions/runner-images#7516]
### Description

The "setup-msys2" action I am using is trying to invoke "powershell.exe" directly: https://github.com/msys2/setup-msys2/blob/5d5539587e977c80c75e37b8fe25226a9843d456/main.js#L79

This started failing yesterday.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/stefantalpalaru/transmission-og/actions/runs/4838926725/jobs/8623655631

### Is it regression?

https://github.com/stefantalpalaru/transmission-og/actions/runs/4835719292/jobs/8618267800

### Expected behavior

"powershell.exe" available in Windows images

### Actual behavior

"powershell.exe" not found

### Repro steps

Try to use https://github.com/msys2/setup-msys2 which requires "powershell.exe" in PATH.

**Comment by Alexey-Ayupov** [comment]
Hello @stefantalpalaru, I have checked, and "powershell.exe" on its place. Also, it is added to the $env:PATH variable. Finally, I could not reproduce your issue. The "setup-msys2" action works fine with the below code.
Could you please check your setup one more time, and close the issue if the problem no longer exists?

```
 - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: base-devel intltool mingw-w64-x86_64-autotools mingw-w64-x86_64-cmake mingw-w64-x86_64-curl mingw-w64-x86_64-dht mingw-w64-x86_64-gtk3 mingw-w64-x86_64-libb64 mingw-w64-x86_64-libevent mingw-w64-x86_64-libnatpmp mingw-w64-x86_64-libnotify mingw-w64-x86_64-libutp mingw-w64-x86_64-miniupnpc mingw-w64-x86_64-openssl mingw-w64-x86_64-qt5-base mingw-w64-x86_64-qt5-tools mingw-w64-x86_64-qt5-winextras mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib    
          msystem: MINGW64
          update: false
          pacboy: false
          release: true
          location: RUNNER_TEMP
          platform-check-severity: fatal 
```

![image](https://user-images.githubusercontent.com/116575425/235432056-7172c730-ca7b-4162-acca-299ddcd26267.png)

![image](https://user-images.githubusercontent.com/116575425/235432294-fa7709f3-ba54-469b-9971-ead5171505e4.png)

![image](https://user-images.githubusercontent.com/116575425/235430348-75966c82-a3e0-46f2-8769-4f3978bb2026.png)
