### ISSUE TITLE
UseRubyVersion 3.1 not found on MacOS 13

### ISSUE THREAD

**Issue by willtho89** [actions/runner-images#7519]
### Description

Hi,

on MacOS 12 we use something like this and it was working great.

```yml
pool:
  vmImage: macOS-12

variables:
  - group: fastlane
  - name: IS_CI
    value: 1

steps:
  - checkout: self
    persistCredentials: true

  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 3.0"
      addToPath: true
    displayName: Use Ruby 3.0
```

with `vmImage: macOS-13` we get the following error tough:

```
##[section]Starting: Use Ruby 3.0
==============================================================================
Task         : Use Ruby version
Description  : Use the specified version of Ruby from the tool cache, optionally adding it to the PATH
Version      : 0.213.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-ruby-version
==============================================================================
##[error]Version spec >= 3.0 for architecture %s did not match any version in Agent.ToolsDirectory.
Available versions: /Users/runner/hostedtoolcache

If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Ruby at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Ruby versions at https://go.microsoft.com/fwlink/?linkid=2005989.
##[section]Finishing: Use Ruby 3.0
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2023-05-02T11:59:40.5483400Z ##[group]Runner Image
2023-05-02T11:59:40.5483540Z Image: macos-13
2023-05-02T11:59:40.5483680Z Version: 20230426.3
2023-05-02T11:59:40.5483940Z Included Software: https://github.com/actions/runner-images/blob/macOS-13/20230426.3/images/macos/macos-13-Readme.md
2023-05-02T11:59:40.5484290Z Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20230426.3

### Is it regression?

No

### Expected behavior

Use a ruby version on MacOS 13

### Actual behavior

Pipeline step UseRubyVersion errors with the following message

##[error]Version spec >= 3.0 for architecture %s did not match any version in Agent.ToolsDirectory.
Available versions: /Users/runner/hostedtoolcache

### Repro steps

Run this pipeline in Azure DevOps
```yml
pool:
  vmImage: macOS-13

variables:
  - group: fastlane
  - name: IS_CI
    value: 1

steps:
  - checkout: self
    persistCredentials: true

  - task: UseRubyVersion@0
    inputs:
      versionSpec: ">= 3.0"
      addToPath: true
    displayName: Use Ruby 3.0
```
