### ISSUE TITLE
Go not found in macOS 13 runner

### ISSUE THREAD

**Issue by paulofierro** [actions/runner-images#7578]
### Description

The [macOS 13 runner README states](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md) that it has the "Go command" installed.

However, if you run `go version` you get an error:
```
go: command not found
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macOS 13 version `20230509.4` ❌ 
Build: https://github.com/paulofierro/GoCommandTester/actions/runs/4950872824/jobs/8855065200

macOS 12 version `20230505.1` ✅ 
Build: https://github.com/paulofierro/GoCommandTester/actions/runs/4950874346

### Is it regression?

yes

### Expected behavior

Go is installed and available as it was in macOS 12.

### Actual behavior

The `go` command is not found.

### Repro steps

Create a workflow with a single step:

```yaml
name: Go command test
on:
  push:
    
jobs:
  test:
    runs-on: macOS-13

    steps:
      - name: Print go version
        run: go version
```
