### ISSUE TITLE
UUID for MacOS-13 is randomly generated vs being preset on MacOS-12 

### ISSUE THREAD

**Issue by antonioalwan** [actions/runner-images#7591]
### Description

Using Azure pipeline, xcode provisioning profile requires some unique device Identifier included for the device used for testing. Thus, adding a specific demand with agent.Name while using macOS-12 works every time the pipeline runs by picking the same UDID. Having the same demands clause on macOs-13 would pick a random UDID for the selected agent. For example running the following pipeline which has `demands` clause
```yaml
pool:
  name: 'Azure Pipelines'
  vmImage: macOS-12
  demands:
  - Agent.Name -equals Azure Pipelines 16
```
Would pick the same UDID: 
```
"platform_UUID" : "4203018E-580F-C1B5-9525-B745CECA79EB",
"provisioning_UDID" : "4203018E-580F-C1B5-9525-B745CECA79EB"
```
However, when switching to MacOS-13 image. the same command causes a random UDID every time it is called.
Just wondering if there is any way to request the same UDID by selecting a different demand or requiring an image with a specific UDID?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current agent version: '3.220.0'

### Is it regression?

MacOS-13

### Expected behavior

To pick the same UDID every time the agent is selected

### Actual behavior

New UDID is randomly generated

### Repro steps

Description to reproduce the issue:
Run a pipeline with 
```yaml
pool:
  name: 'Azure Pipelines'
  vmImage: macOS-12
  demands:
  - Agent.Name -equals Azure Pipelines 16
- task: Bash@3
  displayName: Machine UDID
  inputs:
    targetType: 'inline'
    script: 'system_profiler SPHardwareDataType -json'
```
You get the same UDID
run the same with macOS-13. A new UDID is generated.
