### ISSUE TITLE
Unable to build image if using ubuntu-latest (22.04) Microsoft hosted Agent - error installing google chrome

### ISSUE THREAD

**Issue by jpuckettgomeyra** [actions/runner-images#7633]
### Description

I am running GenerateResourcesAndImage.ps1 in an Azure DevOps pipeline to generate new images on a regular schedule. This is running inside a Microsoft hosted agent. When I use ubuntu-latest to run GenerateResourcesAndImage.ps1, I get the error pasted below. If I use the ubuntu-20.04 it works. This started between May 17 and May 20.

```
==> azure-arm: Provisioning with shell script: /home/vsts/work/1/s/images/linux/scripts/installers/google-chrome.sh
    azure-arm: Downloading 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' to '/tmp/google-chrome-stable_current_amd64.deb'...
    azure-arm: Download completed
    azure-arm: Reading package lists...
    azure-arm: Hit:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease
    azure-arm: Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
    azure-arm: Get:6 https://packages.cloud.google.com/apt cloud-sdk InRelease [6361 B]
    azure-arm: Err:6 https://packages.cloud.google.com/apt cloud-sdk InRelease
    azure-arm:   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
    azure-arm: Hit:7 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
    azure-arm: Reading package lists...
==> azure-arm: W: GPG error: https://packages.cloud.google.com/apt cloud-sdk InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
==> azure-arm: E: The repository 'https://packages.cloud.google.com/apt cloud-sdk InRelease' is not signed.
    azure-arm: Reading package lists...
    azure-arm: Building dependency tree...
    azure-arm: Reading state information...
==> azure-arm: E: Unable to locate package google-cloud-sdk
    azure-arm: Pester v5.4.1
    azure-arm:
    azure-arm: Starting discovery in 1 files.
    azure-arm: Discovery found 11 tests in 163ms.
    azure-arm: Filter 'FullName' set to ('Google Cloud SDK').
    azure-arm: Filters selected 1 tests to run.
    azure-arm: Running tests.
    azure-arm:
    azure-arm: Running tests from '/imagegeneration/tests/CLI.Tools.Tests.ps1'
    azure-arm: Describing Google Cloud SDK
    azure-arm:   [-] Google Cloud SDK 108ms (79ms|28ms)
    azure-arm:    Command 'gcloud --version' has finished with exit code
    azure-arm:        /usr/bin/bash: gcloud: command not found
    azure-arm:    at "gcloud --version" | Should -ReturnZeroExitCode, /imagegeneration/tests/CLI.Tools.Tests.ps1:46
    azure-arm:    at <ScriptBlock>, /imagegeneration/tests/CLI.Tools.Tests.ps1:46
    azure-arm: Tests completed in 540ms
    azure-arm: Tests Passed: 0, Failed: 1, Skipped: 0 NotRun: 10
    azure-arm:

```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Pool: Azure Pipelines
Image: ubuntu-latest
Agent: Hosted Agent

### Is it regression?

works on ubuntu-20.04, does not on ubuntu-latest

### Expected behavior

Able to build a new image without error

### Actual behavior

receive error in description

### Repro steps

Create a pipeline to run GenerateResourcesAndImage.ps1 in Azure DevOps using ubuntu-latest microsoft hosted agent. An example of how this might be set up is below.

```

resources:
  repositories:
  - repository: runner-images
    type: github
    endpoint: github.com
    name: actions/runner-images
    path: runner-images

jobs:
- job: buildimage
  timeoutInMinutes: 480
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - checkout: runner-images

  - powershell: |
      Install-Module -Name Az -Repository PSGallery -Force
    displayName: 'Install Azure Az PowerShell Module'

  - task: AzurePowershell@5
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: pscore
      scriptLocation: 'inlineScript'
      azurePowerShellVersion: 'latestVersion'
      inline: |
        Import-Module ./helpers/GenerateResourcesAndImage.ps1

        GenerateResourcesAndImage -SubscriptionId '$(azureSubscriptionId)' -ResourceGroupName "$(azureVHDResourceGroupName)" -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2004 -AzureLocation "$(azureLocation)" -Verbose -OnError cleanup -AzureTenantId "SNIP" -AllowBlobPublicAccess $False -EnableHttpsTrafficOnly $True -Force -RestrictToAgentIpAddress $True -AzureClientId $env:CLIENT_ID -AzureClientSecret $env:CLIENT_SECRET 
    displayName: 'build the vhd' 
    env:
      CLIENT_ID: $(AzureClientId)
      CLIENT_SECRET: $(AzureClientSecret)
```
