### ISSUE TITLE
Android emulator doesn't finish booting up on MacOS 13

### ISSUE THREAD

**Issue by edgchen1** [actions/runner-images#7671]
### Description

In our CI builds, we start an Android emulator and then wait for it to finish booting up.

We detect that the emulator has booted up with this command:
```sh
${ANDROID_SDK_ROOT}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
```

Since updating the image from macOS 12 to macOS 13, this step has started timing out. It appears that the emulator doesn't finish booting up.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-13
Version: 20230524.1

### Is it regression?

Not sure if it worked with macos-13 before. It works with macos-12, version 20230516.1.

### Expected behavior

The Android emulator finishes booting up and we can detect that it is ready to use.

### Actual behavior

The build times out when using the MacOS 13 agent.

### Repro steps

Here is an Azure DevOps pipeline to reproduce it. Note that it succeeds when using image "macOS-12".

```yaml
jobs:
- job: android_emulator_test
  workspace:
    clean: all
  pool:
    vmImage: 'macOS-13'

  steps:
  - checkout: none

  - task: JavaToolInstaller@0
    displayName: Use jdk 11
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - bash: |
      set -e -x

      ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-31;default;x86_64'

      echo "no" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/avdmanager create avd --name android_emulator_avd --package 'system-images;android-31;default;x86_64' --force

      ${ANDROID_SDK_ROOT}/tools/emulator \
        -avd android_emulator_avd \
        -memory 4096 \
        -timezone America/Los_Angeles \
        -no-snapshot -no-audio -no-boot-anim -no-window \
        -partition-size 4096 &

      ${ANDROID_SDK_ROOT}/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
    displayName: Start Android emulator
    timeoutInMinutes: 10
```
