### ISSUE TITLE
SqlServer LocalDB occasionally fails to initialize correctly 

### ISSUE THREAD

**Issue by Cyberboss** [actions/runner-images#7720]
### Description

For the past few weeks, I've been encountering what seems to be more and more errors when connecting to SQL Server LocalDB. After some investigation, it seems LocalDB either doesn't initialize or initializes in a broken state once every few runs.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/Cyberboss/actions_testbed/actions/runs/5260405046

### Is it regression?

Possibly

### Expected behavior

Consistently able to connect to LocalDB

### Actual behavior

Spurious connection failures to local DB

### Repro steps

2022\*80+ 2019\*80 matrix job definition (The matrix names don't matter except for `os`):
```yml
name: LocalDB Failure

on:
  workflow_dispatch:
jobs:
  test:
    name: Windows Live Tests
    strategy:
      fail-fast: false
      matrix:
        database-type: [ 'SqlServer', 'Sqlite', 'PostgresSql', 'MariaDB', 'MySql' ]
        watchdog-type: [ 'Basic', 'System' ]
        configuration: [ 'Debug', 'Release' ]
        more-jobs: ['a','b']
        even-more-jobs: ['c','d']
        os: ['windows-2019','windows-2022']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check LocalDB Connection
      shell: powershell
      run: |
        Write-Host "Checking"
        sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
```
