### ISSUE TITLE
Python tests fail with ModuleNotFound error on ubuntu-20.04 20230611.

### ISSUE THREAD

**Issue by nikhaxuall** [actions/runner-images#7737]
### Description

I was running into an issue with some python tests failing and throwing a ModuleNotFound error. During the troubleshooting I reran some jobs that completed successfully two days ago (on version 20230517.1).  When they were rerun they ran on version 20230611.1 and failed with the same ModuleNotFound error I was getting on new jobs.

It's a private repo so I can't link anything, but here's the code from the workflow:

```yaml
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies and test
      run: |
        cd jobs
        sudo apt-get update
        sudo apt-get install build-essential libpoppler-cpp-dev pkg-config weasyprint
        python -m pip install pip==23.0.1
        pip install pytest
        pip install -r requirements.txt
        # Python as installed by actions/setup-python ends up in a non-standard location.
        # Added PYTHONPATH here so that python can find weasyprint which is installed by apt above
        AWS_DEFAULT_REGION="us-east-2" PYTHONPATH="/usr/lib/python3/dist-packages" python -m pytest --ignore test/checkers
```
Removing the PYTHONPATH declaration doesn't change anything.

One of the packages it's installing in the requirements file is a local library (`-e ../my_lib1).  To work around this issue I've had to symlink that local library into the PYTHONPATH before running the tests:

`sudo ln -sf /home/runner/work/.../<my_local_lib> /usr/lib/python3/dist-packages`

I want to stress, it's not that only new commits that are failing, clicking the re-run button on something from 2 days ago now fails too.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Image: ubuntu-20.04
  Version: 20230611.1

### Is it regression?

20230517.1

### Expected behavior

I would expect jobs to continue working the same way, and I'd especially expect jobs that previously succeeded to continue to succeed.

### Actual behavior

Jobs that completed successfully on `20230517.1`  are failing when run on `20230611.1` with no changes in code.

### Repro steps

For me, just rerun a job.  For you, I'm not sure.
