### ISSUE TITLE
No trailing newline present in bash_profile

### ISSUE THREAD

**Issue by Qwerty-133** [actions/runner-images#7885]
### Description

The content between `---` is from the output of `cat ~/.bash_profile`
There's no trailing newline present after `POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-macos11` making commands such as `echo 'export ...' >> ~/.bash_profile` fail.

```shell
The following commands need to be run to add spcache to your PATH:
echo 'export PATH="$HOME/.local/share/spcache:$PATH"' >> /Users/runner/.bash_profile
spcache has been added to PATH.
Please restart your shell to start using spcache.
Or run exec $SHELL.
---
[ -f $HOME/.bashrc ] && source $HOME/.bashrc
PERFLOG_LOCATION_SETTING=RUNNER_PERFLOG
POWERSHELL_DISTRIBUTION_CHANNEL=GitHub-Actions-macos11export PATH="$HOME/.local/share/spcache:$PATH"
---
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

   Image: macos-13
  Version: 20230611.2
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20230611.2/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230611.2

   Image: macos-12
  Version: 20230623.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230623.2/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230623.2

   Image: macos-11
  Version: 20230623.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-11/20230623.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20230623.1

### Is it regression?

not sure

### Repro steps

```yml
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-12, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
      - run: echo "---" && cat ~/.bash_profile && echo "---"
```

**Comment by Alexey-Ayupov** [comment]
Hello @Qwerty-133, we will take a look.

**Comment by Alexey-Ayupov** [comment]
@Qwerty-133, could you please use the `echo "" >> ~/.bash_profile` command as a workaround before updating bash_profile file? Meanwhile, we will check what we can do to fix it in our images.

```
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-12, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
      - run: echo "---" && echo "" >> ~/.bash_profile && cat ~/.bash_profile && echo "---"

```
