### ISSUE TITLE
Android project update to Gradle 8 and Java 17 build fails without reason.

### ISSUE THREAD

**Issue by Canato** [actions/runner-images#7915]
### Description

I update my Android project to `Gradle 8` and `Java 17`.
After that, my GitHub Actions stop to work for assemble gradle command.
_(more after some context)_

# Context
### Gradle
- DistributionUrl `https\://services.gradle.org/distributions/gradle-8.0.2-bin.zip` _(before `7.5.1-bin`)_
- Version `8.0.2` _(before `7.4.0`)_

### Java
- JavaVersion.`VERSION_17` _(before JavaVersion.`VERSION_11`)_

## Fixed update issues
- BuildConfig files disable
- Fix resource imports (multi gradle module project)
- Improve R8 proguard rules

## Gradle properties added
-  `org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8`

# Github Actions Workflow

### Gradle commands of each job
- `detektAllModules` ✅  (custom detekt/lint gradle method)
- `testPhoneDebugUnitTest` ✅
- `:app:legacy:base:test :app:legacy:domain:test :app:legacy:data:test :app:data:socketio-client:test :app:data:mqtt-server:test :app:data:network-exceptions:test` ✅
- bundlePhoneRelease 🚫
- assemblePhoneDebug 🚫

#### **Obs:**
1. Both commands work running locally on my machine
2. Both commands work before the update
3. Both commands work on the main branch _(without the update)_

### Github Actions for `assemblePhoneDebug`

> Was added `Setup-java` step for `Java 17` compatibility _(I believe the problem is close to this)_

```yml
  build_phone_debug_job:
    env:
      CI: "true"
    name: Build Phone Debug
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache gradle files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Phone Debug
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assemblePhoneDebug
```

No error is shown, but after re-running enabling `debug logging`, we can see:
> Node Action run completed with exit code 143 

The build took 6m to fails, we have a timeout of 30min

Before re-running
<img src="https://github.com/actions/runner-images/assets/15942449/0e19917e-ca00-4ae9-b869-f16bba0b7708" width="500">

After re-run with debug
<img src="https://github.com/actions/runner-images/assets/15942449/445f4ec0-f9d6-4114-a0a0-a6175581fcda" width="500">

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Not sure where `"Set up job" -> "Runner Image" -> "Version"` is.
But we are using the default GitHub runner's latest ubuntu version.

### Is it regression?

No

### Expected behavior

We should have a final build or a clear error message

### Actual behavior

Fails without explanation

### Repro steps

Android project with gradle 8, Java 17, using GitHub Actions with the latest Ubuntu should reproduce.
