### ISSUE TITLE
macos-13 fails with `sudo: a terminal is required to read the password`

### ISSUE THREAD

**Issue by JarLob** [actions/runner-images#7987]
### Description

[The run](https://github.com/GitHubSecurityLab/actions-permissions/actions/runs/5678918868/job/15390694453) fails with `sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper`

The script does:
```
sudo sysadminctl -addUser mitmproxyuser -admin
sudo cp mitm_plugin.py /Users/mitmproxyuser/mitm_plugin.py
```

It works on `macos-11` and `macos-12` most probably because `/etc/sudoers` used to contain `runner ALL=(ALL) NOPASSWD: ALL`, but not in `macos-13`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230611.2

### Is it regression?

yes, macos-12, https://github.com/GitHubSecurityLab/actions-permissions/actions/runs/5678918868/job/15390694634

### Expected behavior

No error.

### Actual behavior

fails with `sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper`

### Repro steps

sudo sysadminctl -addUser mitmproxyuser -admin
sudo cp mitm_plugin.py /Users/mitmproxyuser/mitm_plugin.py
see https://github.com/GitHubSecurityLab/actions-permissions/actions/runs/5678918868/job/15390694453

**Comment by sergei-pyshnoi** [comment]
Hello @JarLob . Thanks for your report. We will take a look.

**Comment by ilia-shipitsin** [comment]
@JarLob ,

I added your [steps](https://github.com/ilia-shipitsin/sudo/blob/main/.github/workflows/blank.yml#L15-L17)

to workflow, it runs on macos-13 without any issue

https://github.com/ilia-shipitsin/sudo/actions/runs/5693244777/job/15431908696

**Comment by ilia-shipitsin** [comment]
@JarLob , I'm closing this issue (cannot repro using provided steps).
feel free to reopen if issue still persists

**Comment by JarLob** [comment]
I have minimized https://github.com/GitHubSecurityLab/actions-permissions/actions/runs/5678918868/job/15390694453 to
```yaml
on:
  workflow_dispatch:

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-13
        - macos-latest
        - macos-11

    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          sudo sysadminctl -addUser myuser -admin
          sudo -u myuser -H bash -e -c "id" 
```
Please see https://github.com/GitHubSecurityLab/actions-permissions/actions/runs/5856845682/job/15877437623
