### ISSUE TITLE
GitHub Actions Hang Indefinitely Instead of Erroring Out When an Image Doesn't Exist

### ISSUE THREAD

**Issue by petcuvio** [actions/runner-images#8024]
### Description

I recently encountered an issue with GitHub Actions where a workflow was pending indefinitely. After some investigation, I discovered that the problem was caused by a typo in the image name specified in the runs-on field of the workflow YAML file. The image didn't exist, but instead of erroring out and providing feedback about the issue, the workflow just hung in a pending state.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Here's the relevant part of my workflow file:
```yaml
name: Cleanup Old Versions
on:
  workflow_dispatch: 
jobs:
  cleanup:
    env:
      PACKAGE_DOCKER: "container"
      PACKAGE_DOCKER_NAME: "rpg%2Frpg-dockerized"
      PACKAGE_NPM: "npm"
      PACKAGE_NPM_NAME: "rpg"
    runs-on: ubuntu:22.04    # !!! this should have been 'ubuntu-22.04'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
```

### Is it regression?

I don't believe so.

### Expected behavior

A comprehensive message along the lines of: 

` 🛑  runner image "ubuntu:22.04" does not exist`
or
` 🛑  label "ubuntu:22.04" not found`

### Actual behavior

Workflow spins its wheels indefinitely, not __*even*__ re-running it with `debug` flag on, reveals something useful:

![image](https://github.com/actions/runner-images/assets/53478278/4765fa3a-1b73-4353-b6e7-ab5c23db4c00)

### Repro steps

1. take any workflow 
2. replace the `runs-on` property with anything valid in `yaml`, but not a valid runner image: 
```yaml
runs-on: ubuntu:22.04

#or

runs-on: steam-power 

#or

runs-on: unicorn:dreams:and:rainbows

```
