### ISSUE TITLE
Install SSH Key not working on MacOs

### ISSUE THREAD

**Issue by florentm35** [actions/runner-images#8033]
### Description

Hello
I need to push manually with shell on mac OS VM on Azure git, but it failed :
![image](https://github.com/actions/runner-images/assets/31475579/84d0d43c-cbee-4466-b4c7-0e341ed9d183)

The script use can be found in repro step, the real problem is that script work fine on ubuntu-latest

I have some test with ssh and if i disable the strict host key check it's work fine.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: macos-12
Version: 20230709.1

### Is it regression?

No

### Expected behavior

This ssh key and the know host was well added on MacOs

### Actual behavior

```txt
[libelles 8229bb2] test
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
##[error]Bash exited with code '128'.
Finishing: Bash
```

### Repro steps

- Change the git url in second bash script
- Try change vmImage by ubuntu-latest and it's work fine
```yml
trigger:
  - master
variables:
  - group: Pipelines-ssh

jobs:
  - job: Build
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: InstallSSHKey@0
        inputs:
          knownHostsEntry: '$(host)'
          sshPublicKey: $(pubKey)
          sshKeySecureFile: id_rsa
      # Change git information
      - task: Bash@3
        inputs: 
          targetType: inline
          script: |
            git checkout -b libelles;
            git branch -m libelles;

            echo "Email initial : $(Build.RequestedForEmail)";
            email="$(Build.RequestedForEmail)";

            echo "Email final : $email";
            git config --global user.email "$email";

            echo "Nom initial : $(Build.RequestedFor)";
            name="$(Build.RequestedFor)";

            echo "Nom final : $name";
            git config --global user.name "$name";
      # Create file and push it
      # Change git url
      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            echo "toto" > test.txt;
            git add *;
            git commit -m "test";
            git remote set-url origin git@ssh.dev.azure.com:v3/*****/******/**************;
            git push --set-upstream origin libelles
```
