### ISSUE TITLE
No Xamarin bundle symlinks in macos-13 image

### ISSUE THREAD

**Issue by jahmai-ca** [actions/runner-images#8045]
### Description

On the `macos-12` (and earlier) images, it was possible to use `select-xamarin-sdk.sh` with a version label to select which Xamarin SDK version to use (see https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md).

This doesn't seem to be possible on the `macos-13` image. Not only is there none listed in the docs (https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md), but attempting to use the `select-xamarin-sdk.sh` results in an error.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230801.2

### Is it regression?

20230709.1

### Expected behavior

The macos-13 docs list Xamarin version bundle symlinks, and using `select-xamarin-sdk.sh` succeeds in the build.

### Actual behavior

The macos-13 docs do not contain any symlinks and the `select-xamarin-sdk.sh` fails with:

```
Starting: Selecting Xamarin version
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.225.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_21
========================== Starting Command Output ===========================
/bin/bash /Users/runner/work/_temp/4fd70082-8701-4413-8c23-30c8605ba04e.sh
Set Xamarin SDK to 6_12_21
Set Current folder for /Library/Frameworks/Mono.framework/Versions
ln: /Library/Frameworks/Mono.framework/Versions/Current: No such file or directory
##[error]Bash exited with code '1'.
Finishing: Selecting Xamarin version
```

### Repro steps

Include the following in your YAML:

```
# This task selects a specific Xamarin.Mono and Xamarin.iOS combination
- task: Bash@3
  displayName: 'Selecting Xamarin version'
  inputs:
    targetType: 'inline'
    script: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_24'
```

**Comment by erik-bershel** [comment]
Hey @jahmai-ca!
We'll think about adding this feature back.

**Comment by mikhailkoliada** [comment]
Duplicate of 7635, tamarin is not yet added to macOS 13

**Comment by jahmai-ca** [comment]
@mikhailkoliada #7635 is about nuget, did you mean to reference another issue?

**Comment by erik-bershel** [comment]
@jahmai-ca issues are connected to each other. Both require Xamarin for macOS 13. Briefly, in case we find an opportunity to install Xamarin without negative side effects, we will solve both your and the specified by @mikhailkoliada issues.

**Comment by jahmai-ca** [comment]
@erik-bershel Ok. But you said "if". Isn't this required to be able to build MAU / net7-ios / net7-android applications?

**Comment by nbevans** [comment]
Xamarin is still supported until May 2024.

Why has the MacOS-13 image had all traces of Mono, Xamarin, MSBuild etc removed from it?

**Comment by jahmai-ca** [comment]
Not only that but net7-ios and net7-android are supposed to be supported beyond May 2024, unless we missed the memo?

**Comment by nbevans** [comment]
When is this going to be fixed?

**Comment by bwalpoleuk** [comment]
The announcement that Xamarin will support iOS 17 and Android 34 is very welcome news. But to be able to continue to use ADO for CI/CD pipelines for Xamarin we would need the macos-13 agents to have Xamarin tooling support since XCode 15 will be a pre-requisite .

**Comment by nbevans** [comment]
What am I missing? Why is  "need the macos-13 agents to have Xamarin tooling support since XCode 15 will be a pre-requisite" a problem? That's the purpose of this discussion is it not?

**Comment by bwalpoleuk** [comment]
> What am I missing? Why is "need the macos-13 agents to have Xamarin tooling support since XCode 15 will be a pre-requisite" a problem? That's the purpose of this discussion is it not?

Yes exactly, which I was re-enforcing the message that Xamarin supporting iOS 17 and Android API 34 only gets us so far, we can't use exiting CI/CD pipelines without the macos-13 agents being updated to include Xamarin.

**Comment by nbevans** [comment]
Yes - that is the purpose of this discussion.

The Macos-13 agent needs both XCode15 (if it doesn't already) *and* Xamarin (as per latest release blog post which includes support for XCode15 / iOS17)

**Comment by jayanthsagar** [comment]
Any timeline when Xamarin SKDs will be included in macOS13 agents?

**Comment by ranjithtech** [comment]
Why this is closed without a solution. We are still experiencing the same problem. We cannot build our Xamarin forms app with mac-OS13 azure image :(

**Comment by brunonocetti** [comment]
@jayanthsagar @ranjithtech you can use macOS-13 image if you install required dependencies during pipeline execution.

Example:
```
        - script: brew install --cask xamarin-ios
          displayName: 'Install Xamarin.iOS package using Homebrew'

        - script: brew install --cask xamarin-android
          displayName: 'Install Xamarin.Android package using Homebrew'

        - script: curl $(vsForMacDmgUrl) -o /tmp/vsformac.dmg
          displayName: 'Download Visual Studio for Mac'

        - script: hdiutil attach /tmp/vsformac.dmg
          displayName: 'Mount Visual Studio for Mac dmg'

        - script: cp -R /Volumes/Visual\ Studio/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin /tmp/msbuild
          displayName: 'Extract MSBuild'
```

Then use `mono "/tmp/msbuild/MSBuild.dll"`

**Comment by nbevans** [comment]
I tried this today with xamarin ios and it worked on the macos13 agent.  Nice 👍

**Comment by veringm** [comment]
Hi @brunonocetti Thx for the update. However, I get this error on script no 3

Script contents:
curl $(vsForMacDmgUrl) -o /tmp/vsformac.dmg
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/7144a19b-cd8b-4c4c-a691-7041bad3aee7.sh
/Users/runner/work/_temp/7144a19b-cd8b-4c4c-a691-7041bad3aee7.sh: line 1: vsForMacDmgUrl: command not found
curl: (2) no URL specified
curl: try 'curl --help' for more information

Where is the $(vsForMacDmgUrl) variable defined? Where can I find that URL?

**Comment by 1Siger1** [comment]
@veringm Try this URL: https://download.visualstudio.microsoft.com/download/pr/3209737b-50b9-44e0-9331-9f7bdaf5fc15/57c31feafddb763141ff34353400e08a/visualstudioformacinstaller-17.6.0.73.dmg

**Comment by Eric-EvilTwin** [comment]
The path `/Volumes/Visual\ Studio/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin` did not work for me with this version https://download.visualstudio.microsoft.com/download/pr/3209737b-50b9-44e0-9331-9f7bdaf5fc15/57c31feafddb763141ff34353400e08a/visualstudioformacinstaller-17.6.0.73.dmg - I don't see an MSBuild folder inside of that DMG file. Was there another version that this worked on?

**Comment by Eric-EvilTwin** [comment]
FYI - I was able to get my builds working after changing to macos-13 by just installing the casks and using my existing `NuGetCommand@2` and `XamariniOS@2` tasks

```
        - script: brew install --cask xamarin-ios
          displayName: 'Install Xamarin.iOS package using Homebrew'

        - script: brew install --cask xamarin-android
          displayName: 'Install Xamarin.Android package using Homebrew'
```

**Comment by damews** [comment]
> FYI - I was able to get my builds working after changing to `vmImage: 'macos-13'` by just installing the casks and using my existing `NuGetCommand@2` and `XamariniOS@2` tasks
> 
> ```
>         - script: brew install --cask xamarin-ios
>           displayName: 'Install Xamarin.iOS package using Homebrew'
> 
>         - script: brew install --cask xamarin-android
>           displayName: 'Install Xamarin.Android package using Homebrew'
> ```

Added these in my workflow but can't get a build to work with the `macos-13` runner. I also installed the vscode-for-mac using the example provided by @brunonocetti, but still not working. I'm getting these errors:

`The type or namespace name 'Forms' does not exist in the namespace 'Xamarin'`
`The type or namespace name could not be found (are you missing a using directive or an assembly reference?)`

**Comment by Eric-EvilTwin** [comment]
@damews - That sounds like a nuget issue to me. Xamarin.Forms is not part of Xamarin.iOS or Xamarin.Android. I'd suggest checking your nuget references to Xamarin.Forms and your nuget restore step.

**Comment by David-Sobin** [comment]
Adding my frustration to the others:
Why was Xamarin removed from MacOS-13? 
We need Xamarin.iOS 16.4.0.23, the latest version, as well as the latest version of Xcode 15 on MaOS-13.
We need this well beyond end of May, when Microsoft ends support for Xamarin, because we will continue to create builds with Xamarin as we migrate to .NET iOS.

**Comment by veringm** [comment]
I also added the two lines, just "wrapped" it in a task, to align with the rest of my pipeline
```
  - task: PowerShell@2
    displayName: 'Install Xamarin.iOS package using Homebrew'
    inputs:
     targetType: inline
     script: brew install --cask xamarin-ios
  - task: PowerShell@2
    displayName: 'Install Xamarin.Android package using Homebrew'
    inputs:
     targetType: inline
     script: brew install --cask xamarin-android
```
Now the pipeline runs, and artifacts are working.

**Comment by nikamvd** [comment]
> FYI - I was able to get my builds working after changing to `vmImage: 'macos-13'` by just installing the casks and using my existing `NuGetCommand@2` and `XamariniOS@2` tasks
> 
> ```
>         - script: brew install --cask xamarin-ios
>           displayName: 'Install Xamarin.iOS package using Homebrew'
> 
>         - script: brew install --cask xamarin-android
>           displayName: 'Install Xamarin.Android package using Homebrew'
> ```

@Eric-EvilTwin If you don't mind, is it possible for you to share your yml file for reference. We are struggling to build our xamarin.forms project in azure devops using macOS-13 hosted agent.

**Comment by damews** [comment]
> > FYI - I was able to get my builds working after changing to `vmImage: 'macos-13'` by just installing the casks and using my existing `NuGetCommand@2` and `XamariniOS@2` tasks
> > ```
> >         - script: brew install --cask xamarin-ios
> >           displayName: 'Install Xamarin.iOS package using Homebrew'
> > 
> >         - script: brew install --cask xamarin-android
> >           displayName: 'Install Xamarin.Android package using Homebrew'
> > ```
> 
> Added these in my workflow but can't get a build to work with the `macos-13` runner. I also installed the vscode-for-mac using the example provided by @brunonocetti, but still not working. I'm getting these errors:
> 
> `The type or namespace name 'Forms' does not exist in the namespace 'Xamarin'` `The type or namespace name could not be found (are you missing a using directive or an assembly reference?)`

I had one step after these that was calling the select-xamarin-sdk-v2.sh script and doing another Xcode setup. After removing this step, it worked beautifully.

**Comment by hirandesai** [comment]
Hi All, 

I am facing similar error after moving to macos-13 image and I have clueless about how to fix this -
here I am attaching the pipeline code as reference -

```
pool:
  #vmImage: 'macOS-latest'
  vmImage: 'macOS-13'

steps:

- bash: 'brew install --cask xamarin-ios'
  displayName: 'Bash Install Xamarin IOS'

# Not sure if this step is required
- bash: 'curl https://download.visualstudio.microsoft.com/download/pr/3209737b-50b9-44e0-9331-9f7bdaf5fc15/57c31feafddb763141ff34353400e08a/visualstudioformacinstaller-17.6.0.73.dmg -o /tmp/vsformac.dmg'
  displayName: 'Download Visual Studio for Mac'

# Not sure if this step is required
- bash: 'hdiutil attach /tmp/vsformac.dmg'
  displayName: 'Mount Visual Studio for Mac dmg'

- task: ios-bundle-version@1
  inputs:
    sourcePath: Source/xxxx/xxxx/Info.plist
    versionCodeOption: 'buildid'
    versionName: '3.6.$(Build.BuildId)'
    versionCode: '$(Build.BuildId)'    
    printFile: true 

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: AppleCertificate.p12
    certPwd: $(P12Password)
    keychain: 'temp'
    deleteCert: false
  displayName: Install Apple Certificate

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '$(AppleProvisioningProfile)'
  displayName: 'Install Apple Provisioning Profile'    

# added because of error of missing project.assets.json, this wasn't in previous version macos-latest (maxos-12)
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Source/MobileOnly.sln'
    feedsToUse: 'select'
 
 # added this thinking it may solve error (because the previous version worked fine with nuget)
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.x'
  inputs:
    versionSpec: 5.x
    
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'Source/MobileOnly.sln'

- task: XamariniOS@2
  displayName: 'Build Xamarin.iOS project'
  inputs:
    solutionFile: 'Source/MobileOnly.sln'
    configuration: '$(BuildConfiguration)'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)' 
    args: '/p:Platform=iPhone /target:Build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: ' **/*.ipa'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'               

```

I am seeing following error -
```
error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)
```

In the csproj file, I can see the package reference -
![image](https://github.com/actions/runner-images/assets/18441068/f74be26c-dc59-494f-8815-0c4b704ecf23)
