### ISSUE TITLE
`colima start` no longer works on `macos-12` runner 20230812.3

### ISSUE THREAD

**Issue by joffrey-bion** [actions/runner-images#8104]
### Description

My docker setup action looks like this:

```yaml
      # Docker is not installed on GitHub's MacOS hosted workers due to licensing issues
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          
          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
```

This all worked correctly 5 hours ago:
https://github.com/joffrey-bion/chrome-devtools-kotlin/actions/runs/5882244388/job/15952382762

But right now the `colima start` command fails:
https://github.com/joffrey-bion/chrome-devtools-kotlin/actions/runs/5884334898/job/15960009886

```
time="2023-08-16T23:10:01Z" level=info msg="starting colima"
time="2023-08-16T23:10:01Z" level=info msg="runtime: docker"
time="2023-08-16T23:10:01Z" level=info msg="preparing network ..." context=vm
time="2023-08-16T23:10:01Z" level=info msg="creating and starting ..." context=vm
time="2023-08-16T23:10:01Z" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2023-08-16T23:10:01Z" level=info msg="Attempting to download the image" arch=x86_64 digest="sha512:f761b807fe9ba345968df72c07f8c5abcae0c4a44976fe5595c0ff748ef693841221a70e663986c700b027cea32b7cac24d5490d4c721593c39f2b8840c362a2" location="https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.5/alpine-lima-clm-3.18.0-x86_64.iso"
Downloading the image (alpine-lima-clm-3.18.0-x86_64.iso)

315.00 MiB / 315.00 MiB (100.00%) ? p/stime="2023-08-16T23:10:06Z" level=info msg="Downloaded the image from \"https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.5/alpine-lima-clm-3.18.0-x86_64.iso\""
time="2023-08-16T23:10:10Z" level=info msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/runner/.lima/colima/serial*.log\")"
time="2023-08-16T23:10:10Z" level=info msg="SSH Local Port: 49179"
time="2023-08-16T23:10:10Z" level=info msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
time="2023-08-16T23:10:10Z" level=info msg="[hostagent] Driver stopped due to error: \"exit status 255\""
time="2023-08-16T23:10:10Z" level=info msg="[hostagent] Shutting down the host agent"
time="2023-08-16T23:10:10Z" level=warning msg="[hostagent] failed to exit SSH master"
time="2023-08-16T23:10:10Z" level=info msg="[hostagent] Shutting down QEMU with ACPI"
time="2023-08-16T23:10:10Z" level=warning msg="[hostagent] failed to open the QMP socket \"/Users/runner/.lima/colima/qmp.sock\", forcibly killing QEMU"
time="2023-08-16T23:10:10Z" level=info msg="[hostagent] QEMU has already exited"
time="2023-08-16T23:10:10Z" level=fatal msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/Users/runner/.lima/colima/ha.stderr.log\")"
time="2023-08-16T23:10:10Z" level=fatal msg="error starting vm: error at 'creating and starting': exit status 1"
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner image: macos-12
Runner version: 20230812.3

https://github.com/joffrey-bion/chrome-devtools-kotlin/actions/runs/5884334898/job/15960009886

### Is it regression?

Yes, it worked in 20230803.1 (earlier today)

### Expected behavior

`colima start` succeeds and I can use the docker CLI.

### Actual behavior

`colima start` fails with `[hostagent] failed to open the QMP socket \"/Users/runner/.lima/colima/qmp.sock\", forcibly killing QEMU`

### Repro steps

Use a workflow with an action like this to setup docker and colima:

```yaml
      # Docker is not installed on GitHub's MacOS hosted workers due to licensing issues
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          
          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
```
