### ISSUE TITLE
[iTMSTransporter] sh: /Applications/Transporter.app/Contents/itms/bin/iTMSTransporter: No such file or directory

### ISSUE THREAD

**Issue by vhsantos26** [actions/runner-images#8127]
### Description

We moved from AWS EC2 Runners to GitHub Runners and, using the current [MacOS latest runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md), when we try to run the fastlane testflight action to deploy the IPA to the AppStore, we get the following error: 

```
[17:02:23]: [iTMSTransporter] sh: /Applications/Transporter.app/Contents/itms/bin/iTMSTransporter: No such file or directory

[17:02:23]: iTunes Transporter output above ^
[17:02:23]: The call to the iTMSTransporter completed with a non-zero exit status: 127. This indicates a failure.
[17:02:23]: Password contains special characters, which may not be handled properly by iTMSTransporter. If you experience problems uploading to App Store Connect, please consider changing your password to something with only alphanumeric characters.
[17:02:23]: Could not download/upload from App Store Connect! It's probably related to your password or your internet connection.
```

Looks like the Transporter is not installed by default, or we are not using the correct path of it, is there any ideal to solve this?

Fastlane action executed:

```ruby
desc "Testflight Deployment"
lane :deploy do
  testflight(
    api_key: get_app_store_connect_api_key,
    ipa: "./Mobile.ipa",
    apple_id: ENV["APPLE_APP_ID"],
    skip_waiting_for_build_processing: true
  )
end
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230812.3

### Is it regression?

No

### Expected behavior

When the Fastlane action testflight is executed, as the runner have the Transporter installed, the deployment must happen successfully.

### Actual behavior

Getting the error `[iTMSTransporter] sh: /Applications/Transporter.app/Contents/itms/bin/iTMSTransporter: No such file or directory`

### Repro steps

Run the workflow that deploys an IPA to the AppStore Connect like this

```yaml
      - run: bundle exec fastlane deploy
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APPLE_APP_ID: ${{ secrets.APPLE_APP_ID }}
          FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT: 1
          FASTLANE_ITUNES_TRANSPORTER_PATH: /Applications/Transporter.app/Contents/itms
```

Where the Fastlane action is:

```ruby
desc "Testflight Deployment"
lane :deploy do
  testflight(
    api_key: get_app_store_connect_api_key,
    ipa: "./Mobile.ipa",
    apple_id: ENV["APPLE_APP_ID"],
    skip_waiting_for_build_processing: true
  )
end
```
