### ISSUE TITLE
Unable to build .NET apps after using UseDotNet

### ISSUE THREAD

**Issue by mattleibow** [actions/runner-images#8137]
### Description

I have a simple pipeline, install dotnet, install workloads, build a project. However, this does not work:

https://github.com/mattleibow/DevOpsTesting/blob/test/dotnet/azure-pipelines.yml

The result is that once I install .NET, then nothing works:

https://dev.azure.com/mattleibow/OpenSource/_build/results?buildId=681&view=results

`dotnet build` works, but not `msbuild`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Starting: Initialize job
Agent name: 'Azure Pipelines 3'
Agent machine name: 'fv-az623-962'
Current agent version: '3.224.1'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20230804.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20230804.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230804.1
Runner Image Provisioner
2.0.266.1
Current image version: '20230804.1.0'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: UseDotNet (2.226.0)
Downloading task: PowerShell (2.226.1)
Downloading task: MSBuild (1.217.0)
Downloading task: PublishPipelineArtifact (1.199.0)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
   Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
Finished checking job knob settings.
Plugin: 'Test Result Parser plugin' is running in background.
Plugin: 'Test File Publisher plugin' is running in background.
Start tracking orphan processes.
Finishing: Initialize job

### Is it regression?

Yes

### Expected behavior

I can build using msbuild

### Actual behavior

I connot build using msbuild

### Repro steps

Copy the few lines of yaml. I create the app in the yaml, so it is nothing extra. But here it is for simplicity:

```
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: 7.0.x
      - pwsh: |
          dotnet workload install maui
          dotnet new android -o TestAndroidApp
          dotnet build TestAndroidApp
      - task: MSBuild@1
        inputs:
          solution: ./TestAndroidApp/TestAndroidApp.csproj
          msbuildArguments: /restore
```
