### ISSUE TITLE
Conan can't find MSVC compiler with 20230820.1.0 version of windows-2022

### ISSUE THREAD

**Issue by ssrobins** [actions/runner-images#8176]
### Description

The issue described in https://github.com/actions/runner-images/issues/7741 has returned and since I wasn't able to re-open that issue, I'm logging a new one.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image version: 20230820.1.0
https://github.com/ssrobins/sdl2-example/actions/runs/5994323841/job/16255797098

### Is it regression?

Yes, it worked with `20230804.1.0`: https://github.com/ssrobins/sdl2-example/actions/runs/5986066326/job/16238788843

### Expected behavior

I expect CMake to find the MSVC compiler.

### Actual behavior

It fails to find the compiler:

```
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_C_COMPILER could be found.
CMake Error at CMakeLists.txt:6 (project):
  No CMAKE_CXX_COMPILER could be found.
-- Configuring incomplete, errors occurred!
```

### Repro steps

I distilled this down to a simple set of repro steps in the form of GitHub Actions script:
https://github.com/ssrobins/actions-fiddling/tree/missing_compiler
https://github.com/ssrobins/actions-fiddling/actions/runs/5995611589/job/16258891554

```
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        run: |
          pip3 install conan --upgrade
          conan profile detect

      - name: Conan install compiler.update=6
        run: conan install --requires=fmt/9.1.0 --build=missing -s compiler=msvc -s compiler.version=193 -s compiler.update=6
```
