### ISSUE TITLE
runner images: add Debian / Devuan

### ISSUE THREAD

**Issue by metux** [actions/runner-images#8183]
### Tool name

runner image: Debian / Devuan

### Tool license

GPL

### Add or update?

- [X] Add
- [ ] Update

### Desired version

stable and testing

### Brief description of tool

Please add Debian / Devuan runner images, so we can build and test packages for these distros directly.
The provisioning shouldn't differ so much.

It would be great to to have both stable and testing branches available.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

yes (but dont know how to test it yet)

**Comment by vpolikarpov-akvelon** [comment]
Thank you for reaching out to us with your request to add support for the Devuan OS to GitHub Actions. We appreciate your interest in improving our platform.

However, we will not be able to accommodate this request. We understand the importance of providing a wide range of options to our users, but Devuan OS is indeed a niche operating system with limited usage in the broader developer community. Introducing support for it could potentially increase operational complexities and may require significant maintenance efforts, which may divert resources from other critical aspects of the system.

However, I would like to offer some alternatives that may still allow you to achieve your goals. You can consider using Docker images or self-hosted runners to run your CI/CD pipelines with Devuan OS. Docker containers, in particular, provide a flexible and isolated environment that can be tailored to your specific needs. By leveraging these technologies, you can have greater control over your build and test environments without the need for extensive integration into GitHub Actions.

**Comment by metux** [comment]
Hi,

> However, we will not be able to accommodate this request. We understand the importance of providing a wide range of options to our users, but Devuan OS is indeed a niche operating system with limited usage in the broader developer community.

would you perhaps consider Debian - that's obviously far from niche, actually one of the oldest still active and most used distros.

thx-

--mtx

**Comment by vpolikarpov-akvelon** [comment]
Unfortunately, there are no plans to host runners based on Linux distros other then Ubuntu. Sorry for that.

**Comment by ilia-shipitsin** [comment]
@metux ,  did you consider containers ?

for example

```
name: CI

# Controls when the workflow will run
on: [ push, pull_request,  workflow_dispatch ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
     image: debian:bookworm

    steps:
      - uses: actions/checkout@v3

      - name: Install lsb_release
        run: |
          apt-get update
          apt install lsb-release

      - name: run lsb_release
        run: |
          lsb_release -a
      ```


displays debian

![image](https://github.com/actions/runner-images/assets/125650415/a299576b-7674-482c-9b63-4755ccaf3c81)
