### ISSUE TITLE
Hang when trying to build Ubuntu 22.04 image

### ISSUE THREAD

**Issue by nnellanspdl** [actions/runner-images#8192]
### Description

Hi team,

I am using an Azure DevOps Pipeline to run the `GenerateResourcesAndImages.ps1` script to build an Ubuntu 22.04 image.

I'm getting hung up when the script runs the file `/scripts/installers/git.sh`.  Here are the final lines of output:

```
    azure-arm.build_vhd: Downloading 'https://github.com/mislav/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz' to '/tmp/hub/hub-linux-amd64-2.14.2.tgz'...
    azure-arm.build_vhd: Download completed
==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.build_vhd: Step "StepProvision" failed
```

After this, it simply hangs here until the Azure DevOps Pipelines job times out.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

refs/tags/ubuntu22/20230821.1

### Is it regression?

Unsure

### Expected behavior

The script to complete successfully

### Actual behavior

The git.sh script hangs and the process does not advance after that.

### Repro steps

Simply run the `GenerateResourcesAndImage` script.

**Comment by vpolikarpov-akvelon** [comment]
Hey @nnellanspdl. Thank you for reporting. Are you trying to build new pipeline for image generation from scratch or did you have this pipeline working before but it have broken recently? And may I also ask you to share you pipeline definition so we understand how exactly generation is being started?

**Comment by nnellanspdl** [comment]
This pipeline has successfully built older versions of the image.  Here is the relevant snippets from my pipeline.

```yaml
resources:
  repositories:
    - repository: runner-images
      type: github
      name: actions/runner-images
      ref: refs/tags/ubuntu22/20230821.1

stages:
- stage:
  displayName: 'Build Image using GitHub Scripts'
  jobs:
  - job:
    timeoutInMinutes: 360
    steps:
    - checkout: self
    - checkout: runner-images
    - task: AzureCLI@2
      env:
        VNET_RESOURCE_GROUP: $(packerVnetResourceGroup)
        VNET_NAME: $(packerVnet)
        VNET_SUBNET: $(packerSnet)
      inputs:
        connectedServiceNameARM: $(packerServiceConnection)
        addSpnToEnvironment: true
        scriptType: pscore
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/runner-images
        powerShellErrorActionPreference: SilentlyContinue
        failOnStandardError: false
        powerShellIgnoreLASTEXITCODE: true
        inlineScript: |

          Write-Output "Building the image"
          Import-Module ./helpers/GenerateResourcesAndImage.ps1
          GenerateResourcesAndImage `
            -SubscriptionId $(packerSubscriptionId) `
            -ResourceGroupName "$(packerResourceGroup)" `
            -ImageType $(packerImageType) `
            -AzureLocation "$(packerRegion)" `
            -AzureClientId $env:servicePrincipalId `
            -AzureClientSecret $env:servicePrincipalKey `
            -AzureTenantId $env:tenantId `
            -Force `
            -EnableHttpsTrafficOnly $true
```
