### ISSUE TITLE
Windows 2022 - Deployed image gets stuck at "creating" and packer outputs "IMAGE_STATE_UNDEPLOYABLE"

### ISSUE THREAD

**Issue by rybal06** [actions/runner-images#8319]
### Description

When using packer (from this repo, version 20230910.1.0) to build windows server 2022 images, packer reports success and produces an image; however when deploying a virtual machine or vmss instance from the image, it gets stuck at "creating" status within Azure.

In a troubleshooting attempt, I modified windows2022.json to remove all provisioners except for the final sysprep generalize command, and we are able to deploy VM/VMSS from the image as expected.

I modified the build script to add a known password rather than the random UUID so I could log into the VM/VMSS which is stuck at "creating" to do more troubleshooting.

As this works when I remove all provisioners except the final sysprep; it seems like some provisioner is causing the windows2022 image is causing VM / VMSS instance creation to fail?

I attached the sysprep and waagent log files from C:\Windows\Panther but I am not seeing anything out of the ordinary.
[wasetup.log](https://github.com/actions/runner-images/files/12653171/wasetup.log)
[setuperr.log](https://github.com/actions/runner-images/files/12653172/setuperr.log)
[setupact.log](https://github.com/actions/runner-images/files/12653173/setupact.log)

Note: this image was built on 9/15; and linked to a VMSS deployed on 9/18.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230910.1.0

### Is it regression?

No

### Expected behavior

A VM / VMSS is deployed from an image produced by windows2022.json works successfully. 

### Actual behavior

A VM/VMSS deployed from an image produced by windows2022.json gets stuck at "Creating" status in Azure and never deploys.

## Not working (leave all provisioners in-tact)
1. Build packer image from windows2022.json inside of this repository. Note the packer output shows "azure-arm.image: IMAGE_STATE_UNDEPLOYABLE"
2. Attempt to deploy a VM/VMSS using the resulting packer image from windows2022.json.
3. Observe it is stuck at creating.

## Working (remove all provisioners except for sysprep)
1. Checkout this repo, and modify windows2022.json. 
2. Remove all from the provisioners block except for: 
```json
        {
            "type": "powershell",
            "inline": [
                "if( Test-Path $Env:SystemRoot\\System32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\System32\\Sysprep\\unattend.xml -Force}",
                "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /mode:vm /quiet /quit",
                "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
            ]
        }
```
3. Build packer image
4. Link to a VMSS or VM. Note it does not get stuck at "Creating" phase.

**Comment by rybal06** [comment]
[packer.log](https://github.com/actions/runner-images/files/12653715/packer.log)

Packer log output showing:
"azure-arm.image: IMAGE_STATE_UNDEPLOYABLE"

**Comment by rybal06** [comment]
I have a theory, I noticed someone enabled some of the defender options on our subscription and suspect they may be interfering with provisioning. I am going to trigger a build into a different subscription overnight and will update this issue with my findings.

**Comment by rybal06** [comment]
That was the issue. I added this to our pipeline in case someone enables this again. I was going to add this to this repo but noticed this repo doesn't have any dependency on the Az PowerShell module and is passing clientID and client secret directly rather than using a service connection so this would need a slightly different approach.

```yaml
  - task: AzurePowerShell@5
    displayName: 'Ensure security agent autoprovisioning is disabled'
    inputs:
      azureSubscription: ${{ parameters.service_connection_name }}
      pwsh: true
      azurePowerShellVersion: 'LatestVersion'
      ScriptType: 'InlineScript'
      Inline: |
        if ((Get-AzSecurityAutoProvisioningSetting).AutoProvision -eq 'On') {
          Write-Error 'Azure Defender for VMs may interfere with packer VM build and capture processes. `
          Please disable autoprovisioning of defender components in the the subscription $(AZURE_SUBSCRIPTION) or select a different subscription.' -ErrorAction:Stop
        }
        else {
          Write-Host 'Azure Defender for VM autoprovisioning is disabled. Continuing with Packer build using subscription $(AZURE_SUBSCRIPTION).'
        }
```
