### ISSUE TITLE
FE instance being tested makes GET request that returns HTTP 413 

### ISSUE THREAD

**Issue by oscarcalderonc** [actions/runner-images#8321]
### Description

I have the following GH action configuration:

```
 test-cypress:
    # skip build if [skip-ci] in commit.
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup
        run: npm ci
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          SKIP_PREFLIGHT_CHECK: true
          CYPRESS_AUTH_USERNAME: ${{ secrets.CYPRESS_AUTH_USERNAME }}
          CYPRESS_AUTH_PASSWORD: ${{ secrets.CYPRESS_AUTH_PASSWORD }}
        with:
          browser: chrome
          start: npm run start
          project: ./packages/portal
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 240
      - name: Upload cypress video if test fails
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: packages/portal/cypress/videos
          if-no-files-found: ignore
```

This spins up the frontend, which connects to a backend that is running in an AWS EC2 instance it has access to. It has been running fine during the last 2 months, then suddenly the requests to the backend return an HTTP 413 error for a simple GET request that returns a JSON array with 10 items. Also it is a GET request so no payload being sent to the server.

So my tests are failing now. I already looked at the logs of my backend and it doesn't even get reached, so it seems something could be blocking the requests and returning 413. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-latest

### Is it regression?

No

### Expected behavior

To get my frontend running to make successful requests to backend outside GH as it was doing before

### Actual behavior

Requests aren't making it outside the GH action and getting HTTP 413 error instead

### Repro steps

1. To run the github action using the workflow configuration above
