### ISSUE TITLE
Select specific Xcode version in workflow

### ISSUE THREAD

**Issue by salvatoreboemia** [actions/runner-images#8340]
### Description

Hi everyone,

do you know how to specify a specific version of Xcode using a specific macOS version?

I'll explain better

This is my workflow that reads a variable, in addition to this I would like to specify the version of Xcode to use

```
jobs:
  myJobs:
    uses: myFile.yml
    with: 
      macos-version: ${{ vars.MACOSVERSION}}
      branch: myBranch
```

Current _MACOSVERSION_ -> macos-12-xl

Is it possibile in easy way?

Thanks

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-12-xl

### Is it regression?

no

### Expected behavior

I want to use specific version of xcode

### Actual behavior

Not possible to use specific version of xcode

### Repro steps

No step
