### ISSUE TITLE
windows-2022 image 20230918.1.0 removed the "ninja" tool

### ISSUE THREAD

**Issue by mstorsjo** [actions/runner-images#8343]
### Description

The "ninja" tool used to be available in the windows-2022 images, but since 20230918.1.0 it no longer is.

It wasn't part of the official list of provided tools, but as it was available out of the box, CI scripts have come to rely on it. It used to be available as `C:\ProgramData\Chocolatey\bin\ninja.exe`.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/mstorsjo/llvm-mingw/actions/runs/6242492372/job/16957853448

### Is it regression?

Yes, regression from 20230910.1.0

### Expected behavior

As running the command "ninja" has worked in earlier runs with windows-2022, and there hasn't been any explicit intent to remove it, it should remain available.

https://github.com/mstorsjo/llvm-mingw/actions/runs/6242492372/job/16957852949 shows a successful build with windows-2022 image 20230910.1.0, where ninja is available.

### Actual behavior

Actual runs with image version 20230918.1.0 fail to find the "ninja" tool.

### Repro steps

Run a workflow that looks like this:
```
name: Builds
on:
  push:

jobs:
  check-ninja:
    runs-on: windows-2022
    steps:
      - name: Locate ninja
        shell: cmd
        run: |
          where ninja
```
