### ISSUE TITLE
OpenSSL seems no longer present on Windows runners

### ISSUE THREAD

**Issue by thomwiggers** [actions/runner-images#8344]
### Description

In spite of or because of cd9413ee05db8f0e3f05402091cedf54e060542a, my builds that use runner version 20230918.1.0 can't find OpenSSL anymore: see, for example: https://github.com/open-quantum-safe/liboqs-rust/actions/runs/6249790685/job/16968399712

The previous build, which used runner version 20230910.1.0 did pass: https://github.com/open-quantum-safe/liboqs-rust/actions/runs/6249784193/job/16967229587

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230918.1.0

https://github.com/open-quantum-safe/liboqs-rust/actions/runs/6249790685/job/16968399712

### Is it regression?

20230910.1.0

### Expected behavior

Find OpenSSL in `C:\Program Files\OpenSSL`

### Actual behavior

Can't find OpenSSL

### Repro steps

1. don't change anything
2. github breaks your CI

**Comment by erik-bershel** [comment]
Hey @thomwiggers!
It's a bit another issue to fix. `OpenSSL` is on the correct place. Your build failures is more related to the `OpenSSL` version. Accidentally we got `light` but not regular.
We'll fix it in the next release.

**Comment by xanather** [comment]
Oh god I wasted 2 days on this thinking it was an internal configuration change, I'm an enterprise customer.

This makes me loose trust in GitHub provider runners, when will the fix be available?

**Comment by sanikolaev** [comment]
BTW the known workaround is to add this step into your Windows job:
```
      - name: Install OpenSSL
        run: powershell.exe ./.github/workflows/Install-OpenSSL.ps1
```

where `./.github/workflows/Install-OpenSSL.ps1` is a copy of https://github.com/ilia-shipitsin/runner-images/blob/b0381c354e34a74b8a62cc07ffbcbddae01a0ca0/images/win/scripts/Installers/Install-OpenSSL.ps1

**Comment by codybak4** [comment]
Ok thank you I will fix I am not a bot signing @codybak4 / GitHub / mobile
Mac OS

**Comment by nyurik** [comment]
In my Windows CI, I use this step. I wonder if this can be included in the image?

```yaml
      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md
```
