### ISSUE TITLE
Regression in windows-2022: `pkg-config` no longer finds a `pacman`-installed ICU library

### ISSUE THREAD

**Issue by andreasabel** [actions/runner-images#8412]
### Description

Concerns: windows-2022
Works in: 20230918.1.0
- E.g. 2023-09-27 https://github.com/agda/agda/actions/runs/6327426841/job/17183238978#step:8:2

Fails in:  20230924.1.0
- Reproducer: https://github.com/andreasabel/gha-test/actions/runs/6348182406/job/17244347646
- In the wild: 2023-09-28 https://github.com/agda/agda/actions/runs/6331284970/job/17195536846#step:8:1

Problem: The following steps used to install the ICU library so that `pkg-config --modversion icu-i18n` could find it.
https://github.com/andreasabel/gha-test/actions/runs/6348182406/job/17244347646#step:2:2
```pwsh
$env:PATH = "C:\msys64\usr\bin;$env:PATH"
pacman --noconfirm -Sy mingw-w64-x86_64-icu
echo "C:\msys64\mingw64\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
```
Now, after these steps:
- ICU packages are not listed under `pkg-config --list-all`
  https://github.com/andreasabel/gha-test/actions/runs/6348182406/job/17244347646#step:3:1
- `pkg-config --modversion icu-i18n` errors
  https://github.com/andreasabel/gha-test/actions/runs/6348182406/job/17244347646#step:4:2

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

See above.

### Is it regression?

Yes, see above.

### Expected behavior

See above.

### Actual behavior

See above.

### Repro steps

See above.

**Comment by andreasabel** [comment]
I am a bit surprised the same problem does not show here: https://github.com/haskell/text-icu/actions/runs/6341763757/job/17226111909#step:5:2
```yaml
    - name: Setup MSYS path for pkg-config
      run: |
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

    - name: Install the ICU library (Windows)
      run: |
        $env:PATH = "C:\msys64\usr\bin;$env:PATH"
        pacman --noconfirm -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-icu

    - name: Determine the ICU version
      shell: bash
      run: |
        ICU_VER=$(pkg-config --modversion icu-i18n)
        echo "ICU_VER=${ICU_VER}"
```

**Comment by vpolikarpov-akvelon** [comment]
Hey @andreasabel. I've looked into your issue, and it doesn't seem to be a runner regression.

When I compared the working workflow with your "reproducer", I noticed that you forgot to install the `mingw-w64-x86_64-pkg-config` package. While there is a `pkg-config` in the `PATH`, it's related to a different package. To make it work within msys64, you'll need to install `mingw-w64-x86_64-pkg-config` manually using `pacman`. Additionally, you should add `C:\msys64\mingw64\bin` to your `PATH` variable.

Here's an example of a working workflow:

```yaml
- name: Add mingw64 to PATH
  shell: pwsh
  run: |
    echo "C:\msys64\mingw64\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append
- name: Install MinGW and ICU library
  shell: pwsh
  run: |
    $env:PATH = "C:\msys64\usr\bin;$env:PATH"
    pacman --noconfirm -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-icu
- name: Verify ICU library
  shell: pwsh
  run: |
    pkg-config --modversion icu-i18n
```
