### ISSUE TITLE
macos-latest-xlarge breaks setup-ruby action

### ISSUE THREAD

**Issue by andreiz** [actions/runner-images#8455]
### Description

Post announcement of M1 runners being available yesterday, I updated my action to use `runs-on: macos-latest-xlarge`. First of all, links in the `Runner Image` part of job setup are broken:

```
Runner Image
  Image: macos-13
  Version: 20230924.3
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20230924.3/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230924.3
```

Also, the `setup-ruby` is now broken.

```
Run ruby/setup-ruby@v1.154.0
  
Error: The current runner (macos-13-arm64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230924.3

### Is it regression?

No

### Expected behavior

`setup-ruby` action proceeds normally

### Actual behavior

`setup-ruby` action fails

### Repro steps

```
   runs-on: macos-latest-xlarge

    steps:

      - name: Check out
        uses: actions/checkout@v3.3.0

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1.154.0
        with:
          ruby-version: '3.0'
```
