### ISSUE TITLE
Xcode 14.3.0 is missing

### ISSUE THREAD

**Issue by iosdevben** [actions/runner-images#8458]
### Description

Our team needs Xcode 14.3.0 but it seems to be missing from the macOS 13 runner.

Below is the output from my action.

As you can see, where are asking for 14.3, but we're getting 14.3.1.

>Run sudo xcode-select -switch /Applications/Xcode_"$XCODE_VERSION".app
  sudo xcode-select -switch /Applications/Xcode_"$XCODE_VERSION".app
  xcodebuild -version
  shell: /bin/bash -e {0}
  env:
    SCHEME: GlobalCommunicationPlatform
    SDK_VERSION: 16.4
    XCODE_VERSION: 14.3
    DEVICE: iPhone 14 Pro
Xcode 14.3.1
Build version 14E300c

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230924.1

### Is it regression?

Yes. I don't know when this started happening.

### Expected behavior

Xcode 14.3.0 should be executed.

### Actual behavior

Xcode 14.3.1 is executed.

Due to prebuilt dependencies, we need 14.3.0.

### Repro steps

Try using the following GitHub Action:

```
name: Run unit tests

on: [pull_request]

env:
  SCHEME: "GlobalCommunicationPlatform"
  SDK_VERSION: "16.4"
  XCODE_VERSION: "14.3"
  DEVICE: "iPhone 14 Pro"

jobs:
  test:
    runs-on: macos-13
    
    concurrency: # used to cancel previous runs if there is any in progress
      group: ${{ github.head_ref }}
      cancel-in-progress: true

    steps:

    - name: Select Xcode Version
      run: |
        sudo xcode-select -switch /Applications/Xcode_"$XCODE_VERSION".app
        xcodebuild -version
```
