### ISSUE TITLE
Update terraform to 1.6.1

### ISSUE THREAD

**Issue by DenisBalan** [actions/runner-images#8502]
### Description

in `ubuntu-latest` terraform points to `1.6.0`
and its full of different flavours of bugs.
in `1.6.1` they were fixed.

Please updated asap and remove any reference of terraform `1.6.0`

https://github.com/hashicorp/terraform/issues/34024
closure: https://github.com/hashicorp/terraform/issues/33977

Thanks.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

not public

### Is it regression?

Ubuntu 20.04

### Expected behavior

no bug / no crash

### Actual behavior

please just update your image to include tf `1.6.1` instead of `1.6.0`

### Repro steps

pipeline, terraform init, terraform plan
main.tf
```hcl
locals {
  password = sensitive("abc")
}

resource "random_password" "test" {
  length = 3
}

import {
  to = random_password.test
  id = local.password  # crashes as well with `id = sensitive("abc")`
}
```

as per https://github.com/hashicorp/terraform/issues/33977

**Comment by vpolikarpov-akvelon** [comment]
Hey @DenisBalan, thank you for highlighting that. We install the latest release of Terraform every time image is built and current Ubuntu 22.04 runner image (`20231001.1.0`) includes Terraform 1.5.7 that is stable. As 1.6.1 haven't been released yet we will track Terraform updates in order to keep everything as smooth as possible.

**Comment by DenisBalan** [comment]
@vpolikarpov-akvelon not really sure documentation reflects reality, this one https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md it says `1.5.7` but thats not true.

No manual installation of any dependency is done.
Those are the tasks and output of `terraform version`
![image](https://github.com/actions/runner-images/assets/33955091/2ac3cb05-9553-46f9-9348-39373305ba4e)
![image](https://github.com/actions/runner-images/assets/33955091/ea1e0ec8-3fa6-4e09-86c6-34f340787abe)

```
...
      steps:
        - checkout: self
          persistCredentials: true
            
        - task: Bash@3
          displayName: "terraform version"
          inputs:
            targetType: inline
            failOnStderr: true
            script: |
              /usr/local/bin/terraform version
...
```
And ultimately
![image](https://github.com/actions/runner-images/assets/33955091/2e31ef87-399f-4e69-a60c-61d2f6581089)

Anyway waiting for `1.6.1` to be embedded into `ubuntu-latest`
