### ISSUE TITLE
Update/Add Visual Studio for Mac 13 image

### ISSUE THREAD

**Issue by thefex** [actions/runner-images#8528]
### Tool name

Visual studio for Mac

### Tool license

https://visualstudio.microsoft.com/license-terms/visual-studio-mac-eula/

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest stable channel

### Brief description of tool

Github mac13 runners miss Visual studio for mac which prevents building Xamarin.iOS/Android apps that are still supported till April of next year.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
I am not sure.
```

**Comment by mikhailkoliada** [comment]
Hello! VS for Mac is going to be completely retired by August 31 2024, see [here](https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022), we are also aware that Xamarin components will be retired next April, so it was decided that neither Xamarin nor VSMAC will be pre-installed in the runner starting with macOS 13.

**Comment by JohnHDev** [comment]
> Hello! VS for Mac is going to be completely retired by August 31 2024, see [here](https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022), we are also aware that Xamarin components will be retired next April, so it was decided that neither Xamarin nor VSMAC will be pre-installed in the runner starting with macOS 13.

Xamarin has been updated to support Xcode 15 and is a fallback position if developers have not successfully migrated from Xamarin to .NET MAUI by 1st May 2024. To build for Xcode 15 we will need macOS-13 updated with Xamarin symlinks.

We are your paying customers, please listen to us. I pay for a single pipeline for my hobby projects, the company I work for pays for 20 concurrent build hosts.

**Comment by janwiebe-jump** [comment]
@JohnHDev  See https://github.com/actions/runner-images/issues/8320#issuecomment-1736578220

I have used boots to install the latest Xamarion.iOS version on a Mac OS 13 image (in an Azure DevOps runner):


```   
 - script: |
        dotnet tool install --global boots
        boots https://download.visualstudio.microsoft.com/download/pr/de7f727f-243c-4429-8773-eebd735eb1bb/da4a65f27ace7f805914ef63661e0efd/xamarin.ios-16.4.0.18.pkg
   displayName: Install Xamarin.iOS
```

**Comment by thefex** [comment]
VS for mac is not necessary, xamarin ios and android should be sufficient

**Comment by v0idzz** [comment]
For anyone interested in building C# 10 apps with the Visual Studio provided MSBuild, I've implemented a workaround in my project which extracts the MonoBundle from VS for Mac installer and then uses it to build the app: https://github.com/Vulcanova/Vulcanova/blob/main/.github/workflows/ios.yml#L21

**Comment by softlion** [comment]
> For anyone interested in building C# 10 apps with the Visual Studio provided MSBuild, I've implemented a workaround in my project which extracts the MonoBundle from VS for Mac installer and then uses it to build the app: https://github.com/Vulcanova/Vulcanova/blob/main/.github/workflows/ios.yml#L21
> 
> ```yaml
>       - name: Download Visual Studio for Mac
>         run: curl https://download.visualstudio.microsoft.com/download/pr/ceb0ea3f-4db8-46b4-8dc3-8049d27c0107/91eb158e928097dcb6e42ece2db7ebac/visualstudioformac-17.6.7.417-arm64.dmg -o /tmp/vsformac.dmg
>       
>       - name: Mount Visual Studio for Mac dmg
>         run: hdiutil attach /tmp/vsformac.dmg
>       
>       - name: Extract MSBuild
>         run: cp -R /Volumes/Visual\ Studio/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin /tmp/msbuild
> ```
> 
> then, to build the app:
> 
> ```yaml
>       - name: Build
>         run: mono '/tmp/msbuild/MSBuild.dll' <your_csproj>
> ```

Where did you get the dl link I would like to update it ?

**Comment by v0idzz** [comment]
I believe I set up a proxy to monitor the installer’s network traffic.On 25 Mar 2024, at 15:34, ZeBen ***@***.***> wrote:﻿

For anyone interested in building C# 10 apps with the Visual Studio provided MSBuild, I've implemented a workaround in my project which extracts the MonoBundle from VS for Mac installer and then uses it to build the app: https://github.com/Vulcanova/Vulcanova/blob/main/.github/workflows/ios.yml#L21
      - name: Download Visual Studio for Mac
        run: curl https://download.visualstudio.microsoft.com/download/pr/ceb0ea3f-4db8-46b4-8dc3-8049d27c0107/91eb158e928097dcb6e42ece2db7ebac/visualstudioformac-17.6.7.417-arm64.dmg -o /tmp/vsformac.dmg
      
      - name: Mount Visual Studio for Mac dmg
        run: hdiutil attach /tmp/vsformac.dmg
      
      - name: Extract MSBuild
        run: cp -R /Volumes/Visual\ Studio/Visual\ Studio.app/Contents/MonoBundle/MSBuild/Current/bin /tmp/msbuild
then, to build the app:
      - name: Build
        run: mono '/tmp/msbuild/MSBuild.dll' <your_csproj>

Where did you get the dl link I would like to update it ?

**Comment by softlion** [comment]
@v0idzz I fixed your version, as this issue will never be resolved. The path you used is incorrect.  
This is what has worked for me.

So the whole idea is to use the macos13 image in order to get xcode 15 and get rid of the appstore warning.  
(The "latest" image is macos12 with xcode 14 only).

The macos13 image does not have VS Mac pre-installed. And does not contain any xamarin sdk.  
So we install the xamarin sdk via boots.  

But that is insufficient. We also need msbuild from VsMac. That is because msbuild from mono is too old and don't understand xcode 15.

```yaml
pool:
  vmImage: 'macos-13'

- task: Bash@3
  displayName: Install VS Mac 2022 MsBuild
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: |
      echo "downloading"
      curl -L "https://download.visualstudio.microsoft.com/download/pr/ceb0ea3f-4db8-46b4-8dc3-8049d27c0107/91eb158e928097dcb6e42ece2db7ebac/visualstudioformac-17.6.7.417-arm64.dmg" -o "/tmp/vsformac.dmg" 2>/dev/null
      echo "attaching"
      hdiutil attach "/tmp/vsformac.dmg" -noverify 2>/dev/null
      echo "copying"
      mkdir "/tmp/msbuild"
      cp -R "/Volumes/Visual Studio/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin" "/tmp/msbuild"
      ls -alF "/tmp/msbuild/bin"
      echo "done"

- task: Bash@3
  displayName: Install Xamarin.iOS
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: |
      dotnet tool install --global boots
      boots --stable Xamarin.Android
      boots --stable Xamarin.iOS

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Store.p12'
    certPwd: '$(CERT_PASSWORD)'
    keychain: 'temp'

- task: InstallAppleProvisioningProfile@1
  displayName: 'InstallAppleProvisioningProfile'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/release/pro/store')
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'AppStore.mobileprovision'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: ">=6.7.0"

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(Build.SourcesDirectory)/YourSolution.sln'
    feedsToUse: config

- task: Bash@3
  displayName: 'Build iOS IPA'
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: |
      signIdentityEscaped=$(echo "$APPLE_CERTIFICATE_SIGNING_IDENTITY" | sed 's/,/%2C/g')

      cmd='
      /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono
        "/tmp/msbuild/bin/MSBuild.dll"
        "'"$(Build.SourcesDirectory)"'/YourSolution.sln"
        /t:Build
        /p:Configuration=Release
        /p:Platform=iPhone
        /p:buildForSimulator=false
        /p:BuildIpa=true
        /p:Codesignkey="'"$signIdentityEscaped"'"
        /p:CodesignProvision='"$APPLE_PROV_PROFILE_UUID"'
      '
      
      echo $cmd
      eval $cmd

- task: AppCenterDistribute@3
  displayName: 'Post IPA and Symbols to appcenter distribute'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/release/pro/store')
  inputs:
    serverEndpoint: 'Your AppCenter Endpoint See Task Doc'
    destinationType: 'store'
    destinationStoreId: '$(APPCENTER_STOREID)'
    appSlug: 'YourCompany/$(APPCENTER_SLUG)'
    app: 'YourApp/YourApp.iOS/bin/iPhone/Release/YourAPpiOS.ipa'
    symbolsType: Apple
    dsymPath: 'YourApp/WYourApp.iOS/bin/iPhone/Release/YourAppiOS.app.dSYM'
    releaseNotesSelection: 'input'
    releaseNotesInput: 'Updates to our mobile app'
```
