### ISSUE TITLE
[Windows] Update Service (wuauserv) is automatically re-enabled

### ISSUE THREAD

**Issue by mschfh** [actions/runner-images#8599]
### Description

The Windows Update Service (`wuauserv`) is automatically re-enabled, although it is supposed to be disabled:
https://github.com/actions/runner-images/blob/87d32217309153ea156cc44c38d6e4aaaacc9399/images/win/scripts/Installers/Finalize-VM.ps1#L94C6-L94C14

(this was also mentioned by @ilia-shipitsin in https://github.com/actions/runner-images/issues/8380#issuecomment-1734448479)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20231002.1.0

Image: windows-2022
Version: 20231016.1.0

### Is it regression?

unknown

### Expected behavior

Windows Update service is disabled

### Actual behavior

Windows Update service is enabled

### Repro steps

Run the following workflow with `Start-Sleep -Seconds 60; Get-Service wuauserv` as input:

```yaml
name: Execute PowerShell Command

on:
  workflow_dispatch:
    inputs:
      psCommand:
        description: 'PowerShell Command'
        required: true
        default: 'Write-Output "Hello, world!"'

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
    - name: Execute the specified PowerShell command
      run: |
        $command = "${{ github.event.inputs.psCommand }}"
        Write-Output "Executing: $command"
        Invoke-Expression $command
      shell: pwsh
```

Output:
```
Status   Name               DisplayName
------   ----               -----------
Running  wuauserv           Windows Update
```
