### ISSUE TITLE
macos-13-arm64 just sits on Waiting for a runner to pick up this job... 

### ISSUE THREAD

**Issue by misilot** [actions/runner-images#8610]
### Description

Hello,

I am trying to use the standard macos-13-arm64 standard runner described [here](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md). Is there something else I need to do to use this?

It has been waiting for over 50 minutes.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Just sits there, so can't get this.

### Is it regression?

No?

### Expected behavior

Runs?

### Actual behavior

```
Requested labels: macos-13-arm64
Job defined at: kstatelibrariesit/dspace-angular/.github/workflows/docker-ksul.yml@refs/heads/ksul_dspace-etdr-changes
Waiting for a runner to pick up this job...
```

### Repro steps

```
jobs:
  docker:
    # Ensure this job never runs on forked repos. It's only executed for 'kstatelibrariesit/krex-angular'
    if: github.repository == 'kstatelibrariesit/dspace-angular'

    strategy:
        matrix:
            os: [ubuntu-latest, macos-13-arm64]
            include:
                - os: ubuntu-latest
                  arch: amd64
                - os: macos-13-arm64
                  arch: arm64
    runs-on: ${{ matrix.os }}
...
```
The ubuntu-latest, runs and builds, the macos-13-arm64 just sits there.
