### ISSUE TITLE
64bit version of AzureCli breaks Packer

### ISSUE THREAD

**Issue by J-M-Reed** [actions/runner-images#8619]
### Description

Recently the [AzureCli install was updated from 32bit to 64bit ](https://github.com/actions/runner-images/commit/c64e2f53f13bf9bf2d977f9af3a5f859ae99d1bc) this breaks packer when it attempts to get storage keys using the AzureCli

```
- task: AzureCLI@2
    displayName: "Run Packer builds"
    inputs:
      azureSubscription: '${{ parameters.service_connection }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      workingDirectory: '${{ parameters.packer_working_directory }}'
      inlineScript: |
        C:\\ProgramData\\chocolatey\\bin\\packer.exe build `
        -timestamp-ui `
        -parallel-builds=2 `
        -var-file="..\..\..\common.pkrvars.hcl" .
    env:
      PKR_VAR_build_version: $(Build.BuildNumber)
      PKR_VAR_storage_account_access_key: $(STORAGE_ACCOUNT_ACCESS_KEY)
      PKR_VAR_installers_storage_account: ${{ parameters.gallery_storage_account_name }}
```

```
2023-10-18T13:08:21Z: ==> windows_baseline.azure-arm.windows2022: Running builder ...
2023-10-18T13:08:21Z: ==> windows_baseline.azure-arm.windows2022: Getting tokens using Azure CLI
2023-10-18T13:08:21Z: ==> windows_baseline.azure-arm.windows2022: unable to get token from azure cli: Invoking Azure CLI failed with the following error: 'az' is not recognized as an internal or external command,
==> windows_baseline.azure-arm.windows2022: operable program or batch file.
```
Uninstalling the AzureCli and installing the 32bit version resolves the issue

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image version: https://github.com/actions/runner-images/releases/tag/win22%2F20231016.1

### Is it regression?

No

### Expected behavior

Packer should be able to call the AzureCli to get storage tokens

### Actual behavior

Packer errors reporting it can't find the AzureCli

### Repro steps

Create a pipeline that invokes a packer process that needs to pull from a storage account

```
- task: AzureCLI@2
    displayName: "Run Packer builds"
    inputs:
      azureSubscription: '${{ parameters.service_connection }}'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      workingDirectory: '${{ parameters.packer_working_directory }}'
      inlineScript: |
        C:\\ProgramData\\chocolatey\\bin\\packer.exe build `
        -timestamp-ui `
        -parallel-builds=2 `
        -var-file="..\..\..\common.pkrvars.hcl" .
    env:
      PKR_VAR_build_version: $(Build.BuildNumber)
      PKR_VAR_storage_account_access_key: $(STORAGE_ACCOUNT_ACCESS_KEY)
      PKR_VAR_installers_storage_account: ${{ parameters.gallery_storage_account_name }}
```
