### ISSUE TITLE
Operation not permitted on trying to load modules

### ISSUE THREAD

**Issue by adyanth** [actions/runner-images#8623]
### Description

I was trying to load a kernel module from inside the runner, which fails with operation not permitted, even though it looks like the module exists.

PS: I am not sure if this is a bug or expected behavior and I should raise a tool request instead.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
  Version: 20231016.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231016.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231016.1

### Is it regression?

no

### Expected behavior

Load the kernel module successfully.

### Actual behavior

modprobe: ERROR: could not insert 'openvswitch': Operation not permitted.

### Repro steps

Try the below job
```yaml
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: load modules
        run: lsmod && modprobe openvswitch && lsmod
```
