### ISSUE TITLE
macos-13-xlarge runners resolving to inconsistent versions

### ISSUE THREAD

**Issue by eseay** [actions/runner-images#8697]
### Description

I have a set of workflows that themselves depend on a set of reusable workflows, all of which (well, the ones that run on Mac) specify `macos-13-xlarge` for the `runs-on:`.

In the last few days, I have noticed that unit tests have begun to fail due to a few different things - though it happens based on no pattern I can identify:
- Missing Xcode version (specifying `Xcode_15.0.1`)
- Missing simulator specs (specifying iOS 17.0.1 and iPhone 15 Pro)
- A combination of the two

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

- macos-13-arm64 20231024.2
- macos-13 20230924.3

### Is it regression?

Yes. The issue is with non-deterministic image selection, not the image itself.

### Expected behavior

I would expect that a given `runs-on` value would resolve consistently for runs occurring in rapid succession (clarifying that I _do_ expect that the image may change over time as new releases are published).

### Actual behavior

I am seeing in the "Set up job" step of my workflows that inconsistent images are being selected.

Even in concurrent matrix runs of a reusable workflow that specifies `macos-13-xlarge` for its `runs-on`, I am seeing some jobs running on `macos-13-arm64 20231024.2` where others are running on `macos-13 20230924.3`.

### Repro steps

This appears to occur every single time I run my workflow.

**Comment by eseay** [comment]
This appears related to #8642, but I am inclined to say it's not identical since I am explicitly specifying an image by name.

**Comment by erik-bershel** [comment]
Hey @eseay! You are right. It is not the same issues. We'll be there soon with an additional info.

**Comment by piofusco** [comment]
Having a very similar experience. Our workflows will only run inconsistently. Any advice would be grand.

**Comment by erik-bershel** [comment]
Hey, hey @eseay and @piofusco!
We've already found the reason. We'll fix it in the next few hours. Thank you for highlighting such an important point! 
I'll keep this issue open for the next couple of days in case there are any other users who encounter this.

**Comment by piofusco** [comment]
Still experiencing this. Just had a job fail.

Here's the workflow
```
name: UI Tests
on: pull_request
concurrency:
  group: ${{ github.head_ref }}-ui-tests
  cancel-in-progress: true
jobs:
  ui-tests:
    runs-on: macos-13-xlarge
    timeout-minutes: 60
    permissions:
      contents: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore SPM Cache
        uses: actions/cache@v3
        with:
          path: SPMCache
          key: ${{ runner.os }}-spm-reduced-cache-${{ hashFiles('**/packages.yml') }}
          restore-keys: ${{ runner.os }}-spm-reduced-cache-
      - name: Xcode Configuration
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - name: Install Xcodegen
        run: brew install xcodegen
      - name: Generate project
        run: xcodegen generate
      - name: Run UI Tests
        run: bundle exec fastlane journey_tests
        env:
          CI: true
          HAS_PACKAGES_CACHE_HIT: ${{ steps.packages-cache.outputs.cache-hit == 'true' }}
      - name: xcresulttool
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: fastlane/test_output/FanAppUITests.xcresult
          title: "UI Test Results"
        if: success() || failure()
```

Here's a screenshot of the failure
![image](https://github.com/actions/runner-images/assets/6620352/9dcc6859-73b6-417e-b460-ef28dc5f73b1)

Here's the information regarding the runner image
```
Current runner version: '2.311.0'
Operating System
Runner Image
  Image: macos-13
  Version: [2](https://github.com/fanatics-gaming/fanapp-ios/actions/runs/6721014596/job/18265794543?pr=248#step:1:2)0230[9](https://github.com/fanatics-gaming/fanapp-ios/actions/runs/6721014596/job/18265794543?pr=248#step:1:10)24.3
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20230924.3/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230924.3
Runner Image Provisioner
  2.0.3[12](https://github.com/fanatics-gaming/fanapp-ios/actions/runs/6721014596/job/18265794543?pr=248#step:1:14).1
```
