### ISSUE TITLE
Unable to have successful build running unit test using Xcode 15

### ISSUE THREAD

**Issue by lmedranoz** [actions/runner-images#8721]
### Description

Hello,

We had been running the pipeline using Xcode 14.3.1 but now we are trying to update the pipeline to compile with Xcode 15.0 but since them pipeline takes forever to run the unit test.

The error below is what it shows in the console of the pipeline:

```
Executed 285 tests, with 4 failures (0 unexpected) in 2.154 (2.222) seconds
2023-11-02 05:21:59.207 xcodebuild[16838:97963]  IDETestOperationsObserverDebug: Failure collecting diagnostics from simulator: Timed out after 600.0 seconds while waiting for a response from the invoked process
2023-11-02 05:22:00.295 xcodebuild[16838:76000] [MT] IDETestOperationsObserverDebug: 1567.389 elapsed -- Testing started completed.
2023-11-02 05:22:00.296 xcodebuild[16838:76000] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2023-11-02 05:22:00.296 xcodebuild[16838:76000] [MT] IDETestOperationsObserverDebug: 1567.390 sec, +1567.390 sec -- end
Failing tests:
  URLSession_ExtensionTest.testLoadFlightList()
  PaperworkUpdaterTests.test_ShouldFailToUpdatePaperworkAndIncrementAttempts_ForServiceError()
  PaperworkUpdaterTests.test_ShouldUpdatePaperwork()
  AppInfoSendFeedbackFormViewModelTests.testShouldCallApptentiveAndToggleShowConfirmation()

** TEST FAILED **
```

This is how we executing the unit test
```


- task: Xcode@5
  displayName: 'Xcode test'
  condition: ne(variables['TestConfiguration'], '')
  inputs:
    actions: 'test'
    configuration: 'Debug'
    sdk: '$(TestSDK)'
    xcWorkspacePath: 'MyApp.xcworkspace'
    scheme: '$(BuildScheme)'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '$(Xcode_Version_Path)'
    packageApp: false
    signingOption: 'nosign'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 14,OS=16.4'
    publishJUnitResults: true
    args: '-verbose'
```

Please let us know if you need any more information

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

variables:
 - name: Xcode_Version_Path
   value: /Applications/Xcode_15.0.app
 - name: ProjectPathForExecution
   value: $(Build.SourcesDirectory)/Block2Block/
 - name: BuildName
   value: MyApp.ipa

### Is it regression?

No, production build

### Expected behavior

Get a successful build

### Actual behavior

The build is failing running unit test

### Repro steps

The build is failing using Azure develops pipeline

**Comment by erik-bershel** [comment]
Hey @lmedranoz!
Sad to say it, but it is a infamous bug in XCode. 😞  Same here: https://github.com/actions/runner-images/issues/8693
But you may find a [workaround](https://github.com/actions/runner-images/discussions/8651#discussioncomment-7393444) here: https://github.com/actions/runner-images/discussions/8651
I'm going to close this item as a duplicate. But feel free to ask issue related questions or open new issues in case of other concerns.

**Comment by lmedranoz** [comment]
@erik-bershel  Question,

In the link you mention above mentions this:

```
- name: Install yeetd
   run: |
       wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
       sudo installer -pkg yeetd-normal.pkg -target /
       yeetd &
```
Do you know where in the YAML file should add this lines?

**Comment by erik-bershel** [comment]
@lmedranoz should be placed just before the task for XCode. This is a daemon that monitors certain processes and partially resolves the problem.

**Comment by lmedranoz** [comment]
@erik-bershel  I add it the code above:

<img width="791" alt="Screenshot 2023-11-02 at 12 22 32 PM" src="https://github.com/actions/runner-images/assets/106175915/f17635ca-53a8-4e10-90ff-abf6e90d4a87">

But I'm getting the following error:

<img width="454" alt="Screenshot 2023-11-02 at 12 30 43 PM" src="https://github.com/actions/runner-images/assets/106175915/4995d68f-da9b-4cf0-a1e5-27fe1e65644a">


Do you know how can fix this error?

**Comment by erik-bershel** [comment]
@lmedranoz 
How about to test something like that:
```yml
steps:
- script: |
    wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
    sudo installer -pkg yeetd-normal.pkg -target /
    yeetd &
  displayName: 'Download and Install yeetd'
  continueOnError: true

- task: Xcode@5
  displayName: 'Xcode test'
  condition: ne(variables['TestConfiguration'], '')
  inputs:
    actions: 'test'
    configuration: 'Debug'
    sdk: '$(TestSDK)'
    xcWorkspacePath: 'MyApp.xcworkspace'
    scheme: '$(BuildScheme)'
    xcodeVersion: 'specifyPath'
    xcodeDeveloperDir: '$(Xcode_Version_Path)'
    packageApp: false
    signingOption: 'nosign'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 14,OS=16.4'
    publishJUnitResults: true
    args: '-verbose'
  ```
