### ISSUE TITLE
Missing JAVA_HOME with runner macos-13-xlarge in 50% of the scenarios

### ISSUE THREAD

**Issue by SachaTe** [actions/runner-images#8722]
### Description

It has been stated in the [macos-13-arm-64 README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md) that JAVA_HOME should be defined by default and that multiple versions of JAVA are installed. However, despite using the same workflow and runner, the JAVA_HOME definition is missing 50% of the time. 

As an example, let's consider a workflow defined as: 

```
name: Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        config:
          - name: 'MacOS M1 Runner'
            runner: 'macos-13-xlarge'

      fail-fast: false

    runs-on: ${{ matrix.config.runner }}

    steps:
      - name: Test Print
        run: env
```

When running the same script multiple times, the `env` results are inconsistent, with the JAVA variables missing in certain cases.

 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-13-xlarge

### Is it regression?

No

### Expected behavior

The env variables should be consistent

### Actual behavior

Env variables are not consistent and some are missing

### Repro steps

Run the above workflow and compare env outputs
