### ISSUE TITLE
libsodium is missing on MacOS 12.7

### ISSUE THREAD

**Issue by SystemKeeper** [actions/runner-images#8756]
### Description

Try to setup PHP 8.0 like this:

```

    - name: Set up php 8.0
      uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
      with:
        php-version: 8.0
        extensions: apcu, bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, pgsql, pdo_pgsql
        coverage: none
        ini-file: development
        ini-values: apc.enable_cli=on, disable_functions=
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

See errors like:

```
dyld[2420]: Library not loaded: '@loader_path/../../../../opt/libsodium/lib/libsodium.26.dylib'
  Referenced from: '/usr/local/Cellar/php@8.0/8.0.30_1/bin/php'
  Reason: tried: '/usr/local/Cellar/php@8.0/8.0.30_1/bin/../../../../opt/libsodium/lib/libsodium.26.dylib' (no such file), '/usr/local/lib/libsodium.26.dylib' (no such file), '/usr/lib/libsodium.26.dylib' (no such file)
```

Worked fine on 12.6.9 until a few days ago.

Corresponding issue on the `setup-php` repo: https://github.com/shivammathur/setup-php/issues/780

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Image: macos-12
  Version: 20230921.4

### Is it regression?

12.6.9

### Expected behavior

PHP 8.0 should be installed without an issue.

### Actual behavior

PHP 8.0 can't be installed and therefore used.

### Repro steps

See above.
