### ISSUE TITLE
Update/Add .NET Framework 4.8.1 SDK/Targeting Pack (Server 2019)

### ISSUE THREAD

**Issue by gbakeman** [actions/runner-images#8766]
### Tool name

.NET Framework 4.8.1 SDK/Targeting Pack

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

4.8.1

### Brief description of tool

See also #953; this is just the latest version of the .NET Framework SDK and reference assemblies (targeting pack) for building projects in Visual Studio that require it. It appears to already [be a component](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) in the Windows Server 2022 image, but it looks like Server 2019 was skipped over. Would be nice to have!

### URL for tool's homepage

https://devblogs.microsoft.com/dotnet/announcing-dotnet-framework-481/?WT.mc_id=dotnet-35129-website

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?
Referencing @Darleev's [comment](https://github.com/actions/runner-images/issues/953#issuecomment-635249883), it may be possible to manually add the necessary tools:

```bash

cd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $InstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
          $WorkLoads = '--add Microsoft.Net.Component.4.8.1.SDK --add Microsoft.Net.Component.4.8.1.TargetingPack -add Microsoft.Net.ComponentGroup.4.8.1.DeveloperTools'
          $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
          $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
```

I haven't tested this yet.

Edit: Here's a runner step that is working for me:

```yaml
- name: Install DNF 4.8.1 packs
      shell: pwsh
      working-directory: "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer"
      run: |
        $InstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
        $WorkLoads = '--add Microsoft.Net.Component.4.8.1.SDK --add Microsoft.Net.Component.4.8.1.TargetingPack -add Microsoft.Net.ComponentGroup.4.8.1.DeveloperTools'
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
```
