### ISSUE TITLE
[macOS] configure-tccdb-macos.sh contains 2 bad rules

### ISSUE THREAD

**Issue by liam-x** [actions/runner-images#8782]
### Description

This file contains 2 bad rules:
images/macos/provision/configuration/configure-tccdb-macos.sh

Please see PR #8767 for details.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

don't have public build link

### Is it regression?

not sure

### Expected behavior

The PR #8767 contain fix.

### Actual behavior

The PR #8767 contain fix.
The correct rule should allow child process of provisioner take screenshot on macOS runner.

### Repro steps

screencapture ~/Desktop/picture.png

**Comment by Alexey-Ayupov** [comment]
Hello, @liam-x. We will take a look and add your fix in case it fixes the issue.

**Comment by Alexey-Ayupov** [comment]
We are going to close this issue since we could not reproduce it. If you have other questions, feel free to reach us.

**Comment by liam-x** [comment]
Hi @Alexey-Ayupov  

Did you verify the content of the png file?
Without this rule, you can still get the png, but it only contain the macOS wallpaper. all its windows elements are not in the image.

**Comment by Alexey-Ayupov** [comment]
Hi @liam-x, could you please provide an code example, where some windows in macOS open? I will check it. 
According to my quick test, indeed only wallpapers was on screenshots, but I have not run commands to open windows.

**Comment by liam-x** [comment]
Hi @Alexey-Ayupov 

You can just use your script to test. Add 2 open commands before you do screenshot.
Then check the png to see if it contains Finder window.

```
run-name: test issue
on: 
  #[push]
  workflow_dispatch:
      
jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [macos-13, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    - name: check issue
        shell: bash
        run: |
            open ~/
            open ~/Downloads
            mver=$(sw_vers | grep "ProductVersion" | tail -c 5)
            screencapture /Users/runner/Desktop/picture${mver}.png
            azcopy cp "/Users/runner/Desktop/picture${mver}.png" "https://AureStorageAccount.blob.core.windows.net/scr?[SAS]"

```
