### ISSUE TITLE
Update PowerShell LTS release

### ISSUE THREAD

**Issue by Jaykul** [actions/runner-images#8847]
### Tool name

PowerShell

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

7.4

### URL for tool's homepage

https://github.com/PowerShell/PowerShell/releases

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
# Perhaps, but why should PowerShell developers be the only ones stuck in the dark ages?
```

**Comment by vpolikarpov-akvelon** [comment]
Hey @Jaykul. Thank you for your request, we will definitely consider this.

**Comment by Manbearpiet** [comment]
We can't release our code anymore :(, we have a version requirement:
```pwsh
At C:\Users\runneradmin\Documents\PowerShell\Modules\PowerShellBuild\0.6.1\Public\Build-PSBuildMarkdown.ps1:35 char:19 + … oduleInfo = Import-Module "$ModulePath/$ModuleName.psd1" -Global -For … +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

[<<==>>] Exception: The version of PowerShell on this computer is '7.2.16'. The module 'D:\a\AzureDevOpsPowerShellAPI\AzureDevOpsPowerShellAPI\Output\AzureDevOpsPowerShell\AzureDevOpsPowerShell.psd1' requires a minimum PowerShell version of '7.3' to run. 
Verify that you have the minimum required version of PowerShell installed, and then try again.
```

For Ubuntu hosts we use:
```yaml
      - name: Upgrade pwsh (Linux)
        if: runner.os	== 'Linux'
        run: sudo apt-get install --only-upgrade powershell
 ```
 
 We tried manually upgrading the pwsh package on Windows but that fails:
 ```yml
       - name: Upgrade pwsh (Windows)
        if: runner.os	== 'Windows'
        shell: pwsh
        run: | 
          choco upgrade powershell-core -y -d
  ```
  ```txt
  Installing powershell-core...
Ensuring 'C:\Users\runneradmin\AppData\Local\Temp\chocolatey' exists
Running Start-ChocolateyProcessAsAdmin -validExitCodes '0 3010 1641' -workingDirectory 'C:\Users\runneradmin\AppData\Local\Temp\chocolatey\powershell-core\7.4.0' -statements '/i "C:\Users\runneradmin\AppData\Local\Temp\chocolatey\powershell-core\7.4.0\PowerShell-7.4.0-win-x64.msi" /qn /norestart /l*v "C:\Users\runneradmin\AppData\Local\Temp\chocolatey\powershell-core.7.4.0.MsiInstall.log" ' -exeToRun 'C:\Windows\System32\msiexec.exe' 
Test-ProcessAdminRights: returning True
Elevating permissions and running ["C:\Windows\System32\msiexec.exe" /i "C:\Users\runneradmin\AppData\Local\Temp\chocolatey\powershell-core\7.4.0\PowerShell-7.4.0-win-x64.msi" /qn /norestart /l*v "C:\Users\runneradmin\AppData\Local\Temp\chocolatey\powershell-core.7.4.0.MsiInstall.log" ]. This may take a while, depending on the statements.
Error: Process completed with exit code 1.
```
