### ISSUE TITLE
Update/Add Haskell GHC 9.4

### ISSUE THREAD

**Issue by seanhess** [actions/runner-images#8983]
### Tool name

ghc 9.4

### Tool license

https://www.haskell.org/ghc/license.html

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Any 9.4.*

### Approximate size

Gb?

### Brief description of tool

You have ghcup and GHC 9.8 installed on the images, but 9.8 is a bleeding-edge version. The Haskell community uses fairly strict upper-bounds protection on dependencies, meaning that it takes a few months for library authors to catch up to updates in upstream packages. Practically, I can't compile my project in GHC 9.8 because of dependency conflicts. 

If you were to run `ghcup tui` on a computer, you would see that ghcup has "recommended" versions of dependencies. I would defer to their judgement on which version of GHC is appropriate. The following command installs the "recommended" version of GHC. 

```
ghcup install ghc
```

They currently recommend `9.4.7`, which is what I'm using for development. 

I'm confused, however, because ghcup on my runner is already trying to install 9.4.7 and failing. The runner reports that ghcup needs an upgrade to 0.1.19.0, but your page about ubuntu-latest says it already has 0.1.20.0. See output below

```
Installing ghc version 9.4.7
  Warning: ghc 9.4.7 was not found in the cache. It will be downloaded.
  If this is unexpected, please check if version 9.4.7 is pre-installed.
  The list of pre-installed versions is available here: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
  The above list follows a common haskell convention that the three latest major releases of ghc are commonly supported.
  If the list is outdated, please file an issue here: https://github.com/actions/virtual-environments
  by using the appropriate tool request template: https://github.com/actions/virtual-environments/issues/new/choose
  Attempting to install ghc 9.4.7 using apt-get
  /usr/bin/sudo -- sh -c apt-get -y install ghc-9.4.7
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package ghc-9.4.7
  E: Couldn't find any package by glob 'ghc-9.4.7'
  E: Couldn't find any package by regex 'ghc-9.4.7'
  Attempting to install ghc 9.4.7 using ghcup
  /opt/hostedtoolcache/ghcup/0.1.[8](https://github.com/DKISTDC/level2/actions/runs/7144949442/job/19459612960#step:3:9)/x64/ghcup install [9](https://github.com/DKISTDC/level2/actions/runs/7144949442/job/19459612960#step:3:10).4.7
  [ Warn  ] New GHCup version available: 0.1.[19](https://github.com/DKISTDC/level2/actions/runs/7144949442/job/19459612960#step:3:20).0. To upgrade, run 'ghcup upgrade'
  [ Warn  ] This is an old-style command for installing GHC. Use 'ghcup install ghc' instead.
  [ Error ] No available GHC version for 9.4.7
Error: All install methods for ghc 9.4.7 failed
```

### URL for tool's homepage

https://www.haskell.org/ghcup/

### Provide a basic test case to validate the tool's functionality.

```bash
Same as previous versions
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
ghcup install ghc 9.4.7
```

### Tool installation time in runtime

2 mins?

### Are you willing to submit a PR?

Sure!

**Comment by erik-bershel** [comment]
Hey @seanhess!

We would not like to add another Haskell release to the image, since it can easily and quickly be installed in runtime. I tested it using a simple workflow - it took no more than a couple of minutes.
Code:
```yml
name: Haskel 9.4.7

on:
  workflow_dispatch:

jobs:

  haskel_install:
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04]
        haskel: [ 9.4.7 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check Haskel version
      run: |
        ghcup --version
        ghc --version
    - name: Install Haskel ${{ matrix.haskel }}
      run: |
        ghcup install ghc ${{ matrix.haskel }}
        ghcup set ghc ${{ matrix.haskel }}
    - name: Check Haskel version
      run: ghc --version
```
Ubuntu-20.04:
 
<img width="1067" alt="Screenshot 2023-12-09 at 00 51 26" src="https://github.com/actions/runner-images/assets/110455084/be2c1309-505b-4c65-9623-1c318a124953">

Ubuntu-22.04:

<img width="1073" alt="Screenshot 2023-12-09 at 00 51 12" src="https://github.com/actions/runner-images/assets/110455084/3c99181b-42d7-457e-b9bf-7bd1fb8cdba1">
