### ISSUE TITLE
Update MinGW in Windows Server 2019 image: doesn't support Go race detector

### ISSUE THREAD

**Issue by dagood** [actions/runner-images#9009]
### Tool name

MinGW

### Tool license

GNU

### Add or update?

- [ ] Add
- [X] Update

### Desired version

A version compatible with Go race detector.

### Brief description of tool

Currently the Windows Server 2019 image build installs MinGW 8.1.0 from SourceForge:

https://github.com/actions/runner-images/blob/69db5c6c63cee6e97ea5b7d9e0b7318a28a2094c/images/windows/scripts/build/Install-Mingw64.ps1#L6-L19

This build was released in 2018. Recently, the link to SourceForge builds was removed from https://www.mingw-w64.org/downloads/ because the builds are outdated: https://github.com/mingw-w64/mingw-w64.github.io/commit/9887fc64d7f5540bbdea093edb96a3376d96c262.

As of Go 1.21, this build of MinGW prevents the race detector from working. This workflow fails on a stdlib test:

```yml
name: mingw-stdlib-test

on:
  push:
    branches: [ "main" ]

jobs:
  mingw-stdlib-test:
    runs-on: windows-2019
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Run stdlib test
        run: go test -race sort
```

```
exit status 0xc0000139
FAIL	sort	0.022s
FAIL
```

Other builds, like the one used for the Windows Server 2022 image, work fine in my testing on the Windows Server 2019 image after manually installing them:

https://github.com/actions/runner-images/blob/69db5c6c63cee6e97ea5b7d9e0b7318a28a2094c/images/windows/scripts/build/Install-Mingw64.ps1#L53-L56

I know a version update isn't something to take lightly, and I'm not totally sure it makes sense to make this change for this image due to the risk. However, I think it's at least worth raising this issue, even if it only helps others find the cause of this error message in CI. 🙂 

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

It's possible to download a new MinGW version in a workflow, although it's not trivial. In https://github.com/containerd/containerd/pull/9288, doing this with Chocolatey was attempted, but didn't work smoothly.
