### ISSUE TITLE
Update sqlite3

### ISSUE THREAD

**Issue by GuySartorelli** [actions/runner-images#9033]
### Tool name

sqlite3

### Tool license

[public domain](https://www.sqlite.org/copyright.html)

### Add or update?

- [ ] Add
- [X] Update

### Desired version

At least [3.39.0](https://www.sqlite.org/releaselog/3_39_0.html), but preferably the current latest stable release

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Absolutely - if you're open to it I'll be happy to raise a PR for this - but I'll need someone to point me in the right direction for where to start

**Comment by GuySartorelli** [comment]
My main reason for this request is that 3.39.0 is the first version that provides support for `RIGHT JOIN` - but the current installed version in the ubuntu-latest image is 3.37.2

**Comment by erik-bershel** [comment]
Hey @GuySartorelli!
As I see sqlite3 3.37.2 is the latest available build in apt repository. https://packages.ubuntu.com/jammy/sqlite3
I'll take a look what might be done about it.

**Comment by lekoala** [comment]
I'm also interested in this

It seems that the package in kinetic has the same deps libc6 (>= 2.34), libreadline8 (>= 6.0), zlib1g (>= 1:1.2.0) so maybe it's possible to use it without breaking everything

Otherwise maybe it's possible to compile it from source?

**Comment by erik-bershel** [comment]
Hey @GuySartorelli and @lekoala!

After further investigation, I can say that we do not intend to update the installable version of the utility in the images due to maintenance concerns. There is no safe or stable way for us to install this package when building an image, and the method of building from source is unacceptable due to its resource and time consumption I may add. 
As a workaround, I can offer you the following fairly simple workflow, which will allow you to change the version on the fly in less than couple minutes (please note that if you need a different version of the package, it will be enough to update the link - the SQlite3 developers have a fairly transparent format):

```yml
jobs:
  sqlite:
    runs-on: ubuntu-latest
    steps:
    - name: Check sqlite3 version
      run: sqlite3 --version
    - name: Reinstall sqlite3
      run: |
        download_link="https://www.sqlite.org/2023/sqlite-tools-linux-x64-3440200.zip"
        wget "$download_link" -P /tmp
        unzip "/tmp/$(basename "$download_link")" -d /tmp
        sudo install /tmp/sqlite3 /usr/local/bin/
    - name: Check sqlite3 version
      run: sqlite3 --version
```
Example run:
<img width="1073" alt="Screenshot 2023-12-15 at 13 02 41" src="https://github.com/actions/runner-images/assets/110455084/da8ae77f-177e-44cf-8e19-872350395e1d">
