### ISSUE TITLE
windows-latest uses 14.37 toolkit instead of 14.38

### ISSUE THREAD

**Issue by thomthom** [actions/runner-images#9086]
### Description

According to the Windows2022 image description the Visual Studio VC 14.38 toolkit should be available: 
https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md

![image](https://github.com/actions/runner-images/assets/192418/b1d7a807-551c-41ac-94c3-7764bfc0d699)

I have a Visual Studio 2022 project set to use v143 toolset (default, not locked to any version) and latest Windows SDK.

Locally this picks up VC 14.38.33130, but on the GitHub agent I'm getting 14.37.32822.

As seen in the logs:
```
ClCompile:
         C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\CL.exe
```

This particular project have warnings treated as errors and the std lib with `14.37.32822` will emit warnings (thus errors in my configuration).

My workflow is picking `msbuild` with the following setup:

```yml
    - name: Add MSBuild.exe to PATH
      uses: microsoft/setup-msbuild@v1.3
      with:
        vs-version: '[17.8,18.0)' # Version 17.*
```

It accepts Visual Studio 17.8 as a minimum version, but it's not picking the 14.38 toolkit that shipped with that version.

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20231217.2.0

### Is it regression?

unknown

### Expected behavior

I would expect the latest VC (14.38) toolkit installed to be picked when my Visual Studio project is setup to use latest.

### Actual behavior

I'm seeing that my build uses VC 14.37.

### Repro steps

```yml
jobs:
  build-win:
    runs-on: windows-latest

    - name: Add MSBuild.exe to PATH
      uses: microsoft/setup-msbuild@v1.3
      with:
        vs-version: '[17.8,18.0)' # Version 17.*

    - uses: actions/checkout@v4

    - name: Build Binaries - Windows - Release
      shell: cmd
      run: msbuild Release.proj /maxcpucount:2 /p:RunCodeAnalysis=False
```

The project is not a public one.

**Comment by erik-bershel** [comment]
Hey @thomthom! It's notorious issue of Visual Studio with v143. Duplicate: https://github.com/actions/runner-images/issues/7867, https://github.com/actions/runner-images/issues/7832. Base [thread](https://developercommunity.visualstudio.com/t/MicrosoftVCToolsVersionv143defaulttx/10041951). I may recommend to use https://github.com/marketplace/actions/setup-msvc-developer-command-prompt action to pin the latest toolset. Worked fine here https://github.com/actions/runner-images/issues/8891.

**Comment by thomthom** [comment]
Ah! Thank you for the insight. This had me stomped for days both on Azure DevOps and GitHub Actions since I couldn't figure out why I wasn't seeing the errors locally.

I'll try that alternate action. Does it only lock to specific versions? No means of providing "14.38 or newer"? Or "newest". Seems a bit fragile to pin to an exact given how the agents keeps updating. Also, I can easily see myself forgetting to update the CI script when the project updates.

**Comment by erik-bershel** [comment]
> Does it only lock to specific versions?

There seems to be only one option that really works. When I tried to use something like "latest version from 14" which is the default behaviour, it itself didn't work correctly with the same error.

> Also, I can easily see myself forgetting to update the CI script when the project updates.
Oh, how I understand you. Unfortunately, I don't have a more reasonable solution at the moment - this bug will really affect many runs. I think that sooner or later the guys from Visual Studio will solve this problem.

**Comment by thomthom** [comment]
I understand. Is there a public open ticket to track that fix?

Also, how did you make use of that action to lock the toolset?

I commented out my `microsoft/setup-msbuild` step and replaced it with:

```
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
        toolset: '14.38'
```

But when I run `msbuild` it's still using `14.37`.

**Comment by erik-bershel** [comment]
@thomthom 
```yml
   - name: Setup MSVC dev command prompt
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
        toolset: 14.38.33130
```

**Comment by thomthom** [comment]
hm.. it's still failing, even with full version. I also tried to move the action to the very top of the job in case something else earlier should affect things.

Could there be some caching issue in regard to choosing a kit version?

Additional context of my workflow:

```yml
jobs:
  build-win:
    runs-on: windows-latest

    steps:
    - name: Dump info
      run: |
        echo 'github.ref: ${{ github.ref }}'
        echo 'github.head_ref: ${{ github.head_ref }}'
        echo 'github.base_ref: ${{ github.base_ref }}'

    - name: Setup Ruby for use with actions
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Not needed with a .ruby-version file

    # https://github.com/actions/runner-images/issues/9086
    # - name: Add MSBuild.exe to PATH
    #   uses: microsoft/setup-msbuild@v1.3
    #   with:
    #     vs-version: '[17.8,18.0)' # Version 17.*

    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
        toolset: 14.38.33130

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACTION_PAT }}
        submodules: recursive

    - name: Build Binaries - Windows - Release
      working-directory: CExt
      shell: cmd
      run: msbuild Release.proj /maxcpucount:2 /p:RunCodeAnalysis=False
```
