### ISSUE TITLE
The SonarScanner for MSBuild integration failed

### ISSUE THREAD

**Issue by denisyakimov07** [actions/runner-images#9087]
### Description

SQ scan start fails the first time in image version: '20231127.1' then fixed in image version: '20230921.1'.
Fail again in image version: '20231128.1', '20231127.1', '20231211.1', '20231216.1'

 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231216.1, 
20231127.1

### Is it regression?

20230921.1

### Expected behavior

SonarScanner.MSBuild able to run Scan.
![image](https://github.com/actions/runner-images/assets/59424027/46190313-9bf8-4467-a8f7-b6739c040deb)

### Actual behavior

The SonarScanner for MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
![image](https://github.com/actions/runner-images/assets/59424027/7ece12f7-69c8-4f3c-a81f-4132f51f8283)

### Repro steps

1:
```
- task: SonarQubePrepare@5
  inputs:
    SonarQube: '$(SQ_ServiceConnectionsName)'
    scannerMode: 'MSBuild'
    projectKey: '$(SQ_ProjectKey)'
    projectName: '$(SQ_ProjectKey)'
    projectVersion: '$(correntVersionBuildNumber)'
    extraProperties: |
      sonar.verbose = true
  continueOnError: true
```
2:
```
  - task: XamariniOS@2
    displayName: 'XamariniOS build ${{ env.envName }}'
    inputs:
      solutionFile: '$(solutionFileName)'
      configuration: '${{ env.configuration }}'
      buildForSimulator: false
      packageApp: true
    continueOnError: false
```
3:
```
- task: SonarQubeAnalyze@5
  retryCountOnTaskFailure: 2
  continueOnError: true
```

**Comment by mikhailkoliada** [comment]
Hey! This is a problem in sonarqube itself and it has been reported upstream see more here: https://github.com/actions/runner-images/issues/8873

**Comment by andrei-epure-sonarsource** [comment]
@mikhailkoliada is there a place where we can read the changelog of each version of the image?

> The SQ scan failed the first time in the image version: '20231127.1', then it was fixed in the image version: '20230921.1'.
Fail again in image version: '20231128.1', '20231127.1', '20231211.1', '20231216.1'

The problem is likely related to some underlying OS changes which have an impact either on the behavior of dotnet / MSBuild or our own software. It would help us to narrow down the issues.

Also, is there an easy way to spawn a particular image version and connect to it, to easily reproduce such issues?

We've done local manual testing on Mac OS this year and couldn't find problems, we'd need to have the exact setup you have on the images.

**Comment by denisyakimov07** [comment]
@andrei-epure-sonarsource 
You can find the change log here: https://github.com/actions/runner-images

**Comment by themaroqa** [comment]
for anyone hitting the same issue: for me the root cause was the dotnet version. Using dotnet 8 the task fails. As a workaround (while waiting for sonarsource or microsoft to fix the problem) you can add the following in the yaml:
```
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'
```

Adding that snippet resolved my issue.
