### ISSUE TITLE
Packer azure-arm build fails after hardcoded version

### ISSUE THREAD

**Issue by doreluser** [actions/runner-images#9088]
### Description

When running "packer build" with the source "azure-arm", we get the error: "Unknown source type azure-arm"

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current image version: '20231217.2.0'

### Is it regression?

Yes, working on image: 20231205.1.0 

### Expected behavior

azure-arm is an available source for packer

### Actual behavior

azure-arm is unknown. It looks to be related to hardcoding version 1.4.5

### Repro steps

Run packer build with source "azure-arm". This causes the error "Unknown source type azure-arm"

Current Steps: 
Pipeline YML: 

```
trigger: none

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: 'Packer build'
  inputs:
    targetType: 'inline'
    script: 'packer build -on-error=abort -force -var "client_secret=$(client_secret)" -var "image_name=$(image_name)" -var "build_id=$(Build.BuildNumber)" -var "base_image_name=$(base_image_name)" -var "site_name=$(site_name)" -var "pat=$(pat)" -var "branch_name=$(branch_name)" packer\build.pkr.hcl'
```

packer\build.pkr.hcl: 

```
variable "base_image_name" {
  type    = string
  default = "${env("BASE_IMAGE_NAME")}"
}

variable "branch_name" {
  type    = string
  default = "${env("BRANCH_NAME")}"
}

variable "build_id" {
  type    = string
  default = "${env("BUILD_ID")}"
}

variable "image_name" {
  type    = string
  default = "${env("IMAGE_NAME")}"
}

variable "pat" {
  type    = string
  default = "${env("PAT")}"
}

variable "site_name" {
  type    = string
  default = "${env("SITE_NAME")}"
}

variable "client_secret" {
  type    = string
  default = "${env("CLIENT_SECRET")}"
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  build_resource_group_name         = "rg-provisioning"
  client_id                         = "redacted"
  client_secret                     = "${var.client_secret}"
  communicator                      = "winrm"
  managed_image_name                = "${var.image_name}"
  managed_image_resource_group_name = "rg-provisioning"
  os_type                           = "Windows"
  shared_image_gallery {
    gallery_name   = "gallery"
    image_name     = "${var.base_image_name}"
    image_version  = "latest"
    resource_group = "rg-provisioning"
  }
  shared_image_gallery_destination {
    gallery_name        = "image_gallery"
    image_name          = "${var.image_name}"
    image_version       = "1.${var.build_id}"
    replication_regions = ["redacted"]
    resource_group      = "rg-provisioning"
  }
  shared_gallery_image_version_end_of_life_date = timeadd(timestamp(), "120h")
  subscription_id = "redacted"
  tenant_id       = "redacted"
  vm_size         = "Standard_D2_v2"
  winrm_insecure  = true
  winrm_timeout   = "60m"
  winrm_use_ssl   = true
  winrm_username  = "packer"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "file" {
    destination = "C:\\"
    source      = "packer\\scripts\\install.ps1"
  }

  provisioner "powershell" {
    elevated_password = build.Password
    elevated_user     = "redacted"
    inline            = ["C:\\install.ps1 -SiteName ${var.site_name} -Pat ${var.pat}  -BranchName ${var.branch_name}", "Remove-Item -Path C:\\install.ps1"]
  }

}
```

There is a work around to install the latest version of azure-arm before triggering the build, however the image release notes claim this is installed already. 

The workaround is to add: "packer plugins install github.com/hashicorp/azure;" before "packer build" in the YML
