### ISSUE TITLE
Update/Add pipx to M1 runners

### ISSUE THREAD

**Issue by henryiii** [actions/runner-images#9256]
### Tool name

pipx

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.4.3

### Brief description of tool

This is available on all other images, and is the basis for the GitHub Actions for cibuildwheel, nox, and a lot of other Python tooling. It's also pre-installed in lots of other places too, like the manylinux images for Python.

I _think_ it was supposed to be present in https://github.com/actions/runner-images/pull/7599 (given the name of the PR), but it is not present currently for M1.

### URL for tool's homepage

https://pipx.pypa.io

### Provide a basic test case to validate the tool's functionality.

```bash
pipx run cowsay
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes if that helps.

**Comment by Jackenmen** [comment]
Notably, there is no Python present on the image either, usage of https://github.com/actions/setup-python seems to be required to run any kind of Python code since macOS no longer even ships with it. More so, according to https://github.com/actions/runner-images/blob/37a171e44de1f134793d7f0cbff137ca481942ab/images/macos/macos-14-arm64-Readme.md there's no tool cache anymore and setup-python always has to download it? Either way, at least one Python install, along with pipx, would be nice since pipx can then be used with any interpreter that's later installed with actions/setup-python.

**Comment by erik-bershel** [comment]
Hey @henryiii 
The macOS-14 image has been significantly streamlined compared to its predecessors. We removed some packages and programs that could be easily and quickly installed at runtime. Compatibility issues also influenced decisions of this nature. Regarding the stated need to add the 'pipx' package, we will explore what can be done and provide additional information later.

**Comment by henryiii** [comment]
Okay, thanks for looking at it. Having pipx as a supported package manager was very important for composite actions (Python actually didn't matter, since that can be pulled by setup-python and targeted by any pipx, only having pipx actually mattered once `activate-environment: false` was supported by setup-python). Here's what an isolated action looks like with pipx:

<details>
<summary>Pipx installed isolated composite action:</summary>

```yaml
runs:
  using: composite
  steps:
    # Set up a non-EOL, cibuildwheel & pipx supported Python version
    - uses: actions/setup-python@v5
      id: python
      with:
        python-version: "3.8 - 3.12"
        update-environment: false
    - run: >
        pipx run
        --python '${{ steps.python.outputs.python-path }}'
        --spec '${{ github.action_path }}'
        myapp
      shell: bash
```

</details>

Now, if pipx is not installed, the simple workaround initially seemed to be:

<details>
<summary>Pipx not installed incorrectly isolated composite action:</summary>

```yaml
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      id: python
      with:
        python-version: "3.8 - 3.12"
        update-environment: false

    # macos-14 (M1) may be missing pipx (due to it not having CPython)
    - run: |
        "${{ steps.python.outputs.python-path }}" -m pip install pipx
      shell: bash

    # Note that different syntax is required for powershell
    - run: >
        "${{ steps.python.outputs.python-path }}" -m pipx run
        --spec '${{ github.action_path }}'
        myapp
      shell: bash
```

</details>

However, this permanently changes the setup-python provide environment. This makes the composite action surprising (if you try to install something later that is incompatible with pipx's dependencies after running a compatible setup-python call, it will break), and it can affect self hosted runner's environments. That's why you should use pipx instead of pip, but if you have to use pip to get pipx, you are still using pip!

Here's the correct workaround:

<details>
<summary>Pipx not installed isolated composite action:</summary>

```yaml
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      id: python
      with:
        python-version: "3.8 - 3.12"
        update-environment: false

    - id: myapp
      run: |
        "${{ steps.python.outputs.python-path }}" -u << "EOF"
        import os
        import sys
        import venv
        from pathlib import Path
        from subprocess import run
        class EnvBuilder(venv.EnvBuilder):
            def __init__(self):
                super().__init__()
            def setup_scripts(self, context):
                pass
            def post_setup(self, context):
                super().post_setup(context)
                self.python_path = context.env_exe
                run([sys.executable, "-m", "pip", "--python", context.env_exe, "install", r"${{ github.action_path }}"], check=True)
        print("::group::Install cibuildwheel")
        builder = EnvBuilder()
        builder.create(Path(r"${{ runner.temp }}") / "cibw")
        with open(os.environ["GITHUB_OUTPUT"], "at") as f:
            f.write(f"python-path={builder.python_path}\n")
        print("::endgroup::")
        EOF

    # Note that even more different syntax is required for powershell
    # Also, this workaround requires a __main__ module to run it via -m
    - run: >
        "${{ steps.myapp.outputs.python-path }}" -m myapp
      shell: bash
```

</details>

cibuildwheel has to use powershell on Windows, which makes the workaround even a bit more messy.



Having pipx as a package manager alongside the native package managers like brew was _very_ helpful! (if setup python included pipx by default or via an option, that would also work, but has different implications & effects).
