### ISSUE TITLE
VCPKG_ROOT is not "C:\vcpkg" on Windows Server 2022

### ISSUE THREAD

**Issue by jakoch** [actions/runner-images#9269]
### Description

On the Windows 2019 runner the VCPKG_INSTALLATION_ROOT is `c:\vcpkg`
On the Windows 2022 runner the VCPKG_INSTALLATION_ROOT is `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg` (the MSVC path).

This is either an unintended change of the default path or a [documentation issue](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#environment-variables).

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Runner Image
  Image: windows-2022
  Version: 2024012

### Is it regression?

--

### Expected behavior

env.VCPKG_ROOT should not differ between runners.

### Actual behavior

env.VCPKG_ROOT differs between runners.

### Repro steps

My workflow uses `env.VCPKG_ROOT` which differs between runners.

```
      - name: 🔽 Update VCPKG
        run: |
          cd ${{ env.VCPKG_ROOT }}
          git reset --hard
          git pull --quiet
          bootstrap-vcpkg.bat -disableMetrics
          vcpkg integrate
```

**Comment by erik-bershel** [comment]
Hey @jakoch!
There is a bug in your code. Should be next:
```yml
      - name: Update VCPKG
        run: |
          cd ${{ env.VCPKG_INSTALLATION_ROOT }}
          git reset --hard
          git pull --quiet
          bootstrap-vcpkg.bat -disableMetrics
          vcpkg integrate
```

VCPKG_INSTALLATION_ROOT  != VCPKG_ROOT

Could be checked with the next simple workflow:
```
name: VCPKG

on:
  workflow_dispatch:

jobs:
  env:
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
    # Runs a single command using the runners shell
    - name: Print ENV
      run: printenv
```

**Comment by jakoch** [comment]
The bug in the documentation remains.
The VCPKG_INSTALLATION_ROOT is not C:\vcpkg on Windows2022.

Also the default path was `c:\vcpkg` for both runners and worked for years. 
Seems that it broke with MSVC 17.6?
Since VS 17.6 includes vcpkg.exe in the the developer command prompt:
It defines VCPKG_ROOT to C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg
and adds the value of VCPKG_ROOT to the PATH environment variable.
This is the origin of the issue.

Before that one could easily define for all runners:
```
env:
  VCPKG_ROOT: c:\vcpkg
 ```
 
Now VCPKG_ROOT needs to be set to a changing VCPKG_INSTALLATION_ROOT.
I doubt that one can set an env var to the value of another env var easily, e.g.
 
 ```
 env:
   VCPKG_ROOT: ${{ VCPKG_INSTALLATION_ROOT }}
 ```
 
Your suggested solution (`cd ${{ env.VCPKG_INSTALLATION_ROOT }}`) works for the update step of the pre-installed vcpkg, 
but CMakeLists.txt works on VCPKG_ROOT not VCPKG_INSTALLATION_ROOT, see:
 
 ```
 #-------------------------------------------------------------------
# Setup VCPKG
#-------------------------------------------------------------------

if(DEFINED VCPKG_ROOT AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
elseif(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
endif()
```

-----

Sorry to say so, but the easier solution is to simply bypass your preinstallation:
```
env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg

 - name: 🔽 Update VCPKG
        run: |
          git clone https://github.com/microsoft/vcpkg ${{ env.VCPKG_ROOT }}
          cd "${{ env.VCPKG_ROOT }}"
          bootstrap-vcpkg.bat -disableMetrics
          vcpkg integrate
      
```

**Comment by erik-bershel** [comment]
>The bug in the documentation remains.
The VCPKG_INSTALLATION_ROOT is not C:\vcpkg on Windows2022.

Mmm. It's not docs issue. Everything fine with docs and `VCPKG_INSTALLATION_ROOT`.

I made a mistake with `{{}}`:
```yml
name: VCPKG

on:
  workflow_dispatch:

jobs:
  env:
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Print ENV
      run: printenv
    - name: Update VCPKG
      shell: bash
      run: |
          vcpkg_root="$VCPKG_INSTALLATION_ROOT"
          echo "$vcpkg_root"
          cd "$VCPKG_INSTALLATION_ROOT"
          git reset --hard
          git pull --quiet
```
Both OSs will return the same result. You can use `env` variable as you wish. 

Example:
<img width="1072" alt="Screenshot 2024-02-01 at 15 53 55" src="https://github.com/actions/runner-images/assets/110455084/675361da-4e3d-41f3-87f0-b43d42834610">
