### ISSUE TITLE
Ubuntu images cause 400 Bad Request on git push with PowerShell

### ISSUE THREAD

**Issue by Ramo-Y** [actions/runner-images#9312]
## The issue
We have an Azure DevOps pipeline that applies Git flow by creating a release branch, adding a commit and pushing it to the origin. Since February 6, a 400 Bad Request has been issued on the push command. A PowerShell script contains the Git commands and a PAT is used. It last worked on January 30th and no changes have been made to the pipeline or variables for some time. The PAT is valid and has also been regenerated.

This is the job declaration:
```yaml
  - job: GitFlow
    displayName: Apply Git Flow
    workspace: 
      clean: all
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: Powershell@2
      displayName: 'Define Output Variables'
      inputs:
        targetType: inline
        script: >
                Write-Output "##vso[task.setvariable variable=skipBuild]";

    - task: PowerShell@2
      name: BeginRelease
      displayName: Begin Release $(BEGIN_RELEASE)
      condition: and(succeeded(), variables['BEGIN_RELEASE'])
      inputs:
        targetType: filePath
        filePath: $(Build.Repository.LocalPath)/build/azure-pipelines/Scripts/GitFlow.ps1
        arguments: '-Action BeginRelease -Verbose'
        workingDirectory: '$(Build.Repository.LocalPath)'
      env:
        SYSTEM_PERSONALACCESSTOKEN: $(GIT_REPO_PUSH_KEY)
        VERSION_FILE: '$(Build.Repository.LocalPath)/build/azure-pipelines/version.yml'
```

This is the PowerShell script with the git commands:
```powershell
function Invoke-BeginRelease
{
    $begin_release = $env:BEGIN_RELEASE

    git remote set-url origin $env:BUILD_REPOSITORY_URI
    git @authorization remote -v
    git @authorization checkout -B develop origin/develop
    git @authorization checkout -b release/$begin_release
    Set-ProjectVersionInYml -Version $begin_release -OutFile $env:VERSION_FILE
    
    git @authorization add $env:VERSION_FILE
    git @authorization commit -m"Set release version to $begin_release"
    git @authorization push -u origin release/$begin_release
}
```

## Workaround
We fixed it by changing the `vmImage` to `'windows-latest'`

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [x] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Pool: Azure Pipelines
Image: ubuntu-latest
Agent: Azure Pipelines 30

### Is it regression?

Yes

### Expected behavior

Push a new branch with a commit to git

### Actual behavior

`fatal: unable to access 'https://dev.azure.com/{organization}/{project}/_git/{repository}/': The requested URL returned error: 400`

### Repro steps

1. Create a build job with `vmImage: 'ubuntu-latest'`
2. Add a `Powershell@2` task
3. Create a PowerShell script that includes a `git push` command to an Azure DevOps repository
