### ISSUE TITLE
Add `$GOPATH/bin` to `$PATH`

### ISSUE THREAD

**Issue by Goooler** [actions/runner-images#9316]
### Description

I installed something like `go install xxx` on `ubuntu-latest` and ran it in shell, it could not be founded.

This might be a feature instead of a bug.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.312.0

### Is it regression?

Nope

### Expected behavior

`$GOPATH/bin` could be recognized by default.

### Actual behavior

I noticed the workaround from https://github.com/actions/runner-images/issues/731#issuecomment-617039721, try it with the error below:
```
ln: '/bin/7z' and '/usr/bin/7z' are the same file
ln: '/bin/7za' and '/usr/bin/7za' are the same file
ln: '/bin/7zr' and '/usr/bin/7zr' are the same file
ln: '/bin/R' and '/usr/bin/R' are the same file
...
```

### Repro steps

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          shfmt --version
```
