### ISSUE TITLE
Fastlane broken on macos-14

### ISSUE THREAD

**Issue by geeklingo** [actions/runner-images#9341]
### Description

I need to move to macos-14 to run the newer version of XCode to avoid AppStore publishing issues. But either ruby or fastlane seems to be broken on macos-14. Works fine on macos-latest (13).

```shell
Notice: Running Bundle Install
Fetching https://github.com/joshdholtz/fastlane-plugin-github_action
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching rake 13.1.0
Installing rake 13.1.0
Fetching rexml 3.2.6
Fetching public_suffix 5.0.4
Fetching aws-partitions 1.889.0
Installing public_suffix 5.0.4
Fetching multipart-post 2.4.0
Installing rexml 3.2.6
Installing aws-partitions 1.889.0
Installing multipart-post 2.4.0
Fetching json 2.7.1
Fetching optparse 0.4.0
Installing json 2.7.1 with native extensions
Installing optparse 0.4.0
Fetching sshkey 3.0.0
Installing sshkey 3.0.0
Fetching rbnacl 7.1.1
Fetching aws-sdk-core 3.191.1
Installing rbnacl 7.1.1
Fetching xcodeproj 1.24.0
Installing aws-sdk-core 3.191.1
Installing xcodeproj 1.24.0
Fetching google-apis-core 0.11.3
Installing google-apis-core 0.11.3
Fetching aws-sdk-kms 1.77.0
Installing aws-sdk-kms 1.77.0
Fetching aws-sdk-s3 1.143.0
Installing aws-sdk-s3 1.143.0
Bundle complete! 2 Gemfile dependencies, 90 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Notice: Running Fastlane
bundler: failed to load command: fastlane (/opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane)
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in `ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:451:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/ffi-1.16.3/lib/ffi/dynamic_library.rb:[65](https://github.com/EQL-CEPS-Emerging-and-Mobile-Apps/XR010-Safety-Heroes-2.0/actions/runs/7881479916/job/21505292697#step:5:66):in `load_library': Could not open library 'sodium': dlopen(sodium, 0x0005): tried: 'sodium' (no such file), '/System/Volumes/Preboot/Cryptexes/OSsodium' (no such file), '/usr/lib/sodium' (no such file, not in dyld cache), 'sodium' (no such file). (LoadError)
Could not open library 'libsodium.dylib': dlopen(libsodium.dylib, 0x0005): tried: 'libsodium.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.dylib' (no such file), '/usr/lib/libsodium.dylib' (no such file, not in dyld cache), 'libsodium.dylib' (no such file).
Could not open library 'libsodium.so.18': dlopen(libsodium.so.18, 0x0005): tried: 'libsodium.so.18' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.18' (no such file), '/usr/lib/libsodium.so.18' (no such file, not in dyld cache), 'libsodium.so.18' (no such file).
Could not open library 'libsodium.so.18.dylib': dlopen(libsodium.so.18.dylib, 0x0005): tried: 'libsodium.so.18.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.18.dylib' (no such file), '/usr/lib/libsodium.so.18.dylib' (no such file, not in dyld cache), 'libsodium.so.18.dylib' (no such file).
Could not open library 'libsodium.so.23': dlopen(libsodium.so.23, 0x0005): tried: 'libsodium.so.23' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.23' (no such file), '/usr/lib/libsodium.so.23' (no such file, not in dyld cache), 'libsodium.so.23' (no such file).
Could not open library 'libsodium.so.23.dylib': dlopen(libsodium.so.23.dylib, 0x0005): tried: 'libsodium.so.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.23.dylib' (no such file), '/usr/lib/libsodium.so.23.dylib' (no such file, not in dyld cache), 'libsodium.so.23.dylib' (no such file).
Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib, /opt/homebrew/lib
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/ffi-1.16.3/lib/ffi/library.rb:95:in `block in ffi_lib'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/ffi-1.16.3/lib/ffi/library.rb:94:in `map'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/ffi-1.16.3/lib/ffi/library.rb:94:in `ffi_lib'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rbnacl-7.1.1/lib/rbnacl/sodium.rb:11:in `extended'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rbnacl-7.1.1/lib/rbnacl/sodium/version.rb:14:in `extend'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rbnacl-7.1.1/lib/rbnacl/sodium/version.rb:14:in `<module:Version>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rbnacl-7.1.1/lib/rbnacl/sodium/version.rb:9:in `<module:Sodium>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rbnacl-7.1.1/lib/rbnacl/sodium/version.rb:7:in `<module:RbNaCl>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rbnacl-7.1.1/lib/rbnacl/sodium/version.rb:6:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/rbnacl-7.1.1/lib/rbnacl.rb:12:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jwt-2.7.1/lib/jwt/algos.rb:4:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jwt-2.7.1/lib/jwt/encode.rb:3:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jwt-2.7.1/lib/jwt/encode.rb:3:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jwt-2.7.1/lib/jwt.rb:8:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api/token.rb:1:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/spaceship/lib/spaceship/connect_api.rb:3:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/build_watcher.rb:1:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core.rb:11:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core.rb:11:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane.rb:1:in `<top (required)>'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:41:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:451:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:5[84](https://github.com/EQL-CEPS-Emerging-and-Mobile-Apps/XR010-Safety-Heroes-2.0/actions/runs/7881479916/job/21505292697#step:5:85):in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
Error: Process completed with exit code 1.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

unknown - i don't see that option can only see ubuntu images and not the macos

### Is it regression?

Yes - works in macos-13 / macos-latest

### Expected behavior

Fastlane should execute without ruby errors

### Actual behavior

```shell
bundler: failed to load command: fastlane (/opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane)
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in `ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/fastlane/lib/fastlane/cli_tools_distributor.rb:126:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.219.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:451:in `exec'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/bundle:25:in `<main>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/ffi-1.16.3/lib/ffi/dynamic_library.rb:65:in `load_library': Could not open library 'sodium': dlopen(sodium, 0x0005): tried: 'sodium' (no such file), '/System/Volumes/Preboot/Cryptexes/OSsodium' (no such file), '/usr/lib/sodium' (no such file, not in dyld cache), 'sodium' (no such file). (LoadError)
Could not open library 'libsodium.dylib': dlopen(libsodium.dylib, 0x0005): tried: 'libsodium.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.dylib' (no such file), '/usr/lib/libsodium.dylib' (no such file, not in dyld cache), 'libsodium.dylib' (no such file).
Could not open library 'libsodium.so.18': dlopen(libsodium.so.18, 0x0005): tried: 'libsodium.so.18' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.18' (no such file), '/usr/lib/libsodium.so.18' (no such file, not in dyld cache), 'libsodium.so.18' (no such file).
Could not open library 'libsodium.so.18.dylib': dlopen(libsodium.so.18.dylib, 0x0005): tried: 'libsodium.so.18.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.18.dylib' (no such file), '/usr/lib/libsodium.so.18.dylib' (no such file, not in dyld cache), 'libsodium.so.18.dylib' (no such file).
Could not open library 'libsodium.so.23': dlopen(libsodium.so.23, 0x0005): tried: 'libsodium.so.23' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.23' (no such file), '/usr/lib/libsodium.so.23' (no such file, not in dyld cache), 'libsodium.so.23' (no such file).
Could not open library 'libsodium.so.23.dylib': dlopen(libsodium.so.23.dylib, 0x0005): tried: 'libsodium.so.23.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibsodium.so.23.dylib' (no such file), '/usr/lib/libsodium.so.23.dylib' (no such file, not in dyld cache), 'libsodium.so.23.dylib' (no such file).
Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib, /opt/homebrew/lib
```

### Repro steps

1. Confirm it works using macos-13
2. Update yaml to use macos-14
3. Watch it fail

**Comment by Alexey-Ayupov** [comment]
Hello @geeklingo. We will take a look, however could you please provide a code snippet to reproduce the error or link to your workflow? It will shorten investigation time.

**Comment by geeklingo** [comment]
> Hello @geeklingo. We will take a look, however could you please provide a code snippet to reproduce the error or link to your workflow? It will shorten investigation time.

Hi, it's a private repo but here is the workflow that causes this. Please note, it works fine when i use macos-latest. It's failing at running `bundle exec fastlane`

```
  deployForiOS:
    name:  Release to AppStore Connect
    runs-on: macos-14
    needs: buildForiOS
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    
    - name: Download iOS Artefact
      uses: actions/download-artifact@v4
      with:
        name: Build-iOS
        path: build/iOS
        
    - name: Fix File Permissions and Run fastlane
      env:
        APPLE_TEAM_ID: ${{ env.GITHUB_ORG_SECRETS_APPLE_TEAM_ID }}
        
        MATCH_REPOSITORY: ${{ env.GITHUB_ORG_SECRETS_MATCH_REPOSITORY }}
        MATCH_DEPLOY_KEY: ${{ env.GITHUB_ORG_SECRETS_MATCH_DEPLOY_KEY }}
        MATCH_PASSWORD: ${{ env.GITHUB_ORG_SECRETS_MATCH_PASSWORD }}
        GH_PAT: ${{ env.GITHUB_ORG_SECRETS_MATCH_GIT_PRIVATE_KEY }} | base64 -d
        
        APPSTORE_ISSUER_ID: ${{ env.GITHUB_ORG_SECRETS_APPSTORE_ISSUER_ID }}
        APPSTORE_KEY_ID: ${{ env.GITHUB_ORG_SECRETS_APPSTORE_KEY_ID }}
        APPSTORE_P8: ${{ env.GITHUB_ORG_SECRETS_APPSTORE_KEY_CONTENTS }}
        
        IOS_BUILD_PATH: ${{ format('{0}/build/iOS', github.workspace) }}
        IOS_BUNDLE_ID: redacted 
        PROJECT_NAME: redacted 
        GITHUB_REPOSITORY: redacted
      run: |
        export APP_STORE_CONNECT_API_KEY_KEY="${{ env.GITHUB_ORG_SECRETS_APPSTORE_KEY_CONTENTS }}"
        export APPLE_SIGNING_ID="${{ env.GITHUB_ORG_SECRETS_APPLE_SIGNING_ID }}"
        export MATCH_GIT_PRIVATE_KEY=$(echo ${{ env.GITHUB_ORG_SECRETS_MATCH_GIT_PRIVATE_KEY }} | base64 -d)
        export FASTLANE_PASSWORD="${{ env.GITHUB_ORG_SECRETS_FASTLANE_PASSWORD }}"
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${MATCH_GIT_PRIVATE_KEY}"
        find $IOS_BUILD_PATH -type f -name "**.sh" -exec chmod +x {} \;
        echo "::notice::Running Bundle Install"
        bundle install
        echo "::notice::Running Fastlane"
        bundle exec fastlane ios release
```
