### ISSUE TITLE
Different screen sizes in one workflow

### ISSUE THREAD

**Issue by Artem-Mirochnik** [actions/runner-images#9345]
### Description

Hello there,

We use Github actions almost everyday and we encountered a problem with screen sizes. We run 5 jobs in parallel on macos-latest and we save screenshots for every failure, and we noticed such a thing that the screen size is different every time. Each time the same job can have different sizes which leads to incorrect failures. Github support said that you can possibly help.

Here are screenshots:
![big_screen](https://github.com/actions/runner-images/assets/135663619/b1c50b3f-4b28-4efc-bb76-c1c638f2bb74)
![small_screen](https://github.com/actions/runner-images/assets/135663619/9ac35a9f-c12c-44fd-93b0-5ab39a35437f)

Here you can clearly see that in the same run, different jobs have different sizes.

Could you please tell us how to make the screen sizes equally large for all jobs?

Thank you,
Artem.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

job1  
  Image: macos-12
  Version: 20231216.1

job2
  Image: macos-12
  Version: 20231216.1

job3
  Image: macos-12
  Version: 20240127.1

job4
  Image: macos-12
  Version: 20240127.1

job5
  Image: macos-12
  Version: 20240105.1

### Is it regression?

no

### Expected behavior

all jobs use big screens

### Actual behavior

all jobs use different screens

### Repro steps

launch a work flow with several parallel jobs

**Comment by mikhailkoliada** [comment]
Hey! Could you provide links to workflows which give you different results? (not mandatory those workflows should be public, we only need links to the runs)

**Comment by Artem-Mirochnik** [comment]
> Hey! Could you provide links to workflows which give you different results? (not mandatory those workflows should be public, we only need links to the runs)

Sure.
https://github.com/safeandreliable/test/actions/runs/7818994302
https://github.com/safeandreliable/test/actions/runs/7835969273

**Comment by erik-bershel** [comment]
Hey @Artem-Mirochnik!

In general, we don't have much control over the screen resolution on virtual machines - there is no such need for us.

For agent based on Anka I tried next:
```yml
name: Veertu - Anka
on:
  workflow_dispatch:
jobs:
  veertu:
    runs-on: macos-12
    steps:

    - name: Change screen resolution
      run: |
        if [ -f "/Library/Application Support/Veertu/Anka/addons/change_res" ]; then
          /Library/Application\ Support/Veertu/Anka/addons/change_res 1440x900x32@30
        fi

    - name: Capture screenshot
      run: screencapture screenshot.png

    - name: Check screenshot resolution
      run: identify -format "%w x %h" "screenshot.png"
 ```
 
 It will allow you to control exactly the screen size only on Anka-based macOS-12 agents (or all the macOS-13 agents). The same time VMware based macOS-12 agents will always have the same resolution because of the architecture. I guess you may try to find snippet to control it too if you need.
An important point:
- acceptable parameters can vary within a certain range, but the amount of resources is limited and I highly recommend using the minimum required screen size.
