### ISSUE TITLE
 CmdLine@2 script: 'dotnet workload install maui maui-ios' installs old versions of SDKs using vmImage: macos-13

### ISSUE THREAD

**Issue by faceoffers28** [actions/runner-images#9355]
### Description

Here is the Task I'm using,

```
- task: CmdLine@2
  displayName: 'Install Maui & iOS'
  inputs:
    script: 'dotnet workload install maui maui-ios'
```

On Monday 2/12/24, the Task was installing the following:

Installing workload manifest microsoft.net.sdk.ios version 17.2.8004
Installing pack Microsoft.Maui.Sdk version 8.0.3

Starting on 2/13/24, the Task was installing the following:

Installing pack Microsoft.iOS.Sdk version 16.4.8825-net8-rc1
Installing pack Microsoft.Maui.Sdk version 8.0.0-rc.1.9171

As a result, I'm getting this error when trying to Publish.

error NETSDK1140: 17.0 is not a valid TargetPlatformVersion for iOS.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

On 2/12/24

Image: macos-13
Version: 20240114.1
Included Software: https://github.com/actions/runner-images/blob/macos-13/20240114.1/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240114.1

Starting on 2/14/24

Image: macos-13
Version: 20240204.1
Included Software: https://github.com/actions/runner-images/blob/macos-13/20240204.1/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240204.1

### Is it regression?

Issue started on 2/13/24

### Expected behavior

I would expect the script to install the correct versions of the SDKs.

### Actual behavior

The script is installing older versions of all the SDKs.

### Repro steps

Run this command on the image prior to 2/13/24.

```
- task: CmdLine@2
  displayName: 'Install Maui & iOS'
  inputs:
    script: 'dotnet workload install maui maui-ios'
```
