### ISSUE TITLE
HTTP GET request returns old result in Node.js

### ISSUE THREAD

**Issue by canbax** [actions/runner-images#9443]
### Description

I'm using Node.js 20. My YML file is as simple as below.

```
name: Unit test
on: [push, pull_request]
jobs:
  install-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run test

```
My tests pass on local but they fail on GitHub workflow https://github.com/canbax/GPS-miner/actions/runs/8131285823/job/22220431826

The failing test is making 2 HTTP requests to https://query.wikidata.org/ to get data. Both of them return the same result but they are actually different queries. When I log the queries I see that they are different. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20240225.1.0

### Is it regression?

I don't know

### Expected behavior

the test should pass

### Actual behavior

the test fails

### Repro steps

just re-run https://github.com/canbax/GPS-miner/actions/runs/8131285823/job/22220431826
