### ISSUE TITLE
Hypervisor framework not avaiblable on macOS ARM64 runners for running docker containers

### ISSUE THREAD

**Issue by romeroalx** [actions/runner-images#9460]
### Description

When trying to run Docker on an ARM64 macOS runner either directly with Docker desktop or using Colima, in both cases it complains that the virtualization framework not being enabled, while it is enabled for the x86_64 macOS runners.

Colima will not start because it launches QEMU with `-accel hvf`. The output does not say that much, but when trying to launch QEMU manually with that option enabled, it says `Error: HV_UNSUPPORTED`:

```
Run qemu-system-aarch64 -m 1G -drive file=ubuntu-23.10-minimal-cloudimg-arm64.qcow2,if=virtio -display default,show-cursor=on -machine type=virt -accel hvf

qemu-system-aarch64: -accel hvf: Error: HV_UNSUPPORTED
```

I have tried to check manually the support but also throws an error

```
Run sysctl kern.hv_support

sysctl: unknown oid 'kern.hv_support'
```

I have checked with the arm64 runners `macos-14` and `macos-13-xlarge`. However, the installation of Docker in both ways works fine on my personal M1 arm64 MAC, and also on the x86_64 macOS runners.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Runner Image
  Image: macos-14-arm64
  Version: 20240116.1
 ```
 
https://github.com/romeroalx/build-docker-images-arm64/actions/runs/8170604833/job/22337064074

```
Runner Image
  Image: macos-13-arm64
  Version: 20240219.3
```

https://github.com/romeroalx/build-docker-images-arm64/actions/runs/8170604827/job/22337064332

### Is it regression?

no

### Expected behavior

```
Run sysctl kern.hv_support

kern.hv_support: 1
```

### Actual behavior

```
> qemu-system-aarch64 -m 1G -drive file=ubuntu-23.10-minimal-cloudimg-arm64.qcow2,if=virtio -display default,show-cursor=on -machine type=virt -accel hvf
qemu-system-aarch64: -accel hvf: Error: HV_UNSUPPORTED

> sysctl kern.hv_support
sysctl: unknown oid 'kern.hv_support'
```

### Repro steps

```yaml
    jobs:
      docker:
        name: docker
        runs-on: macos-14
        steps:
          # - run: sysctl kern.hv_support
          # Install colima and docker
          - run: brew install colima docker
          # Test launch qemu with -accel hvf and do not stop if fails
          - run: wget https://github.com/abiosoft/colima-core/releases/download/v0.6.7/ubuntu-23.10-minimal-cloudimg-arm64.qcow2
          - run: /opt/homebrew/bin/qemu-system-aarch64 -m 1G -drive file=ubuntu-23.10-minimal-cloudimg-arm64.qcow2,if=virtio -display default,show-cursor=on -machine type=virt -accel hvf -nographic &
          # Start colima daemon
          - run: colima start
          - run: docker ps
          - run: docker pull alpine:latest
          - run: docker image ls
```
