### ISSUE TITLE
Held broken apt packages

### ISSUE THREAD

**Issue by BTOdell** [actions/runner-images#9546]
### Description

I'm trying to install GStreamer development libraries before running my main application build, but apt seems to be in a broken state on the Ubuntu 22.04 runners.

```yaml
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install --no-install-recommends libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
```

Output:
```
Run sudo apt-get -y update
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [136 kB]
Get:8 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [34.5 kB]
Get:9 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main armhf Packages [12.2 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1502 kB]
Hit:16 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [289 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1619 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [271 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1059 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [240 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1286 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [229 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1591 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [267 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [851 kB]
Get:22 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [162 kB]
Fetched 9890 kB in 2s (5631 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgstreamer1.0-dev : Depends: libunwind-dev
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

These two packages should exist for Ubuntu 22.04 LTS:
https://packages.ubuntu.com/search?keywords=libgstreamer&searchon=names&suite=jammy&section=all

I've been stuck on this for hours trying every apt command as a workaround to try to get passed this but it's totally broken.

---

I posted a similar issue on GitHub Community Discussions: https://github.com/orgs/community/discussions/113480
but it hasn't received any notice.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240317.1.0

### Is it regression?

No

### Expected behavior

GStreamer dev packages should successfully install.

### Actual behavior

Package installation fails due to "held broken packages".

### Repro steps

```yaml
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install System Dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install --no-install-recommends libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
```
