### ISSUE TITLE
DockerCompose@0 give problems on latest images

### ISSUE THREAD

**Issue by mlankamp** [actions/runner-images#9616]
### Description

All azure devops pipeline jobs with image version '20240401.4.0' fail on DockerCompose@0 steps:

```
Starting: Compose build ....
==============================================================================
Task         : Docker Compose
Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
Version      : 0.231.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-compose-tsg
==============================================================================
##[error]Unhandled: Docker Compose was not found. You can provide the path to docker-compose via 'dockerComposePath' 
##[error]Error: Docker Compose was not found. You can provide the path to docker-compose via 'dockerComposePath' 
    at DockerComposeConnection.setDockerComposePath (/home/vsts/work/_tasks/DockerCompose_6975e2d1-96d3-4afc-8a41-498b5d34ea19/0.231.0/dockercomposeconnection.js:166:23)
    at new DockerComposeConnection (/home/vsts/work/_tasks/DockerCompose_6975e2d1-96d3-4afc-8a41-498b5d34ea19/0.231.0/dockercomposeconnection.js:22:14)
    at success (/home/vsts/work/_tasks/DockerCompose_6975e2d1-96d3-4afc-8a41-498b5d34ea19/0.231.0/dockercompose.js:35:26)
Finishing: Compose build precalcworker

```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Initialize job:
```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az158-513'
Current agent version: '3.236.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20240401.4.0'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DockerCompose (0.231.0)
Downloading task: AzureCLI (2.237.3)
```

### Is it regression?

yes, retry failed tasks runs on 20240324.1.0

### Expected behavior

DockerCompose runs

### Actual behavior

Error:
```
##[error]Unhandled: Docker Compose was not found. You can provide the path to docker-compose via 'dockerComposePath' 
##[error]Error: Docker Compose was not found. You can provide the path to docker-compose via 'dockerComposePath' 
```

### Repro steps

- Create a pipeline
- Add a DockerCompose@0 step:
```
  - task: DockerCompose@0
    displayName: Compose build image
    inputs:
      dockerComposeCommand: 'build examplecontainer'
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: ${{ parameters.registrySubscription }}
      azureContainerRegistry: ${{ parameters.registryEndpoint }}
      dockerComposeFile: src/docker-compose.yml
      qualifyImageNames: true
      projectName: ""
      dockerComposeFileArgs: |
        TAG=${{ parameters.imagetag }}
```
