### ISSUE TITLE
Fastlane action broken on ubuntu-xlarge

### ISSUE THREAD

**Issue by geeklingo** [actions/runner-images#9639]
### Description

Same issue as i had on MacOS a little while ago: https://github.com/actions/runner-images/issues/9341

Now happening with using ubuntu-xlarge_a41492fcb2fe

Image: ubuntu-22.04
Version: 20240324.2.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240324.2/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240324.2

I can't apply the workaround i used with MacOS as my yaml is slightly different with linux/android builds

```
  deployForAndroid:
    name: 🤖 Deploy for Android
    runs-on: ubuntu-xlarge
    needs: buildForAndroid
    if: startsWith(github.event.ref, 'refs/tags/deploy') || startsWith(github.event.ref, 'refs/tags/Deploy') || startsWith(github.event.ref, 'refs/tags/androiddeploy')
    env:
      GOOGLE_PLAY_KEY_FILE_PATH: ${{ format('{0}/fastlane/google-fastlane.json', github.workspace) }}
      ANDROID_BUILD_FILE_PATH: ${{ format('{0}/build/Android/myapp.aab', github.workspace) }}
      ANDROID_PACKAGE_NAME: com.myapp
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build-Android
          path: build/Android
          
      - name: Add Authentication
        run: echo "${{ env.GITHUB_ORG_SECRETS_GOOGLE_PLAY_KEY_FILE }}" | base64 -d > $GOOGLE_PLAY_KEY_FILE_PATH
  
      - name: 🚀 Set up Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          
      - name: Upload to Google Play Internal
        uses: maierj/fastlane-action@516faaa1c6c7b366ecd238b4e4608d286874dd94
        with:
          lane: 'android internal' # Change to upload to a different lane
      
      - name: Cleanup to avoid storage limit
        if: always()
        uses: geekyeggo/delete-artifact@54ab544f12cdb7b71613a16a2b5a37a9ade990af
        with:
          name: build-Android
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20240324.2.0

### Is it regression?

worked last week

### Expected behavior

fastlane should run without error

### Actual behavior

Same as the MacOS issue with libsodium load errors

### Repro steps

Try to deploy Android build to Google Play
