### ISSUE TITLE
update cmake to >= 3.29.2

### ISSUE THREAD

**Issue by rursprung** [actions/runner-images#9680]
### Tool name

cmake

### Tool license

BSD

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.29.2

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by rursprung** [comment]
CMake 3.29.1 - which is currently packaged on the runners - contains a regression which causes a variety of projects to fail building. CMake 3.29.2 reverts this and has been released yesterday. please urgently update CMake on the runner images to >= 3.29.2 so that these projects (and the ones depending on them) build fine with the default CMake and don't need to manually install a specific version.

some background from vcpkg discussions: https://github.com/microsoft/vcpkg/issues/37968 & https://github.com/microsoft/vcpkg/pull/38144 (see esp. the linked original tickets for further information)

**Comment by erik-bershel** [comment]
Hey @rursprung!

Thank you for arising this issue. It is often only through the efforts of users that we can learn about some updates or problems.

This week's deployment has already ended, we will not start a new one on Friday - this brings more issues and cons than pros. Starting Monday we will begin rolling out new images. Rolling back to the previous image is also not an option in this case - the Ubuntu images contained some major blockers.

Generally task requires no action in terms of updating. On `Ubuntu` images we always install the latest available release from the `Kitware/CMake` repository. On `Windows` images, `Cmake` is provided as part of the `MinGW` installation, the latest available package from the `Chocolatey` repository, and as part of the `Visual Studio` installation. On `macOS` `Cmake` is installed from `Homebrew`. `Cmake` is also part of the `Android` installation on all systems, but the situation there is different and does not overlap with the stated problem. In all cases, we cannot speed up the availability of more recent `Cmake` in the repository.

I will keep this issue open for better user awareness until the end of the day.

**Comment by kklobe** [comment]
for anyone needing a quick fix, this CMake runner action can help: https://github.com/marketplace/actions/actions-setup-cmake

I just added

```yml
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.2'
```

to our runner script and it worked great.

**Comment by erik-bershel** [comment]
There is an alternative method, seems a bit faster:

```yml
jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14, macos-13, macos-12, windows-2019, windows-2022, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.29.2" 
```

Result:

<img width="295" alt="Screenshot 2024-04-12 at 17 43 50" src="https://github.com/actions/runner-images/assets/110455084/349ce8c8-8b2a-4112-9041-45486368202f">

Using previous:

```yml
jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14, macos-13, macos-12, windows-2019, windows-2022, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: jwlawson/actions-setup-cmake@v2
       with:
         cmake-version: '3.29.2'
```

I've got next:

<img width="292" alt="Screenshot 2024-04-12 at 17 46 52" src="https://github.com/actions/runner-images/assets/110455084/94a4c316-acef-428e-9a87-80e78737c699">
