### ISSUE TITLE
Regression: Microsoft Edge is missing in macOS-14-arm64

### ISSUE THREAD

**Issue by mxschmitt** [actions/runner-images#9734]
### Description

Microsoft Edge should be installed as per here. But it seems missing since a recent macOS-14 update.

Downstream issue: https://github.com/microsoft/playwright-dotnet/issues/2920

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Image: macos-14-arm64
  Version: 20240415.6

### Is it regression?

yes

### Expected behavior

It's installed.

### Actual behavior

It's not installed.

### Repro steps

```yaml
name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: test
    strategy:
      matrix:
        runs-on: [macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - run: ls -la "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge"
```

Expected: Edge installed across the macOS versions.
Actual: It's not available on macOS 14.
