### ISSUE TITLE
macos 14 is only arm64

### ISSUE THREAD

**Issue by wmertens** [actions/runner-images#9741]
### Description

I specify

```
  build-bindings:
    strategy:
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
```

but I get an arm64 host. Are there no more x64 hosts for macos 14?

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-14-arm64
  Version: 20240415.6

### Is it regression?

not sure

### Expected behavior

should get latest macos with x64, even if that's not the latest macos

### Actual behavior

get arm64

### Repro steps

ask for x64 macos-latest runner

**Comment by mikhailkoliada** [comment]
Hello! As stated in the [table](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) the only intel-based macOS-14 runner is `macos-14-large` ([doc](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners)). There are no plans to introduce macOS-14 intel standard runners as of now.

**Comment by javierggt** [comment]
I'm sorry, but if I understood correctly, @wmertens is not trying to run macOS-14 specifically. He uses `macos-latest`. I assumed `macos-latest` would be macOS-14, but the actual issue is with macos-latest.

I just hit an issue where I'm using `macos-latest` to build a conda package and it determines the platform is ARM, so I might have the same issue.

**Comment by nulano** [comment]
https://github.com/actions/runner-images?tab=readme-ov-file#available-images shows `macos-latest` as being an ARM platform.

**Comment by mikhailkoliada** [comment]
Starting OS14 standard runners are going to be arm based, i.e. standard OS13 runner is intel but OS14 and further are the arm ones.

**Comment by str4d** [comment]
The other issue is that, prior to now, all `*-latest` runners were x86_64. Switching `macos-latest` from x86_64 to ARM64 breaks a bunch of workflows that involve caching (e.g. https://github.com/actions/runner-images/issues/9732#issuecomment-2080020545), because the caching approaches that GitHub recommends (e.g. [here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#example-using-the-cache-action)) pattern-match on `runner.os`.

**Comment by wmertens** [comment]
Right, I think it would be better to either:

- make the combo macos-latest+x86 be macos-13
- fail the CI when macos-latest+x86 is requested

**Comment by MordechaiHadad** [comment]
I am unable to use x86 runner for macos

![image](https://github.com/user-attachments/assets/cdcb765b-1949-4b95-94f3-8082fac50c26)

Workflow file:

```yaml
on: push

jobs:
  arm:
    runs-on: macos-latest
    steps:
      - name: Get architecture
        run: uname -m
  regular:
    runs-on: macos-latest-large
    steps:
      - name: Get arch again
        run: uname -m
```
