### ISSUE TITLE
Go binary cannot be found on macOS 13 and macOS 14 runner images

### ISSUE THREAD

**Issue by markdumay** [actions/runner-images#9757]
### Description

With the recent switch from `macos-12` to `macos-14` when using the `macos-latest` tag, it appears the Go binary cannot longer be found. The `macos-13` image also appears to be affected. The docs (e.g. [macos-13](https://github.com/actions/runner-images/blob/macos-13/20240421.1/images/macos/macos-13-Readme.md), [macos-14-arm64](https://github.com/actions/runner-images/blob/macos-14-arm64/20240422.3/images/macos/macos-14-arm64-Readme.md)) still suggest multiple versions of Go should be preinstalled.

NB: the code has not been tested with the macOS large runners due to account / billing limitations.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`2.316.0`, see https://github.com/markdumay/gha-hugo-macos/actions/runs/8865382577

### Is it regression?

No

### Expected behavior

Running `go version` from within the workflow should return a valid Go version, e.g. `go version go1.21.9 darwin/amd64`.

### Actual behavior

On `macos-13` and `macos-14`, running `go version` returns an error:

```bash
/Users/runner/work/_temp/xxx-xxx-xxx-xxx-xxx.sh: line 1: go: command not found
Error: Process completed with exit code 127.
```

### Repro steps

1. Create a new workflow file in any repository, e.g. `.github/workflows/fail.yml` and copy the following code:

```yml
name: Go installation check (fail)
on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os:
          - macos-14
          - macos-13
      
    runs-on: ${{ matrix.os }}

    steps:
    - run: go version
```

2. Manually run the workflow `Go installation check (fail)` in the actions overview.

**Comment by irkode** [comment]
not listed in the 13 and 14 readmes as "installed"

using setup-go will succeed and report 1.22.2 for all versions

```
name: Go installation check (fail)
on:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os:
          - macos-14
          - macos-13
          - macos-12
      
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">1.0.0"
      - name: RUN Go
        run: go version
```
