### ISSUE TITLE
PowerShell Modules missing when running with PowerShell Core

### ISSUE THREAD

**Issue by ltrochmann-gcmlp** [actions/runner-images#9957]
### Description

PowerShell modules is not preset when we set the task "PowerShell@2" to use PowerShell Core

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az686-950'
Current agent version: '3.239.1'

Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter

Runner Image
Image: windows-2022
Version: 20240514.3.0
Included Software: https://github.com/actions/runner-images/blob/win22/20240514.3/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240514.3

Runner Image Provisioner
2.0.370.1

Current image version: '20240514.3.0'

### Is it regression?

no

### Expected behavior

With the below task
```yaml
- task: PowerShell@2
        inputs:
          targetType: "inline"
          script: |
            Get-InstalledModule
          pwsh: true
        displayName: "Uninstall Microsoft.Graph.*"
```

I was expecting the same result as when the `pwsh` is set to false
![image](https://github.com/actions/runner-images/assets/7861037/6c19a353-2402-436e-ad0f-844b85ec2aba)

### Actual behavior

It is not listing anything
![image](https://github.com/actions/runner-images/assets/7861037/39c6ee08-de66-43b2-b0f6-1b9cf8cc1223)

### Repro steps

Create a pipeline with the tasks below, and you will see that for the first task the modules are listed but for the second there is nothing.
```yaml
- task: PowerShell@2
        inputs:
          targetType: "inline"
          script: |
            Get-InstalledModule
          pwsh: false
        displayName: "List Modules listed"

- task: PowerShell@2
        inputs:
          targetType: "inline"
          script: |
            Get-InstalledModule
          pwsh: true
        displayName: "List Modules listed"
```
